### ISSUE TITLE
Popup trigger bug

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#10]
Chromium v67.0.3396.87
Image Max URL v0.4.8
Mouseover popup trigger `Ctrl+Shift+Alt`

This bug has been annoying me since v0.4.5 or v0.4.7. The trigger would be executed even if I only pressed `Ctrl+Shift`.

Steps to reproduce:
1. Set popup trigger to `Ctrl+Shift+Alt`
1. Open any webpage with at least one image (e.g. youtube.com)
1. Press `Ctrl+Shift` while hovering mouse on top of an image (no effect as expected)
1. Press `Alt+e` (will open chromium's menu)
1. Press `Esc` or click anywhere on the page (to hide the menu)
1. Press `Ctrl+Shift` while hovering mouse on top of an image (trigger is unexpectedly executed)

**Comment by qsniyg** [comment]
Thank you very much for taking the time to share the steps! Should be fixed in 0.4.9 :)
