### ISSUE TITLE
Strikingly CDN support

### ISSUE THREAD

**Issue by susanqt** [qsniyg/maxurl#100]
Example of a modified/compressed image:
http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_9000,w_1200,f_auto,q_auto/1515559/534889_633117.jpg
Example of full-size image:
http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/1515559/534889_633117.jpg

Removing `c_limit,fl_lossy,h_9000,w_1200,f_auto,q_auto` seems to work fine.

**Comment by qsniyg** [comment]
Thanks, added it in! Yeah it uses Cloudinary, haven't yet made a generic rule for it (I don't know if it's even possible, if wanting to retain maximum compatibility).
