### ISSUE TITLE
instagram.com candidates_sorter not always correct

### ISSUE THREAD

**Issue by robindz** [qsniyg/maxurl#1000]
This is what currently is used to sort instagram posts.
```js
var candidates_sorter = function(a, b) {
    if (a.is_unprocessed)
        return -1;
    if (b.is_unprocessed)
        return 1;
    return b.size - a.size;
};
```
But it fails to properly sort some posts' images, such as these: https://www.instagram.com/p/B7AXLsplw6Y/ & https://www.instagram.com/p/B8BFW14Ffwz/

I changed the function above to this:
```js
var candidates_sorter = function(a, b) {
    if (!a.is_unprocessed || !b.is_unprocessed) {
        if (a.is_unprocessed)
            return -1;
        if (b.is_unprocessed)
            return 1;
    }
    return b.size - a.size;
};
```

Now it properly sorts the posts I linked above and I haven't seen any problems with other posts that didn't have this issue before.

**Comment by qsniyg** [comment]
Thank you very much! You're absolutely right, it should be fixed now :)
