### ISSUE TITLE
mangadex.org

### ISSUE THREAD

**Issue by Steamarino** [qsniyg/maxurl#1003]
**Docs:** https://api.mangadex.org/docs.html#section/Retrieving-Covers-from-the-API/Construct-Cover-URLs

In a nutshell: remove `.{ 256|512 }.jpg` from the url

The domain has to be wildcard (`*.mangadex.org`) because the cdn domain can always change and there are other cdn subdomains that are being actively used

**Known image domains:** `uploads.mangadex.org`, `s2.mangadex.org`

**Format:**
`https://uploads.mangadex.org/covers/{ manga.id }/{ cover.filename }`
`https://uploads.mangadex.org/covers/{ manga.id }/{ cover.filename }.{ 256|512 }.jpg`

**Example:**
256 https://uploads.mangadex.org/covers/304ceac3-8cdb-4fe7-acf7-2b6ff7a60613/12158456-0511-468b-be37-8d2aa3772723.png.256.jpg
512 https://uploads.mangadex.org/covers/304ceac3-8cdb-4fe7-acf7-2b6ff7a60613/12158456-0511-468b-be37-8d2aa3772723.png.512.jpg
original https://uploads.mangadex.org/covers/304ceac3-8cdb-4fe7-acf7-2b6ff7a60613/12158456-0511-468b-be37-8d2aa3772723.png
s2 https://s2.mangadex.org/covers/304ceac3-8cdb-4fe7-acf7-2b6ff7a60613/12158456-0511-468b-be37-8d2aa3772723.png

**Comment by qsniyg** [comment]
Thanks! Supported :)
