### ISSUE TITLE
update to tellonym.me

### ISSUE THREAD

**Issue by DevWannabe-dot** [qsniyg/maxurl#1007]
Hello! I've been to the site tellonym.me, and thought I could get full size profile pictures. With no success, I tried the Android app, which allows me to get the biggest image displayable, but only for screenshots. I don't like the ideia of capturing my screen and losing image data, so I'm wondering if there is a way to get the original image from tellonym.me?

#### If you right-click and open in new tab the main profile image, you get a 200x200 image: 
![image](https://user-images.githubusercontent.com/64389041/156812212-6ed75247-8541-4360-8ff1-c9a82b48c494.png)
That's https://userimg.tellonym.me/xs/1_1e9782237fa625a7798451b8cc054a14.jpg

#### On the other hand, if you scroll down and right-click the small profile image embedded on the "tells" section, you get a 50x50 thumbnail:
![image](https://user-images.githubusercontent.com/64389041/156812365-350590d0-903d-48ab-90f1-a5288b33c456.png)
That's https://userimg.tellonym.me/thumb/1_1e9782237fa625a7798451b8cc054a14.jpg

<hr>

#### By using IMU, I am given this URL https://img.tellonym.me/1_1e9782237fa625a7798451b8cc054a14.jpg, which is obsolete.

```
		if (domain === "userimg.tellonym.me") {
			// https://userimg.tellonym.me/xs/14963714_5e0b7c3e269dfb54fdb68c797c571cc9.jpg
			//   https://img.tellonym.me/14963714_5e0b7c3e269dfb54fdb68c797c571cc9.jpg
			return src.replace(/:\/\/[^/]*\/+[a-z]+\/+/, "://img.tellonym.me/");
		}
```

#### If I replace or remove the /xs/ or /thumb/, I get an amazonaws link: https://yh4do6twt0.execute-api.eu-central-1.amazonaws.com/prod?key=1_1e9782237fa625a7798451b8cc054a14.jpg
![image](https://user-images.githubusercontent.com/64389041/156813947-5dde0c7f-80eb-4542-ad72-fce82245a10a.png)

Hope this helps anyone find out! Thanks so much.

**Comment by qsniyg** [comment]
Thank you very much! Fixed :)
