### ISSUE TITLE
Not An Issue More of A Request

### ISSUE THREAD

**Issue by srinac** [qsniyg/maxurl#1008]
Is it possible you could add https://www.pearlygates.net to max url. I'm trying to find bigger images from this link https://www.pearlygates.net/catalogue/2022sp/index.html? There are 600x900 from Chrome's dev tools but apparently there are bigger res (1300x1800).
Thanks if not thanks

**Comment by qsniyg** [comment]
Replace `/100/` with `/200/` in the image URL :)

https://www.pearlygates.net/catalogue/2022sp/contents/pages/200/h1.jpg
