### ISSUE TITLE
ebookjapan support

### ISSUE THREAD

**Issue by synthtech** [qsniyg/maxurl#101]
Page example: https://ebookjapan.yahoo.co.jp/books/121625/A000053677/
Thumbnail image: https://cache2-ebookjapan.akamaized.net/contents/thumb/s/SX277060.jpg?1560846301000

Original image:
- https://cache2-ebookjapan.akamaized.net/contents/thumb/l/SX277060.jpg?1560846301000
or
- https://haishin.ebookjapan.jp/contents/thumb/l/SX277060.jpg

**Comment by qsniyg** [comment]
Thank you, it's in now! :)
