### ISSUE TITLE
squareenixmangaandbooks.square-enix-games.com

### ISSUE THREAD

**Issue by RolerGames** [qsniyg/maxurl#1010]
#### Info
Site: https://squareenixmangaandbooks.square-enix-games.com
Image CDN: https://fyre.cdn.sewest.net
#### Example
On the Free Preview of a product (https://squareenixmangaandbooks.square-enix-games.com/en-us/product/9781646090921?preview=yes) get the image URL
> https://fyre.cdn.sewest.net/manga-books/610a98293b7287001317e56e/cover-DIK9xjOaB.jpg?width=1000

Remove
> ?width=1000

And get
> https://fyre.cdn.sewest.net/manga-books/610a98293b7287001317e56e/cover-DIK9xjOaB.jpg

**Comment by qsniyg** [comment]
Thanks! Supported :)
