### ISSUE TITLE
Support for tagesschau.de

### ISSUE THREAD

**Issue by h-h-h-h** [qsniyg/maxurl#1013]
Website: https://www.tagesschau.de/

This worked for every image from the website I tried it with.

URL transformation by example:

- Source URL (article thumbnail): https://www.tagesschau.de/multimedia/bilder/coronavirus-deutschland-283~_v-videowebm.jpg
- Source URL (bigger article image on top of article): https://www.tagesschau.de/multimedia/bilder/coronavirus-deutschland-283~_v-gross20x9.jpg
- Destination URL, found via trial and error: https://www.tagesschau.de/multimedia/bilder/coronavirus-deutschland-283.jpg

So, the text from the tilde `~` to the character before the file extension needs to be removed.

**Comment by qsniyg** [comment]
Thank you! Seems to be the same system that wdr.de uses, so I just merged the rules. Interestingly, while WDR supports no `~_v-...`, it significantly reduces the image quality, but `~_v-original` returns the original(?) resolution. This doesn't appear to affect tagesschau, but it's easier to just merge the rules together, as they seem to use the same system :)
