### ISSUE TITLE
Instagram not working properly on browsers not supporting BigInt

### ISSUE THREAD

**Issue by GTR8000** [qsniyg/maxurl#1023]
I've been using the Github script with Tampermonkey in Firefox for the past few months to grab the 1440px version of photos from Instagram, and it's been flawless. All of a sudden a few days ago it has completely stopped working. I disabled the script and installed the Image Max URL 0.19.5 Firefox extension instead, which seems to be able to grab the 1080px versions, but not the 1440px versions. Very strange, I wonder if Instagram has changed something with their code that the script is no longer recognizing?

I am signed into Instagram and the issues are effecting all accounts I follow, so it's not an issue with private accounts that I follow, for example.

**Comment by qsniyg** [comment]
Recently they removed most of the post information from the page source, so I need to reconfigure the script to only retrieve information from the API calls instead.

**Comment by GTR8000** [comment]
Thank you for the super quick response! The script is absolutely brilliant, thanks for all you've done to make it effortless to grab images and video from sites like Instagram.

**Comment by GTR8000** [comment]
Well this sucks, I think Instagram did something with my account to prevent me from using your script and other downloader apps. I've always made sure to keep the options disabled that draw attention to your account, especially the Use Native API, but it seems that they got me anyway without actually banning my account. I'm simply unable to get the script or any of the Android apps to download the 1440 versions while I'm logged in. Only the 1080 versions while I'm logged out are working.

I've come to this conclusion by trying the script with a different Instagram account, and it seems to be working as it did previously. Dammit.

**Comment by qsniyg** [comment]
That's possible, but I think this is more of a A/B test. If you don't mind, would you mind sending to my email listed on qsniyg.github.io) the source code of a post page that doesn't work? I'd recommend sending it through an encrypted pastebin (such as privatebin.info), just in case it contains personal information.

**Comment by GTR8000** [comment]
Sure no problem I can do that tonight or tomorrow.

For what it's worth, only one of my accounts is affected, and it's the account that I use one of the Android apps with signed in. I bet the app was behaving badly and using the Native API. I tried that account on a completely different browser and it's still giving me issues. 🤦‍♂️

**Comment by GTR8000** [comment]
Email sent, thanks!

**Comment by qsniyg** [comment]
Thanks! Received and took a quick look. It's what I thought, a recent A/B test IG is doing where they are now replacing their website to use React, and not embedding image etc. info within the page. This is almost certainly going to be the future, but their trial has been limited to a few accounts, probably to catch any unexpected issues before it's rolled out to the public.

**Comment by GTR8000** [comment]
As soon as I saw the different formatting of the source code, I knew something was afoot. I guess I got a little paranoid that they messed with one of my accounts, but it turns out that they probably just picked one of the accounts randomly to test with.

I know you haven't had time to look at the code in depth, but what's your gut feeling as far as the future of Image Max URL? Do you think it will be able to adapt to whatever changes they're potentially making?

Obviously I'm happy to help test anything with that account. Just note that I only use the script, manually updating it in TamperMonkey (Firefox) when you post a new version.

Thanks again, appreciate the super quick responses. 👍

**Comment by qsniyg** [comment]
> I know you haven't had time to look at the code in depth, but what's your gut feeling as far as the future of Image Max URL? Do you think it will be able to adapt to whatever changes they're potentially making?

Almost certainly, yes. My problem is that I have no way to test it, and the Instagram code is an absolute jungle. I just need to rewrite it to avoid calling the post page, and instead rely entirely on the API.

**Comment by qsniyg** [comment]
Good to hear, but I didn't change anything IG-related yet. Honestly I am pretty scared to make any change, as the IG-related code is a huge spaghetti mess, and I'm unable to test anything. Any change I usually make there ends up needing at least 4-5 commits of regression fixes later...

**Comment by GTR8000** [comment]
They broke it again lol...FML!

**Comment by qsniyg** [comment]
> They broke it again lol...FML!

They made the change you reported permanent across all devices. So now I need to removed the `_sharedData`-dependent pieces of code (and thereby also strip out the related optimizations, so it might be rather far-reaching).

**Comment by GTR8000** [comment]
I suppose it was inevitable. Are these changes going to make maxurl less effective? Will it still be able to grab the 1440px versions instead of 1080px? Thanks!

**Comment by qsniyg** [comment]
It should still support it, yes, but it might be slower to load the images and possibly be more quick to flag your account (error 429) due to an increase in API calls.

**Comment by GTR8000** [comment]
Crap. The slower loading I can deal with, the account flagging sucks. Guess I'll have to go back to using the ALT+T+I trick to find the pics in the media list. :(

**Comment by qsniyg** [comment]
To be clear, it won't be any worse than most other extensions that explicitly support IG (unless they simply scrape the page itself - perhaps I could add an option for that too). If you have the popup set on a keyboard binding (rather than mouseover) and you don't overdo it, it shouldn't flag your account (hopefully, anyways).

**Comment by GTR8000** [comment]
Yeah I'm using the SHIFT key to open the image/video in a new tab. Works great. Oh and I use the script in TamperMonkey, not the extension. I've found that works best for me. Thanks, I'll stop spamming up this thread now lol

**Comment by qsniyg** [comment]
IG should work for most browsers now (any browser supporting `BigInt`).

If you enable "Instagram: Use Native API" (recommended), please enable "Instagram: Don't use web API" as well.

**Comment by qsniyg** [comment]
@GTR8000 That's really strange. Do you have multiple versions of the script installed (e.g. userscript and extension, or two different userscript managers, etc.), by any chance? In theory, `Instagram: Use native API` should toggle whether or not it uses API calls, so disabling it should return the 1440x1800 image that's on the page (if for some reason the API call returns the 1080x1350 version instead).

If you're sure there's only one version installed, could you send the post you're trying to access, as well as your settings (options->export->save)?

**Comment by GTR8000** [comment]
Only the script is installed in TamperMonkey...I deleted the extension months ago and double checked that it's only the one instance installed.

This could well be a "me" problem at this point, as I'm running Waterfox Classic 2021.08.1. I'm not sure if you're familiar, but it's built on an older version of Firefox. The script has always worked fine, up until the recent changes Instagram made, and now with the updates to the script it seems to have trouble pulling the max resolution version. Script works great with all other sites, so if I have to open up the Page Info/Media tab to download the occasional Instagram post, that's fine.

I will email you the stuff you've asked for tomorrow. Thanks!

**Comment by qsniyg** [comment]
Ah yes it could be due to Waterfox. Sorry I glossed over that when you wrote it at first.

Could you try running `a=5n` and `BigInt(5)` in the console (F12) and send a screenshot of the console output? If it fails, then that is indeed the problem.

I'll try to find another way to support it regardless, I don't want to deprecate old browsers :)

**Comment by GTR8000** [comment]
**BigInt is not supported in your browser**

**Comment by GTR8000** [comment]
Emailing you a console dump now, standby

**Comment by qsniyg** [comment]
@GTR8000 Hmm, no mention of the library. Is "Allow 3rd-party libraries" enabled?

**Comment by qsniyg** [comment]
@GTR8000 Ah no wonder, I made a typo. Please try again :)

**Comment by GTR8000** [comment]
Bam, works now, 1440x1800 image opening in a new tab! You're the man, thanks for working so hard to support fools like me running ancient browsers LOL

For anyone else having similar issues, grab the latest userscript.user.js and make sure the following two options are enabled:

Allow 3rd-party libraries = **YES**
Instagram: Use native API = **YES**

**Comment by GTR8000** [comment]
Until IG breaks something again LOL! Thanks again, VERY much appreciated!
