### ISSUE TITLE
www.acplasticsinc.com

### ISSUE THREAD

**Issue by ayunami2000** [qsniyg/maxurl#1030]
https://www.acplasticsinc.com/image?filename=good-things-about-plasic.jpg&width=1060&height=300

also this website isnt really that well built, it has no cap for image max size... so if its down or not loading it could be i typed a very large number as the width/height...

**Comment by qsniyg** [comment]
I've supported it by just removing the width/height queries, I'm not sure if this is the maximum size, but it appears to work.
