### ISSUE TITLE
Add www.sq-lab.com support

### ISSUE THREAD

**Issue by TheLastZombie** [qsniyg/maxurl#1034]
Possibly used by other shops as well, but I haven't found any thus far.

- Resized:
  - https://www.sq-lab.com/out/pictures/generated/product/1/390_195_75/sqlab.sattel.6ox.infinergy.ergowave.active.2.1.main.jpg
  - https://www.sq-lab.com/modules/ajaxzoom/ajaxzoom/pic/zoomthumb/s/q/sqlab.sattel.6ox.infinergy.ergowave.active.2.1.main_1200x1200.jpg
- Original:
  - https://www.sq-lab.com/out/pictures/master/product/1/sqlab.sattel.6ox.infinergy.ergowave.active.2.1.main.jpg

**Comment by qsniyg** [comment]
Thank you very much as usual! The rule might be too tight, but it works for the images you've sent.
