### ISSUE TITLE
Incompatibility with Violentmonkey BETA v2.13.0.11 and above

### ISSUE THREAD

**Issue by brian6932** [qsniyg/maxurl#1037]
This was the reason given: https://github.com/violentmonkey/violentmonkey/issues/1502#issuecomment-1128080983

**Comment by qsniyg** [comment]
Can you see if the latest commit fixes it? https://github.com/qsniyg/maxurl/commit/5a80e1dbfc09332ae09e244baa011fb41327ee0e

**Comment by brian6932** [comment]
Fixed
