### ISSUE TITLE
[site] fastly.com

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#1038]
`https://www.fastly.com/cimages/6pk8mg3yh2ee/4zLuDTDqRq5H2Nuj8Ch0jB/d51cd0d20e0881043bec5c84151f1f4f/hero-laptop_1.png?auto=webp&fit=contain&height=345&width=626`
>> 
`https://www.fastly.com/cimages/6pk8mg3yh2ee/4zLuDTDqRq5H2Nuj8Ch0jB/d51cd0d20e0881043bec5c84151f1f4f/hero-laptop_1.png`
(via `https://www.fastly.com`)

**Comment by qsniyg** [comment]
Thank you very much as usual!

**Comment by dym-sh** [comment]
np, kinda strange that did not get caught by regular patterns

**Comment by qsniyg** [comment]
Many websites using fastly are supported, but fastly.com itself wasn't :)

**Comment by dym-sh** [comment]
also, thanks for the invite :D

cant promise much, but i'll try to help out whenever i can :+1:

**Comment by qsniyg** [comment]
Thank you! You've helped a lot already :) I'm less capable of maintaining this repository nowadays (as you've probably noticed), so I figured it would be if I weren't the sole bottleneck for the project.
