### ISSUE TITLE
[Site] wx.qlogo.cn

### ISSUE THREAD

**Issue by doio** [qsniyg/maxurl#1039]
`https://wx.qlogo.cn/mmhead/l9wBIj25RSIYlPTnn3LJQtvc6MtvYQic0MoR91agezsw/132`
➜
`https://wx.qlogo.cn/mmhead/l9wBIj25RSIYlPTnn3LJQtvc6MtvYQic0MoR91agezsw/0`

Similar to `mmbiz.qpic.cn`

**Comment by qsniyg** [comment]
Thank you very much! Supported

**Comment by doio** [comment]
Hi!

There's an another kind like this on the domain:

`http://wx.qlogo.cn/mmopen/aXUpZVUYfjw3n5ZtyC7CB16NMTmib2QqWiaEz4c1hbtIY39AMVnopBrliadL0sgKgItyMTadNTLUMyqAq1yyuicx4F8PQD69KxdC/96`
➜
`http://wx.qlogo.cn/mmopen/aXUpZVUYfjw3n5ZtyC7CB16NMTmib2QqWiaEz4c1hbtIY39AMVnopBrliadL0sgKgItyMTadNTLUMyqAq1yyuicx4F8PQD69KxdC/0`

**Comment by qsniyg** [comment]
Thanks! It should already work for it, but I've added it as another example/test URL in case the rule changes :)
