### ISSUE TITLE
cdn.donmai.us - not working with some url patterns

### ISSUE THREAD

**Issue by aslian** [qsniyg/maxurl#1040]
An URL pattern on cdn.donmai.us currently is not being handled by the script.

The URL:
https://cdn.donmai.us/sample/0b/32/sample-0b325822cc92a57e28303acf91a557ca.jpg

Should redirect to:
https://cdn.donmai.us/original/0b/32/0b325822cc92a57e28303acf91a557ca.jpg

Thank you for the great project! It's very helpful.

**Comment by qsniyg** [comment]
Thank you very much! Should be supported now :)

**Comment by aslian** [comment]
That was fast!

**Comment by aslian** [comment]
@qsniyg

**Comment by qsniyg** [comment]
Sorry for getting back so late. It should be fixed (again) now.
