### ISSUE TITLE
i.im.cz

### ISSUE THREAD

**Issue by ayunami2000** [qsniyg/maxurl#1041]
https://i.im.cz/a/c3B3aWxsaWFtc2lhbUBnbWFpbC5jb20AYXl1bmFtaTIwMDAA/40?r2=0.4934940655797597

Appears to provide full-size image when no size is specified. Also appears to resize it to larger than original size if specified as well.

URL of what I believe to be the max resolution: https://i.im.cz/a/c3B3aWxsaWFtc2lhbUBnbWFpbC5jb20AYXl1bmFtaTIwMDAA

**Comment by qsniyg** [comment]
Thanks, supported! The slug is base64... try `atob(...)`ing it :)

**Comment by ayunami2000** [comment]
Yeah lmao I noticed that, was glad it wasn't anything more though
