### ISSUE TITLE
(Fully) support poipiku

### ISSUE THREAD

**Issue by contextnerror** [qsniyg/maxurl#1043]
Currently using the popup on an image thumbnail will get a larger version of the thumbnail, instead of the full image.

Example page: https://poipiku.com/1730391/6923507.html
Thumbnail: https://img.poipiku.com/user_img00/001730391/006923507_LCCtJd0Fq.jpeg_640.jpg
Full size: https://img-org.poipiku.com/user_img00/001730391/006923507_LCCtJd0Fq.jpeg

**Comment by qsniyg** [comment]
Thanks! Supported :)
