### ISSUE TITLE
Firefox extension not updated

### ISSUE THREAD

**Issue by DisasterInbound** [qsniyg/maxurl#1044]
Hello

I was wondering if you had plans to update the extension that is on their extension store, or if you are only planning to release it on userscript moving forward. 

I know there is the option of sideloading the extension but since it seems it only works temporarily (until the app is closed) I was looking for a proper extension that could be installed.

Thanks.

**Comment by qsniyg** [comment]
I would like to do so eventually, but I'm not sure when/how. I'm considering trying an unlisted nightly build, maybe that will be easier. I've given a little more detail here: https://github.com/qsniyg/maxurl/issues/1048#issuecomment-1170554322

**Comment by DisasterInbound** [comment]
Thank you for the update. 

I've read and I totally understand your point on this issue. I'm okay with using the userscript instead of the extension however, I would like to know what are the differences and which features are not available on it, since you mentioned there are some features available only on the extension.

**Comment by qsniyg** [comment]
Oops, forgot to close this one. FF releases are resumed now :)
