### ISSUE TITLE
extension and userscript work on flickr photostream but not on flickr photo page

### ISSUE THREAD

**Issue by radam9** [qsniyg/maxurl#1052]
Hey there,
First I wanna thank you for the extension, it is great and I have been using it a lot!

I have been using the extension a lot with Flickr and it has been working just fine.
Just recently (about 2 weeks ago) I started having issues with it.
I tested the issue on Firefox and Chrome using the Extension and Userscript but it didn't work with any combination.

The extension works just fine on any image in the following URL (ex: https://www.flickr.com/photos/skymatthews/), but it doesn't work in this URL (ex: https://www.flickr.com/photos/skymatthews/40089706483/) anymore (it did in the past).

**Comment by qsniyg** [comment]
Thanks for reporting! It should be fixed now :) The issue is that they've added `pointer-events: none` to their `<img>` tags.

I believe setting `Element finding mode` to `Full` would have also worked around the issue, but I wouldn't recommend using it (for issues detailed in the warning when enabling that option).

**Comment by radam9** [comment]
Great!
I tested it with the Userscript and it is working, but it is not working with the extension on Firefox.
Do I need to do something to load the newest changes, or do I have to wait for the next release?
Thanks

**Comment by qsniyg** [comment]
Yes, you'll need to sideload the development version: https://github.com/qsniyg/maxurl#sideloading-the-extension . Don't use the XPI yet, as it hasn't been updated.

**Comment by radam9** [comment]
Ohh, great!
thanks a lot.
