### ISSUE TITLE
Another Ebay rule

### ISSUE THREAD

**Issue by qsniyg** [qsniyg/maxurl#1068]
Thanks to ABCFE on discord:

I would like to add my own rule. I have not found anything in the settings for this.
So for example that, here:
https://www.ebay-kleinanzeigen.de/s-anzeige/canon-imagerunner-drucker/2211175347-225-3120
`https://img.ebay-kleinanzeigen.de/api/v1/prod-ads/images/86/86687f14-c485-41ea-a0fe-8afd446babe9?rule=$_59.JPG`
 the preview image has maximum size by changing $_59.JPG to $_57.JPG or $_59.PNG to $_57.PNG.

**Comment by TheLastZombie** [comment]
I wrote a quick Bash script to check all suffixes between 0 and 100. Seems like 57 is indeed the highest resolution, but it might prove helpful in the future anyway, so here it is:

<details>

<summary>Script</summary>

```Shell
#!/usr/bin/env bash

mkdir img.ebay-kleinanzeigen.de
cd img.ebay-kleinanzeigen.de

for i in {0..100}
do
	wget -q "https://img.ebay-kleinanzeigen.de/api/v1/prod-ads/images/86/86687f14-c485-41ea-a0fe-8afd446babe9?rule=\$_$i.JPG" -O "$i.JPG" && \
	gm identify -format "$i: %P" "$i.JPG"
done

cd -
rm -r img.ebay-kleinanzeigen.de
```

</details>

<details>

<summary>Output</summary>

```
0: 72x96
1: 300x400
2: 150x200
3: 600x800
6: 53x70
7: 113x150
8: 225x300
9: 113x150
12: 375x500
14: 48x64
16: 225x300
18: 150x200
19: 300x400
20: 450x600
21: 375x500
22: 45x60
23: 60x80
24: 224x298
26: 105x140
27: 360x480
32: 750x1000
34: 38x50
35: 225x300
37: 131x175
39: 24x32
45: 900x1200
56: 75x100
57: 1200x1600
58: 480x640
59: 720x960
62: 169x225
72: 281x375
75: 244x325
85: 545x726
86: 768x1024
90: 165x220
97: 68x90
```

</details>
