### ISSUE TITLE
How to disable popup warning?

### ISSUE THREAD

**Issue by despecial** [qsniyg/maxurl#1078]
Not sure why this message keeps popping up when I view a single image (already original file)
<img width="597" alt="Bildschirmfoto 2022-10-17 um 13 06 30" src="https://user-images.githubusercontent.com/4135109/196162150-51380ded-fcf3-4313-a2ef-c4c47eb8c501.png">

I do not want to use this feature but it keeps showing me this warning. Please remove it or let me know how to deactivate it.
Even if I enable it it shows this message, saying Alt+Shift+i is needed. (Trigger mode: key)

**Comment by qsniyg** [comment]
Disable "Enable tooltip" under "Redirection" :)
