### ISSUE TITLE
olx group

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1079]
olx group includes couple of websites
main:
https://www.olx.ua/
https://www.olx.bg/
https://www.olx.pl/
https://www.olx.ro/
https://www.olx.pt/
https://www.olx.co.id/
https://www.olx.in/

others:
https://obido.pl/
https://renew.olx.in/
https://www.321sprzedane.pl/
https://www.autotrader.co.za/
https://www.autovit.ro/
https://www.imovirtual.com/
https://www.letgo.com/
https://www.olxautos.cl/
https://www.olxautos.com.ar/
https://www.olxautos.com.co/
https://www.olxautos.com.mx/
https://www.otodom.pl/
https://www.otoplus.com/
https://www.property24.com/
https://www.standvirtual.com/
https://www.storia.ro/
https://www.webuyanycarusa.com/

their image urls have identical pattern

https://ireland.apollo.olxcdn.com/v1/files/6dxjbzpofcc23-UA/image;s=100x100
https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImNxYTBpaGU4dHozMzItQVVUT1ZJVFJPIiwidyI6W3siZm4iOiJxN216NTNiaWZwemstQVVUT1ZJVFJPIiwicyI6IjE2IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.uO-XJYmuH6VVb4HLXTLJs5c3rKw7SeTIltsNx-QjCUM/image;s=148x110
https://apollo-ireland.akamaized.net/v1/files/7a4ysqoowqvx1-OLXAUTOTR/image;s=300x600;q=60

I figured out that max image opens if size value is maxed for ex. 9999x9999 (with removed quality value):

https://ireland.apollo.olxcdn.com/v1/files/6dxjbzpofcc23-UA/image;s=9999x9999
https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6ImNxYTBpaGU4dHozMzItQVVUT1ZJVFJPIiwidyI6W3siZm4iOiJxN216NTNiaWZwemstQVVUT1ZJVFJPIiwicyI6IjE2IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.uO-XJYmuH6VVb4HLXTLJs5c3rKw7SeTIltsNx-QjCUM/image;s=9999x9999
https://apollo-ireland.akamaized.net/v1/files/7a4ysqoowqvx1-OLXAUTOTR/image;s=9999x9999

sad thing is that they have quite a lot of images servers, I have no idea if it possible to parse them, but if there is a way that would be great.
also they have the one common feature, each url (that I saw) contains "olx"

ps thx for this script. it helps me very much with my job 👍

**Comment by talizea** [comment]
`;s=0x0;f=jpeg`

That gets the full resolution (slightly more elegant than 9999x9999) and higher bitrate jpg instead of webp.

**Comment by karpuzikov** [comment]
Thanks for tip. Isn't png be better?

**Comment by qsniyg** [comment]
Thanks! Turns out a similar rule already existed, but it wasn't as well supported (it just removed `;.*` rather than replacing it with `;s=0x0`)
