### ISSUE TITLE
panasonic.com 2nd pattern

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1080]
this kind of URLs works if remove characters after "*name.png"
https://www.panasonic.com/content/dam/pim/ua/uk/en/eneloo/eneloop%20pro/ast-1198632.png.pub.thumb.644.644.png
https://www.panasonic.com/content/dam/pim/ua/uk/en/eneloo/eneloop%20pro/ast-1198632.png

**Comment by qsniyg** [comment]
Thanks! Supported
