### ISSUE TITLE
bhphotovideo.com

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1083]
https://static.bhphoto.com/images/images150x150/1547727640_1453015.jpg

max size (allegedly) opens if size value change to 2500x2500

https://static.bhphoto.com/images/images2500x2500/1547727640_1453015.jpg

**Comment by qsniyg** [comment]
Thanks! There is another pattern (`/images/multiple_images/images500x500/`), which I haven't supported yet, as many images under the `multiple_images` folder don't support `2500x2500`. Likely the best solution would be to try common sizes (`2500x2500`, `2000x2000`, etc.) and see which ones work for the image.
