### ISSUE TITLE
Site: induna.com

### ISSUE THREAD

**Issue by tathastu871** [qsniyg/maxurl#1084]
Thumbnail URL
```
https://www.induna.com/uploaded_images/dvd_vcd_master/thumbnails/01_07_00_dvd%2024.jpg
```
![01_07_00_dvd 24 (2)](https://user-images.githubusercontent.com/65007212/197811274-53ac26dd-2d97-4ac4-a745-a13adecfe9b7.jpg)

Preview URL:
```
https://www.induna.com/uploaded_images/dvd_vcd_master/medium/01_07_00_dvd%2024.jpg
```
![01_07_00_dvd 24](https://user-images.githubusercontent.com/65007212/197810614-da62b5cf-2c5d-4f6f-82ab-a7cda55c1aac.jpg)

MAX_URL:
```
https://www.induna.com/uploaded_images/dvd_vcd_master/original/01_07_00_dvd%2024.jpg
```
![01_07_00_dvd 24 (1)](https://user-images.githubusercontent.com/65007212/197811914-bce1872d-e38b-48cb-9707-f019e264ecad.jpg)

Change thumbnails or medium --> original

But due to cloudfare protection image cannot be downloaded using curl or wget

But can be opened in browser and downloaded using save image as

**Comment by tathastu871** [comment]
@qsniyg

**Comment by qsniyg** [comment]
Thank you very much for your detailed descriptions! I've added this and two others you've mentioned
