### ISSUE TITLE
Site: maniadb.com

### ISSUE THREAD

**Issue by tathastu871** [qsniyg/maxurl#1087]
Thumnail Url:
```
http://i.maniadb.com/images/album_t/80/968/968531_1_f.jpg
```
![968531_1_f](https://user-images.githubusercontent.com/65007212/197827007-1356dd5f-6a94-41f0-9db8-de32a52401f6.jpg)

Preview Url: 
```	http://i.maniadb.com/images/album_t/260/968/968531_1_f.jpg
```
![968531_1_f (1)](https://user-images.githubusercontent.com/65007212/197827047-5fa0ad3d-9cb5-432e-bc5d-0efac4de665a.jpg)

Max Url:
```
http://i.maniadb.com/image.php?path=/images/album/968/968531_1_f.jpg
```
![image](https://user-images.githubusercontent.com/65007212/197827075-9ecd90b5-09db-4d8a-bef7-6cef84c513db.png)

**Another Endpoints**  

Artist:  
http://i.maniadb.com/images/artist_t/260/.*
http://i.maniadb.com/images/artist_t/80/.*

** REPLACE**   
 /artist_/[0-9]+/  OR /album_/[0-9]+/ ---> /artist/ OR /album

**Note: FOR MAX URL: 2 endpoints** 
1).
```
http://i.maniadb.com/image.php?path=/images/album/968/968531_1_f.jpg
```
OR
2). 
```
http://i.maniadb.com/images/album/968/968531_1_f.jpg
```
FOR SOME IMAGE 1). WORKS AND FOR SOME 2). WORKS

**IMP NOTE**  
**FOR max url extension is .jpg but downloaded file be corrupted. Hence after downloading it has to be renamed from .jpg to .png** 
**Replacing .jpg to .png in URL --> may work and downloaded png will be viewable but its  header will be corrupted hence metadata can't be read**

**Comment by tathastu871** [comment]
@qsniyg

**Comment by tathastu871** [comment]
Aso update to work in https://qsniyg.github.io/maxurl/

**Comment by tathastu871** [comment]
Add above all support to

https://qsniyg.github.io/maxurl/

**Comment by TheLastZombie** [comment]
The website will be updated as soon as https://github.com/qsniyg/maxurl/pull/1069 is merged. For now, you can use the userscript instead (make sure to install it from [here](https://github.com/qsniyg/maxurl/raw/master/userscript.user.js)).
