### ISSUE TITLE
asus.com

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1090]
full size image opens if size and format values remove
https://dlcdnwebimgs.asus.com/gain/4008fdce-f050-4a02-980c-299cdd100c20/w80/fwebp
https://dlcdnwebimgs.asus.com/gain/4008fdce-f050-4a02-980c-299cdd100c20/

**Comment by qsniyg** [comment]
Sorry for getting to this so late. Supported, thanks for reporting!

**Comment by karpuzikov** [comment]
❤

**Comment by karpuzikov** [comment]
another patterns
3 values
https://dlcdnwebimgs.asus.com/gain/442388A8-C91B-4EC5-952F-4AC5931A09A1/w717/h525/w292
2 values
https://dlcdnwebimgs.asus.com/gain/DCD48CA3-52FF-41AC-89EF-F2E9FD3E4F05/w100/h100

**Comment by qsniyg** [comment]
Thanks, fixed! The issue was simply that uppercase GUIDs weren't supported :)
