### ISSUE TITLE
shueisha.online

### ISSUE THREAD

**Issue by Andy8r0X** [qsniyg/maxurl#1091]
from site: https://shueisha.online/business/14881
https://assets.shueisha.online/image/2022/05/16083443333424/800/0374_009.jpg

Maximum image size(as far as I can find): /1600/
https://assets.shueisha.online/image/2022/05/16083443333424/1600/0374_009.jpg

url must referrer to: https://shueisha.online/

**Comment by qsniyg** [comment]
Thanks! Supported :)

Looks like the full version is available at `https://assets.shueisha.online/image/-/2022/05/16083443333424/0/0374_009.jpg`
