### ISSUE TITLE
Getty Images no longer return full image

### ISSUE THREAD

**Issue by chr1sx** [qsniyg/maxurl#1092]
[Getty](https://github.com/m-rots/getty) utility still provides full image, so there is a workaround.

**Comment by qsniyg** [comment]
Could you send the image you tried? It works for me, but currently it will only redirect images that don't have any URL parameters after it. There is a way to fix it (redirect if `w=0` doesn't exist), but I haven't implemented it yet.

**Comment by chr1sx** [comment]
Every image that I open have url parameters now, for example: 
https://www.gettyimages.com/detail/photo/inflatable-tube-ghost-balloon-image-libre-de-droits/1429418112
https://media.gettyimages.com/id/1429418112/photo/inflatable-tube-ghost-balloon.webp?s=1024x1024&w=gi&k=20&c=Iuzpr-LeVrAzlubNp1S_AcBRGJDLsDp4_vwjKrAzPak=

**Comment by qsniyg** [comment]
This should now be fixed. Please let me know if it doesn't work.

**Comment by chr1sx** [comment]
Thank you for looking into this, unfortunately does not seem to work.
Addon redirects me to 469x369 image:
https://media.gettyimages.com/id/1429418112/photo/inflatable-tube-ghost-balloon.jpg?s=170667a&w=0&k=20&c=o__Z7_fExkbdrlN1n_1VqA5YXgW5N_gkHSnccQFvPN4=
2048x1069 is the max:
https://media.gettyimages.com/id/1429418112/photo/inflatable-tube-ghost-balloon.jpg?s=2048x2048&w=gi&k=20&c=ypPNkncbkl0EhQn-_kPBjMcEbvg4qCATWCyWqIrwO7c=

**Comment by qsniyg** [comment]
Can you send me your settings? That's interesting, because I can't even find the 469x369 link on my end.
