### ISSUE TITLE
Kemono Party

### ISSUE THREAD

**Issue by BrandonKMLee** [qsniyg/maxurl#1093]
Test page: https://kemono.party/patreon/user/33422522/post/48314137
test image: https://kemono.party/thumbnail/data/ff/71/ff717529dfe93a3bdf8ede16ebb203dc63d129f7029a13c18996cac78502a2b2.jpg
test endpoint: https://kemono.party/data/ff/71/ff717529dfe93a3bdf8ede16ebb203dc63d129f7029a13c18996cac78502a2b2.jpg?f=Akio%20Plugsuit.jpg

**Comment by qsniyg** [comment]
Thanks! Fixed :)
