### ISSUE TITLE
Houzz - st.hzcdn.com

### ISSUE THREAD

**Issue by Kerobyte** [qsniyg/maxurl#1094]
Low res: https://st.hzcdn.com/simgs/pictures/living-rooms/award-winning-shingle-style-victorian-renovation-main-line-gardner-fox-associates-inc-img~3a21260d02a75ac5_4-5874-1-195fa82.jpg
Max res(?): https://st.hzcdn.com/simgs/pictures/living-rooms/award-winning-shingle-style-victorian-renovation-main-line-gardner-fox-associates-inc-img~3a21260d02a75ac5_14-5874-1-195fa82.jpg

The current rule used by Max URL doesn't apply to this URL scheme.
```
if (domain === "st.hzcdn.com") {
	// https://st.hzcdn.com/fimgs/4da1bc970046413d_0612-w74-h74-b0-p0--home-design.jpg
	//   https://st.hzcdn.com/simgs/4da1bc970046413d_4-0612.jpg
	//   https://st.hzcdn.com/simgs/4da1bc970046413d_14-0612/transitional-kitchen.jpg
	// 14, 9, 4, 15, 8, 10, 11, 3, 13, 7, 2, 6, 1, 12, 5, 0
	return src
		.replace(/\/fimgs\/([0-9a-f]+)_([0-9]+)-[^/]*(\.[^/.]*)$/, "/simgs/$1_14-$2$3")
		.replace(/(\/simgs\/[0-9a-f]+)_[0-9]+(-[0-9]+[./])/, "$1_14$2");
```

**Comment by qsniyg** [comment]
Thank you! Fixed :)
