### ISSUE TITLE
sites using 00.jpg and orig_00.jpg

### ISSUE THREAD

**Issue by jedikalimero** [qsniyg/maxurl#1095]
Lately there are many sites that show an image called 00.jpg (or whatever number in a series) and then there is a link to open a full image that goes in the format orig_00.jpg (the original name with the suffix orig_).

Sometimes there is no link but the image exists and then Maxurl fail to fetch this bigger image, so Maxurl should search for this image even if there is no link for it because more often than not, the image exists.

Weirdly, sometimes the 00.jpg is bigger than orig_00.jpg and sometimes it depends on the image being in portrait or landscape mode.

Here is an example URL where Maxurl fails to find that larger image that is not linked but exists:
[NSFW](https://www.nightdreambabe.com/veronica-rodriguez-in-hardcore-action)

**Comment by qsniyg** [comment]
I've supported it for some websites. Currently it's opt-in, as many of these sites don't support it. I was unable to find an example where `orig_00` is smaller than `00`, if you find one, could you send it? If it's NSFW, please send it privately as I try not to have public-facing NSFW links in the repository (my contact info is available at https://qsniyg.github.io/)
