### ISSUE TITLE
`imgsrc.baidu.com` should be used for original pictures on `tiebapic.baidu.com`

### ISSUE THREAD

**Issue by n0099** [qsniyg/maxurl#1100]
Currently neither https://tiebapic.baidu.com/forum/pic/item/4ba6b7fd5266d016e17995ecd22bd40734fa350b.jpg?tbpicau=2022-12-25-05_2ae0f8dbe307e91d5228fb7b90bdc060 nor https://tiebapic.baidu.com/forum/pic/item/4ba6b7fd5266d016e17995ecd22bd40734fa350b.jpg (without the `tbpicau` query string param) will give the original image, it will only output this placeholder:
![image](https://user-images.githubusercontent.com/13030387/209225544-c13d826b-2dc6-4aae-b640-9f9ee0247836.png)

run the following bash can verify this:
```bash
curl -s -w '%{stderr}%{time_total}s\n' 'https://tiebapic.baidu.com/forum/pic/item/4ba6b7fd5266d016e17995ecd22bd40734fa350b.jpg?tbpicau=2022-12-25-05_2ae0f8dbe307e91d5228fb7b90bdc060' | identify -
curl -s -w '%{stderr}%{time_total}s\n' 'https://tiebapic.baidu.com/forum/pic/item/4ba6b7fd5266d016e17995ecd22bd40734fa350b.jpg' | identify -
```
![image](https://user-images.githubusercontent.com/13030387/209248811-82dd2b38-dfeb-458b-bb36-f91dac830500.png)

So it should be redirected to the historical domain `https://imgsrc.baidu.com/forum/pic/item/4ba6b7fd5266d016e17995ecd22bd40734fa350b.jpg` which doesn't require the `tbpicau` param and works fine as it had been.

Detailed differences between these two domains can be found at https://github.com/Starry-OvO/aiotieba/pull/63#issuecomment-1363476824 (in chinese)

**Comment by qsniyg** [comment]
Thank you very much for the detailed report! Fixed :)

**Comment by n0099** [comment]
Did changes from the commit d764b072bf0bba8c3a182f721027e4290600e7d9 appear in the latest release? I'm still getting redirected to the `tiebapic.baidu.com` domain.

**Comment by qsniyg** [comment]
@n0099 There have been no stable releases since June 2021, you'll need to sideload the git repository for it to be updated.

**Comment by qsniyg** [comment]
@n0099 Yes, you'll need to use https://raw.githubusercontent.com/qsniyg/maxurl/master/userscript.user.js instead. Sorry, I should remove the greasyfork link from the repo.

**Comment by n0099** [comment]
Currently the domain `imgsrc.baidu.com` requires a request header `Referer: https://tieba.baidu.com`: https://github.com/lumina37/aiotieba/pull/63#issuecomment-2447263162
