### ISSUE TITLE
medibang.com (ART Street)

### ISSUE THREAD

**Issue by contextnerror** [qsniyg/maxurl#1101]
Post link: https://medibang.com/picture/4b2112261505098280008769655/
Thumbnail link: https://dthezntil550i.cloudfront.net/4b/latest/4b2112261505098280008769655/1280_960/d5b22a94-4864-45d5-96e7-cbca9e0043f4.png
Full size link: https://dthezntil550i.cloudfront.net/4b/latest/4b2112261505098280008769655/dd808367-6027-42bb-b458-1500e7774d8d.png

Using the popup after clicking the image to expand will retrieve the full sized version, otherwise it just fetches the thumbnail.

**Comment by qsniyg** [comment]
Thanks! Fixed
