### ISSUE TITLE
Always open a new tab？

### ISSUE THREAD

**Issue by s3327445** [qsniyg/maxurl#1102]
I don’t know which setting to move to.
 Now I keep opening new tabs. 
It doesn’t work after reinstalling.
 Can the author give me the default setting file？
 thank you

**Comment by qsniyg** [comment]
The setting that changes the behavior is is `Popup action`.

To reset the settings to default, just import `{}` (press Import, then type `{}` in the text box, then click on the lower Import button).

**Comment by qsniyg** [comment]
Closing as I believe the information I provided should answer the question. Please let me know if you need more help though :)
