### ISSUE TITLE
yt3.googleusercontent.com - Fix support for YouTube Channel Banner/Cover

### ISSUE THREAD

**Issue by BarnMTB** [qsniyg/maxurl#1103]
Example of a YouTube Channel Banner/Cover image 
(via Right-click & Open image in new tab): `https://yt3.googleusercontent.com/UXRO2yDJDJM0BZxkTidsLpU87N4eoFj7iMqi7rF3emmIfbcIqNkTZ4eT_hKhA62A52Frgn1VPvQ=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj`

If you opened the mentioned URL in a new tab, it currently does not replace the URL with the one that provides the full version of the image, which could look something like this:
`https://yt3.googleusercontent.com/UXRO2yDJDJM0BZxkTidsLpU87N4eoFj7iMqi7rF3emmIfbcIqNkTZ4eT_hKhA62A52Frgn1VPvQ=s0?imgmax=0`

Note: Channel Profile image still works as expected
(Example of a Channel Profile Image: `https://yt3.ggpht.com/ytc/AMLnZu8GQ7FPSdjojM1D2CBGdbWcSmuxR3k9gfdxgy9S=s88-c-k-c0x00ffffff-no-rj`)

**Comment by qsniyg** [comment]
Can you try with https://github.com/qsniyg/maxurl/commit/eee88442a7a691d5444df510ee5407084744be1c ?

**Comment by BarnMTB** [comment]
Thank you. I reinstalled the Userscript with the latest version via Github and the link in the example now redirects correctly, so now I'm not describing Userscrpt/Edge version as everything now works correctly. 
(Reinstalled by opening Github Raw file and selecting Reinstall in the dialog)

Prior to reinstallation, the Userscript was installed via Github
- Userscript version 0.19.5
- Tampermonkey v.4.16.1 
- Edge v.108.0.1462.54 (Release, x64)

The Firefox version still does not work correctly on my end
- Extension version 0.19.5
- Firefox Extension
- Firefox Developer Edition 109.0b7 (Beta, x64)

While testing with Firefox I noticed that when the Channel Cover was hosted on `yt3.ggpht.com` the redirect works fine but not `yt3.googleusercontent.com` consistently
(Tested on a new clean Firefox profile with no configuration.)
This is also an issue on `qsniyg.github.io/maxurl/` (Tested with extension/userscript disabled)

For example, these channel cover does not work:
- https://yt3.googleusercontent.com/UXRO2yDJDJM0BZxkTidsLpU87N4eoFj7iMqi7rF3emmIfbcIqNkTZ4eT_hKhA62A52Frgn1VPvQ=w2120-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj
- https://yt3.googleusercontent.com/UktSbUmViaeJ8mZi1jpT5ETuAbzm4a27ejlydHGr8Zvz7IxxDTIw3qOWFG0D7ry0f8i1HkisYg=w2120-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj
- https://yt3.googleusercontent.com/CCHyHCW_ahamls2LlyUHUrtBgHDH4WSdo4N0yfNtVxtOjcKvsVnkajpewSUm8XcmHl-O4P0h=w2120-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj

But these works properly:
- https://yt3.ggpht.com/FgfS5-kLU4LroyKomx1Z-W_UxVzPo4iWwioMuOsg8S74wMXbpTg3vh1_PC_tJABz6AZVQ1zNiQ=w2120-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj
- https://yt3.ggpht.com/nPWwkq9VnlXcO8L_m_Zq43LybkGzeC8amzC-pLw8UcAZADRtO6Nh0jSUmsMp_SmzRMpwcyGZ=w2120-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj

**Comment by qsniyg** [comment]
Sorry, yeah, the extension version hasn't been updated yet. I've just updated the website version, but it may take ~10 minutes for GitHub's cache to use the new version.
