### ISSUE TITLE
Access imgur images

### ISSUE THREAD

**Issue by eightyy8** [qsniyg/maxurl#1106]
i.imgur.io and .com full scale images can be accessed just by adding _?maxwidth=90000&fidelity=high_ to the end (i.imgur.io/XxXxXxX_d.filetype?maxwidth=90000&fidelity=high)

"&shape=" doesn't give any benefits to the images quality.

_Example_:

- **Default**
https://i.imgur.io/MzDoRsM_d.webp?maxwidth=640&shape=thumb&fidelity=medium

- **No specs**
https://i.imgur.io/MzDoRsM_d.webp

- **Modified**
https://i.imgur.io/MzDoRsM_d.webp?maxwidth=90000&fidelity=high

**Comment by eightyy8** [comment]
The _maxwidth_ doesn't have to be 90000 it's just assuring the maximum size.
It would be helpful to know the maximum image resolution that imgur allows to be sure..

**Comment by qsniyg** [comment]
Thanks, fixed! You can get the original version by just removing `_d` :)

**Comment by eightyy8** [comment]
> Fixed!

I think you missed the &shape= part
(https://i.imgur.io/MzDoRsM_d.webp?maxwidth=640&shape=thumb&fidelity=medium)

Appreciate it. 🙌

**Comment by qsniyg** [comment]
Sorry I don't understand. What does the shape part do? IMU redirects the link to https://i.imgur.com/MzDoRsM.png, which is 2000x1800 (the `maxwidth=90000` link is 1920x1728).

**Comment by eightyy8** [comment]
> What does the shape part do? IMU redirects the link to https://i.imgur.com/MzDoRsM.png

Sorry, I presumed that parameter was necessary because of the other imgur .com URL working, as it included that shape parameter that the .io didn't have, after I found it not seeming to work (on the site). The site probably isn't using the latest commits...

![shape.png](https://user-images.githubusercontent.com/64216434/211063722-24cdeb85-629f-48d1-b81e-ee446631da5f.png)

Also, you can only use .webp when you remove the parameters because if you use .png or other file types it will redirect you back to the image's page on the feed

**Comment by qsniyg** [comment]
Thanks! I've tracked the webp fallback in a new issue. And yes, the website hasn't been updated yet.
