### ISSUE TITLE
images.apkeasy.me / img.apkeasy.com

### ISSUE THREAD

**Issue by eightyy8** [qsniyg/maxurl#1110]
Came across this generic APK download site. Even though I've seen IMU redirect similiar URLs it doesn't seem supported. I tried fiddling around with it, unsuccessful.

Example of the two unique image URLs it uses across the site:

https://images.apkeasy.me/hidden-settings-banner/fill/640/360/no/1/aHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tLzRlTE5oeFZHTXp2eExOVDV2RkVWcGZlTmIyUHNyU0FSR2tJYVFtNVByOXloUWRfZVgxWXhsMkJKVDd6eUdUNUxiSk1DPXcxMDAw

https://img.apkeasy.com/screenshot-0/fill/0/620/no/1/aHR0cHM6Ly9wbGF5LWxoLmdvb2dsZXVzZXJjb250ZW50LmNvbS9JbVdZQmN6SFNlbVhXa2hVNmpBc2lFREpNbWFjY2wtYnRXcnpMT1c2VXktOUhhQmY2S3dxbDYwR1dTal9pM0MxZmc9dzE0NDAtaDYyMA==.webp

_Both image URLs from_: https://apkeasy.com/hidden-settings/net-procesamos-settings/

**Comment by qsniyg** [comment]
Thanks! Supported :)

By the way, whenever you see `aHR0c` in a link, it almost always means that it's a base64-encoded URL. Try running `atob("aHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tLzRlTE5oeFZHTXp2eExOVDV2RkVWcGZlTmIyUHNyU0FSR2tJYVFtNVByOXloUWRfZVgxWXhsMkJKVDd6eUdUNUxiSk1DPXcxMDAw")` in the console (F12) :)
