### ISSUE TITLE
Extension doesn't work with Firefox Microsoft store version

### ISSUE THREAD

**Issue by TristanWasTaken** [qsniyg/maxurl#1111]
Individually loading an image with right-click isn't working with Firefox extension in the Firefox Microsoft store app version. I uninstalled the microsoft store app and installed Firefox with the installer from firefox.com and the right-click function works again. "Replace all images" did work though.

Browser details from before: [image](https://cdn.discordapp.com/attachments/934863572826210304/1061439681876742254/image.png)
```
Firefox Browser
Windows MSIX package
mozilla-MSIX - 1.0
108.0.2 (64-bit)
```
Browser details from right now: [image](https://cdn.discordapp.com/attachments/876615724372746250/1061898676206837870/image.png)
```
Firefox Browser
108.0.2 (64-bit)
```

**Comment by qsniyg** [comment]
Unfortunately I can't reproduce the issue as I don't have access to the Microsoft store at the moment. Were you able to open the popup through a keybinding (`shift+alt+i` by default) rather than right click?
