### ISSUE TITLE
image.winudf.com (apkpure images)

### ISSUE THREAD

**Issue by eightyy8** [qsniyg/maxurl#1113]
Another APK site. IMU gives a higher resolution of apkpure's images. But it can be higher quality, simply by removing the _&type=.webp_

**Examples:**

Original link = https://image.winudf.com/v2/image/YWRtaW5faWNfbGF1bmNoZXJfcGxheV9zdG9yZS5wbmdfMTUwMjE2MzE4NzkwMw/icon.png?w=160&fakeurl=1&type=.webp

IMU link = 
https://image.winudf.com/v2/image/YWRtaW5faWNfbGF1bmNoZXJfcGxheV9zdG9yZS5wbmdfMTUwMjE2MzE4NzkwMw/icon.png?fakeurl=1&type=.webp

Without type = https://image.winudf.com/v2/image/YWRtaW5faWNfbGF1bmNoZXJfcGxheV9zdG9yZS5wbmdfMTUwMjE2MzE4NzkwMw/icon.png?fakeurl=1

_It is the same resolution but in higher quality, without the artifacts and whatnot._

**Comment by eightyy8** [comment]
Any updates?

**Comment by qsniyg** [comment]
Thanks, fixed! The main issue is actually the 'Accept' header, otherwise it will still return a .webp under a browser.
