### ISSUE TITLE
Govdeals.com (I have no idea why this isnt working ffs)

### ISSUE THREAD

**Issue by Luke-L** [qsniyg/maxurl#1117]
please will someone help with this, I've been trying for like literally an hour and it still wont work.
Thumbnail:
`https://www.govdeals.com/photos/6794/Thumbnails/6794_3402_1-1.jpg`
`https://webassets.lqdt1.com/assets/photos/19303/19303_52_2.jpg?cb=230210170000&w=256&webp=true`
Full size: 
`https://www.govdeals.com/photos/6794/6794_3402_1-1.jpg`
`https://webassets.lqdt1.com/assets/photos/19303/19303_52_2.jpg?cb=230125171332&h=480&webp=true`
`https://webassets.lqdt1.com/assets/photos/19303/19303_52_2.jpg?cb=230210170000` (this also works and might be easier)

This is what I have so far, but I feel like I've tried a hundred variations on this. 
```ts
if (domain_nowww === "govdeals.com") {
	newsrc = src.replace(/(\/photos\/)([0-9]+\/)(Thumbnails\/)(.*)/i, "$1$2$4");
	if (newsrc !== src)
		return decodeuri_ifneeded(newsrc);
```
Pretty sure I also tried
```ts
if (domain_nowww === "govdeals.com") {
	src = src.replace(/(\/photos\/)([0-9]+\/)(Thumbnails\/)(.*)/i, "$1$2$4");
```

**Comment by qsniyg** [comment]
Your regex is correct (worked for me when I tried it). I'm not sure why it wouldn't work for you (I assume you included the trailing `}`?). Did you run `npm run build` to update userscript.user.js?

I'll update the script soon with that rule :)

For the reference, I've written the rule like this:

```js
if (domain_nowww === "govdeals.com") {
	// thanks to Luke-L on github: https://github.com/qsniyg/maxurl/issues/1117
	// https://www.govdeals.com/photos/6794/Thumbnails/6794_3402_1-1.jpg
	//   https://www.govdeals.com/photos/6794/6794_3402_1-1.jpg
	// https://www.govdeals.com/photos/6794/thumbnails/6794_3402_1-1.jpg
	//   https://www.govdeals.com/photos/6794/6794_3402_1-1.jpg
	return src.replace(/(\/photos\/+[0-9]+\/+)Thumbnails\/+(.*)/i, "$1$2");
}
```

The only functional difference is that I've added `+` to `\/`, as `https://www.govdeals.com/photos////6794///////Thumbnails///6794_3402_1-1.jpg` works too.

**Comment by Luke-L** [comment]
> Did you run `npm run build` to update userscript.user.js

no, im not using the userscript, im on chrome so adding the extension by dragging the github folder over the extensions page. do i need to do that still?

**Comment by qsniyg** [comment]
Yeah it's a bit confusing, but yes, `userscript.user.js` is the base for everything else (including the chrome extension).

**Comment by Luke-L** [comment]
ok thanks. how do i do that... tried running it in command prompt at the folder dir and it says npm isnt recognized ://

**Comment by Luke-L** [comment]
pls help i have no idea how to js, i barely just know python lol

**Comment by qsniyg** [comment]
> ok thanks. how do i do that... tried running it in command prompt at the folder dir and it says npm isnt recognized ://

Do you have npm and node.js installed?

**Comment by Luke-L** [comment]
i dont think so, unless they come with vscode.
