### ISSUE TITLE
LiveATC.net: full versions of WX weather radars

### ISSUE THREAD

**Issue by pointydev** [qsniyg/maxurl#1119]
Hey there,

[LiveATC.net](https://www.liveatc.net/) has a thumbnail service for weather radars that show possibly poor flight conditions, which are generated by [UCAR](https://weather.rap.ucar.edu/radar/), and can be found here: https://www.liveatc.net/badwxfeeds.php.

After quickly glancing over the URLs generated by the site, I don't think it would be feasible to link back to the original generated images at UCAR, but it is possible to redirect from the thumbnail service to either the original file stored serverside or to a version of the image that is the same size as the original.

Example base thumbnail URL: [link](https://www.liveatc.net/phpthumb/phpThumb.php?src=/wx_radar/RAX/RAX-Feb-13-2023-0000Z-radar.png&w=75)
Without being resized (remove `&w=`): [link](https://www.liveatc.net/phpthumb/phpThumb.php?src=/wx_radar/RAX/RAX-Feb-13-2023-0000Z-radar.png)
The original file cached by the server (remove `/phpthumb/phpThumb.php?src=` and `&w=`): [link](https://www.liveatc.net/wx_radar/RAX/RAX-Feb-13-2023-0000Z-radar.png)

While very limited in scope, this'd be a great addition.

Thanks,
Elliott

**Comment by qsniyg** [comment]
Thank you, added! There's no such thing as too limited in scope for the script :)
