### ISSUE TITLE
Harper's Bazaar Germany

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1126]
Script doesn't work for me on this page - https://www.harpersbazaar.de/zeitgeist/berlinale-armani-beauty-harpers-bazaar-party-mit-sydney-sweeney

Should be an easy rule to add:
https://static.harpersbazaar.de/fit/2756x2756/images/2023-02/o5a4227.jpg
→
https://static.harpersbazaar.de/fit/0x0/images/2023-02/o5a4227.jpg

**Comment by qsniyg** [comment]
Thanks, supported!
