### ISSUE TITLE
Wonderland Magazine

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1127]
https://www.wonderlandmagazine.com/2023/02/24/sophia-lillis-spring-2023

maxurl opens this picture
https://media.wonderlandmagazine.com/uploads/2023/02/SOPHIA-SHOP-scaled.jpg
instead of the full size one
https://media.wonderlandmagazine.com/uploads/2023/02/SOPHIA-SHOP.jpg

**Comment by qsniyg** [comment]
Thanks! Supported :)
