### ISSUE TITLE
Rawpixel

### ISSUE THREAD

**Issue by eightyy8** [qsniyg/maxurl#1128]
This site has a great collection of photos/art but currently IMU doesn't support it. I'm not sure whether it is possible, for some images or all of them, because it's a "freemium" service - using Public Domain images but also Paid Premium.
Either way it's worth a try.

**Here is one Public Domain image:**
https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvcGQzNS0wMzA3My5qcGc.jpg

_from:_ https://www.rawpixel.com/image/431529

**And here is one Premium image:**
https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvam9iNjAyLW0wMV8xLWt6bTZsYWk1LmpwZw.jpg

_from:_ https://www.rawpixel.com/image/6172476

I tried changing the ```
/image_800/
``` parameter to change the resolution but it only allowed me to change it to `1000`, not higher, lower or between...

**Comment by qsniyg** [comment]
Thanks, I'll take a look at this!

```
> atob("czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvcGQzNS0wMzA3My5qcGc")
's3fs-private/rawpixel_images/website_content/lr/pd35-03073.jpg'
```

**Comment by qsniyg** [comment]
It's partially supported now. I can't find any way to directly access the images, but it can now redirect to `/image_1300/` and use a higher resolution base image (doesn't affect resolution, but helps the image quality).
