### ISSUE TITLE
canyon.eu

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1131]
https://cdn0.it4profit.com/s3size/rt:fill/w:100/h:100/g:no/el:1/f:webp/plain/s3://cms/canyon/4d/b9/4db91b0dde37751a5ceaa0ddd9796d36/58794.png

works if remove everything between
"/s3size" and "/plain

https://cdn0.it4profit.com/s3size/plain/s3://cms/canyon/4d/b9/4db91b0dde37751a5ceaa0ddd9796d36/58794.png

**Comment by qsniyg** [comment]
Thanks! I wonder if there's a way to find the name of the s3 bucket, we could probably redirect directly rather than relying on their proxy system.
