### ISSUE TITLE
[Site Rule] ipcc.ch

### ISSUE THREAD

**Issue by Adrthegamedev** [qsniyg/maxurl#1132]
This one shouldn't be difficult to implement.

Minimised image: https://www.ipcc.ch/site/assets/uploads/sites/4/2019/11/Figure-3.4-150x150.jpg
Original image: https://www.ipcc.ch/site/assets/uploads/sites/4/2019/11/Figure-3.4.jpg

Minimised image: https://www.ipcc.ch/site/assets/uploads/sites/4/2019/11/Figure-3.2-1024x577.jpg
Original image: https://www.ipcc.ch/site/assets/uploads/sites/4/2019/11/Figure-3.2.jpg

**Comment by qsniyg** [comment]
Thanks! Supported
