### ISSUE TITLE
preview.redd.it rule broken

### ISSUE THREAD

**Issue by pointydev** [qsniyg/maxurl#1133]
Hey there,

I've been reversing a lot of images that have originated on Reddit recently, and a lot of the URLs found by search engines are from `preview.redd.it` instead of `i.redd.it`. The current rule expects a format with only the image ID and file extension after the domain and before the query string, but increasingly I've found URLs that include the name of the post they are from too, therefore breaking IMU.

Example (from something I was just working with):
Input - https://preview.redd.it/black-eyed-pees-grail-v0-87udn5gszb6a1.jpg?auto=webp&s=b9ceef6cf0f71ab67ac319e35e41c5c08e3d6553
Input currently returns "Broken image" when processed by IMU.
Original - https://i.redd.it/87udn5gszb6a1.jpg

Thanks,
Elliott

**Comment by qsniyg** [comment]
Thanks! Fixed
