### ISSUE TITLE
nzxt.com

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1136]
https://nzxt.com/assets/cms/34299/1627488599-streamerpc1-white-2000x2000-hero.png?ar64=MTox&auto=format&bg64=I2Y2ZjZmOQ&fit=crop&h=100&w=100

works if remove values after *.png

https://nzxt.com/assets/cms/34299/1627488599-streamerpc1-white-2000x2000-hero.png

**Comment by qsniyg** [comment]
Thanks! Supported
