### ISSUE TITLE
eposaudio.com

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1142]
https://www.eposaudio.com/globalassets/__pim/products/h3-series/h3pro-hybrid--green/61c08317-24bd-42ce-8b84-9e82942d0788_33711_h3pro-hybrid-green_if-design-award_fullsizepng.png?width=50

remove value after *.png

https://www.eposaudio.com/globalassets/__pim/products/h3-series/h3pro-hybrid--green/61c08317-24bd-42ce-8b84-9e82942d0788_33711_h3pro-hybrid-green_if-design-award_fullsizepng.png

**Comment by qsniyg** [comment]
Thanks!
