### ISSUE TITLE
bechtle.com

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1143]
https://media.bechtle.com/is/180712/1c4b3d4ee288fc9434f5175bf56070570/c3/picture/d123c83ae884430b8c2a291fdc48a79c?version=0
https://media.bechtle.com/is/180712/1c4b3d4ee288fc9434f5175bf56070570/c3/gallery/d123c83ae884430b8c2a291fdc48a79c?version=0

full size opens if replace "picture" or "gallery" "zoom" with "original"
https://media.bechtle.com/is/180712/1c4b3d4ee288fc9434f5175bf56070570/c3/original/d123c83ae884430b8c2a291fdc48a79c?version=0

**Comment by qsniyg** [comment]
Interesting, a different `/is/` rule. Thanks!
