### ISSUE TITLE
Google Books frontcover

### ISSUE THREAD

**Issue by ghost** [qsniyg/maxurl#1144]
https://books.google.com/books/content?id=1kbG47pDHG4C&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=Aflre71czgapxhuindxku68lr68xivjhgbzra9zjnf5zhh2xfx1jrxrty3q2w-ebrz5ucnodada29rulgxzrxtg8a0jlleq_qxhiffsddmavimb77darndec-o9naxv8vehbfxa55x3-

_Highest and probably the source quality:_

https://books.google.com/books/content?id=1kbG47pDHG4C&printsec=frontcover&img=0&zoom=0

IMU has one for google books but it uses the &h=9999 parameter which is higher quality, but not as high as it can go, and IMU keeps the unnecessary _edge_ and tracking _imgtk_ parameters. IMU also only responds if it includes the cosmetic _/publisher/_ in it (/books/**publisher**/content?id=).

**Comment by eightyy8** [comment]
Also, google books only stores full res front covers if it includes a small preview of the book or no copyright so to read the entirety.

**Comment by qsniyg** [comment]
Thanks! It turns out that if `?sig=` is present, it does not allow either `img` or `zoom` to be modified. I've updated the rule to support both cases.
