### ISSUE TITLE
kingston.com

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1149]
https://media.kingston.com/kingston/product/ktc-product-ssd-sedc1000b-240gb-1-tn.png
https://media.kingston.com/kingston/product/ktc-product-ssd-sedc1000b-240gb-1-lg.jpg

to
https://media.kingston.com/kingston/product/ktc-product-ssd-sedc1000b-240gb-1-zm-lg.jpg

**Comment by qsniyg** [comment]
Thanks! Supported.
