### ISSUE TITLE
comicvine update

### ISSUE THREAD

**Issue by synthtech** [qsniyg/maxurl#115]
Comicvine's image urls have changed to `comicvine1.cbsistatic.com`, though the old domain still works for now.

Page example: https://comicvine.gamespot.com/gunnm-last-order-1-vol-1/4000-541071/

Thumb: https://comicvine1.cbsistatic.com/uploads/scale_small/13/136525/5341716-1.jpg
Original: https://comicvine1.cbsistatic.com/uploads/original/13/136525/5341716-1.jpg

**Comment by qsniyg** [comment]
Thank you very much! Updated :)
