### ISSUE TITLE
Extension not respecting EXIF data

### ISSUE THREAD

**Issue by Luke-L** [qsniyg/maxurl#1150]
Colors, crop, and rotation are not reflected in the image popup. ex. https://www.flickr.com/photos/labanex/3461671947/

**Comment by qsniyg** [comment]
Actually, what's going on here is that the original image (`https://live.staticflickr.com/3619/3461671947_085a36f175_o.jpg`) is unrotated/cropped. As far as I can see, there's no EXIF data in the original image pertaining to the crop/rotation. I assume the user must have edited the image in Flickr's tools after uploading it.

I'll close the issue, but if you find an example that has EXIF metadata where IMU fails, please let me know and I'll take a look :)
