### ISSUE TITLE
original size of the avatar image for gitee user

### ISSUE THREAD

**Issue by n0099** [qsniyg/maxurl#1158]
Take https://gitee.com/yinian1992 as an example:
From https://foruda.gitee.com/avatar/1676894742397292147/2072_yinian1992_1598196937.png!avatar200
![](https://foruda.gitee.com/avatar/1676894742397292147/2072_yinian1992_1598196937.png!avatar200)
to https://foruda.gitee.com/avatar/1676894742397292147/2072_yinian1992_1598196937.png
![](https://foruda.gitee.com/avatar/1676894742397292147/2072_yinian1992_1598196937.png)

It seems there's no restriction on the referrer header.

**Comment by qsniyg** [comment]
Thanks! I can't access it for some reason, but I'll trust you that it works :)

**Comment by n0099** [comment]
Maybe you need a VPN from mainland china.
