### ISSUE TITLE
genie.co.kr

### ISSUE THREAD

**Issue by JustLurkingHere** [qsniyg/maxurl#1163]
From site https://www.genie.co.kr/

URL is https://image.genie.co.kr/Y/IMAGE/IMG_MUZICAT/IV2/Genie_Magazine/13051/Mgz_Sub_IMG_20230407110405.jpg/dims/resize/Q_80,0

It must be https://image.genie.co.kr/Y/IMAGE/IMG_MUZICAT/IV2/Genie_Magazine/13051/Mgz_Sub_IMG_20230407110405.jpg to get the picture with original quality.

Thank you so much

**Comment by qsniyg** [comment]
Supported, thanks for reporting!
