### ISSUE TITLE
newsjamm.co.kr & bstage.in

### ISSUE THREAD

**Issue by JustLurkingHere** [qsniyg/maxurl#1164]
From site https://newsjamm.co.kr/ (which uses a subdomain under https://bstage.in/)

URL is https://image.static.bstage.in/cdn-cgi/image/metadata=none,dpr=2,width=640/newsjamm/14edb6f2-cd55-461e-bc00-ed4c4421c8d8/f9aa520f-b9cd-4f7d-8be7-f9d1cc565d20/ori.jpg

It must be https://image.static.bstage.in/cdn-cgi/image/metadata=none/newsjamm/14edb6f2-cd55-461e-bc00-ed4c4421c8d8/f9aa520f-b9cd-4f7d-8be7-f9d1cc565d20/ori.jpg to get the original resolution.

Thank you so much

**Comment by qsniyg** [comment]
Thanks! You can actually remove the `cdn-cgi` segment entirely: https://image.static.bstage.in/newsjamm/14edb6f2-cd55-461e-bc00-ed4c4421c8d8/f9aa520f-b9cd-4f7d-8be7-f9d1cc565d20/ori.jpg
