### ISSUE TITLE
m.media-amazon.com

### ISSUE THREAD

**Issue by TristanWasTaken** [qsniyg/maxurl#1167]
(third party) **docs:** [forums.mangadex.org](https://forums.mangadex.org/threads/en-cover-ripping-in-high-quality.1069452/post-16606131)

The extension redirects full sized images to smaller versions if you directly open the full sized cover with the product ASIN

Example:
- https://www.amazon.co.jp/dp/B0BG56NRZW
- https://m.media-amazon.com/images/P/B0BG56NRZW.01.MAIN._SCRM_.jpg
![RZW 01 MAIN _SCRM_](https://user-images.githubusercontent.com/43283797/232175358-3a4c9c3f-7609-43d2-9a27-5220d040e21e.jpg)
- extension redirects to https://m.media-amazon.com/images/P/B0BG56NRZW.01.jpg
![B0BG56NRZW 01](https://user-images.githubusercontent.com/43283797/232175396-5f6a6363-39d6-4894-81fc-443a2c5ced4f.jpg)

**Comment by qsniyg** [comment]
Thank you very much for documenting this! It should be fixed now :)
