### ISSUE TITLE
Support for tvtropes.org

### ISSUE THREAD

**Issue by ljcool2006** [qsniyg/maxurl#1170]
Example image that has webp stuff applied to it: https://static.tvtropes.org/pmwiki/pub/images/tvt_blue.png

Example image that is the original png image with no webp stuff applied: https://tvtropes.org/pmwiki/pub/images/tvt_blue.png

All you have to do is remove the "static." part from the URL.

**Comment by qsniyg** [comment]
Thanks! Supported.
