### ISSUE TITLE
user avatar of Discuz!X based forum site

### ISSUE THREAD

**Issue by n0099** [qsniyg/maxurl#1172]
According to its source:
https://github.com/codersclub/DiscuzX/blob/5d23e9684bd91a71de36ac5c237c1ed6a074f026/upload/uc_server/avatar.php#L66
https://gitee.com/Discuz/DiscuzX/blob/5d23e9684bd91a71de36ac5c237c1ed6a074f026/upload/uc_server/avatar.php#L66

for any url matching following regexp:
```regex
example.org/uc_server/data/avatar/(\d{3}/\d{2}/\d{2}/\d{2}(_real|)_avatar_)(big|middle|small).jpg
```
should being redirect to
```regex
example.org/uc_server/data/avatar/$1big.jpg
```
there's a misconfiged([`mod_autoindex`](https://httpd.apache.org/docs/2.4/mod/mod_autoindex.html) enabled) site you can reference:
[![image](https://user-images.githubusercontent.com/13030387/236094650-4cfaa85a-8bf2-4ef4-a9f1-9a7d7fb79cb9.png)](https://wewestar.com/uc_server/data/avatar/000/27/01/)
[![image](https://user-images.githubusercontent.com/13030387/236094807-4ff43032-ba0d-466f-8e6b-88407176bc5d.png)](https://wewestar.com/uc_server/data/avatar/000/27/01/17_avatar_small.jpg)
[![image](https://user-images.githubusercontent.com/13030387/236094862-5adfbbb0-ceff-4277-b7e4-2aa48238ee20.png)](https://wewestar.com/uc_server/data/avatar/000/27/01/17_avatar_middle.jpg)
[![image](https://user-images.githubusercontent.com/13030387/236094895-83f5ba05-6987-4783-961d-8922fe682e01.png)](https://wewestar.com/uc_server/data/avatar/000/27/01/17_avatar_big.jpg)

**Comment by qsniyg** [comment]
Thank you! It should be supported now :)
