### ISSUE TITLE
page.kakao.com

### ISSUE THREAD

**Issue by TristanWasTaken** [qsniyg/maxurl#1176]
https://page.kakao.com
example: https://page.kakao.com/content/56566288
default image url: https://dn-img-page.kakao.com/download/resource?kid=bXtxpT/hzN2hYnygX/dIpdFOEOrYAyfehnSQ8EG0&filename=th3
max image:
- https://dn-img-page.kakao.com/download/resource?kid=bXtxpT/hzN2hYnygX/dIpdFOEOrYAyfehnSQ8EG0
- https://dn-img-page.kakao.com/download/resource?kid=bXtxpT/hzN2hYnygX/dIpdFOEOrYAyfehnSQ8EG0&filename=o1

**Comment by qsniyg** [comment]
Thanks! Supported :)
