### ISSUE TITLE
tapas.io

### ISSUE THREAD

**Issue by TristanWasTaken** [qsniyg/maxurl#1182]
https://tapas.io
(3rd party) docs: [forums.mangadex.org](https://forums.mangadex.org/threads/en-cover-ripping-in-high-quality.1069452/#post-16606176)
example:
- https://tapas.io/series/solo-leveling-comic/info
- small:
  - new cdn: https://us-a.tapas.io/sa/f1/e50af48f-7bd6-433c-b3ae-4737b720d1bb_z.jpg
  - old cdn: https://d30womf5coomej.cloudfront.net/sa/f1/e50af48f-7bd6-433c-b3ae-4737b720d1bb_z.jpg
- big:
  - new cdn: https://us-a.tapas.io/sa/f1/e50af48f-7bd6-433c-b3ae-4737b720d1bb.jpg
  - old cdn: https://d30womf5coomej.cloudfront.net/sa/f1/e50af48f-7bd6-433c-b3ae-4737b720d1bb.jpg

**Comment by qsniyg** [comment]
Thanks! Supported :)
