### ISSUE TITLE
kuaikanmanhua.com

### ISSUE THREAD

**Issue by TristanWasTaken** [qsniyg/maxurl#1183]
https://www.kuaikanmanhua.com/
(3rd party) docs: [forums.mangadex.org](https://forums.mangadex.org/threads/en-cover-ripping-in-high-quality.1069452/#post-16606245)
>  Jpeg has slightly more noise than webp but may be less of a pain to convert. For the webp file, remove the part after the file extension 

this is why I'm giving an example for the method to get webp images

example:
- https://www.kuaikanmanhua.com/web/topic/9796
- https://www.kuaikanmanhua.com/sou/%E8%BF%99%E4%B8%80%E4%B8%96%E6%88%91%E6%9D%A5%E5%BD%93%E5%AE%B6%E4%B8%BB
- https://tn1-f2.kkmh.com/image/221107/QPyXEZYLe.webp-t.w207.jpg.h.p
- https://tn1-f2.kkmh.com/image/221107/QPyXEZYLe.webp

**Comment by qsniyg** [comment]
Sorry for getting back so late about this. Supported now!
