### ISSUE TITLE
tweakers.net

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1185]
from
https://tweakers.net/i/iuMupMRu66cQap-kQMvC38Dj0_U=/fit-in/188x141/filters:strip_icc():fill(white):strip_exif()/i/2003264188.jpeg?f=thumblarge
to
https://tweakers.net/ext/i/2003264188.jpeg

**Comment by qsniyg** [comment]
Sorry for getting to this so late. Supported! :)
