### ISSUE TITLE
avatar for `v2ex.com`

### ISSUE THREAD

**Issue by n0099** [qsniyg/maxurl#1187]
https://www.v2ex.com/member/QianyanSanren
https://cdn.v2ex.com/avatar/b0f5/edea/608064_normal.png?m=1682942036
https://cdn.v2ex.com/avatar/b0f5/edea/608064_xlarge.png

**Comment by qsniyg** [comment]
Sorry for getting back so late. Turns out you can get 512x512 images: https://cdn.v2ex.com/avatar/b0f5/edea/608064_xxxlarge.png?m=1682942036 :)
