### ISSUE TITLE
Support for cnet.com

### ISSUE THREAD

**Issue by ljcool2006** [qsniyg/maxurl#1188]
https://www.cnet.com/a/img/resize/70642c109c306b840632343d45e815283ff5eace/hub/2021/05/14/c51e0011-709a-4efd-906f-223644c6583e/cash-money-piggy-bank-calculator-stimulus-tax-credit-2021-savings-calculations-math-cnet-cnet-2021-019.jpg?auto=webp&fit=crop&height=675&width=1200

https://www.cnet.com/a/img/70642c109c306b840632343d45e815283ff5eace/hub/2021/05/14/c51e0011-709a-4efd-906f-223644c6583e/cash-money-piggy-bank-calculator-stimulus-tax-credit-2021-savings-calculations-math-cnet-cnet-2021-019.jpg

**Comment by qsniyg** [comment]
Are you using the latest git version? It redirects for me.

**Comment by ljcool2006** [comment]
I didn't even realize that someone had already provided the fix for this; searching "cnet" in the issue tracker showed 0 results prior to posting the issue. I use the version found in the Firefox Add-ons site (last updated 2023/02) so maybe that's why the image doesn't redirect to the original size.
