### ISSUE TITLE
wevpstatic.net

### ISSUE THREAD

**Issue by JustLurkingHere** [qsniyg/maxurl#1190]
From site https://weverse.io/ (which uses a subdomain under https://wevpstatic.net/)

URL is https://phinf.wevpstatic.net/MjAyMzA1MjJfNTUg/MDAxNjg0NzY2ODk4MjAy.dZY02zGoooRX3-K-O1U_d5tRs3APOB2DqEQoIizz4f4g.AFEl-MDN3M8NI4xaMa1sDvxJqW-3FyNsd6evkH5LPnAg.JPEG/image.jpg?type=s468_468_stopgif

It must be https://phinf.wevpstatic.net/MjAyMzA1MjJfNTUg/MDAxNjg0NzY2ODk4MjAy.dZY02zGoooRX3-K-O1U_d5tRs3APOB2DqEQoIizz4f4g.AFEl-MDN3M8NI4xaMa1sDvxJqW-3FyNsd6evkH5LPnAg.JPEG/image.jpg to get the original resolution.

Thank you so much

**Comment by qsniyg** [comment]
Thanks! Supported
