### ISSUE TITLE
disqus

### ISSUE THREAD

**Issue by Tristan31415926535897932384626433832795** [qsniyg/maxurl#1192]
https://disqus.com
There are no docs about avatar sizes, but I found a few avatar sizes that work for all users I tested it with
Please note that the biggest working image res I found is 200, but [disqus official docs](https://help.disqus.com/en/articles/1717081-updating-your-account-settings) say they recommend 128x128, so some users may don't have a working 200x avatar res
Please also note that disqus is mostly used by users as embed on third party sites (which shouldn't be a problem since the rules are for the cdn domains)

format: `https://c.disquscdn.com/uploads/users/<id1>/<id2>/avatar<res>.jpg`
working res examples with my own avatar: https://disqus.com/api/users/avatars/tristanwastaken.jpg
- 36: https://c.disquscdn.com/uploads/users/36733/2961/avatar36.jpg
- 92 (default) https://c.disquscdn.com/uploads/users/36733/2961/avatar92.jpg
- 128 https://c.disquscdn.com/uploads/users/36733/2961/avatar128.jpg
- 200 (biggest) https://c.disquscdn.com/uploads/users/36733/2961/avatar200.jpg

**Comment by qsniyg** [comment]
Sorry for getting back so late. Supported now :)
