### ISSUE TITLE
support for xperienceunited.com

### ISSUE THREAD

**Issue by fyhtma** [qsniyg/maxurl#1193]
from 800px (default): https://xperienceunited.com:8080/userphotos/63f20f4cd1ab9a64b2909056-1676823380378-800.webp?0-6406eac4bc4b4c2ad16245c5.webp

to full res: https://xperienceunited.com:8080/userphotos/63f20f4cd1ab9a64b2909056-1676823380378.webp?0-6406eac4bc4b4c2ad16245c5

thanks!

**Comment by qsniyg** [comment]
Sorry for getting back so late, it should be supported now :)

**Comment by fyhtma** [comment]
-800.webp to .webp works great, but could you add support for 


thumbnail
https://xperienceunited.com:8080/userphotos/65d9a4a1b5bae389c7707e69-1710510618678-thumbnail?0-6406eac4bc4b4c2ad16245c5
to full res
https://xperienceunited.com:8080/userphotos/65d9a4a1b5bae389c7707e69-1710510618678.webp?0-6406eac4bc4b4c2ad16245c5

**Comment by qsniyg** [comment]
For some reason I'm getting "Forbidden" when trying to access the links.

**Comment by fyhtma** [comment]
hmm it seems that the links only work for logged in users. those gave me "Forbidden" moment ago, when I logged in again the links work again

**Comment by qsniyg** [comment]
Does https://xperienceunited.com:8080/userphotos/65d9a4a1b5bae389c7707e69-1710510618678-thumbnail.webp?0-6406eac4bc4b4c2ad16245c5 work too, or only without the extension?

**Comment by fyhtma** [comment]
> Does https://xperienceunited.com:8080/userphotos/65d9a4a1b5bae389c7707e69-1710510618678-thumbnail.webp?0-6406eac4bc4b4c2ad16245c5 work too, or only without the extension?

this doesn't work, need to be without extension

**Comment by qsniyg** [comment]
See if https://github.com/qsniyg/maxurl/commit/a8176930a6684261aa80d68fef866c1f101c8428 fixes it for you.
