### ISSUE TITLE
Fix chan.sankakucomplex.com regex

### ISSUE THREAD

**Issue by kooper100** [qsniyg/maxurl#1195]
I found that loading images and videos from chan.sankakucomplex.com does not work anymore. It seems to load the preview/sample instead. I normally use the firefox extension but for the sake of trying to fix it I edited the userscript version.
I fixed it in the userscript version by updating the regex in two places from

`
/:\/\/[^/]+\/+(?:[a-z]+\/+)?post\/+show\/+[0-9]+(?:[?#].*)?$/
`
to
`
/:\/\/[^/]+\/+(?:[a-z]+\/+)?post\/+show\/+[0-9a-z]+(?:[?#].*)?$/
`

and

`
/^([a-z]+:\/\/[^/]+\/+(?:[a-z]+\/+)?post\/+show\/+[0-9]+)(?:[?#].)?$/
`
to
`
/^([a-z]+:\/\/[^/]+\/+(?:[a-z]+\/+)?post\/+show\/+[0-9a-z]+)(?:[?#].)?$/
`

Basically, it looks like the post id in the url used to be just numbers but now contains both numbers and letters which the old regex didn't match anymore. idol.sankakucomplex.com still seems to only use numbers in the url unlike chan, but I think the regex change should work for both. I also found that the userscript version doesn't work on idol.sankakucomplex.com (it only loads the preview), but the extension does work. So I couldn't really test whether updating the above regex in the userscript breaks idol.sankakucomplex.com since it doesn't work in the first place using the userscript version.

For example this is what the post url looks like now:
`
https://chan.sankakucomplex.com/post/show/171caa16c531b321f98e63124c94c8ab  (SFW)
`
The old regex only matches if the last part of the url is only numbers.

I'm not a js/ts dev and I was a bit lost in the size of the file, hopefully this helps.

**Comment by qsniyg** [comment]
Thanks for the heads up and giving such a detailed explanation! It should be supported now :)
