### ISSUE TITLE
ecoflow.com

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1198]
https://eu.ecoflow.com/cdn/shop/products/ecoflow-river-2-pro-portable-power-station-42466006433956_150x.png?v=1675844913
if remove "_sizex"
opens full image
https://eu.ecoflow.com/cdn/shop/products/ecoflow-river-2-pro-portable-power-station-42466006433956.png?v=1675844913

**Comment by qsniyg** [comment]
Thanks! Seems like it's another shopify site. I should probably add a general rule for it eventually...
