### ISSUE TITLE
seiska.fi

### ISSUE THREAD

**Issue by fyhtma** [qsniyg/maxurl#1203]
original, found from https://www.seiska.fi/kotimaa/sanna-marin-ja-uusi-rakas-savayttivat-olavi-uusivirran-keikalla-paat-vakisinkin-kaantyivat/1112108
https://image.seiska.fi/1112138.webp?imageId=1112138&width=710&format=webp

i would like to have it in this format or even higher resolution:
https://image.seiska.fi/1112138.webp?imageId=1112138&width=3840&format=jpg

**Comment by qsniyg** [comment]
Thanks for reporting! The larger image you linked is actually upscaled unfortunately, but IMU will now return the original size from seiska.fi (https://image.seiska.fi/1112138.webp?width=-1&height=-1&format=jpg - 2500x1668)
