### ISSUE TITLE
Booklive.jp not working for me.

### ISSUE THREAD

**Issue by Tenome** [qsniyg/maxurl#1204]
Development userscript version 2023.8.0, Firefox 117.0b9 (64-bit)

https://res.booklive.jp/261971/002/thumbnail/2L.jpg
https://res.booklive.jp/271414/002/thumbnail/2L.jpg

Console output:

> unreachable code after return statement 2L.jpg:20294:3
> https://res.booklive.jp/261971/002/thumbnail/X.jpg Image Max URL.user.js:381:26
> Uncaught DOMException: CSSStyleSheet.insertRule: Not allowed to access cross-origin stylesheet
>     <anonymous> https://res.booklive.jp/261971/002/thumbnail/2L.jpg:1
> 2L.jpg:1
> Error: Not an image: (no content-type) Image Max URL.user.js:99477:20
>     cb moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/ Image Max URL.user.js#243:99477
>     onload_cb moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/ Image Max URL.user.js#243:99318
>     onprogress moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/ Image Max URL.user.js#243:99362
>     HttpRequested moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/sandbox/injected-web.js:1
>     onHandle moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/sandbox/injected-web.js:1
>     Ie moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/sandbox/injected-web.js:1
> GET
> https://res.booklive.jp/favicon.ico
> [HTTP/2 404 Not Found 0ms]
> 
> Source map error: Error: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://291eac70-2f90-47ad-a6b8-c53a8315a656/polyfill.min.js
> Source Map URL: polyfill.min.js.map
> unreachable code after return statement 2L.jpg line 1 > injectedScript:19565:3
> unreachable code after return statement 2L.jpg line 1 > injectedScript:19675:3
> unreachable code after return statement 2L.jpg line 1 > injectedScript:20294:3
> unreachable code after return statement 2L.jpg line 1 > injectedScript:19565:3
> unreachable code after return statement 2L.jpg line 1 > injectedScript:19675:3
> unreachable code after return statement 2L.jpg line 1 > injectedScript:20294:3

**Comment by qsniyg** [comment]
Thanks for reporting! Fixed :)
