### ISSUE TITLE
Twitch Thumbnails

### ISSUE THREAD

**Issue by IZeeLikeEyeZee** [qsniyg/maxurl#1206]
It seems like maxurl doesn't already know about this but just btw a twitch thumbnail like this:
> https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/04c620b026effc608615_izeeh_49191263485_1693287287//thumb/thumb0-640x360.jpg

can go up to 1280x720:
> https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/04c620b026effc608615_izeeh_49191263485_1693287287//thumb/thumb0-1280x720.jpg

**Comment by qsniyg** [comment]
Thanks! Supported :)
