### ISSUE TITLE
[rule] SayWho.it / SayWho.fr

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1208]
https://saywho.it/events/giorgio-armani-porta-la-sua-one-night-only-a-venezia-e-omaggia-il-cinema

maxurl opens this picture on this page
https://saywhofr.fra1.cdn.digitaloceanspaces.com/app/uploads/2023/09/armani_prive_02092024_lidovica_arcero_57.jpg-768x512.jpeg
instead of the original one
https://saywhofr.fra1.cdn.digitaloceanspaces.com/app/uploads/2023/09/armani_prive_02092024_lidovica_arcero_57.jpg.jpeg

Can't find it right now, but I also saw a few links that have "-scaled" in them instead of numbers.

Same goes for saywho.fr

**Comment by qsniyg** [comment]
Thanks! Supported :)
