### ISSUE TITLE
bazar.bg

### ISSUE THREAD

**Issue by ValiumBear** [qsniyg/maxurl#1214]
Example:
https://cdn6.focus.bg/bazar/b8/pics/b8b49b17c189da8a1453bd59812f82ec.jpg > 
https://cdn6.focus.bg/bazar/b8/original/b8b49b17c189da8a1453bd59812f82ec.jpg

https://cdn6.focus.bg/bazar/b8/large/b8b49b17c189da8a1453bd59812f82ec.jpg > 
https://cdn6.focus.bg/bazar/b8/original/b8b49b17c189da8a1453bd59812f82ec.jpg

**Comment by qsniyg** [comment]
Thanks! Supported.
