### ISSUE TITLE
[rule] lovestoriesintimates.com

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1215]
https://lovestoriesintimates.com/en/rib-socks-l2370865400.html

maxurl opens 800x1200 image on this website
https://lovestories.xcdn.nl/OQ75_RM1200,1200,255,255,255/-/catalog/product/l/L2370865400_M1.jpg

changing "OQ75_RM1200,1200,255,255,255" to anything ("lol" for example) loads a 2666x4000 image
https://lovestories.xcdn.nl/lol/-/catalog/product/l/L2370865400_M1.jpg

**Comment by qsniyg** [comment]
Thanks! I replaced it to `/-/`, seemed fitting with the one beside it.
