### ISSUE TITLE
[rule] Highsnobiety.com

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1216]
https://www.highsnobiety.com/p/rachel-sennott-interview/

Should be easy :) Maxurl loads this 2880x4320 picture
https://www.highsnobiety.com/static-assets/dato/1695121414-hx32_rachel_sennott_112.jpg?fp-x=0.5&fp-y=0.5&fit=crop&auto=compress%2Cformat&cs=srgb&ar=6667%3A10000&w=2880

deleting all strings after ? loads 6666x10000 image
https://www.highsnobiety.com/static-assets/dato/1695121414-hx32_rachel_sennott_112.jpg

**Comment by qsniyg** [comment]
Thanks! Supported :)
