### ISSUE TITLE
zhimg.com

### ISSUE THREAD

**Issue by n0099** [qsniyg/maxurl#1219]
example from https://zhuanlan.zhihu.com/p/404369011
https://pica.zhimg.com/70/v2-cf43c815483cd4abc039f4136bc8c8e3_1440w.avis?source=172ae18b&biz_tag=Post
to
https://pica.zhimg.com/70/v2-cf43c815483cd4abc039f4136bc8c8e3.avis

**Comment by qsniyg** [comment]
Thanks! Supported :)
