### ISSUE TITLE
[rule] Elmundo.es

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1222]
Popup doesn't work for me at all on their website - https://www.elmundo.es/yodona/moda/2023/10/06/651d76ffe85ece75048b45c6.html

Opening first image in a new tab loads webp image
https://phantom-elmundo.unidadeditorial.es/adbb169d7cffb61dcb0c976c949bf9e7/crop/80x7/1408x1778/resize/1280/f/webp/assets/multimedia/imagenes/2023/10/04/16964302641590.jpg

but the original image is located here
https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2023/10/04/16964302641590.jpg

**Comment by qsniyg** [comment]
Thanks! Supported the rule.

As for the popup not working, it works for me... can you send your settings?

**Comment by sn3akyb3ar** [comment]
I tried with default settings, but nevermind, you can close the issue, it seems like it only didn't work on this first image, and it works now :)
