### ISSUE TITLE
Add support for addons.mozilla.org

### ISSUE THREAD

**Issue by oifj34f34f** [qsniyg/maxurl#1223]
## Demo

Thumbnail: https://addons.mozilla.org/user-media/previews/thumbs/281/281762.jpg
Original: https://addons.mozilla.org/user-media/previews/full/281/281762.png

https://addons.mozilla.org/firefox/addon/linguist-translator/ (first screenshot)

**Comment by qsniyg** [comment]
Thanks! Supported :)

**Comment by qsniyg** [comment]
@oifj34f34f Correct, FF doesn't allow any extensions to work under addons.mozilla.org.
