### ISSUE TITLE
[rule] Purple.fr

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1224]
Easy one again. Just a quick warning - there are some NSFW pics
https://purple.fr/diary/courreges-ss24-pfw/

Maxurl opens this one: https://i0.wp.com/static.purple.fr/2023/09/Screenshot-2023-09-27-at-16.16.37-374x550.png
Should open this instead: https://static.purple.fr/2023/09/Screenshot-2023-09-27-at-16.16.37.png

**Comment by qsniyg** [comment]
Thanks! Supported :)
