### ISSUE TITLE
[RULE] album.biliimg.com

### ISSUE THREAD

**Issue by doio** [qsniyg/maxurl#1226]
A sub-domain of bilibili.com

Image URL: 
`https://album.biliimg.com/bfs/new_dyn/cff5e1d43b05f89941e3259027ba03cb36180361.jpg@135h_1s_!web-comment-note.avif`

Original Image: 
`https://album.biliimg.com/bfs/new_dyn/cff5e1d43b05f89941e3259027ba03cb36180361.jpg`

From comments in `https://www.bilibili.com/video/BV11N41147WG/`

**Comment by qsniyg** [comment]
Thanks! Supported :)
