### ISSUE TITLE
eMAG

### ISSUE THREAD

**Issue by ValiumBear** [qsniyg/maxurl#1228]
Example:
https://s13emagst.akamaized.net/products/43324/43323414/images/res_75bf76c9d8450a07ecb29cb8fce9cc64.jpg?width=300&height=300&hash=CCF5DBDA23683CC1B3880BDBC810E3A9 >
https://s13emagst.akamaized.net/products/43324/43323414/images/res_75bf76c9d8450a07ecb29cb8fce9cc64.jpg

The hash is not required by server 🙉

**Comment by qsniyg** [comment]
Thanks! Yeah, sometimes the hash is only required for image transformation options :)
