### ISSUE TITLE
Add support for images.kinorium.com / kinorium.com

### ISSUE THREAD

**Issue by puddyplexer** [qsniyg/maxurl#1230]
I would like to request support for this website: images.kinorium.com / kinorium.com

Sample 1
https://images.kinorium.com/movie/shot/90483/h280_902025.jpg
https://images.kinorium.com/movie/shot/90483/w1500_902025.jpg

Sample 2
https://images.kinorium.com/movie/poster/90483/h280_39038026.jpg
https://images.kinorium.com/movie/poster/90483/w1500_39038026.jpg

Sample 3
https://images.kinorium.com/movie/backstage/90483/h280_49774877.jpg
https://images.kinorium.com/movie/backstage/90483/w1500_49774877.jpg

Sample 4 
https://images.kinorium.com/movie/promo/90483/h280_50128627.jpg
https://images.kinorium.com/movie/promo/90483/w1500_50128627.jpg

Sample 5
https://images.kinorium.com/movie/cover/90483/h280_37648326.jpg
https://images.kinorium.com/movie/cover/90483/w1500_37648326.jpg

Sample 6
https://images.kinorium.com/movie/fanart/90483/h280_44866117.jpg
https://images.kinorium.com/movie/fanart/90483/w1500_44866117.jpg

As far as I know, it's always
'h280' for thumbnails
and
'w1500' for full size images.

regex
https://images\.kinorium\.com/movie/(\w+)/(\d+)/h280_(\d+)\.jpg
https://images.kinorium.com/movie/$1/$2/w1500_$3.jpg

**Comment by qsniyg** [comment]
Thank you! Some (but not all) variants also support `/original_`.
