### ISSUE TITLE
Add support for Spotify Community

### ISSUE THREAD

**Issue by oifj34f34f** [qsniyg/maxurl#1231]
https://community.spotify.com/

Thumbnail: https://community.spotify.com/t5/image/serverpage/image-id/164115iB6FC1DFABF76FC91/image-size/medium?v=v2&px=400
Original: https://community.spotify.com/t5/image/serverpage/image-id/164115iB6FC1DFABF76FC91 or https://community.spotify.com/t5/image/serverpage/image-id/164115iB6FC1DFABF76FC91/image-size/original (not sure which is better to use)

**Comment by qsniyg** [comment]
Thanks! I've added support for it, and also made the Khoros/Lithium rule generic.
