### ISSUE TITLE
Discord new CDN authentication url params

### ISSUE THREAD

**Issue by TristanWasTaken** [qsniyg/maxurl#1232]
Domains affected:
- *.discordapp.net
- *.discordapp.com

announcement:
![Screenshot 2023-11-06 010151](https://github.com/qsniyg/maxurl/assets/43283797/1587ff8f-de43-4093-87e4-1c27ecbf5883)

Source:
- [message link](https://discord.com/channels/613425648685547541/697138785317814292/1157372186160537750)
- [Server Invite](https://discord.gg/discord-developers)

**Comment by qsniyg** [comment]
Thanks for letting me know. I guess it'll have to turn into a host rule soon.

**Comment by qsniyg** [comment]
I've added a host rule, but also kept the regular rule as it still seems to work. If they decide to disable it, the host rule will still work.
