### ISSUE TITLE
mi.com

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1235]
there is 2 patterns i find
first
https://cdn.ksyru0-fusion.fds.api.mi-img.com/b2c-mishop-pms-ru/pms_1669890168.73868564.png?w=200&h=200&thumb=1
https://i02.appmifile.com/653_operatorx_operatorx_xm/22/09/2022/4f2737a135c6a79a80984a0167c43c8a.jpg?w=600&h=600&thumb=1
remove everything after *.png or *.jpg
https://cdn.ksyru0-fusion.fds.api.mi-img.com/b2c-mishop-pms-ru/pms_1669890168.73868564.png
https://i02.appmifile.com/653_operatorx_operatorx_xm/22/09/2022/4f2737a135c6a79a80984a0167c43c8a.jpg

second

https://i04.appmifile.com/900_item_ru/09/08/2023/f6638076763903377c6b9f57b372cd0d!600x600!85.png
size values, starts with "!" up untul ".png"
https://i04.appmifile.com/900_item_ru/09/08/2023/f6638076763903377c6b9f57b372cd0d.png

**Comment by qsniyg** [comment]
Thanks! Supported.
