### ISSUE TITLE
Add support for mashable.com

### ISSUE THREAD

**Issue by ljcool2006** [qsniyg/maxurl#1236]
For example, this:
https://helios-i.mashable.com/imagery/archives/00lnkFNXYjcFzERp8dvE0Zo/images-1.fill.size_2000x378.v1647009212.gif
becomes:
https://helios-i.mashable.com/imagery/archives/00lnkFNXYjcFzERp8dvE0Zo/images-1.gif

**Comment by qsniyg** [comment]
Thanks! Supported.
