### ISSUE TITLE
403 ERROR/Blocked by website

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1237]
Before, I could easily download the original images from Posty but now it's banned.
This is website: postype.com
Sample link: https://cottonlinen.postype.com/goods/15699239
<img width="1500" alt="image" src="https://github.com/qsniyg/maxurl/assets/98095197/cdea5e67-9c99-402f-88aa-ad54e050365a">
Please fix it @@ Posty uses hosting [cloudfront. net]

**Comment by qsniyg** [comment]
It works for me, but you have to use the popup (use the save key to download).
