### ISSUE TITLE
mi.com

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1241]
https://i01.appmifile.com/v1/MI_18455B3E4DA706226CF7535A58E875F0267/pms_1536382068.06398947!200x200!85.jpg
remove values
https://i01.appmifile.com/v1/MI_18455B3E4DA706226CF7535A58E875F0267/pms_1536382068.06398947.jpg

**Comment by qsniyg** [comment]
Thanks! The rule should be fixed now.
