### ISSUE TITLE
Support Pocket Comics reader images

### ISSUE THREAD

**Issue by uwuceo** [qsniyg/maxurl#1250]
When opening an image from the reader in a new tab(click reader, shift right-click), you get a cropped, re-saved jpeg that comes from a much taller image, so the portion on-screen can load faster.

Example link:

https://images.comico.io/content/en/320/320/201/1_1685853099542.jpg/dims/crop/x2000+0+0/optimize?Policy=identifierinfothatsaysyoucanaccessthispage

Removing "/dims/crop/x2000+0+0/optimize" gives you the original image the cropped ones come from. I've seen the first and last numbers (2000 and 0 in this case) change, but I think it should be safe to remove as "/dims/crop/*/optimize" so you get:

https://images.comico.io/content/en/320/320/201/1_1685853099542.jpg?Policy=identifierinfothatsaysyoucanaccessthispage

You can get free chapters to test if this works, but I don't know if you can include a test image, as the identifier info changes pretty frequently. Thanks!

**Comment by qsniyg** [comment]
Sorry for getting to this so late. Thanks for reporting, should be supported now :)

**Comment by uwuceo** [comment]
I tried it now with the extension, and user script, and it doesn't work. Do I need to change some settings to make it work?

**Comment by uwuceo** [comment]
Never mind, I think I downloaded the wrong version of the user script. Does the extension need to be updated?

**Comment by qsniyg** [comment]
@uwuceo Yes, but it has just been updated a few days ago, so the next update will probably be in a few weeks. In the meantime, you can sideload it if you need it.
