### ISSUE TITLE
Add Invidious support

### ISSUE THREAD

**Issue by oifj34f34f** [qsniyg/maxurl#1251]
Invidious is an alternative front-end to YouTube: https://github.com/iv-org/invidious

https://yewtu.be/channel/UCX6OQ3DkcsbYNE6H8uQQuVA

**Comment by qsniyg** [comment]
Thanks for reporting, I've supported yewtu.be as well as invidious video playback.

**Comment by oifj34f34f** [comment]
It would be great to add other instances like iv.nboeck.de (I use them): https://docs.invidious.io/instances/

**Comment by qsniyg** [comment]
Done, thanks!

**Comment by oifj34f34f** [comment]
Could you please update the instances list? I'm using https://invidious.privacyredirect.com/, which is not in userscript

**Comment by qsniyg** [comment]
Done :)
