### ISSUE TITLE
Archived.moe (and its sister sites)

### ISSUE THREAD

**Issue by vscum** [qsniyg/maxurl#1253]
This one is too confusing for me. some of the boards use a different domain to host the archived pictures, as described [here](https://archived.moe/_/articles/faq/). There were some maxurl rules already in place for some of these, but they dont seem to work for me. I have created WORKING regex for one of the sites (archiveofsins.com) but couldnt get it properly implemented into the script. 
Maybe if i was better with coding I could put together a string of if > then statements, but its just beyond me. 
Any help is appreciated.
here is the working regex for the site, may be nsfw idk. https://regex101.com/r/ZmZq1T/2

**Comment by qsniyg** [comment]
Thanks, I've done a quick job of this. It can be improved later.
