### ISSUE TITLE
[rule] Elconfidencial.com

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1256]
https://www.vanitatis.elconfidencial.com/estilo/belleza/2024-01-12/sidney-sweeney-moda-belleza-embajadora-pelo_3810125/

maxurl currently opens this
https://images.ecestaticos.com/9cgcsvmkyC8-YZ1q-gpt7oYLlmQ=/0x326:2275x3307/1440x1920/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F16b%2Fde7%2F19e%2F16bde719e1cdf5bf5b75916dd34b02b7.jpg

and the original image is here
https://f.elconfidencial.com/original/16b/de7/19e/16bde719e1cdf5bf5b75916dd34b02b7.jpg

**Comment by qsniyg** [comment]
Thanks! Supported.
