### ISSUE TITLE
Support Ridibooks website

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1257]
Sample link of a manhwa: https://ridibooks.com/books/4851000001
I wonder if the cover of this series has a larger image. There are many sizes

https://img.ridicdn.net/cover/4851000001             120px × 174px
https://img.ridicdn.net/cover/4851000001/large       165px × 240px
https://img.ridicdn.net/cover/4851000001/xlarge      225px × 327px
https://img.ridicdn.net/cover/4851000001/xxlarge     480px × 696px

add ?hdpi
https://img.ridicdn.net/cover/4851000001/large?dpi=hdpi#1      165px × 240px
https://img.ridicdn.net/cover/4851000001/large?dpi=xhdpi       220px × 320px
https://img.ridicdn.net/cover/4851000001/large?dpi=xxhdpi      330px × 480px

https://img.ridicdn.net/cover/4851000001/xlarge?dpi=hdpi       225px × 327px
https://img.ridicdn.net/cover/4851000001/xlarge?dpi=xhdpi      300px × 436px
https://img.ridicdn.net/cover/4851000001/xlarge?dpi=xxhdpi     450px × 654px

https://img.ridicdn.net/cover/4851000001/xxlarge?dpi=hdpi      480px × 696px
https://img.ridicdn.net/cover/4851000001/xxlarge?dpi=xhdpi     640px × 928px
https://img.ridicdn.net/cover/4851000001/xxlarge?dpi=xxhdpi    960px × 1392px

Until now ..../xxlarge?dpi=xxhdpi is the largest size I know

**Comment by Froktime** [comment]
> [Seems like](https://slow.pics/c/qBUGpwOy) `format=png` is higher quality than `webp` (default) or `jpg`.
> 
> https://img.ridicdn.net/cover/4851000001/xxlarge?dpi=xxhdpi&format=png

this png is like a gif image 
![ảnh](https://github.com/qsniyg/maxurl/assets/98095197/0b5b0400-31a0-4e4b-92ec-2455aaf01d88)
In ebook books, the publisher will insert original images or it's on twitter so I can compare it with the cover on this website

**Comment by qsniyg** [comment]
Thanks to both! I've used &format=png as @neckothy suggested.

The artifacts @Froktime noticed appear to be part of the original image. Compare the buildings at the bottom of these two images:

https://img.ridicdn.net/cover/4851000001/xxlarge?dpi=xxxhdpi
https://img.ridicdn.net/cover/4851000001/xxlarge?dpi=xxxhdpi&format=png
