### ISSUE TITLE
Support crepe

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1259]
Link of website: crepe.cm

Regular images on the website
https://i.crepe.land/https://crepe.land/portfolio/0/0t/0tfibilw6uaf2k1n3mrwml6va2s8ap29_%EC%8A%A4%ED%8B%B4%ED%82%B9.png?q=100&t=i&v=3a&w=800&x=1
https://i.crepe.land/https://crepe.land/portfolio/0/0t/0tfibilw6uaf2k1n3mrwml6va2s8ap29_%EC%8A%A4%ED%8B%B4%ED%82%B9.png?q=100&t=i&v=3a&w=800&x=2
https://i.crepe.land/https://crepe.land/portfolio/0/0t/0tfibilw6uaf2k1n3mrwml6va2s8ap29_%EC%8A%A4%ED%8B%B4%ED%82%B9.png?h=75&t=i&v=3a&w=75&x=2

Original image: https://crepe.land/portfolio/0/0t/0tfibilw6uaf2k1n3mrwml6va2s8ap29_%EC%8A%A4%ED%8B%B4%ED%82%B9.png

**Comment by qsniyg** [comment]
Thank! Supported
