### ISSUE TITLE
Support Kobo covers

### ISSUE THREAD

**Issue by watatomo** [qsniyg/maxurl#1260]
Pretty simple. Example page [here](https://www.kobo.com/jp/en/ebook/GcVwJprCST2E6FwwKwgqWg/ir5rZB3wSUmLErEhJxHhLA).

Opening the cover image on the page gives you this url: `https://cdn.kobo.com/book-images/6d559572-f916-462d-a69f-b50708a35365/353/569/90/False/GcVwJprCST2E6FwwKwgqWg.jpg`

All you have to do is remove everything after the first path, which results in this following url: `https://cdn.kobo.com/book-images/6d559572-f916-462d-a69f-b50708a35365/GcVwJprCST2E6FwwKwgqWg.jpg`

From what I can tell, it refers to `width/height/quality`. Not so sure what the `false` though.

**Comment by qsniyg** [comment]
Thank you! The boolean value seems to toggle saturation.
