### ISSUE TITLE
fix Plurk SNS

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1262]
Type 1/ Same format (jpg)
Thumbnail:    https://images.plurk.com/mx_5sahzQQOBEDOlCFYF02WX8.jpg
Original image:     https://images.plurk.com/5sahzQQOBEDOlCFYF02WX8.jpg
Type 2/ Different format (png,gif, webp...)/ different characters (jpeg, jpe)
Thumbnail:    https://images.plurk.com/mx_1enwpR3JJbhoAUUpcpKb9Q.jpg
Original image:     https://images.plurk.com/1enwpR3JJbhoAUUpcpKb9Q.png
The script supports the same format, but when the original image is png img, it doesn't work. !!! thumbnail is usually jpg

**Comment by qsniyg** [comment]
Thanks, fixed!
