### ISSUE TITLE
Images not auto-redirecting on Apple Music

### ISSUE THREAD

**Issue by posnipy** [qsniyg/maxurl#1264]
For example, I used Image Max URL on this Apple Music album. Using "open image in new tab" does not redirect to a higher resolution version. I'm using the latest version of Firefox.

https://music.apple.com/us/album/hypermagic-mountain/1481250063

**Comment by qsniyg** [comment]
Thanks for reporting, seems like it's a regression from last version. I'll see if I can fix it :)

**Comment by qsniyg** [comment]
Should be fixed now!

**Comment by Gateway31** [comment]
I figured not to make a new issue, but it's still bit on topic: any idea why when I right-click on some images from one of Apple Music's radio schedule pages - e.g., https://music.apple.com/radio/ra.978194965 - I am no longer getting highest possible quality images? It used to redirect to *_999999999x0w-999.png_ image links, now it doesn't do that no more. Some images still redirect to _/source_, but not every single one.
And by the way, when I put this image link - https://is1-ssl.mzstatic.com/image/thumb/RadioSource221/v4/ea/7e/35/ea7e35b2-eb1d-f08f-521e-6623d65944b0/bb_source.png/592x592cc.webp - on the https://qsniyg.github.io/maxurl/ I get _Broken image_ error message.

<img width="1014" height="244" alt="Image" src="https://github.com/user-attachments/assets/3a33c4d8-b709-415d-bd62-53de6260bae5" />

**Comment by qsniyg** [comment]
@Gateway31 Thanks for reporting, should be fixed now!
