### ISSUE TITLE
Improving image.civitai.com rule

### ISSUE THREAD

**Issue by aslian** [qsniyg/maxurl#1265]
I think it should be `original=true` instead of current `width=0`.

This is scaled URL from grid:
https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/c759a98f-a02c-44b5-55f2-4ee5810eef00/width=450/282851.jpeg

This one is what maxurl suggest currently:
https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/c759a98f-a02c-44b5-55f2-4ee5810eef00/width=0/282851.jpeg
```
Content-Type:	Length: 109877 (107K) [image/jpeg]
Format:		/tmp/gmAgpwqt JPEG 800x1280+0+0 DirectClass 8-bit 107.3Ki 0.000u 0:01
MD5:		d3141fa702499cced990efe3295d4853  -
```

This one is from image page https://civitai.com/images/282851:
https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/c759a98f-a02c-44b5-55f2-4ee5810eef00/original=true/282851.jpeg
❢　Note that is has wrong extension even on the image page, and serves with wrong content-type.
```
Content-Type:	Length: 1535118 (1,5M) [text/plain]
Format:		/tmp/gmkKbsuW PNG 800x1280+0+0 DirectClass 8-bit 1.5Mi 0.000u 0:01
MD5:		19a1c1c994b5d22607757bc0d69c69b5  -
```

https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/c759a98f-a02c-44b5-55f2-4ee5810eef00/original=true/282851
```
Content-Type:	Length: 1535118 (1,5M) [text/plain]
Format:		/tmp/gmzx5uCd PNG 800x1280+0+0 DirectClass 8-bit 1.5Mi 0.000u 0:01
MD5:		19a1c1c994b5d22607757bc0d69c69b5  -
```

https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/c759a98f-a02c-44b5-55f2-4ee5810eef00/original=true/282851.png
```
Content-Type:	Length: 1535118 (1,5M) [text/plain]
Format:		/tmp/gmMx2Zv2 PNG 800x1280+0+0 DirectClass 8-bit 1.5Mi 0.000u 0:01
MD5:		19a1c1c994b5d22607757bc0d69c69b5  -
```

https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/c759a98f-a02c-44b5-55f2-4ee5810eef00/original=true
```
Content-Type:	Length: 1535118 (1,5M) [text/plain]
Format:		/tmp/gmVQcRco PNG 800x1280+0+0 DirectClass 8-bit 1.5Mi 0.000u 0:01
MD5:		19a1c1c994b5d22607757bc0d69c69b5  -
```

**Comment by qsniyg** [comment]
Thanks, fixed!

**Comment by aslian** [comment]
Nice! But what about the wrong extension part? Are there some helper functions for such situations?

**Comment by qsniyg** [comment]
Yes there are, but they're only for sites that absolutely need them to work. Unfortunately due to the way greasemonkey's XHR system works, you need to download the image completely before being able to figure out the actual content type. I *could* add an option to run it for the popup after every image has been loaded, but that would make streaming popup images impossible.

**Comment by aslian** [comment]
Well, these extensions is not a very big problem for me. Don't know for other users...

**Comment by qsniyg** [comment]
@aslian I won't worry about it unless someone complains. There's too many features in the backlog already (the number of open issues on this repo...), and I'm struggling to find much time to work on this project :(
