### ISSUE TITLE
page.kakao.com '&filename=o1' param

### ISSUE THREAD

**Issue by TristanWasTaken** [qsniyg/maxurl#1266]
page.kakao.com was added in #1176 where I listed an url with `&filename=o1`, but there was no difference between the image served when it was removed
turns out there is an *incredibly* small chance to not get the full size of the cover if you don't add the query param `&filename=o1`
example: https://page.kakao.com/content/58396566
- 160x216 https://dn-img-page.kakao.com/download/resource?kid=7QQvu/hAd4ne478s/N76c0HerPo9poqVpoc0IC1
- 720x1030 https://dn-img-page.kakao.com/download/resource?kid=7QQvu/hAd4ne478s/N76c0HerPo9poqVpoc0IC1&filename=o1

**Comment by qsniyg** [comment]
Thanks, fixed!
