### ISSUE TITLE
Support Arbum website

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1267]
Thumbnail image/Resized image:
https://an.arbum.art/p/01836a47-7a00-7553-bf41-a1b9046bfde1.png
https://an.arbum.art/p/01836a47-7a00-7553-bf41-a1b9046bfde1.png?preset=ArtworkPreview&size=200&ratio=1&dpr=2
https://an.arbum.art/i/01836a47-7a00-7553-bf41-a1b9046bfde1.png?preset=600&dpr=2

Original image:
https://an.arbum.art/i/01836a47-7a00-7553-bf41-a1b9046bfde1.png

**Comment by qsniyg** [comment]
Thanks, supported!
