### ISSUE TITLE
spigen.com

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1268]
https://partners.spigen.com/cdn/shop/products/title_ipad_pro_11_2020_rugged_armor_pro_02_175x.progressive.jpg?v=1659056452

need to remove "_*x.progressive"

https://partners.spigen.com/cdn/shop/products/title_ipad_pro_11_2020_rugged_armor_pro_02.jpg?v=1659056452

**Comment by qsniyg** [comment]
Thanks, the spotify generic rule didn't look for `.progressive`, fixed now :)
