### ISSUE TITLE
Support Lezhin

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1273]
**System 1** includes 3 websites: lezhin.com, lezhinus.com, lezhin.jp
These websites use the same image system
**_Banner:_**
+ Thumb: https://ccdn.lezhin.com/v2/inventory_items/4514079591694336/media/upperBannerMobile.webp?updated=1675058642000&width=688
+ Original image: https://ccdn.lezhin.com/v2/inventory_items/4514079591694336/media/upperBannerMobile      (they're png image but cannot insert "png" into "upperBannerMobile.png", links will be invalided)

**_Cover:_**
+ Thumb: https://ccdn.lezhin.com/v2/comics/6626593178189824/images/tall.webp?updated=1678868634586&width=354
+ Original image: https://ccdn.lezhin.com/v2/comics/6626593178189824/images/tall.jpg

**_Comic Info Extend cover_**
+ Thumb: https://ccdn.lezhin.com/v2/comics/6626593178189824/images/wide.webp?updated=1678868634586&width=800
+ Original image: https://ccdn.lezhin.com/v2/comics/6626593178189824/images/wide.jpg

**System 2:** lezhin.es
The original image can be jpg/jpeg, webp or png image. I think webp compresses images a lot. If possible, choose to download png or jpg
- https://image.balcony.studio/LEZHIN_ES/banner/2024/1706679627760.webp
--> https://image.balcony.studio/LEZHIN_ES/banner/2024/1706679627760.png
- https://image.balcony.studio/es/co_thumbnail/daf_1000741/1706673426120.webp
--> https://image.balcony.studio/es/co_thumbnail/daf_1000741/1706673426120.jpeg
- https://image.balcony.studio/es/co_thumbnail/LZ_3000041/1631786095698.webp
--> https://image.balcony.studio/es/co_thumbnail/LZ_3000041/1631786095698.jpg

- https://image.balcony.studio/es/co_thumbnail/daf_1000741/1706673425903.webp
--> https://image.balcony.studio/es/co_thumbnail/daf_1000741/1706673425903.webp

**Comment by qsniyg** [comment]
Thanks for the detailed report! It should be supported now :)
