### ISSUE TITLE
fix kemono and coomer being slow/unresponsive

### ISSUE THREAD

**Issue by vscum** [qsniyg/maxurl#1277]
kemono.party and coomer.party have been changed to .su domains. this also patches the slow search from previously using domain_nosub to domain_now. this is not a new rule, just a changed one that already exists
```ts
		if(domain_nowww === "kemono.party" ||
      			domain_nowww === "kemono.su" ||
      			domain_nowww === "coomer.party" ||
			domain_nowww === "coomer.su") {
			newsrc = src.replace(/\/thumbnail\/+data\/+/, "/data/");
			if (newsrc !== src)
				return newsrc.replace(/:\/\/img\./, "://c1.");
		}
```

**Comment by qsniyg** [comment]
Thanks for reporting. Does this commit not work for you? https://github.com/qsniyg/maxurl/commit/7d72ec66f2988eed66b507f5e83b30c508a7d154

There shouldn't be any speed difference between `domain_nosub` and `domain_nowww`. Using `domain_nowww` will miss quite a few subdomains that were used by them.

**Comment by vscum** [comment]
> Thanks for reporting. Does this commit not work for you? [7d72ec6](https://github.com/qsniyg/maxurl/commit/7d72ec66f2988eed66b507f5e83b30c508a7d154)

i have the userscript set to update through violentmonkey, so it hadnt updated to this beta (?) version. i will try this.

**Comment by qsniyg** [comment]
I'll tentatively close this issue, as it should work properly. If it doesn't, please let me know :)
