### ISSUE TITLE
Discord changes rules

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1278]
I had heard that Discord was going to change and today it really changed.
https://media.discordapp.net/attachments/1134546497606791248/1206941945436577792/image.png?ex=65ddd747&is=65cb6247&hm=3a7cdd94a6ca9b2668b1ee548d0e8fbe7f8dfba011ca4ad436609204d0666825&=&format=webp&quality=lossless&width=1098&height=732
=> Original image: https://media.discordapp.net/attachments/1134546497606791248/1206941945436577792/image.png?ex=65ddd747&is=65cb6247&hm=3a7cdd94a6ca9b2668b1ee548d0e8fbe7f8dfba011ca4ad436609204d0666825    (download automatically, **when you reload it**.)
I'm not sure which images will be **invalided**, so I took randomly the image. I think even if they are invalided, images' links will have **format=webp**, **quality=lossless**, **width=....**, **height=....**

**Comment by qsniyg** [comment]
Supported, thanks!
