### ISSUE TITLE
iTunes/Apple Music PNG thumbnails

### ISSUE THREAD

**Issue by uwuceo** [qsniyg/maxurl#1282]
Recently I noticed I get redirected to a new thumbnail photo (xxxxxxxxxxxxx.jpg/999999999x0w-999.png) that's a PNG the same resolution as the "original" (?), instead of to xxxxxxxxxxxxx.jpg (maybe original? anyway it was better quality than the jpg thumbnails)

The new PNG thumbnail is slightly different compared to the previous final redirect (xxxxxxxxxxxxx.jpg)

Is the new PNG slightly better or slightly worse? Are the previous final redirects (xxxxxxxxxxxxx.jpg) not available anymore, or just at a different URL?

Here are some hyperleveled comparison pics:

https://slow.pics/c/D17oQqd4

https://slow.pics/c/9Yz54lvw

Thanks!

**Comment by uwuceo** [comment]
I couldn't find the "original" JPG for the album below using the extension, but Ben Dodson's Apple Music Artwork Finder could find it, maybe it helps.

https://music.apple.com/us/album/%E6%81%8B%E6%84%9B%E8%84%B3-single/1631116697

https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/ae/f8/9f/aef89fbe-c066-952b-2864-783ec60a11fc/4547366572957.jpg/999999999x0w-999.png

https://a5.mzstatic.com/us/r1000/0/Music112/v4/ae/f8/9f/aef89fbe-c066-952b-2864-783ec60a11fc/4547366572957.jpg

**Comment by qsniyg** [comment]
@uwuceo IMU redirects the URL you linked for me to https://a1.mzstatic.com/us/r1000/063/Music112/v4/ae/f8/9f/aef89fbe-c066-952b-2864-783ec60a11fc/4547366572957.jpg, does it not for you?

**Comment by uwuceo** [comment]
When I try to access the image you linked I get:

Unable to connect

An error occurred during a connection to a1.mzstatic.com.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox Developer Edition is permitted to access the web.

**Comment by uwuceo** [comment]
Well, I just deactivated uBlock and it loaded :P

I'll leave it off and test a couple more.

**Comment by uwuceo** [comment]
I disabled uBlock, reloaded the image you linked and reactivated it, and it works now. Tried a few images, and it got the "original" jpg/png for all of them.

Thanks for helping me figure it out!
