### ISSUE TITLE
Add fanbox

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1287]
fanbox.cc

https://downloads.fanbox.cc/images/post/7521021/w/1200/QLCWVrj9WHWkTPLLSOePGVQ8.jpeg
=> https://downloads.fanbox.cc/images/post/7521021/QLCWVrj9WHWkTPLLSOePGVQ8.png
Original images can be jpg, jpeg, png, gif

**Comment by qsniyg** [comment]
Thanks, supported :)
