### ISSUE TITLE
Xenforo avatars

### ISSUE THREAD

**Issue by TristanWasTaken** [qsniyg/maxurl#1289]
Xenforo avatars
seems to be already supported for xenforo.com with `/data/` in-between?
https://xenforo.com/community/threads/get-user-avatar-url.200352/
https://xenforo.com/community/data/avatars/l/196/196224.jpg?1701365171
https://xenforo.com/community/data/avatars/o/196/196224.jpg?1701365171

format:
![xf](https://github.com/qsniyg/maxurl/assets/43283797/8e5586e2-1f60-4eb9-b457-7c5df2dfbe64)

example:
https://forums.mangadex.org
m - https://forums.mangadex.org/community/avatars/m/387/387489.jpg?1681789858
l - https://forums.mangadex.org/community/avatars/l/387/387489.jpg?1681789858
o - https://forums.mangadex.org/community/avatars/h/387/387489.jpg?1681789858

**Comment by qsniyg** [comment]
I've made the rule a little more generic (and explicitly supported mangadex), it should work for most sites now :)
