### ISSUE TITLE
mdpr.jp|img-mdpr.freetls.fastly.net 

### ISSUE THREAD

**Issue by billkewl** [qsniyg/maxurl#1290]
Hello.

Currently maxurl strips all parameters from images on mdpr.jp (img-mdpr.freetls.fastly.net)
However the highest quality can only be retrieved by adding a quality=100 parameter.

```
https://img-mdpr.freetls.fastly.net/article/3PAL/nm/3PALRhB9GlTvhbGVrKYxgnU0GJMdFkmrnGGowdtaTok.jpg

https://img-mdpr.freetls.fastly.net/article/3PAL/nm/3PALRhB9GlTvhbGVrKYxgnU0GJMdFkmrnGGowdtaTok.jpg?quality=100
```

Could you please fix its hard coded rule?
Thank you.

**Comment by qsniyg** [comment]
Thanks, fixed!
