### ISSUE TITLE
Add Heavenly tv

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1292]
https://image.heavenly.tv/content/11260069207084254729-20240130085043.png?w=300
=> https://image.heavenly.tv/content/11260069207084254729-20240130085043.png

https://image.heavenly.tv/content-item/17738048344724538567-20240219084049.jpg?w=600
=> https://image.heavenly.tv/content-item/17738048344724538567-20240219084049.jpg

**Comment by qsniyg** [comment]
Thanks, supported!
