### ISSUE TITLE
Add LnwShop domain

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1301]
This type of website domain is very similar to Wordpress. The different from Wordpress is that it's designed for Thai people.

Sample 1
https://www.firstlove-online.com/      (Using a premium domain seems to hide the Lnwshop extension)

https://cp.lnwfile.com/_/cp/_fit/300/400/mb/j8/vx.jpg
-> https://cp.lnwfile.com/_/cp/_raw/mb/j8/vx.jpg
https://cp.lnwfile.com/_/cp/_resize/300/400/6k/44/q2.jpg
-> https://cp.lnwfile.com/_/cp/_raw/6k/44/q2.jpg

Sample 2
http://andra-shop.lnwshop.com/

https://ff.lnwfile.com/_/ff/_resize/300/400/x5/3v/ui.jpg
-> https://ff.lnwfile.com/_/ff/_raw/x5/3v/ui.jpg

Sample 3
http://preorder-dr.lnwshop.com/

https://dt.lnwfile.com/_/dt/_fit/600/600/jj/kl/tv.webp
-> https://dt.lnwfile.com/_/dt/_raw/jj/kl/tv.webp

**Comment by qsniyg** [comment]
Thanks! Supported :)
