### ISSUE TITLE
page.kakao.com

### ISSUE THREAD

**Issue by TristanWasTaken** [qsniyg/maxurl#1307]
in #1266 support for the `filename=o1` query param was added
I just found an url that isn't being rewritten due to the query param

https://page.kakao.com/content/57096997
- https://page-images.kakaoentcdn.com/download/resource?kid=qFrns/hAd47wJicm/Cr4Bq4DkXn44OcNbCVb3Sk&filename=o1/dims/resize/384
- https://page-images.kakaoentcdn.com/download/resource?kid=qFrns/hAd47wJicm/Cr4Bq4DkXn44OcNbCVb3Sk&filename=o1

**Comment by qsniyg** [comment]
Thanks! Updated.
