### ISSUE TITLE
[rule] Voici.fr

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1310]
https://photo.voici.fr/adam-sandler-lenny-kravitz-billie-eilish-les-stars-presentes-aux-peoples-choice-awards-2024-59444

https://voi.img.pmdstatic.net/scale/~1~voi~2024~02~19~15af5e46-e0a6-4c83-a188-c42170541d61.jpeg/autox600/quality/65/crop-from/center/picture.jpeg

Original: https://i.pmdstatic.net/voi/2024/02/19/15af5e46-e0a6-4c83-a188-c42170541d61.jpeg

**Comment by qsniyg** [comment]
Thanks, supported :)
