### ISSUE TITLE
[ET Online] Get much larger image

### ISSUE THREAD

**Issue by BlindWanda** [qsniyg/maxurl#1311]
Just saw that maxurl only adapts the URL to a certain point but still keeps the "?width=640" tag at the end. If you remove that tag then you get the full-size image they are using. Can this be added in to remove that?

[Original ET online resized image url]
https://www.etonline.com/sites/default/files/styles/slide/public/images/2020-07/gettyimages-1179647624.jpg?width=640
[Adapted maxurl for ET online still resized]
https://www.etonline.com/sites/default/files/images/2020-07/gettyimages-1179647624.jpg?width=640
[Much larger image without the width tag]
https://www.etonline.com/sites/default/files/images/2020-07/gettyimages-1179647624.jpg

**Comment by qsniyg** [comment]
Should be fixed now, thanks for reporting!
