### ISSUE TITLE
Add dlsite

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1312]
https://www.dlsite.com/

Thumbnail: https://img.dlsite.jp/resize/images2/work/books/BJ617000/BJ616372_img_main_240x240.jpg
Original: https://img.dlsite.jp/modpub/images2/work/books/BJ617000/BJ616372_img_main.jpg

Webp img: https://img.dlsite.jp/modpub/images2/work/doujin/RJ438000/RJ437590_img_smp4.webp
Original: https://img.dlsite.jp/modpub/images2/work/doujin/RJ438000/RJ437590_img_smp4.jpg

**Comment by qsniyg** [comment]
Thanks, supported!
