### ISSUE TITLE
Add Ameba Manga

### ISSUE THREAD

**Issue by SUPER7X** [qsniyg/maxurl#1313]
It's the one site I use regularly that your extension doesn't have. Would save me so much time if you added it.

https://dokusho-ojikan.jp

thumbnail: https://stat.dokusho-ojikan.jp/bf0e01c5-6bc4-4ce0-815a-1d90b9e19130.jpg?dh=302&dw=212&of=webp&q=70
original: https://stat.dokusho-ojikan.jp/bf0e01c5-6bc4-4ce0-815a-1d90b9e19130.jpg

As far as I'm aware, the images are always JPGs with URLs always formatted in this exact way.

Thanks!

**Comment by qsniyg** [comment]
Thanks, supported!
