### ISSUE TITLE
Add open graph image preview for steam chat

### ISSUE THREAD

**Issue by n0099** [qsniyg/maxurl#1314]
https://www.inori.moe/2023/11/22/just-updated-the-blog/
```html
<meta property="og:image" content="http://inori.moe/img/covers/hexoupdate.jpg">
<meta name="twitter:image" content="http://inori.moe/img/covers/hexoupdate.jpg">
```
https://steamcommunity-a.akamaihd.net/chat/image/ytVLh2iuegcBz8cmwozQlRfu4DI9bkP3nqrIsC2towJsb9Vg8-QAX71yzn1RAw/share_image.jpg?s=256x140
https://steamcommunity-a.akamaihd.net/chat/image/ytVLh2iuegcBz8cmwozQlRfu4DI9bkP3nqrIsC2towJsb9Vg8-QAX71yzn1RAw/share_image.jpg

**Comment by qsniyg** [comment]
Thanks, supported!
