### ISSUE TITLE
Fix crepe

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1315]
crepe.cm

Previously, it was possible to remove the `https://i.crepe.land/` and `?h=75&t=i&v=3a&w=75&x=2` parts to get original imgs, but now only some links are available, the remaining links are all banned.
![ảnh](https://github.com/qsniyg/maxurl/assets/98095197/fb20f317-f6c2-4716-a4fe-aece704ff396)

The original image can still be gotten. The only thing is that the image is in webp format (if saved on chrome, the extension will not change, but on firefox, it will show as webp format)
https://i.crepe.land/https://crepe.land/portfolio/h/ht/ht7tw8xcih435lphickqr5powq4mhokw_dasflas2_%25EB%258B%25892.png?h=75&t=i&v=3a&w=75&x=2
=>
https://i.crepe.land/https://crepe.land/portfolio/h/ht/ht7tw8xcih435lphickqr5powq4mhokw_dasflas2_%25EB%258B%25892.png?t=i

I think the old rule should still be left and if the old rule doesn't work, then move on to rule 2
https://crepe.land/portfolio/0/0k/0kgg7umu41h8494mztn86cef9qp6yjjg_1654326234275.png

**Comment by qsniyg** [comment]
Thanks! Should be fixed now.
