### ISSUE TITLE
Tumblr images no longer redirecting at all

### ISSUE THREAD

**Issue by nyahgust** [qsniyg/maxurl#1316]
I'm unsure why or how to troubleshoot the issue, but as of around a week ago, Tumblr images no longer redirect at all. 

From what I recall, the way they would usually work is that you would load up an image and then a pop-up would appear that would redirect to a higher-quality version when clicked. I've used this tool quite a lot for Tumblr in particular, but it no longer seems to be working on my end (through Firefox nightly and installed as a script, though I did try the extension version as well and got no results). 

I checked some other websites (i.e. Twitter) and the extension still works on images from other sites. I also checked to see if this issue was reported elsewhere and didn't see anything–it may be just on my end, but I haven't made any changes to settings that should've affected the script this way.

**Comment by nyahgust** [comment]
https://64.media.tumblr.com/34c14ceab6f5e5f22df5d6c6ba63638e/6bea1972cb8aab3d-ce/s2048x3072/c49bbd8ea7193f4750837281b6fc06b4ff6c80df.pnj 
^ Random example of an image link that should be redirecting (width is limited by url, ends with pnj instead of png) but there's no pop-up or redirecting when I view the image.
<img width="1605" alt="Screenshot 2024-04-19 at 12 44 03 PM" src="https://github.com/qsniyg/maxurl/assets/114715856/f6300ada-2e67-4dce-b794-391f8cee94fb">

**Comment by qsniyg** [comment]
Thanks for reporting! Should be fixed now :)
