### ISSUE TITLE
Add theplace-2.com

### ISSUE THREAD

**Issue by fyhtma** [qsniyg/maxurl#1317]
Could you please add this site? Thanks

https://theplace-2.com/photos/Alizee-md896/pic-557421.html
> https://theplace-2.com/cache/archive/alizee/img/23-26-gthumb-gwdata1200-ghdata1200-gfitdatamax.jpg [982x1200px]
>> http://www.theplace2.ru/archive/alizee/img/23-26.jpg [3928x4803px]

**Comment by qsniyg** [comment]
It already redirects for me... does it not for you?

**Comment by fyhtma** [comment]
No it doesn't for some reason. Updated the addons in Firefox and Chrome to Image Max URL 2024.3.0 version. Also made fresh install of add-on to Firefox Developer Edition with default settings.  Tried also Edge with Tampermonkey and userscript_smaller.user.js but none of them doesn't redirects.

**Comment by qsniyg** [comment]
Ah, it's because it was added in the development/git version. I'll close the issue because it should be fixed next release (although please feel free to re-open it if it doesn't work).
