### ISSUE TITLE
Support for LDDB

### ISSUE THREAD

**Issue by CetaceanNation** [qsniyg/maxurl#1320]
Easy rule, just remove `/thumb` path component.

Page: https://www.lddb.com/laserdisc/37544/SF098-1168/Back-to-the-Future
Thumbnail: https://www.lddb.com/cover/ld/37501-37600/thumb/37544.jpg
Max size: https://www.lddb.com/cover/ld/37501-37600/37544.jpg

Side note: watermarks are only removed when logged in.

**Comment by qsniyg** [comment]
Thanks, supported!
