### ISSUE TITLE
[rule] Cronica.com.mx

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1321]
https://www.cronica.com.mx/escenario/sydney-sweeney-alvaro-morte-secreto-encuentro-fans-inmaculada.html

for the top pic maxurl opens this (948x465). 
https://imagenes.cronica.com.mx/files/image_948_465/files/fp/uploads/2024/05/04/6636c21b5dafb.r_d.974-506-4938.jpeg 
→
https://imagenes.cronica.com.mx/uploads/2024/05/04/6636c21b5dafb.jpeg (1920x1080)

For other pics it's the same, but without changing name of the file
https://imagenes.cronica.com.mx/files/content_image_desktop_filter/uploads/2024/05/04/6636c5b6a654c.jpeg
→
https://imagenes.cronica.com.mx/uploads/2024/05/04/6636c5b6a654c.jpeg

I think there's more variations, but I think it's safe to just delete everything between .mx and /uploads every time :)

**Comment by qsniyg** [comment]
Thanks, supported!
