### ISSUE TITLE
popsugar thumbor with "/top/" in URL

### ISSUE THREAD

**Issue by bsydow** [qsniyg/maxurl#1323]
rule seems not to recognize `/top/`. According to [Thumbor](https://github.com/thumbor/thumbor/blob/master/docs/usage.rst#vertical-align), `/middle/`, `/top/`, `/bottom/`, `/left/`, `/center/` and `/right/` can also appear in the url.

#### Example without `/top/` (work): 
https://media1.popsugar-assets.com/files/thumbor/IWdahdA6opuJPPhyljg2Jct2BQ0=/fit-in/1584x2376/filters:format_auto():upscale()/2019/04/23/687/n/1922564/c90ff4fbad79253f_GettyImages-1138768729.jpg

expected URL: https://media1.popsugar-assets.com/files/2019/04/23/687/n/1922564/c90ff4fbad79253f_GettyImages-1138768729.jpg

#### Example with `/top/` (does not work): 
https://media1.popsugar-assets.com/files/thumbor/nABWpoAEkMbUUQ-0rBRznnHGnlQ=/fit-in/792x527/top/filters:format_auto():upscale()/2019/04/23/687/n/1922564/7aba47deaf9aef0f_GettyImages-1144527044.jpg

expected URL: https://media1.popsugar-assets.com/files/2019/04/23/687/n/1922564/7aba47deaf9aef0f_GettyImages-1144527044.jpg

If I remove `/top/` from the URL, MaxURL can convert it (tested via https://qsniyg.github.io/maxurl/)

**Comment by qsniyg** [comment]
Thanks, I've replaced the custom thumbor rule with the generic thumbor converter, which handles that case :)
