### ISSUE TITLE
Coveteur.com

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1325]
https://coveteur.com/jemima-kirke-closet-tour/

Maxurl opens: https://coveteur.com/media-library/image.jpg?id=52237495&width=980 

Obviously, deleting "width" loads full image :)

Seems like some pictures also have height and other parameters like here
https://coveteur.com/2019/05/02/actress-sydney-sweeney-on-cusp-of-meteoric-rise/

**Comment by tathastu871** [comment]
REMOVE ALL HEIGHT WIDTH PARAMETER AND ADD
&quality=100 -> This maxes out the quality
https://coveteur.com/media-library/image.jpg?id=52237495&quality=100

BEST QUALITY

**Comment by qsniyg** [comment]
Thank you! Supported :)
