### ISSUE TITLE
[rule] Lavanguardia.com

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1326]
Pretty much the same rule as here - https://github.com/qsniyg/maxurl/issues/1321

https://www.lavanguardia.com/magazine/moda/20201129/6062006/greta-fernandez-me-caigo-mi.html

https://www.lavanguardia.com/files/content_image_desktop_filter/uploads/2020/11/27/5fc037b9cc702.jpeg
→
https://www.lavanguardia.com/uploads/2020/11/27/5fc037b9cc702.jpeg

**Comment by qsniyg** [comment]
Thanks! I've merged a bunch of other similar rules together as well.
