### ISSUE TITLE
New Spotify Filter Pattern

### ISSUE THREAD

**Issue by lazybookwyrm** [qsniyg/maxurl#1329]
Hey, found a new pattern similar to the ones in an older issue here https://github.com/qsniyg/maxurl/issues/833

"82c1" returns higher resolution images than the currently implemented "b273". I've gotten 1000x1000, 1500x1500, 1600x1600, etc. up to 2000x2000.

**Comment by ItsProyal** [comment]
Thought I would add on some of my notes from a couple weeks ago when I was searching for higher quality spotify images.


# Cover Art
_ab67616d0000_

| Format | Key  | Dimensions                                                                    |     | Format | Key  | Dimensions                                                                  |
| ------ | ---- | ----------------------------------------------------------------------------- | --- | ------ | ---- | --------------------------------------------------------------------------- |
| JPEG   | 82c1 | [2000x2000](https://i.scdn.co/image/ab67616d000082c1664e38c99d077cc52ab48914) |     | WEBP   | aa54 | [640x640](https://i.scdn.co/image/ab67616d0000aa54664e38c99d077cc52ab48914) |
| JPEG   | b273 | [640x640](https://i.scdn.co/image/ab67616d0000b273664e38c99d077cc52ab48914)   |     | WEBP   | 75a0 | [640x640](https://i.scdn.co/image/ab67616d000075a0664e38c99d077cc52ab48914) |
| JPEG   | d452 | [640x640](https://i.scdn.co/image/ab67616d0000d452664e38c99d077cc52ab48914)   |     | WEBP   | a426 | [640x640](https://i.scdn.co/image/ab67616d0000a426664e38c99d077cc52ab48914) |
| JPEG   | 1e02 | [300x300](https://i.scdn.co/image/ab67616d00001e02664e38c99d077cc52ab48914)   |     | WEBP   | e1a3 | [300x300](https://i.scdn.co/image/ab67616d0000e1a3664e38c99d077cc52ab48914) |
| JPEG   | f848 | [300x300](https://i.scdn.co/image/ab67616d0000f848664e38c99d077cc52ab48914)   |     | WEBP   | ab87 | [300x300](https://i.scdn.co/image/ab67616d0000ab87664e38c99d077cc52ab48914) |
| JPEG   | 4851 | [64x64](https://i.scdn.co/image/ab67616d00004851664e38c99d077cc52ab48914)     |     | WEBP   | 2d53 | [300x300](https://i.scdn.co/image/ab67616d00002d53664e38c99d077cc52ab48914) |
| JPEG   | 745c | [64x64](https://i.scdn.co/image/ab67616d0000745c664e38c99d077cc52ab48914)     |     | WEBP   | 11eb | [64x64](https://i.scdn.co/image/ab67616d000011eb664e38c99d077cc52ab48914)   |
|        |      |                                                                               |     | WEBP   | 90d5 | [64x64](https://i.scdn.co/image/ab67616d000090d5664e38c99d077cc52ab48914)   |
|        |      |                                                                               |     | WEBP   | 54be | [64x64](https://i.scdn.co/image/ab67616d000054be664e38c99d077cc52ab48914)   |

# Avatar
_ab6761610000_

| Format | Key  | Dimensions |     | Format | Key  | Dimensions |
| ------ | ---- | ---------- | --- | ------ | ---- | ---------- |
| JPEG | e5eb | [640x640](https://i.scdn.co/image/ab6761610000e5ebe03a98785f3658f0b6461ec4) |     | WEBP | 8ef1 | [640x640](https://i.scdn.co/image/ab67616100008ef1e03a98785f3658f0b6461ec4) |
| JPEG | 5174 | [320x320](https://i.scdn.co/image/ab67616100005174e03a98785f3658f0b6461ec4) |     | WEBP | 86f7 | [640x640](https://i.scdn.co/image/ab676161000086f7e03a98785f3658f0b6461ec4) |
| JPEG | f178 | [160x160](https://i.scdn.co/image/ab6761610000f178e03a98785f3658f0b6461ec4) |     | WEBP | 939b | [320x320](https://i.scdn.co/image/ab6761610000939be03a98785f3658f0b6461ec4) |
|  |  |  |     | WEBP | 918b | [320x320](https://i.scdn.co/image/ab6761610000918be03a98785f3658f0b6461ec4) |
|  |  |  |     | WEBP | 101f | [160x160](https://i.scdn.co/image/ab6761610000101fe03a98785f3658f0b6461ec4) |
|  |  |  |     | WEBP | 102f | [160x160](https://i.scdn.co/image/ab6761610000102fe03a98785f3658f0b6461ec4) |

# Header / Banner
_ab6761860000_
(note: some banners seem to only have the 1016 encoding.)

| Format | Key  | Dimensions |     | Format | Key  | Dimensions |
| ------ | ---- | ---------- | --- | ------ | ---- | ---------- |
| JPEG | 1016 | [2660x1140](https://i.scdn.co/image/ab67618600001016a0dbecfa2aa77f59a3debf3a) |     | WEBP | eab1 | [2660x1140](https://i.scdn.co/image/ab6761860000eab1a0dbecfa2aa77f59a3debf3a) |
| JPEG | 6fba | [1495x641](https://i.scdn.co/image/ab67618600006fbaa0dbecfa2aa77f59a3debf3a) |     | WEBP | 3e24 | [2660x1140](https://i.scdn.co/image/ab67618600003e24a0dbecfa2aa77f59a3debf3a) |
| JPEG | 660e | [1493x640](https://i.scdn.co/image/ab6761860000660ea0dbecfa2aa77f59a3debf3a) |     | WEBP | 9d80 | [1495x641](https://i.scdn.co/image/ab67618600009d80a0dbecfa2aa77f59a3debf3a) |
|  |  |  |     | WEBP | d7b3 | [1495x641](https://i.scdn.co/image/ab6761860000d7b3a0dbecfa2aa77f59a3debf3a) |
|  |  |  |     | WEBP | 0194 | [1493x640](https://i.scdn.co/image/ab67618600000194a0dbecfa2aa77f59a3debf3a) |
|  |  |  |     | WEBP | c09f | [1493x640](https://i.scdn.co/image/ab6761860000c09fa0dbecfa2aa77f59a3debf3a) |
# Gallery Image
_ab6761670000_

| Format | Key  | Dimensions |     | Format | Key  | Dimensions |
| ------ | ---- | ---------- | --- | ------ | ---- | ---------- |
| JPEG | 82e8 | [2027x1140](https://i.scdn.co/image/ab676167000082e8cb99cfc3d47e59832136b38b) |     | WEBP | 6054 | [2027x1140](https://i.scdn.co/image/ab67616700006054cb99cfc3d47e59832136b38b) |
| JPEG | e911 | [1000x563](https://i.scdn.co/image/ab6761670000e911cb99cfc3d47e59832136b38b) |     | WEBP | 1217 | [1000x563](https://i.scdn.co/image/ab67616700001217cb99cfc3d47e59832136b38b) |
| JPEG | ecd4 | [640x360](https://i.scdn.co/image/ab6761670000ecd4cb99cfc3d47e59832136b38b) |     | WEBP | de4a | [640x360](https://i.scdn.co/image/ab6761670000de4acb99cfc3d47e59832136b38b) |
| JPEG | d8f8 | [200x113](https://i.scdn.co/image/ab6761670000d8f8cb99cfc3d47e59832136b38b) |     | WEBP | ea36 | [200x113](https://i.scdn.co/image/ab6761670000ea36cb99cfc3d47e59832136b38b) |
| JPEG | e30a | [64x36](https://i.scdn.co/image/ab6761670000e30acb99cfc3d47e59832136b38b) |     | WEBP | 81f9 | [64x36](https://i.scdn.co/image/ab676167000081f9cb99cfc3d47e59832136b38b) |

**Comment by qsniyg** [comment]
Thank you @ItsProyal for this amazing list! Supported now :)
