### ISSUE TITLE
Update plurk

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1330]
https://images.plurk.com/mx_3Bf8xiLf27TXtb3xf4g4Dd.jpg
=>  https://images.plurk.com/3Bf8xiLf27TXtb3xf4g4Dd.gif
thumbnails are always jpg img, original imgs can be jpg/jpeg/gif/png/(?webp)... 

image link can cause error if the image format is incorrect
![ảnh](https://github.com/qsniyg/maxurl/assets/98095197/845edb56-f7eb-48d6-9f1a-689ddefa985f)
https://images.plurk.com/3Bf8xiLf27TXtb3xf4g4Dd.jpg (error)

**Comment by qsniyg** [comment]
Thanks, fixed!
