### ISSUE TITLE
[rule] Esquire Germany

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#1334]
https://www.esquire.de/news/gesellschaft/sydney-sweeney-der-euphoria-star-im-interview

https://static.esquire.de/3000x4286/focal_1500x1500:1501x1501/images/2022-07/au2357226-1730ff54f3c-1171671-2.jpg
\>
https://backend.esquire.de/sites/esquire.de/files/images/2022-07/au2357226-1730ff54f3c-1171671-2.jpg

Some of the original pics that I tested had smaller size, but I guess it's because their engine upscales them.

**Comment by qsniyg** [comment]
Supported, thanks!

**Comment by sn3akyb3ar** [comment]
@qsniyg Seems like Esquire slightly changed the url format to this (same pic as in first post).

https://static.esquire.de/0x172:4912x7189/2560x3657/images/2022-07/au2357226-1730ff54f3c-1171671-2.jpg

And larger pic is still at the same url

https://backend.esquire.de/sites/esquire.de/files/images/2022-07/au2357226-1730ff54f3c-1171671-2.jpg

**Comment by qsniyg** [comment]
Thanks, updated :)
