### ISSUE TITLE
Support for px-monkey.com

### ISSUE THREAD

**Issue by fyhtma** [qsniyg/maxurl#1335]
need support for this site [related] / [big] -> [orig]
https://www.px-monkey.com/en/valka-ve-vietnamu/nam-the-vietnam-experience-1965-1975-vol--1-2/
>thumbnails
>http://cdn.myshoptet.com/usr/www.px-monkey.com/user/shop/related/13020-1_nam-the-vietnam-experience-1965-1975-vol--1-2.jpg?63efb864
or regular pics
>https://cdn.myshoptet.com/usr/www.px-monkey.com/user/shop/big/13020_nam-the-vietnam-experience-1965-1975-vol--1-2.jpg?63efb863

>>https://cdn.myshoptet.com/usr/www.px-monkey.com/user/shop/orig/13020_nam-the-vietnam-experience-1965-1975-vol--1-2.jpg?63efb863

**Comment by qsniyg** [comment]
Thanks, supported!
