### ISSUE TITLE
Support request for phots on fileserver:  file[01-06].es.c01.co

### ISSUE THREAD

**Issue by leoli1110** [qsniyg/maxurl#1337]
sample script should be as follow
if(domain.match(/^file[0-9]+\.es\.c01\.co/)){console.log(src.replace(/_[0-9]+x[0-9]+(\.[^/.]*)$/,""))}
yet, i cann't make it works in @@

example:

https://file01.es.c01.co/upload/E9E55B4EDD33C8E0/202402/4768047368473278140.jpg_120x160.ashx
https://file01.es.c01.co/upload/E9E55B4EDD33C8E0/202402/4768047368473278140.jpg

**Comment by qsniyg** [comment]
Thanks for reporting! Supported.

I'm not sure what you mean by `@@`, are there other URLs with a different pattern?
