### ISSUE TITLE
Add support for Steam inventory images

### ISSUE THREAD

**Issue by ljcool2006** [qsniyg/maxurl#1338]
Example:

https://community.akamai.steamstatic.com/economy/image/RgGbIK_Xaakl8PcQ2KQKK0i_2YIC7wZf7gTzKvLti-4wttL6ECYQfWnVrvtPO17Cg21bxebO3U9ipAtKlE8ALp2SN7cy4BnDeP3mbTsvYTyjoI8dxrcZq7BhYmFUB80R9lCkKSBHR24nqw/330x192?allow_animated=1

becomes:

https://community.akamai.steamstatic.com/economy/image/RgGbIK_Xaakl8PcQ2KQKK0i_2YIC7wZf7gTzKvLti-4wttL6ECYQfWnVrvtPO17Cg21bxebO3U9ipAtKlE8ALp2SN7cy4BnDeP3mbTsvYTyjoI8dxrcZq7BhYmFUB80R9lCkKSBHR24nqw?allow_animated=1

**Comment by qsniyg** [comment]
Thanks, supported!
