### ISSUE TITLE
Update zerochan

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1341]
zerochan.net
I found the script works with Zerochan but is only available for jpg originals and not for pngs

https://s1.zerochan.net/Marie.Antoinette.600.532255.jpg
=> https://static.zerochan.net/Marie.Antoinette.full.532255.jpg

https://s1.zerochan.net/Berusaiyu.no.Bara.600.3749354.jpg
=> https://static.zerochan.net/Berusaiyu.no.Bara.full.3749354.png

**Comment by qsniyg** [comment]
Thanks, fixed!
