### ISSUE TITLE
Add aladin

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1344]
www.aladin.co.kr

https://image.aladin.co.kr/product/33894/48/cover100/k132930727_1.jpg
https://image.aladin.co.kr/product/33894/48/cover200/k132930727_1.jpg
https://image.aladin.co.kr/product/33894/48/cover500/k132930727_1.jpg

=> https://image.aladin.co.kr/product/33894/48/letslook/k132930727_fl.jpg

_cover500_ = _LetsLook_, __1_=__FL_

**Comment by Froktime** [comment]
Content of a ebook
https://image.aladin.co.kr/product/33226/88/letslook/K452937057_t6l.jpg?RS=490.333333&WG=3&WS=100&&WO=30&WF=-15x15&WU=https://image.aladin.co.kr/img/common/openmarket_ci.png

=> https://image.aladin.co.kr/product/33226/88/letslook/K452937057_t6l.jpg

**Comment by thiagojramos** [comment]
![image](https://github.com/user-attachments/assets/7d3ff240-fe80-4fdd-a894-71e9a59817f0)

**Comment by qsniyg** [comment]
Thanks, fixed! I don't see any difference for the two links listed https://github.com/qsniyg/maxurl/issues/1344#issuecomment-2212490216 though.

**Comment by Froktime** [comment]
> Thanks, fixed! I don't see any difference for the two links listed [#1344 (comment)](https://github.com/qsniyg/maxurl/issues/1344#issuecomment-2212490216) though.

Img with width=750px
https://image.aladin.co.kr/product/28728/13/letslook/8934967323_wbl.jpg?MW=750&

=> Original img https://image.aladin.co.kr/product/28728/13/letslook/8934967323_wbl.jpg

I really don't know how, but please remove the following character sequences "?" The code of this website operates arbitrarily in each book.  With some books you will see the logo of the website, and it depends on whether you are viewing it by phone or PC.

**Comment by Froktime** [comment]
https://image.aladin.co.kr/product/33922/4/cover500/8934935758_1.jpg?RS=170

=> https://image.aladin.co.kr/product/33922/4/letslook/8934935758_fl.jpg

I assume 8934935758 is the id of a book. These ids can be Numbers, K + numbers, e + numbers (Ex: 3674577867, k6827492589, e2693384078). 
1////
Id is numbers / k + numbers, you can get the original img in the form of a link:
image.aladin.co.kr/product/[?????]/[1-9]/letslook/[id]_fl.jpg

The content of the 2 types of book id has 2 link types

 Type 1/ Type has WATERMARK and CAN/MAYBE be resized 
https://image.aladin.co.kr/product/33226/88/letslook/K452937057_t3l.jpg?RS=490.333333&WG=3&WS=1000&&WO=30&WF=-15x15&WU=https://image.aladin.co.kr/img/common/openmarket_ci.png
=> https://image.aladin.co.kr/product/33226/88/letslook/K452937057_t3l.jpg

Type 2/ No watermark and resized images (Normal size 750px)
https://image.aladin.co.kr/product/28728/13/letslook/8934967323_t12l.jpg?MW=750&
=> https://image.aladin.co.kr/product/28728/13/letslook/8934967323_t12l.jpg


2///
original image of ids "e + numbers" is a base64 link and book's content is base64 link.  So it's difficult to redirect back to the original image.

**Comment by Froktime** [comment]
Interestingly
https://image.aladin.co.kr/product/34198/67/letslook/K702931417_t12l.jpg?RS=490&WG=3&WS=1000&&WO=300&WU=https://image.aladin.co.kr/img/common/openmarket_ci.png

https://image.aladin.co.kr/product/34198/67/letslook/K702931417_t12l.jpg?RS=490.333333&WG=3&WS=1000&&WO=300&WU=https://image.aladin.co.kr/img/common/openmarket_ci.png

https://image.aladin.co.kr/product/33226/88/letslook/K452937057_t6l.jpg?RS=490.333333&WG=3&WS=1000&&WO=30&WF=-15x15&WU=https://image.aladin.co.kr/product/28728/12/cover500/8934967315_2.jpg

**Comment by qsniyg** [comment]
Thanks, I've removed the query string.
