### ISSUE TITLE
[EuroGamer] Get much larger image

### ISSUE THREAD

**Issue by BlindWanda** [qsniyg/maxurl#1345]
Compressed/ Resized Image URL:
https://assetsio.gnwcdn.com/Deadpool-Double_Controller-DP_16x9-FINAL-91c067ffa6e5f5a587c4.jpg?width=690&quality=75&format=jpg&dpr=2&auto=webp

Uncompressed/Real size Image URL:
https://assetsio.gnwcdn.com/Deadpool-Double_Controller-DP_16x9-FINAL-91c067ffa6e5f5a587c4.jpg

Article for you to test yourself if needed:
https://www.eurogamer.net/xbox-unveils-deadpool-bum-controller-as-competition-prize-for-one-lucky-recipient

This is the same situation as last time like [ET Online](https://github.com/qsniyg/maxurl/issues/1311) a few months ago which you sorted out ♥

**Comment by qsniyg** [comment]
Thanks! It seems to redirect already to the larger image for me... are you using the latest (git) version of the script?

**Comment by BlindWanda** [comment]
![Untitled](https://github.com/user-attachments/assets/f5c3882b-9dc3-48de-ba5b-f144269dd538)
Yes, and on top of that, I always grab the latest one from Git Hub.

**Comment by Froktime** [comment]
> ![Untitled](https://private-user-images.githubusercontent.com/96992261/350394913-f5c3882b-9dc3-48de-ba5b-f144269dd538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDA3MzEsIm5iZiI6MTcyMzU0MDQzMSwicGF0aCI6Ii85Njk5MjI2MS8zNTAzOTQ5MTMtZjVjMzg4MmItOWRjMy00OGRlLWJhNWItZjE0NDI2OWRkNTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA5MTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MGRlOTk5NTk2ODcyMmNkMDQ3YzU2Njg1YWUzMzBiNzUyMTE1NWY0NTNhNWUxMDg4YmMwYzIwOTA3ZWE1ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2mQ64g9aRBbtm4iS0fXL80ubP7i69RGtP3yjtlFOBR8) Yes, and on top of that, I always grab the latest one from Git Hub.

You should use Script through Tampermonkey. Script is great! Extension ver. is not as flexible as script at times. Do use both to complement each other!!!

**Comment by qsniyg** [comment]
Should be fixed with 2024.8.0.
