### ISSUE TITLE
zvuk.com

### ISSUE THREAD

**Issue by karpuzikov** [qsniyg/maxurl#1348]
from
https://cdn-image.zvuk.com/pic?type=release&id=33069874&hash=eab46a14-19b2-418d-b0d7-361abce2a43a
https://cdn-image.zvuk.com/pic?type=release&id=33069874&size=400x400&hash=eab46a14-19b2-418d-b0d7-361abce2a43a

remove everything after id of release

target
https://cdn-image.zvuk.com/pic?type=release&id=33069874

**Comment by qsniyg** [comment]
Thanks, I've set it to just keep the "type" and "id" queries.
