### ISSUE TITLE
infinite loading bug

### ISSUE THREAD

**Issue by wadawada** [qsniyg/maxurl#135]
https://lh3.googleusercontent.com/C6yBYozE1sXc9o_jsrh29_AYQ6ffCKO-fpooQ5nwuu7FSgQvdGtfSbcJVBUGSDi1VXE9TqYT2g=s0?imgmax=s0

page won't stop loading with the script on

**Comment by qsniyg** [comment]
@wadawada Could you link the page hosting the image?

**Comment by wadawada** [comment]
I'm using latest script with latest Chrome Stable Version 76.0.3809.132 (Official Build) (64-bit) with Tampermonkey
page stops infinite loading if I disable the script
I encounter this problem earlier with other images but I didn't spend the time to report it until now, but one recurring example is, all images on Chrome WebStore Overview wtill trigger the problem

For example, pages are fine
https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb
https://chrome.google.com/webstore/detail/volume-master/jghecgabfgfdldnmbfkhmffcabddioke
https://chrome.google.com/webstore/detail/google-keep-chrome-extens/lpcaedmchfhocbbapmcbpinfpgnhiddi

but right click pictures on overview page and open image on new tab will trigger infinite reloading
https://lh3.googleusercontent.com/pmbYBeSLw7RHa2dEBsVn2QZtHPl-SLvmweqEQRVYDWwalzeB_Y0rfOxOdbD14r4rIHh_Uidt9A=w640-h400-e365
https://lh3.googleusercontent.com/ru1pi54cUQV9150hRrSIHXY7NUyebf73zyDixotlrnueQ_slIJjpQ_FxAxMX9sSJrQzBJCo04Mo=w640-h400-e365
https://lh3.googleusercontent.com/AREyFzev3wVPpGJf0edj0HBFGRD7lj_XVw35c1jZ0JdPATsjrx0XXKaibJMAchPJJzdueJIYHA=w640-h400-e365

Images can be loaded but page keeps refreshing and won't stop until I close the page

**Comment by qsniyg** [comment]
@wadawada Strange, I can't seem to replicate this on my end at all, same Chrome version and all...

Looking at the code, I'm not exactly sure why it would do this though, as it only redirects if the new URL is different from the window's URL. Once it redirects, the URL shouldn't be different, unless another addon changes it as well.

So my _guess_ is that it could be another addon that changes the URL, or prevents it from reloading properly? Could you try temporarily disabling other addons and userscripts (i.e. only have Image Max URL running), and see if the problem still exists? If this seems like a lot of work, you can also create a separate Chrome profile (https://pureinfotech.com/add-new-user-profiles-google-chrome/) and install just Tampermonkey+Image Max URL from there.

If that still causes the bug however, would you mind sending me a backup of your Tampermonkey data? If you go to the extension options, select "Utilities", make sure "Include script storage" and "Include Tampermonkey settings" are selected, and export a Zip (feel free to remove other scripts you have installed from the zip, only "Image Max URL.user.js", "Image Max URL.options.json", "Image Max URL.storage.json", and "Tampermonkey.global.json" are required).

If it is indeed another addon that caused this issue, would you mind letting me know which one it is? I'll try and see if I can improve compatibility with it, and if not, I'll mention that it conflicts the redirect behavior so other users can know.

Thanks!

**Comment by wadawada** [comment]
Sorry you're right. Your script works fine alone.

There's something conflicting with your script that I need to find, but it takes some work because I have over 30 extensions installed on Chrome, plus some which are disabled.

So I'll need to find an extension (or if you know any) to save my current enabled extension list on Chrome and then I can try to disable them one by one to see which extension is causing the problem, but it may take some time.

**Comment by qsniyg** [comment]
@wadawada From a quick search, you could maybe try this: https://chrome.google.com/webstore/detail/export-links-of-all-exten/cmeckkgeamghjhkepejgjockldoblhcb

**Comment by wadawada** [comment]
Finally I figured the infinite loading is caused by 2 similar scripts enabled at the same time
I forgot I installed [this script](https://greasyfork.org/en/scripts/2312-resize-image-on-open-image-in-new-tab) some time ago, which has similar functions and stop being updated

Enabling 2 sciprts may not always caused problem, for example
https://www.youtube.com/channel/UCXpbSh6g1ZWHxk-UQv86VzA
but obviously it causes problems on other images and I have disable the other script

**Comment by qsniyg** [comment]
@wadawada Ah good to know, that makes sense yeah :)

Since they're very similar, there's not much I can do on my end to improve compatibility between both, but if there's anything that's lacking for you in this script, please let me know and I'll try my best to add it :)
