### ISSUE TITLE
Add shoulder.fan

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1350]
https://shoulder.fan/@kkato/main/48153560276361

Self-download images when opened on other tabs.
The limited images are WEBP formats and the max size is 1080 px width.

Check width in resized images

https://cdn0.berapt.com/i/co/46f4/86df/5ec67cbe/814a/36d03b3b36fc/47c9b5b4bae5423db090265997f0cec6?h=eyJ2ZXJzaW9uIjoxLCJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9&p=eyJhcHAiOiJTSE9VTERFUiIsImlzQWR1bHQiOnRydWUsImFjY291bnRJZCI6IjAzM2RmMDU4LTVjZWUtNGI5OC1hNzBiLWU2YTQ5ZDliYzcyYSIsInVzZXJJZCI6ImUxNWRhZWNlLTMyZTUtNDQ0OC1hNjM1LTQzZDdhY2Q0YjUyZCIsImV4cCI6MTcyMzgxODY3NH0&s=4d99R-yiq3fBFWAKT46Vb76eBkWYmWcgohtYOm3M-5NiFLJwzSR-QR91DzYQN0Lx8E5-ry4ZROsAzvGLRJ8vyA&sz=_???_

48px: `sz=xxs`
84px: `sz=xs`
192px: `sz=s`
360px: `sz=m`
480px: `sz=l`
720px: `sz=xl`
984px: `sz=xxl`
1080px: `sz=xxxl`

=> original img

any size: `size=origin`

https://cdn0.berapt.com/i/co/46f4/86df/5ec67cbe/814a/36d03b3b36fc/47c9b5b4bae5423db090265997f0cec6?h=eyJ2ZXJzaW9uIjoxLCJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9&p=eyJhcHAiOiJTSE9VTERFUiIsImlzQWR1bHQiOnRydWUsImFjY291bnRJZCI6IjAzM2RmMDU4LTVjZWUtNGI5OC1hNzBiLWU2YTQ5ZDliYzcyYSIsInVzZXJJZCI6ImUxNWRhZWNlLTMyZTUtNDQ0OC1hNjM1LTQzZDdhY2Q0YjUyZCIsImV4cCI6MTcyMzgxODc2N30&s=5SkWk5q7ei5zywrCvMHZT5jDARVVhYW9z4eOxNLbyWmf4n4Zy91s-GOvlbnzRa76vCG37ERXrUmKZP5AAawUfg&size=origin
=> the original image is usually jpg/jpeg and png but can also webp if the author uploads the webp image

I realized I had to use pictures in one article to get rid of h,s,p and turn into this.
https://cdn0.berapt.com/i/co/46f4/86df/5ec67cbe/814a/36d03b3b36fc/47c9b5b4bae5423db090265997f0cec6?size=origin
if used for other photos (croped photos on the homepage) it does not return the original image because they have hidden the actual original image link

**example**
_**COVER AVATAR**_
https://cdn0.berapt.com/i/pf/406a/3ac3/81f27e31/97c7/972293e8fb65/b35273a2714d419b85db82c4637dca23?sz=s

**_Cropped img on homepage_**
https://cdn0.berapt.com/i/ba/48f9/bd22/6b9791ef/a635/f0926719ccc9/bcf0666f13214708b381c62eec4eaaf9?sz=xxxl

Although you can't get the original image, you can get the largest image (width 1080 webp format) in the resized image.

**_COVER AVATAR_**
https://cdn0.berapt.com/i/pf/406a/3ac3/81f27e31/97c7/972293e8fb65/b35273a2714d419b85db82c4637dca23?size=origin

**_Cropped img on homepage_**
https://cdn0.berapt.com/i/ba/48f9/bd22/6b9791ef/a635/f0926719ccc9/bcf0666f13214708b381c62eec4eaaf9?size=origin

**Comment by qsniyg** [comment]
Thanks, supported!

**Comment by qsniyg** [comment]
Thanks, supported!
