### ISSUE TITLE
Support for heatworld.com / images.bauerhosting.com

### ISSUE THREAD

**Issue by fyhtma** [qsniyg/maxurl#1351]
https://heatworld.com/shopping/beauty/demi-rose-self-care-skincare/
> https://images.bauerhosting.com/legacy/media/5fd0/a688/a673/6105/5180/9ad9/DEMI-rose-beauty-tips.jpg?ar=16%3A9&fit=crop&crop=top&auto=format&w=992&q=80
>> https://images.bauerhosting.com/legacy/media/5fd0/a688/a673/6105/5180/9ad9/DEMI-rose-beauty-tips.jpg

**Comment by qsniyg** [comment]
Thanks, supported!
