### ISSUE TITLE
jpg5.su

### ISSUE THREAD

**Issue by evilxsloth** [qsniyg/maxurl#1352]
Examples:
Thumbnail size: https://simp6.jpg5.su/images3/20240813_070359e9bfcbe7154929c1.th.jpg
Medium size: https://simp6.jpg5.su/images3/20240813_070359e9bfcbe7154929c1.md.jpg
Full size: https://simp6.jpg5.su/images3/20240813_070359e9bfcbe7154929c1.jpg

Thumbnail size: https://simp4.jpg5.su/IMG_18687a176c20c99d7d45.th.jpg
Medium size: https://simp4.jpg5.su/IMG_18687a176c20c99d7d45.md.jpg
Full size: https://simp4.jpg5.su/IMG_18687a176c20c99d7d45.jpg

**Comment by qsniyg** [comment]
Thanks, supported.
