### ISSUE TITLE
Support for Tammi.fi

### ISSUE THREAD

**Issue by fyhtma** [qsniyg/maxurl#1353]
https://www.tammi.fi/kirja/george-lucas/star-wars.-tahtien-sota/9789520425715
> https://kirja.s3.amazonaws.com/prod/9789520425715_frontcover_final_medium.jpg
>> http://kirja.s3.amazonaws.com/prod/9789520425715_frontcover_final_original.jpg

**Comment by qsniyg** [comment]
Thanks, supported!
