### ISSUE TITLE
Support for Aliexpress

### ISSUE THREAD

**Issue by fyhtma** [qsniyg/maxurl#1354]
https://www.aliexpress.com/i/1005003147394555.html
> https://ae-pic-a1.aliexpress-media.com/kf/Sa279b9a0021d4c14a2d9609a42ed6d2b5.jpg_120x120.jpg_.webp (thumbnail in left corner)
>> https://ae-pic-a1.aliexpress-media.com/kf/Sa279b9a0021d4c14a2d9609a42ed6d2b5.jpg

**Comment by qsniyg** [comment]
Redirects for me... are you using the latest git?

**Comment by fyhtma** [comment]
Hmm it seems to work for me with Edge+Tampermonkey+userscript v2024.3.0
But with Firefox 129.0.1 + addon v2024.3.0 it doesnt redirects 
Also tried with Firefox Developer Edition 130.0b6 (64-bit) and clean install of addon v2024.3.0. Doesn't redirects either

**Comment by qsniyg** [comment]
Should be fixed with 2024.8.0.
