### ISSUE TITLE
Fix google drive

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1356]
https://drive.google.com/u/0/drive-usercontent/1JJl3cZGtxAtAn8GP2cDPho2Z4rGNl8-w=w300-h285-p-k-rw-v1-nu-iv1
https://drive.google.com/u/0/drive-viewer/AKGpihZlOg9yvMoany-vpQkG0q-PlF_ZdR8yuAAZdRvfDwhoCiiySMEIvsSPz9xS-vIhwnfdHnbJq1X4dyRUs_SmH-K8IHUrnTVgfA=s2560

=> https://drive.google.com/u/0/drive-usercontent/1JJl3cZGtxAtAn8GP2cDPho2Z4rGNl8-w=s0
https://drive.google.com/u/0/drive-viewer/AKGpihZlOg9yvMoany-vpQkG0q-PlF_ZdR8yuAAZdRvfDwhoCiiySMEIvsSPz9xS-vIhwnfdHnbJq1X4dyRUs_SmH-K8IHUrnTVgfA=s0

It looks like Google is creating more original photo-link domains.

**Comment by qsniyg** [comment]
Thanks, supported!
