### ISSUE TITLE
Support for kompakt.fm

### ISSUE THREAD

**Issue by acidzab** [qsniyg/maxurl#1357]
Hi, i've discovered how to access to original image hosted on Kompakt.fm

From:
https://s3.amazonaws.com/media.kompakt.fm/01/assets/releases/fitted/ext016-pshal_p_shaw.jpg?v=1
To:
https://s3.amazonaws.com/media.kompakt.fm/01/assets/releases/original/ext016-pshal_p_shaw.jpg?v=1

**Comment by qsniyg** [comment]
Thanks, supported!
