### ISSUE TITLE
[Feature Request] Hotkey to Copy Image to Clipboard? 

### ISSUE THREAD

**Issue by fourteen-1** [qsniyg/maxurl#1358]
There is a option in the settings that enables the copying of the image url to clipboard. It would be really useful to have a option to copy the entire image to clipboard using a hotkey.

Firefox unfortunately doesn't have a native hotkey to copy-to-clipboard, you can only copy image from the right-click context menu. There aren't even any 3rd party extensions providing this simple yet important functionality.

It would be great to have this copy image to clipboard with a hotkey functionality for at least this extension. 

Thanks for reading.

**Comment by qsniyg** [comment]
Thanks for the feature request! Closing this in favor of https://github.com/qsniyg/maxurl/issues/269 :)
