### ISSUE TITLE
nudostar.tv new rule

### ISSUE THREAD

**Issue by vscum** [qsniyg/maxurl#1359]
if (domain === "nudostar.tv") return src.replace(/_\d+px(\.\w+)/, "$1");
// https://nudostar.tv/contents/y/y/yyuki-1/1000/yyuki-1_0023_320px.jpg
// https://nudostar.tv/contents/y/y/yyuki-1/1000/yyuki-1_0023.jpg

**Comment by qsniyg** [comment]
Thanks, supported!
