### ISSUE TITLE
Support for Nintendo.com European images

### ISSUE THREAD

**Issue by immewnity** [qsniyg/maxurl#1361]
Nintendo Europe resizes images by appending a string towards the end. Some are easy to determine, like
* https://www.nintendo.com/eu/media/images/08_content_images/games_6/gamecube_11/gcn_pokemoncolosseum/CI16_GCN_PokemonColosseum_image950w.png > https://www.nintendo.com/eu/media/images/08_content_images/games_6/gamecube_11/gcn_pokemoncolosseum/CI16_GCN_PokemonColosseum.png
* https://www.nintendo.com/eu/media/images/11_square_images/games_18/smart_device_6/SQ_SmartDevice_AnimalCrossingPocketCamp_image500w.jpg > https://www.nintendo.com/eu/media/images/11_square_images/games_18/smart_device_6/SQ_SmartDevice_AnimalCrossingPocketCamp.jpg

Others can be a bit trickier:
* https://www.nintendo.com/eu/media/images/10_share_images/portals_3/2x1_SuperMarioHub_banner66LG.jpg > https://www.nintendo.com/eu/media/images/10_share_images/portals_3/2x1_SuperMarioHub.jpg
* https://www.nintendo.com/eu/media/images/08_content_images/games_6/gameboy_color/CI_GBC_PokemonGoldAndSilver_CharaPikachu_CMM_big.jpg > https://www.nintendo.com/eu/media/images/08_content_images/games_6/gameboy_color/CI_GBC_PokemonGoldAndSilver_CharaPikachu.jpg
* https://www.nintendo.com/eu/media/images/06_screenshots/games_5/game_boy_color_2/gbc_pokemonsilverversion/GBC_PokemonSilverVersion_02_TM_Standard.jpg > https://www.nintendo.com/eu/media/images/06_screenshots/games_5/game_boy_color_2/gbc_pokemonsilverversion/GBC_PokemonSilverVersion_02.jpg

**Comment by qsniyg** [comment]
Thanks, supported!
