### ISSUE TITLE
delock.com (bilder.tragant.de)

### ISSUE THREAD

**Issue by fyhtma** [qsniyg/maxurl#1362]
https://www.delock.com/produkt/91759/merkmale.html
thumb
-> https://bilder.tragant.de/produkte/leiste/6185535ddfc404.16360188.jpg
or ""orig""
->  https://bilder.tragant.de/produkte/orig/6185535ddfc404.16360188.jpg

i want these to redirect to
--> https://bilder.tragant.de/produkte/hoch/6185535ddfc404.16360188.jpg

**Comment by qsniyg** [comment]
Thanks, supported!
