### ISSUE TITLE
img-baila.hpplus.jp enhancement

### ISSUE THREAD

**Issue by billkewl** [qsniyg/maxurl#1365]
Sometimes the image url has resolution after uuid e.g.
https://img-baila.hpplus.jp/h/large/image/d1/d17274ad-f5be-4e78-bc5c-53fab5ded54d-1280x1096.jpg

Current rule redirects this to 
https://cdn-baila.hpplus.jp/image/d1/d17274ad-f5be-4e78-bc5c-53fab5ded54d-1280x1096.jpg

It would be nice to remove the resolution part as well
https://cdn-baila.hpplus.jp/image/d1/d17274ad-f5be-4e78-bc5c-53fab5ded54d.jpg

Thanks.

**Comment by qsniyg** [comment]
I get "Access Denied" when doing this... do you need to be logged in to see it?

**Comment by qsniyg** [comment]
Thanks, should be fixed!
