### ISSUE TITLE
Add support for rtl.hr

### ISSUE THREAD

**Issue by ValiumBear** [qsniyg/maxurl#1367]
Example:
URL: https://www.rtl.hr/emisije/gustan-s-pazaninom
Image: https://images.rtl.hr/media/images/822x468/Nov2022/c755032ed5a7494a17e8_47733.jpg?v=5470
Full size: https://images.rtl.hr/media/images/0x0/Nov2022/c755032ed5a7494a17e8_47733.jpg?v=5470

**Comment by qsniyg** [comment]
Thanks, supported!
