### ISSUE TITLE
Add gray media-owned tv station sites

### ISSUE THREAD

**Issue by liamengland1** [qsniyg/maxurl#1370]
https://en.wikipedia.org/wiki/List_of_stations_owned_or_operated_by_Gray_Television

`https://gray-wctv-prod.gtv-cdn.com/resizer/v2/QV5S634SSVDPLFDC7TJKQIQUHU.jfif?auth=cb16b69204edd60a484b3a0c753cde1f8f12fe5cf505d0bcc740f76e2069ef29&width=1200&height=800&smart=true`
to
`https://cloudfront-us-east-1.images.arcpublishing.com/gray/QV5S634SSVDPLFDC7TJKQIQUHU.jfif`

`https://gray-wdbj-prod.gtv-cdn.com/resizer/v2/IRGMGZ7VQNAWBH6PPN2G4ZTKAU.jpg?auth=4e91ac97e4bce4a88e2b6b7f0c58447faf270c570efc5ddffea6d7c90d3e62b8&width=1600&height=900&smart=true`
to
`https://cloudfront-us-east-1.images.arcpublishing.com/gray/IRGMGZ7VQNAWBH6PPN2G4ZTKAU.jpg` (not bigger but OG file)

`https://gray-wvir-prod.gtv-cdn.com/resizer/v2/UIAONGT3WVDQNMHDRYDSCJQCT4.jpeg?auth=bd8e6e45bdf0b0800ae321d2d916aca8c2e9909bdca44bc82c302246bc6db428&width=1300&height=975&smart=true`
to
`https://cloudfront-us-east-1.images.arcpublishing.com/gray/UIAONGT3WVDQNMHDRYDSCJQCT4.jpeg` (also not bigger)

Also can be found in this format:
`https://gray-wvir-prod.gtv-cdn.com/resizer/-rzLIYFvpWLGCV9x_yiPNKQVS0Q=/arc-photo-gray/arc3-prod/public/HM5GPD4PQZHRZL2ANO3YXUXC6A.png`
to
`https://cloudfront-us-east-1.images.arcpublishing.com/gray/HM5GPD4PQZHRZL2ANO3YXUXC6A.png`

Or this format:
`https://gray-kvly-prod.gtv-cdn.com/resizer/v2/https%3A%2F%2Fcloudfront-us-east-1.images.arcpublishing.com%2Fgray%2FALWQDT5MIREGTGOVBMOKZYHJBY.jpg?auth=696f1c074052f5d043f46b46b3072587d5b47b7e8ee5356c6c91968a79843a53&width=980&smart=false`
to
`https://cloudfront-us-east-1.images.arcpublishing.com/gray/ALWQDT5MIREGTGOVBMOKZYHJBY.jpg`

**Comment by qsniyg** [comment]
Thanks, supported!
