### ISSUE TITLE
add homepornbay.com

### ISSUE THREAD

**Issue by vscum** [qsniyg/maxurl#1373]
if (domain === "homepornbay.com") {
	return src.replace(/(.*\/\d{5,})s\.(jpg|jpeg|png)/, "$1.$2");
}
// https://homepornbay.com/c/a/1/24/59161/3086207s.jpg
// https://homepornbay.com/c/a/1/24/59161/3086207.jpg

**Comment by qsniyg** [comment]
Thanks! Turns out it was already supported, but only the `pic.` subdomain.
