### ISSUE TITLE
AJC / arc

### ISSUE THREAD

**Issue by liamengland1** [qsniyg/maxurl#1375]
`https://www.ajc.com/resizer/v2/SK2DBT6OQZRKZMFLNQXDW3ONJM.jpg?auth=852f70ce395b0017a080c454b8600d84c15f9d8625ab106a1ed17a1762b5dd07&width=1600&height=900&smart=true`
to
`https://cloudfront-us-east-1.images.arcpublishing.com/ajc/SK2DBT6OQZRKZMFLNQXDW3ONJM.jpg`

`https://www.ajc.com/resizer/v2/2NQ42HBDE5KMVK7YD3IDJKTDTI.jpg?auth=806c87c71561e3ee70b1bfb39a869c585603a23c1f55db0a17cc084d6a465baf&width=1600&height=900&smart=true`
to
`https://cloudfront-us-east-1.images.arcpublishing.com/ajc/2NQ42HBDE5KMVK7YD3IDJKTDTI.jpg`

etc. 

Maybe this can be made generic for other sites using arc?

such as

`https://www.nj.com/resizer/v2/NKR3FPARHRDGNNBHG6X3TXV2J4.jpg?auth=c9d4d180304d4d024ac5498d54e550c1a244b4783ab3432446502f296536c664&width=600&height=450&smart=true`
to
`https://cloudfront-us-east-1.images.arcpublishing.com/advancelocal/NKR3FPARHRDGNNBHG6X3TXV2J4.jpg`

**Comment by qsniyg** [comment]
I don't know if it can be made generic, as we need to know both the location (`us-east-1`) and the bucket name (`ajc` / `advancelocal`).

Supported these though, thanks!

**Comment by liamengland1** [comment]
Yeah good point idk what I was thinking there. If I find another unsupported arc domain I'll try to do a PR next time

**Comment by qsniyg** [comment]
Thank you! The info is pretty easy to find though, just view source on the main page of the site, search for `arcpublishing` and you'll find both.
