### ISSUE TITLE
Add korean tumblr

### ISSUE THREAD

**Issue by Froktime** [qsniyg/maxurl#1382]
tumblbug.com
Tumblbug is a Korean tumblr but image code is different than tumblr and strong encryption

https://img.tumblbug.com/eyJidWNrZXQiOiJ0dW1ibGJ1Zy1pbWctYXNzZXRzIiwia2V5Ijoic3RvcnkvNGRjNWQzMjItZDRhMy00NGY3LWIwZmItNDhjZTFiNGVkMDk2LzMyMmIzMzlkLTc3YmEtNGJhZS1iYWI1LWFhMjcwNjE5MWJhZi5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjEyNDAsIndpdGhvdXRFbmxhcmdlbWVudCI6dHJ1ZX19fQ==

originally i saw this link it wasn't this form but recently they changed it, also the old code couldn't get the original image because it contained a hash

link analysis (new code): 
1/ I noticed when removing == the link will get error
2/ notice the link line is a base64 string
![image](https://github.com/user-attachments/assets/3612cb0a-2e79-416d-90d8-efd6ad9683fc)

`{"bucket":"tumblbug-img-assets","key":"story/4dc5d322-d4a3-44f7-b0fb-48ce1b4ed096/322b339d-77ba-4bae-bab5-aa2706191baf.jpg","edits":{"resize":{"width":1240,"withoutEnlargement":true}}}`
=> `{"bucket":"tumblbug-img-assets","key":"story/4dc5d322-d4a3-44f7-b0fb-48ce1b4ed096/322b339d-77ba-4bae-bab5-aa2706191baf.jpg"}`
this string's encoded base64 again: `eyJidWNrZXQiOiJ0dW1ibGJ1Zy1pbWctYXNzZXRzIiwia2V5Ijoic3RvcnkvNGRjNWQzMjItZDRhMy00NGY3LWIwZmItNDhjZTFiNGVkMDk2LzMyMmIzMzlkLTc3YmEtNGJhZS1iYWI1LWFhMjcwNjE5MWJhZi5qcGcifQ==`

Get original img:
https://img.tumblbug.com/eyJidWNrZXQiOiJ0dW1ibGJ1Zy1pbWctYXNzZXRzIiwia2V5Ijoic3RvcnkvNGRjNWQzMjItZDRhMy00NGY3LWIwZmItNDhjZTFiNGVkMDk2LzMyMmIzMzlkLTc3YmEtNGJhZS1iYWI1LWFhMjcwNjE5MWJhZi5qcGcifQ==

I also tested the decoded string
 `{"bucket":"tumblbug-img-assets","key":"story/4dc5d322-d4a3-44f7-b0fb-48ce1b4ed096/322b339d-77ba-4bae-bab5-aa2706191baf.jpg"}`
=> https://img.tumblbug.com/story/4dc5d322-d4a3-44f7-b0fb-48ce1b4ed096/322b339d-77ba-4bae-bab5-aa2706191baf.jpg
return the original link similar to the base64 encoded link above

**Comment by qsniyg** [comment]
Thanks! Supported :)

I think the image system is https://github.com/lovell/sharp, but I'm not completely certain.
