### ISSUE TITLE
add support for pimpandhost.com "profile image"

### ISSUE THREAD

**Issue by Earthworm-Banana** [qsniyg/maxurl#1389]
### **Warning NSFW Content:**
**Example 1:**
Thumb: https://pimpandhost.com/media/profile_image/3/2/7/8/1/n/i/D/1niD/3278955bdbc544f0ff1d79afad3581d58e2c2a_thumb1140_250.jpg

Full: https://pimpandhost.com/media/profile_image/3/2/7/8/1/n/i/D/1niD/3278955bdbc544f0ff1d79afad3581d58e2c2a.jpg

**Example 2:**
Thumb: https://pimpandhost.com/media/profile_image/2/3/2/8/Y/A/d/_/YAd/232885b347e100a7bc07f068b54714d6ab44a2_thumb1140_250.jpg
Full: https://pimpandhost.com/media/profile_image/2/3/2/8/Y/A/d/_/YAd/232885b347e100a7bc07f068b54714d6ab44a2.jpg

**Comment by qsniyg** [comment]
Thanks for reporting. Can you send SFW test cases?

**Comment by Earthworm-Banana** [comment]
### **SFW:**
**Example 1:**
Thumb: https://pimpandhost.com/media/profile_image/2/5/9/9/1/5/D/l/15Dl/2599871b5eae05c7060ec24e20c8435578acf0_thumb1140_250.jpg

Full: https://pimpandhost.com/media/profile_image/2/5/9/9/1/5/D/l/15Dl/2599871b5eae05c7060ec24e20c8435578acf0.jpg

**Example 2:**
Thumb: https://pimpandhost.com/media/profile_image/3/0/6/4/1/h/J/u/1hJu/306496cafa493353f382d28168f2dfaccde5ee_thumb1140_250.jpg
Full: https://pimpandhost.com/media/profile_image/3/0/6/4/1/h/J/u/1hJu/306496cafa493353f382d28168f2dfaccde5ee.jpg

**Comment by qsniyg** [comment]
Thanks, supported!
