### ISSUE TITLE
Make popup behavior more configurable

### ISSUE THREAD

**Issue by qsniyg** [qsniyg/maxurl#14]
Right now, the behavior is:

```
when (trigger_keys_are_pressed) {
  start_loading_image();
}

when (image_finished_loading) {
  show_popup();

  if (trigger_keys_are_pressed) {
    when (!trigger_keys_are_pressed) {
      hide_popup();
    }
  } else {
    when (any_key_is_pressed) {
      hide_popup();
    }
  }
}
```

This behavior was chosen because it could be annoying to have to keep holding down the trigger keys while the image is loading in order to see the image. However, this behavior could be confusing or annoying to some users, so it should be configurable.

**Comment by Acid-Crash** [comment]
Hi, is it possible to add case when popUp is still visible/present after dedicated key is released but the mouse is still over enlarged image (aka hide popUp after keys were released and mouse was hovered out of the original image)?

**Comment by qsniyg** [comment]
Good idea, I'll look into that a bit later :)

**Comment by decembre** [comment]
8 - simplement un option pour garder la popup d'options au-dessus et toujours visible.
C'est plus pratique pour faire des tests...

**Comment by qsniyg** [comment]
@decembre Ah okay, I see now :) Maybe the testbed area could have a toggle button that would ensure the popup would stay open. If unchecked, it would work as it would for other sites, so one could test the popup open/close behavior.

**Comment by decembre** [comment]
Wait and see your next version ....

**Comment by qsniyg** [comment]
@decembre The testbed will likely not be in the next version as it will require quite a significant amount of refactoring. However, since live-reloading of settings will be (and already mostly is), you could just open another window beside it and test it live as you modify your settings, without needing to reload that page :)

**Comment by qsniyg** [comment]
@Acid-Crash Apologies for getting back so late on your feature request, I had entirely forgotten! Just implemented it here: https://github.com/qsniyg/maxurl/commit/275f09380678dea249672bdb4d04d5c711c4c18a

By default "Don't close until mouse leaves" is set to true, it'll only close if both the mouse is out of the image and the desired close behavior is triggered (that is, any/all trigger keys released)

**Comment by decembre** [comment]
Here a link to the:
<a href="https://thumbnailzoomplus.wordpress.com/manual/preferences/"> Dialog Thumbnail Zoom Plus’ Preferences : Opening The Preferences</a>

Seems inspiring and have screenshots....

**Comment by qsniyg** [comment]
@decembre Interesting, thanks for the link. So these are the ones that are missing:

 * Show partial image (that'd take a bit of refactoring, and would only properly work for the extension)
 * Save as options (good idea, already has a bit of support for this, but more options wouldn't hurt)
 * Show border (personally I don't see much of a reason for this, and it would conflict with custom CSS styles)
 * Show pictures using all available space/Max size (both are impossible due to WebExtension constraints, these are only possible with XUL)
 * Show caption
 * Add to history (exists for the redirect option, but not for the popup option)

The rest I believe is already implemented (although blacklist doesn't blacklist the popup itself, I'll have to add an option for that).

Are there any of the above features that you find really useful?

**Comment by decembre** [comment]
"The rest I believe is already implemented":
Impressive work!

For the rest:
The save settings and show caption settings can be useful.
Don't need "add to history".

The principal for me is to have choice (but strangely, i prefer simplicity ...).
and easily access at some powerful options when i need.

About them, maybe a way to show all shortcut available when we hover the addon icon should be interesting, since you have added so many possibility to it.

Finally, the principal problem is to keep settings comprehensible:
that's difficult.

**Comment by qsniyg** [comment]
@decembre The new release is up. The other features will be added in a future release :) In general it should work much better, especially the mouseover trigger (many various fixes were applied for it). The French translation is still very much a work in progress though.

**Comment by decembre** [comment]
I test it right now !
;-)
Some quick notes:
1 - **Close the pop-up when i move the mouse out** of the thumbnail or link (just the movement no key):
Seems not working or i can't find the good settings.
It don't close when i move out the original image (in the gallery).
It close only when i move out the pop-up.

2 - **The preview pop-up position and the focus to it.** 
That's better, it stay near the cursor, but i hope:
- it **never cover the cursor** ( and the original image) and It **don't take the focus**.
By example, when if want preview image in a gallery (opened by hover):
When i hover an image and the preview appear, in the same time it take the focus and the gallery close (because gallery lost its focus).
So, i need re-hover the gallery and etc...

3 - Too many preview for unwanted elements in the pages (sprites /icon / background):
By example for this page:
<a href="https://thumbnailzoomplus.wordpress.com/manual/usage/">TZ+ - Basic Usage</a>

The popup open for:
[](https://s2.wp.com/wp-content/themes/pub/inove/img/icons.gif)
[](https://s2.wp.com/wp-content/themes/pub/inove/img/searchbox.gif)
[](https://s2.wp.com/wp-content/themes/pub/inove/img/sidesep.gif)
That's distributing...

- **MaxUrl work on AMO site?**:
I try on your addon page , but see nothing.
Normally my settings in about:config of Waterfox make extensions working on AMO sites.

That's all for now, folks:
I go drink my coffee.

PS:
For other things i notice, i continue here or i open new  issue ?

**Comment by qsniyg** [comment]
@decembre 

>It close only when i move out the pop-up.

Ah right! I forgot about that. I'll try and implement that soon :)

>Too many preview for unwanted elements in the pages (sprites /icon / background):

I could add an option to further configure the minimum size acceptable before opening a popup. Right now I think it's at 20 pixels wide/high. Not really sure what else I could do.. maybe add an option to avoid popping up for background images? A lot of websites use background images instead of normal image tags for images displayed on the site though.

>MaxUrl work on AMO site?

I just tried it under Waterfox, and it seems to work, although I installed it directly from the site. I wasn't able to find a way to search for addons under it.

>For other things i notice, i continue here or i open new issue ?

Either way is fine. Discord might also be easier, as it's just a normal chat, but I don't really mind, whatever's easiest for you :)

**Comment by decembre** [comment]
Here is good for me.

For AMO, i speak about preview, not install:
On your addon page:
https://addons.mozilla.org/en-US/firefox/addon/image-max-url/
screenshots are not matching .

**Comment by qsniyg** [comment]
I believe I've fixed everything (except for the screenshots, will do that tomorrow), thanks again for reporting! :)

**Comment by decembre** [comment]
Tested your last version:
That's better!
Near close that i wanted.

Some notes:
1 - Where is the preference (if implemented...) to open the **Options in its own pop-up / widget** ?
2 - What the meaning of **"exclude images tab"** ?
3 - What do **"Replace Images"** and its impact ?
4 - in **"Extra"**:
What the meaning and the influence on performance of:
**"Max images to process at once"** and **"Max images per domain at once**" ?
I ask that for my problem about "gallery on hover":
Now that's better, but many time the preview take time to open and the gallery close.
Against that, It is possible to have an option (one more!) which open the preview more quickly, before the image is fully loaded ?
Seems TZ+ have this one and work perfectly on this type of case.
5 - Can we exclude some particular image precisely ?

6 - Should be interesting to exclude site / image in the "IMU entry in context menu": 
Add a sub menu entry "exclude this site / image".

**Comment by qsniyg** [comment]
1) I'm not quite sure what you're talking about, sorry... do you mean if it made its own separate window, not part of the page? If so, that's unfortunately not possible due to WebExtension limitations, it'd need to be reimplemented in XUL (#119).
2) If you open an image by itself in a new tab, it'll prevent a popup from appearing for the image opened in the new tab, as it's likely not necessary.
For example, if you were to open this in a new tab: https://i-h2.pinimg.com/474x/2c/03/5a/2c035a1668bfe4fc71abbade44a9423d--flat-design-ui-design.jpg?b=t , it would redirect, but it wouldn't open the popup if you were to hover your mouse over it
3) It replaces all images on a page with their larger versions. For example, it can be useful if you use an addon to download all images on a page.
4) Both of those options allow you to limit how many images are downloaded at once for the Replace Images button. The first is the total limit, and the second is the limit per domain (if the domain limit is larger than the total limit, it'll still be limited by the total limit).
If "Wait until image is fully loaded" or "Use data URLs" is selected, this will affect how many images can be downloaded at once, if not, it'll affect how many can be processed at once.
For most websites, processing is nearly instant, but for some (such as Flickr), it can actually take a long time, because it needs to run API calls to find the full image.
The limits are primarily useful to prevent the website from temporarily blocking you for sending too many requests (something that did happen to me a few times haha).

4.5: I agree, that'd be very useful (#126), but implementing that is actually a little tricky for a number of reasons, it'd require a bit of rewriting. I opened an issue so that I don't forget about it though :)

5: Yes, through the blacklist. But make sure "Don't popup blacklisted images" is enabled, otherwise it only prevents processing that URL (meaning it will not try to find a larger version, but it will still open a popup for it).

6: Good idea, thanks! I've created a new issue for it (#127) This one also might take a bit of time to implement, but it's probably not going to be as difficult as 4.5 :)

**Comment by decembre** [comment]
Thanks for the infos.
It's more clear now.

That's strange about WebExtension limit popup or widget function:
Security problem ?
But you can open a popup for a preview ?
But yes i am not a dev and i know WebExtension add many problems to my use of Firefox:
I use Waterfox when they abandon XUL and all its possibility across it.

I wait the result of your last changes.......

**Comment by qsniyg** [comment]
@decembre 

From what I understand, WebExtensions are basically userscripts with a little extra functionality. Chrome invented the base for them (in fact, chrome extensions for the most part can be included in Firefox Quantum-based browsers with only a simple addition in the manifest.json file), and Chrome didn't like the idea of having too much happen outside of the browser window. Meaning, pretty much every extra permission granted to WebExtensions are, for the most part, non-visual. So custom UI elements (like a real popup window) unfortunately can't be created.

I agree though, it's very unfortunate Firefox abandoned XUL. WebExtensions are great in their own respect (they allow for much greater user control over them/security), but it'd have been nice had Firefox opted to support both, instead of only WebExtensions.

**Comment by decembre** [comment]
I tested your last updated version....
About "gallery on hover" (previous - 4) :
If i don't use "API Cal" option, the poup can be open without losing the focus of the hovering thumbnail (the thumbnail stay activ)e.
But ..... the pop up is empty.
A way to have the both thing working:
Popup and Keep focus on thumbnail?

**Comment by qsniyg** [comment]
>If i don't use "API Cal" option, the poup can be open without losing the focus of the hovering thumbnail (the thumbnail stay activ)e.

I don't really understand this, sorry... for me, when it loads (has the waiting cursor), it will lose focus, but when the image is loaded, the thumbnail gains focus again. Setting the "Rules using API calls" option to "No" reduces the time, but it still loses focus for a second or so.

>But ..... the pop up is empty.

Could you share a screenshot of this? Sorry, I can't seem to replicate this issue, the popup works either way for me... (although enabling API calls results in a larger image) I tested it in Waterfox as well, but it still works for me.

Could you share which page/image under Flickr causes this issue, and share your configuration (the Export button at the top of the options page)?

>A way to have the both thing working:
>Popup and Keep focus on thumbnail?

If the issue is the waiting cursor, then yes, I can add an option for it to use document.body instead of creating an invisible element. It won't show the cursor on all pages (which is why I used the invisible element instead), but it'll work for most pages.

>Maybe loading in background the other previews, can prevent that (because they should be previewed instantly when need) ?

That's a good idea! I've tracked it at #151.

**Comment by decembre** [comment]
By example on this page:
[Tim‘s First Portrait](https://www.flickr.com/photos/axatron/40236844260/in/pool-portrait_face "Tim‘s First Portrait").
Here a screenshot:
![MAXURL - PB hover - BIG](https://user-images.githubusercontent.com/868778/66695062-c71bb780-ecbc-11e9-90e4-afb87e5a4157.gif)

And my config...
[MAXURL - TEST config - 01.txt](https://github.com/qsniyg/maxurl/files/3720229/MAXURL.-.TEST.config.-.01.txt)

**Comment by qsniyg** [comment]
@decembre I see, it's the last one where the gallery closes that you're referencing?

Would you mind linking the script that does that so I can test? I'm really not sure what the cause is, sorry...

**Comment by decembre** [comment]
You should install theses 3 userstyles:
[Flickr Widescreen - ALLinONE TOTAL (part 1)](https://userstyles.org/styles/52167/flickr-widescreen-allinone-total-part-1-v-105 "Flickr Widescreen - ALLinONE TOTAL (part 1)")
and:
[Flickr - AUTO More Mini Thumbnail in Photo page v.2 - OK exclude 2019](https://greasyfork.org/fr/scripts/31560-flickr-auto-more-mini-thumbnail-in-photo-page-v-2-ok-exclude-2019 "Flickr - AUTO More Mini Thumbnail in Photo page v.2 - OK exclude 2019")

**Comment by qsniyg** [comment]
@decembre Alright, I've managed to reproduce the issue, and with the next update, the issue should be gone :) (unless "Use invisible element when waiting" is set to "Yes", which is the old behavior. It will default to "No")

**Comment by decembre** [comment]
Thanks for your attention!
After update i don't see  in the option:
"Use invisible element when waiting"....
And i have always the same problem...

**Comment by qsniyg** [comment]
@decembre Sorry, I meant the upcoming update :) I still have a few things to do before releasing it

**Comment by decembre** [comment]
;-)

**Comment by qsniyg** [comment]
@decembre The update's live :) It also supports partial loading of images (which is enabled by default for the extension, although not for the userscript)

**Comment by decembre** [comment]
After a quick test:
Yes you solve the hover problem!
:-)
Now i can test it in other place and options....
