### ISSUE TITLE
Gamer.ne.jp

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#142]
Small: `https://image.gamer.ne.jp/news/2019/20190909/002727856d434cbc81bc398e8b20960824e2/m/19.jpg`

Large: `https://image.gamer.ne.jp/news/2019/20190909/002727856d434cbc81bc398e8b20960824e2/o/19.jpg`

Page example: https://www.gamer.ne.jp/news/201909090027/

**Comment by qsniyg** [comment]
Thanks! Added :)
