### ISSUE TITLE
sinaimg.cn now requires custom header?

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#147]
It seems links like `https://wx4.sinaimg.cn/mw690/9a646dd9ly1g7qil8atsgj22ao328qv6.jpg` now cannot be redirected to `https://wx4.sinaimg.cn/large/9a646dd9ly1g7qil8atsgj22ao328qv6.jpg` any more without enabling mouseover popup. 

Is this a new change to sinaimg? It used to work straightly. And even now, I can manually open /large/ link just fine, so it seems to have no referer check at least.

**Comment by qsniyg** [comment]
Unfortunately yes, some URLs require custom headers, or they will be blocked (if the Referer is wrong). Opening them in their own tab works, but some Referers will result in it not working.

That being said, I should add some kind of way to allow for same-origin Referers (i.e. when opening in a new tab), for this to be less annoying (same for Imgur).
