### ISSUE TITLE
Add support for cloudfront.net

### ISSUE THREAD

**Issue by afterdelight** [qsniyg/maxurl#153]
Add support for sites like nonno.hpplus.jp

Media link samples:
https://nonno.hpplus.jp/article/43541
https://nonno.hpplus.jp/article/43631
https://d3bhdfps5qyllw.cloudfront.net/org/69/699a139af95bc892ed2bfd186a9f4de7_1080x1400_h.jpg
https://d3bhdfps5qyllw.cloudfront.net/org/e0/e0bdc35bdcc727865e10d1cd6aa3b53a_1080x1393_h.jpg

Or is this already the max resolution?

Thanks!

**Comment by qsniyg** [comment]
Unfortunately, I don't think it's possible to do it for the images you sent unfortunately. It seems like all of their URLs require a pattern of `[0-9a-f]{32}_[0-9]+x[0-9]+_[wh].jpg` (hex for 32 characters, a size in the format ???x??? where ??? are numbers, and either w or h at the end, probably standing for width and height). Even their largest images are in this format:

https://d3bhdfps5qyllw.cloudfront.net/org/e4/e4853d07abe3aecb35dab2944c4631f3_5616x3744_w.jpg (5616x3744)

So I'm not really sure how the script will be able to find the larger version for those images.

This being said, I did find another pattern:

https://d3bhdfps5qyllw.cloudfront.net/sqr/0f/0fa3d6cb4776d9c8827ac13649fcd653_1080x1080_w.jpg

and:

https://d3bhdfps5qyllw.cloudfront.net/thm/0f/0fa3d6cb4776d9c8827ac13649fcd653_1080x1080_w.jpg

By replacing `sqr` (square?) or `thm` (thumbnail?) with `org` (original?), you'll get the full version:

https://d3bhdfps5qyllw.cloudfront.net/sqr/0f/0fa3d6cb4776d9c8827ac13649fcd653_1080x1080_w.jpg

Thanks very much for submitting! The sqr/thm rule is in the script now :)

(By the way, "cloudfront.net" is actually just the CDN service they use, each site using Cloudfront has a cloudfront.net subdomain, and for some sites, it's easier to use that than creating a subdomain on their site that "links" to the cloudfront subdomain. If you check [sites.txt](https://github.com/qsniyg/maxurl/blob/master/sites.txt), you'll find about a hundred or so cloudfront.net domains :)

**Comment by afterdelight** [comment]
Alright, turned out it was already the max res huh? Thanks for the commit and the answer :)
