### ISSUE TITLE
Popup doesn't stay open after releasing keys

### ISSUE THREAD

**Issue by blue-lightning** [qsniyg/maxurl#16]
Currently set to Ctrl + Alt, but Ctrl + Shift expresses the same behaviour:
- Hold both Ctrl and Alt: popup flashes repeatly (not unexpected but kind of weird)
- Release Alt but hold Ctrl: popup stay (idea)
- Release both Ctrl and Alt: popup disappear instead of staying open.

Version: 0.70, Addon
Browser: Firefox 62.0.3 x64
Sample site: any site, but here's the first one:
`https://www.ghacks.net/2018/10/12/load-larger-image-copies-with-image-max-url`

**Comment by qsniyg** [comment]
Great idea, thanks for sharing! I'll make that configurable in the next update.

>Hold both Ctrl and Alt: popup flashes repeatly

To be clear, is this the series of events that caused it?

* Hold your mouse over the image
* Press Ctrl then Alt (while holding both)
* The popup loads (both are still held)
* The popup flickers

I haven't noticed this behavior before. If it isn't too much work, would it be possible to do a video demonstrating this? It would help me to figure out what the cause is.

**Comment by qsniyg** [comment]
I've added the option here: https://github.com/qsniyg/maxurl/commit/3023949118c1c5212570e2c8952abcbcdcac552c

I'll need to test more before pushing an update, but let me know if it works for you (clone the source, go to `about:debugging`, "Load Temporary Addon", and select "manifest.json" in the root). By default, it retains the old behavior, but setting "Keep popup open until:" to "All triggers are released" should fix it.

**Comment by blue-lightning** [comment]
Loading Temporary Addon give me this error: "Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page."
In the mean time, [here](https://www.youtube.com/watch?v=q14wPKXbLAU)'s the video. Sorry for the bad quality, I don't have any screen recording software installed and just use PowerPoint instead. Break down of the vid:
0:0:0 - 0:0:2 Hold Ctrl+Alt, popup flashed repeatly
0:0:2 - 0:0:4 Release Alt, popup held. Good because now I can click on it to open in a new tab to save. I wish there were an option to open right to a new tab instead of popping up and click. Should I make a separate issue on GitHub for you to manage this request easier?
0:0:4 - 0:0:13 Various test on tapping Ctrl+Alt, popup flashed instead of staying open. I also try to tap then release Alt why holding Ctrl but the popup disappear too. It seems that if I hold Ctrl+Alt for it to flash long enough, release Alt held the popup back. If I hold Ctrl+Alt not long enough, release Alt release the popup instead. Minimum duration is about 6 seconds.

**Comment by blue-lightning** [comment]
1. New feature: thanks, that's very nice of you!
2. Debugging: event keydown was triggered repeatly as you've guessed, but I think that's normal. Testing on another computer yielded the same result. According to my knowledge the keyboard event getting triggered repeatly is a feature, JS even has a [property](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat) to check it.
3. Addon new version: screenshot [here](https://imgur.com/a/78TwkF1). All this time and I only knew of console.log, so sad.

**Comment by qsniyg** [comment]
>but I think that's normal

Indeed it is exactly what should have happened, I was just making sure it wasn't a problem with your keyboard :)

>screenshot here

Was there a flicker when you ran it? It looks normal..

>why did the version number stay at 0.70.0 instead of 0.71.0?

I forgot to update the version for manifest.json. Not a big deal though, once I update the extension I'll make sure to update the version there as well.

**Comment by blue-lightning** [comment]
You wrote to trigger a popup, so I trigger a popup. Holding both keys down just repeat that block in the screenshot over and over, no additional sentence. But looking at your "true" screenshot, it doesn't have the trigger_popup() call like mine does?

**Comment by qsniyg** [comment]
>Holding both keys down just repeat that block in the screenshot over and over, no additional sentence

Could you share a screenshot (reload the page first, or `console.clear()`, and then hold both down until it flickers)? That's exactly what I was looking for :)

**Comment by blue-lightning** [comment]
[Here](https://imgur.com/a/8wdl5Ti) and [here](https://imgur.com/a/aGJKAVL). I was wrong, trigger_popup() did show up repeatly, only the final block didn't have that line. Sorry about that.
Too tired so I'm going to sleep now, will get back to you tomorrow.

**Comment by qsniyg** [comment]
Try the latest commit (you might need to `git reset --hard HEAD` or undo the `console.trace()` change to avoid conflicts), I've added the feature, and I might have fixed the flickering problem :)

**Comment by blue-lightning** [comment]
✓  Mouse over new tab
✓  Keep popup open until all triggers are released
✓  Disable flickering

You're the best.

**Comment by qsniyg** [comment]
Glad to know it works! Published :)
