### ISSUE TITLE
[Twitter] medium size available but not orig

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#165]
Visiting these links are fine:
```
https://pbs.twimg.com/media/Bu4G7k3CcAA6Nx7.jpg
https://pbs.twimg.com/media/Bu4G7k3CcAA6Nx7.jpg?name=medium
```

Issue happens when I open it with orig parameter. `https://pbs.twimg.com/media/Bu4G7k3CcAA6Nx7.jpg?name=orig`

Instead of using orig alone, can we try other parameters if orig fails? Something like:
```
https://pbs.twimg.com/media/Bu4G7k3CcAA6Nx7.jpg?name=orig
https://pbs.twimg.com/media/Bu4G7k3CcAA6Nx7.jpg?name=large
https://pbs.twimg.com/media/Bu4G7k3CcAA6Nx7.jpg?name=medium
https://pbs.twimg.com/media/Bu4G7k3CcAA6Nx7.jpg?name=small
https://pbs.twimg.com/media/Bu4G7k3CcAA6Nx7.jpg
```

**Comment by qsniyg** [comment]
Thank you! I decided to rewrite the twitter rule entirely as well, as it was in a pretty terrible shape. It'll both loop through various names, as well as prefer png over jpg, to (possibly) avoid compression (I haven't checked this though, maybe it's just placebo).
