### ISSUE TITLE
Bookwalker Support

### ISSUE THREAD

**Issue by NotLemon** [qsniyg/maxurl#17]
Would supporting Bookwalker be acceptable?

Product page: https://bookwalker.jp/de320cc93c-47f1-422d-a917-e14f3be19b67/

Standard image: https://rimg.bookwalker.jp/7759762/frDGCemG5kX9EBY8IrbThQ__.jpg
Alt image: https://c.bookwalker.jp/7759762/t_700x780.jpg
Original undisplayed image: https://c.bookwalker.jp/coverImage_2679576.jpg

Here is a bookmarklet we made that explains URL conversion for reference:
`javascript:!function(a){var b=document.createElement("textarea"),c=document.getSelection();b.textContent=a,document.body.appendChild(b),c.removeAllRanges(),b.select(),document.execCommand("copy"),c.removeAllRanges(),document.body.removeChild(b)}("https://c.bookwalker.jp/coverImage_" + (parseInt($('meta[property="og:image"]').attr('content').split("/")[3].split("").reverse().join(""))-1) + ".jpg");`

**Comment by qsniyg** [comment]
That's brilliant! Thank you so much, added to 0.7.4 :)
