### ISSUE TITLE
Image-Tabs not working since version 11.13 using Firefox TOR Browser (current release and previous version)

### ISSUE THREAD

**Issue by idontwantausernameok** [qsniyg/maxurl#170]
Using Firefox TOR Browser (current release and previous version),
after version 11.13 of Image Max Urls, with 'Image-Tabs' nothing happens or else there is a never-ending our-glass (waiting...).
I've tried removing and re-installing with no improvement (TOR & Extension).
I've tested both 11.14 & 11.15 and had to revert to 11.13 which still works perfectly.
"https://addons.mozilla.org/firefox/downloads/file/3453576/image_max_url-0.11.13-an+fx.xpi?src=dp-btn-primary" 

PS: Thanks for the great extension!

**Comment by qsniyg** [comment]
0.11.14 really was a trainwreck of a release haha.

Could you link which image you encounter this issue with? I just tried, and it works for me with [this image](https://pbs.twimg.com/media/EK3eZtaVAAAB256.jpg)... 

If you have issues with that image, could you try using [this build of the extension](https://github.com/qsniyg/maxurl/issues/168#issuecomment-561628371), and follow the instructions in the comment to get a log? Make sure to open the developer console before going to the URL, and make sure Persist Logs is enabled. 

Thank you for reporting!

**Comment by qsniyg** [comment]
Indeed, the issue was due to the `chrome.cookies` API. After setting `privacy.firstparty.isolate` to true (the default), I managed to replicate the issue. Turns out the fix is really simple: set `firstPartyDomain` to null in the `chrome.cookies.getAll` request :)
