### ISSUE TITLE
Sveriges Television https://www.svt.se/

### ISSUE THREAD

**Issue by TheLovinator1** [qsniyg/maxurl#18]
Hi,

0,1% of your users will probably benefit this so it is not a super important thing to add.
Images on the website for the Swedish television broadcaster SVT can be better quality.
Main website is https://www.svt.se/ and CDN is https://www.svtstatic.se/.

**Example URLs**:
https://www.svtstatic.se/image/cinema/760/19912234/1541383772?quality=70&format=auto
https://www.svtstatic.se/image/wide/480/19864886/1540988000?quality=70&format=auto
https://www.svtstatic.se/image/square/200/19910166/1541348996?quality=70&format=auto

URL is svtstatic.se/image/crop/width/ID/verson.extension

Crop can be `Original`, `cinema`, `imax`, `square`, `tv`, `fourthree`, `portrait`, `logo` and`wide` .
Width can be `Unscaled`, `default` or an integer
ID isn't always 8 numbers, older images seem to only have 7
Version can be left out, only for cache busting (E.g. [/image/wide/992/19912126?quality=70&format=auto](https://www.svtstatic.se/image/wide/992/19912126?quality=70&format=auto))
Extension can be `.jpg`, `.png`, `.gif` and `.webp`.

We get .jpg 100% of the time even if  `format=auto` is in the URL so I guess it can be left out?

**Quality**
Looks like images have 70% quality at default. Can be changed by changing `?quality=70` to `?quality=100` in the URL. Changing it to 100 increases the quality. Removing everything defaults to 70%.

[/image/wide/992/19912126/1541373740?quality=70](https://www.svtstatic.se/image/wide/992/19912126/1541373740?quality=70) is 72 KB
[/image/wide/992/19912126/1541373740?quality=100](https://www.svtstatic.se/image/wide/992/19912126/1541373740?quality=100) is 392 KB
[/image/wide/992/19912126/1541373740](https://www.svtstatic.se/image/wide/992/19912126/1541373740) is 72 KB

**Resolution**
Different crop has different resolution. Thumbnails has `/224/`, normal images has `/992/`, square thumbnail has `/200/` in the URL. 992px looks like the biggest they use.
Can be changed to `/unscaled/` to get original image.
[/image/wide/224/19912126/1541373740?quality=100](https://www.svtstatic.se/image/wide/224/19912126/1541373740?quality=100) is 224x126px
[/image/wide/unscaled/19912126/1541373740?quality=100](https://www.svtstatic.se/image/wide/unscaled/19912126/1541373740?quality=100) is 1920x1080px

**Crop**
Different images are cropped differently.
Can be `Original`, `cinema`, `imax`, `square`, `tv`, `fourthree`, `portrait`, `logo` and `wide`. 

Example: Changing `/cinema/` to `/original/` to get non-cropped verison:
[/image/cinema/unscaled/19765912/1540298095?quality=100](https://www.svtstatic.se/image/cinema/unscaled/19765912/1540298095?quality=100) 832px vertical
[/image/original/unscaled/19765912/1540298095?quality=100](https://www.svtstatic.se/image/original/unscaled/19765912/1540298095?quality=100) 1080px vertical

**Image format**
Images are served as JPEG at default. Can be changed to PNG to increase quality(?). If images are changed to .png we don't need `quality=100`.

[/image/original/unscaled/19765912/1540298095.jpg?quality=100](https://www.svtstatic.se/image/original/unscaled/19765912/1540298095.jpg?quality=100) is 706 KB
[/image/original/unscaled/19765912/1540298095.png](https://www.svtstatic.se/image/original/unscaled/19765912/1540298095.png) is 2,23 MB

**Problems with changing file format**
Some images get darker while others don't.

This one changes color:
[/image/original/unscaled/19912234/1541383772.png](https://www.svtstatic.se/image/original/unscaled/19912234/1541383772.png)
[/image/original/unscaled/19912234/1541383772?quality=100](https://www.svtstatic.se/image/original/unscaled/19912234/1541383772?quality=100)

This one doesn't change:
[/image/original/unscaled/19911014/1541355230?quality=100](https://www.svtstatic.se/image/original/unscaled/19911014/1541355230?quality=100)
[/image/original/unscaled/19911014/1541355230.png](https://www.svtstatic.se/image/original/unscaled/19911014/1541355230.png)

Sorry for the wall of text, and thanks if you try to do any of this!
~@TheLovinator1

**Comment by qsniyg** [comment]
Wow, that's an insane amount of research, thank you so much!

Looks like if `unscaled` is used, the "crop" element can be literally anything:

https://www.svtstatic.se/image/asdfghjkl/unscaled/19912234/1541383772.png?quality=10

I think I'll go for PNG, as there could in theory be images that have translucent backgrounds. The lighter image might be a problem with their JPG compressor.

Interestingly enough, there was already an instance of the site in the script, for a different system (used by many other news websites): https://github.com/qsniyg/maxurl/commit/5bb8dbfe6e51bccfcdb4e1fb23c784fbc9559116#diff-27f9d4a32bb1055d6e25712679ce34afR5728

**Comment by TheLovinator1** [comment]
Looks like the original image is in the source code:
```html
<meta data-react-helmet="true" property="twitter:image" content="https://www.svtstatic.se/image-cms/svtse/1541383772/svts/article19912234.svt/alternates/large/khashoggisoner-jpg"/>
<meta data-react-helmet="true" property="image_base_url" content="https://www.svtstatic.se/image-cms/svtse/1541383772/svts/article19912234.svt/alternates/{image_versions.name}/khashoggisoner-jpg"/>
<meta data-react-helmet="true" property="og:image" content="https://www.svtstatic.se/image-cms/svtse/1541383772/svts/article19912234.svt/alternates/large/khashoggisoner-jpg"/>
```

Your image also works with my URL:
https://www.svtstatic.se/image/original/unscaled/18662486/1531589739.png

**Comment by qsniyg** [comment]
Ah good catch! Now looking at the `image-cms` version, it seems like the original image was indeed a .jpg, and comparing it with the .png does show the same color difference. When viewing it in an image editor, however, there is no difference, so it's likely a browser problem (color spaces are apparently quite difficult).

However, when using `.jpg?quality=100`, the quality is degraded slightly in comparison to the original image.

Original/PNG:

![fabric_orig](https://user-images.githubusercontent.com/20496822/47993545-942c7500-e0a4-11e8-9ce0-820dc6955282.png)

JPG (with `quality=100`):

![fabric_jpg](https://user-images.githubusercontent.com/20496822/47993543-9393de80-e0a4-11e8-8622-ba141957c074.png)

I think I'll stick with the .png option, unless there's a way to retrieve the original file.

**Comment by qsniyg** [comment]
Implemented in https://github.com/qsniyg/maxurl/commit/672d11a7b7dae544107901e9f5b9a98cd6af1a70
