### ISSUE TITLE
Redirecting got "access denied" due to hotlink prevention mechanism 

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#180]
Example (from https://akibatan.com/2017/06/music-theater-2017-live-report/ ):

Original: `https://i0.wp.com/akibatan.com/wp-content/uploads/2017/06/music-theatre-2017-live-report-09.jpg?ssl=1`

When the script redirects to https://i1.wp.com/akibatan.com/wp-content/uploads/2017/06/music-theatre-2017-live-report-06.jpg it shows 

```
Error 1011 Ray ID: 549c902f7a33e03f • 2019-12-23 18:57:47 UTC
Access denied
What happened?
The owner of this website (akibatan.com) does not allow hotlinking to that resource (/wp-content/uploads/2017/06/music-theatre-2017-live-report-09.jpg).
```

**Comment by qsniyg** [comment]
Thanks for reporting! As I wrote in the commit, for some reason I had fixed this in `check_image_get` (the function used for the popup), where it's not actually required, but didn't in `check_image`, where it's vital for it to get the Referer header correct.
