### ISSUE TITLE
Redirects wrongly for images uploaded by browser addon

### ISSUE THREAD

**Issue by haarp** [qsniyg/maxurl#185]
Hello,

I'm using maxurl v.0.12.0 as an userscript and I'm very happy to have found it! Thanks for making it!

I recently tested a browser addon, [Re-host to imgur](https://addons.mozilla.org/en-US/firefox/addon/re-host-to-imgur/), which uploads images to imgur and opens them in a new tab, by right-clicking images.

However when I use it on a site supported by maxurl, it opens a new tab on imgur, only for maxurl to redirect the image back to the original site. It seems maxurl believes to still be on the original site, despite the URL bar saying otherwise. Weird, huh?

Cheers!

**Comment by qsniyg** [comment]
You're very welcome!

That was actually a new feature that was added in 0.12.0, which finds the source image that was uploaded to Imgur (especially useful if the person uploading the image to Imgur didn't upload the largest version). But you're right, there should be an option to toggle this behavior, I hadn't thought of that! In the next version (will be in a day or two, or you can use the git master directly to use it now if you want), disabling "Redirect to source image for Imgur" should fix it :)

**Comment by haarp** [comment]
Awesome, thanks for the super quick reaction!
