### ISSUE TITLE
Support for Steam store (store.steampowered.com) image carousel

### ISSUE THREAD

**Issue by 07416** [qsniyg/maxurl#19]
[example page](http://store.steampowered.com/app/356500/STAR_WARS_Galactic_Battlegrounds_Saga/)

Steam's native image viewer (click on a thumbnail followed by larger image) doesn't show the image at full size. Please add support to browse through the entire gallery. Videos shouldn't be included.

**Comment by qsniyg** [comment]
Using Ctrl+Shift (or whatever the mouseover key is bounded to) over the gallery images doesn't work for you? For me, it returns:

https://steamcdn-a.akamaihd.net/steam/apps/356500/ss_3ee60560c645c0c6740d62e538e863219a7aa5dc.jpg?t=1498859229

**Comment by 07416** [comment]
> 
> 
> Using Ctrl+Shift (or whatever the mouseover key is bounded to) over the gallery images doesn't work for you? For me, it returns:
> 
> https://steamcdn-a.akamaihd.net/steam/apps/356500/ss_3ee60560c645c0c6740d62e538e863219a7aa5dc.jpg?t=1498859229

Image Max URL returns the full-sized image, as it should. I'm requesting gallery support for Steam.

**Comment by 07416** [comment]
@qsniyg Wait... does this extension have "gallery"-support?

**Comment by qsniyg** [comment]
Could you explain what you mean by gallery support? Sorry, I'm not quite sure I follow...

**Comment by 07416** [comment]
> 
> 
> Could you explain what you mean by gallery support? Sorry, I'm not quite sure I follow...

Image hosts which support uploading multiple images as a "gallery", Imgur as an example: https://imgur.com/a/PWgY0?gallery

Imagus, Mouseover Popup Image Viewer (now-discontinued) and Hover Zoom+ all support browsing images in a gallery (with directional keys)

**Comment by qsniyg** [comment]
Should be implemented now! Use the left and right arrow keys to go through the carousel (you might want to set the popup close trigger to only ESC in the [options page](https://qsniyg.github.io/maxurl/options.html)).

It doesn't work very well on Imgur for now, I think I'll have to make a custom rule for that one. But it works on Reddit, Steam, and hopefully most other websites.

**Comment by 07416** [comment]
@qsniyg I hope you can update the gallery with a counter (as seen in the image above). 

As for the Steam support, please exclude the (low-quality) video thumbnails which are displayed when browsing past ("left") the first image.

**Comment by qsniyg** [comment]
The counter is definitely possible, I'll work on it when I implement the close button for the popup :)

For excluding thumbnails, it is a possibility, but as much as possible, I'd like to avoid options that are specific per-site. I could maybe add an user-specified option for ignoring images that are smaller than a specified resolution though, which would more or less do the same thing.

As for the last, I think that's going a bit too site-specific for this script. However, there are a lot of site-specific features that could be neat to add, so I think adding a plug-in system of sorts would make more sense, and would allow for this kind of feature to be added. I'll have to think about this some more to figure out how it would work though.
