### ISSUE TITLE
unreachable code after return statement

### ISSUE THREAD

**Issue by haarp** [qsniyg/maxurl#190]
Hello,

I'm using the userscript variant of this, v0.12.2 in Violentmonkey on Firefox 71.0. When this userscript is enabled, it makes the browser send 7 lines of log to stdout for each site load. This can become quite spammy over time. Here's the log from one site load, but I doubt the line numbers will be usable:

```
JavaScript warning: https://site.com/, line 11530: unreachable code after return statement
JavaScript warning: https://site.com/, line 14458: unreachable code after return statement
JavaScript warning: https://site.com/, line 20837: unreachable code after return statement
JavaScript warning: https://site.com/, line 30344: unreachable code after return statement
JavaScript warning: https://site.com/, line 34746: unreachable code after return statement
JavaScript warning: https://site.com/, line 35722: unreachable code after return statement
JavaScript warning: https://site.com/, line 35924: unreachable code after return statement
```

Worse, if the desktop session has its log dumped somewhere (as is the default for most X11 session managers), this makes for a quickly growing logfile, that could also be used to reconstruct entire browsing sessions. That's not strictly a maxurl issue (Firefox shouldn't be logging errors to stdout willy-nilly) but I want to mention it anyway.

Cheers!

**Comment by qsniyg** [comment]
I really should test under firefox more haha. Should be fixed now, sorry about that!

**Comment by haarp** [comment]
Lightning fast, thanks a lot :100: 

I'm having trouble applying he commit with Violentmonkey's atrocious built-in editor, so I'll wait for the next version before I can tell you if it worked.

**Comment by qsniyg** [comment]
@haarp You're welcome :) The way I usually do it is just to open up the file directly in the browser (e.g. through file:///home/qsniyg/maxurl/userscript.user.js), and Violentmonkey will popup, asking if I want to install the userscript (it'll overwrite the old version).

In any case though, there's a relatively major regression that was introduced in the last version (all browser keybindings are disabled in the options page), so the next release will be sooner than the usual weekly schedule, maybe tomorrow or something :)
