### ISSUE TITLE
Images opened in their own tabs do not redirect anymore to the original size image in v0.12.0 and onwards on Firefox 56

### ISSUE THREAD

**Issue by Bwin4L** [qsniyg/maxurl#192]
Hello,

On Firefox 56 (yes, it's old and and I should probably move to other XUL-based browsers), since the changes to how requests are made in v0.12.0, image redirection seems to be broken.
I believe it might be caused by a Firefox bug: I looked at the response and while resp.readyState does equal 2, the headers are null (resp.responseHeaders = null). Fortunately, the "fix" (workaround) is rather simple.
Changing line 31337 on v0.12.2 from:
```
if (resp.readyState >= 2) {
```
to
```
if (resp.readyState >= 2 && resp.responseHeaders) {
```
i.e. checking whether the response headers are indeed there fixes the issue for me.
The same "fix" must probably also be applied on line 33111, for GET requests:
change it from
```
if (incomplete_request && resp.readyState >= 2) {
```
to
```
if (incomplete_request && resp.readyState >= 2 && resp.responseHeaders) {
```

I would absolutely understand you if you didn't want to implement this fix, after all I'm the one using an old browser. Despite this, would you still consider adding this to the script's code?

Thanks!
Bwin.

**Comment by qsniyg** [comment]
Thank you very much for the detailed report and fix! For some reason while testing, that situation never occurred, but it makes complete sense that it could happen.

**Comment by Bwin4L** [comment]
Wow, that was blazingly fast! Thanks a lot! :)
