### ISSUE TITLE
Improved rule for img.blick.ch

### ISSUE THREAD

**Issue by carozzz** [qsniyg/maxurl#194]
Low-res image link: https://img.blick.ch/incoming/2998379-v4-teaserbildenergyair.jpg?imwidth=1000&ratio=FREE&x=0&y=293&width=4256&height=2397

With the current rule `ratio=FREE` an image with a resolution of 2000x1331 is displayed.

https://img.blick.ch/incoming/2998379-v4-teaserbildenergyair.jpg?ratio=FREE

But if you append `&x=0&y=0` after `ratio=FREE` you'll get the image with 4256x2832 resolution.

https://img.blick.ch/incoming/2998379-v4-teaserbildenergyair.jpg?ratio=FREE&x=0&y=0

**Comment by qsniyg** [comment]
Thank you very much! It'll be added in the next release (which will likely be in a day or two, there's another relatively serious bug that got fixed)
