### ISSUE TITLE
Add mouseover event trigger option

### ISSUE THREAD

**Issue by qsniyg** [qsniyg/maxurl#198]
The "mouseover" trigger works the same way as the key trigger, which allows it to find images hidden behind other elements as well as `background-image`s. However, having a simple mouseover event might be more desirable in some cases as it doesn't pop up for images behind divs etc.

**Comment by LoneFenris** [comment]
Not sure if there's some trick to this, but I can't seem to get images to popup when this is on -- at least not on Reddit or Instagram.

**Comment by qsniyg** [comment]
@LoneFenris Ah, I had tested it with the highlight images enabled, my mistake haha. It should work better now :)

That being said, Instagram still doesn't work properly with that option because of image masks. Other than rearchitecting the script to work like Imagus/MPIV etc. (i.e. rules specify which elements should be hoverable), I don't know if this is really possible to support with this option for those sites.

I don't mind doing so if there is a genuine need for it, but in theory, you should be able to have the same experience by enabling `Exclude background-images`  and setting `Close when leaving` to `Thumbnail` (and have Instagram images supported) :)
