### ISSUE TITLE
akiba-souken.com (akiba-souken.k-img.com)

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#199]
Example page:

https://akiba-souken.com/article/43402/

Example image URL:

`https://akiba-souken.k-img.com/thumbnail/images/official/71/71cea5d83dfa537e053b8b8e31b98649.jpg?w=60&h=60
`
-->

`https://akiba-souken.k-img.com/assets/images/official/71/71cea5d83dfa537e053b8b8e31b98649.jpg`

Current rule doesn't redirect /thumbnail/ to /assets/

**Comment by qsniyg** [comment]
Thank you very much! Should be fixed now :)
