### ISSUE TITLE
Twitter: Change redirection

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#2]
Hi. The script currently appends `:orig` to the url. This causes my browser to save it as `.jpg_orig`.

Can you change it from
`https://pbs.twimg.com/media/Dbxmq4BV4AA2ozg.jpg:orig`
to?
`https://pbs.twimg.com/media/Dbxmq4BV4AA2ozg?format=jpg&name=orig`

My browser will save it as `.jpeg`

**Comment by qsniyg** [comment]
Great idea! I set it to return `https://pbs.twimg.com/media/Dbxmq4BV4AA2ozg.jpg?name=orig` instead, as then the file extension will still be available.
