### ISSUE TITLE
PopUp styling

### ISSUE THREAD

**Issue by Acid-Crash** [qsniyg/maxurl#20]
It would be nice to be able to have some sort of customization (for the extension version) for the popUp appearance (borders, shadows, border-radius): either in form of presets  or a custom field where user can add their own CSS rules (find example below)

```css
border: 7px solid hsla(0,0%,95%,.6); 
border-radius: 5px; 
box-shadow: 0 0 2px #666
```

**Comment by qsniyg** [comment]
That's a great idea! I've implemented it here: https://github.com/qsniyg/maxurl/commit/7305f1d811a56001fade88b6c60b1e50c746857a, see if it works for you :)

**Comment by Acid-Crash** [comment]
Wow that was fast!
Hmm, I'm on Firefox and extension v0.7.6. Can see any cunsomization options yet.
Not sure if they shuld be here...

**Comment by qsniyg** [comment]
I haven't updated it on the add-on page yet. Try downloading the repository (either via git, or via the tarball), go to `about:debugging`, and select "Load temporary extension", navigate to the place where you cloned/extracted the repository, and select `manifest.json`.

**Comment by Acid-Crash** [comment]
Did it.
All in all it works however there are few issues:
- Save button (in options) overlaps with textarea for custom CSS.
![image](https://user-images.githubusercontent.com/32600318/48136201-b4785180-e2a7-11e8-966b-6da9a5f4a730.png)
- After closing options window and reopening it again custom CSS code textarea becomes blank
- After adding this
```
padding: 0; margin: 0;
border: 15px solid red; 
border-radius: 5px; 
box-shadow: 0 0 2px #666;

```
I've noticed smaill cleavage on the bottom of the popUp, not sure how to remove it
![image](https://user-images.githubusercontent.com/32600318/48136138-94489280-e2a7-11e8-81f3-d4a28ef3cec7.png)

**Comment by qsniyg** [comment]
All should be fixed, thanks for reporting them!

**Comment by 07416** [comment]
I recommend adding a preset option to center images.

**Comment by qsniyg** [comment]
Could you clarify what you mean by center images? Do you mean centering the popup on the page?

**Comment by 07416** [comment]
> 
> 
> Could you clarify what you mean by center images? Do you mean centering the popup on the page?

Yes.

**Comment by qsniyg** [comment]
@07416 Apologies for the delay, it should be implemented here: https://github.com/qsniyg/maxurl/commit/d70695a2b18f7a661c1ff8efc40305aff2f11e33

I'll push an update in a bit :)
