### ISSUE TITLE
A different type of Tieba image URL

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#22]
Example: https://imgsa.baidu.com/forum/w%3D580/sign=b48af07db34543a9f51bfac42e168a7b/2b3e91160924ab1890b8cfbe31fae6cd7a890b60.jpg

Should redirect to 

http://imgsrc.baidu.com/forum/pic/item/2b3e91160924ab1890b8cfbe31fae6cd7a890b60.jpg

**Comment by qsniyg** [comment]
Thanks! I wonder if there are any other imgs* domains for baidu then, I guess I'll have to look into that later.
