### ISSUE TITLE
Google randomly found a redirect to a 2000x2000 version of a post, something that's not possible due

### ISSUE THREAD

**Issue by acoolrocket** [qsniyg/maxurl#227]
You can find the original reddit comment with links to pictures here: https://www.reddit.com/r/tumblr/comments/f4lrrp/google_randomly_found_a_redirect_to_a_2000x2000/fhrks0r/

So this is something unexpected, somehow Google found a redirect whilst if you were to fetch the image from the Tumblr page itself, you were always stuck to being directed to the 1280x1280 version.

If you look at the url itself, it changes from 's1280x1920' to 's2048x3072', then followed by [a completely different sequence of letters/numbers].jpg, so there's no telling how to exactly go about finding that 2000x2000 version, since if you were to only do the 's1280x1920' to 's2048x3072' change, you'd get an error.

Here's another post I found with a redirect to the 2048x2048 version, then the 1280x1280 version for comparison.

**Comment by qsniyg** [comment]
Thank you very much for sharing the info! I believe this has already been handled here: https://github.com/qsniyg/maxurl/issues/88

Although this script _does_ support the larger versions with the new URL scheme, it only works if you use it on the blog hosting the image, as I'm not sure how to find the post ID from the URL itself (which is needed for the API calls). If the post has more than one image, you also need an API key (although I added one in the git master version, so you can also use that while waiting for the new version :)

I'll close this issue as I believe it's handled by the issue linked above, but if it isn't, let me know and I'll reopen it :)

**Comment by acoolrocket** [comment]
So in essence your saying the second part after the /s2048x3072/ or /s1280x1920/ is almost impossible to decipher given its randomly generated?

**Comment by qsniyg** [comment]
@acoolrocket I believe it's likely a signature of sorts, where they use some sort of hashing function with an unknown salt over the URL (or parts of the URL). But it could also be random. Either way, as far as I know it's unfortunately impossible to generate that portion without having access to the API.
