### ISSUE TITLE
Men's Wearhouse Support

### ISSUE THREAD

**Issue by user-00** [qsniyg/maxurl#244]
Please add support for images from menswearhouse.com.

-------------------
Example 1 (from https://www.menswearhouse.com/p/joe-joseph-abboud-navy-space-dye-stripe-slim-fit-sweater-67AA67AC01):

https://images.menswearhouse.com/is/image/TMW/MW40_67AA_01_JOE_JOSEPH_ABBOUD_NAVY_SET?$40MainPDP$
--> should become -->
https://images.menswearhouse.com/is/image/TMW/MW40_67AA_01_JOE_JOSEPH_ABBOUD_NAVY_MAIN?hei=3500&wid=2759&align=0,-1

-------------------
Example 2 (from https://www.menswearhouse.com/p/pronto-uomo-silver-black-tie-bar-81VT02):

https://images.menswearhouse.com/is/image/TMW/MW40_81VT_02_PRONTO_UOMO_BLACK_SET?$40MAINQV$
--> should become -->
https://images.menswearhouse.com/is/image/TMW/MW40_81VT_02_PRONTO_UOMO_BLACK_MAIN?hei=3500&wid=2759&align=0,-1

Technically, by specifying 3500x2759, a bunch of white space gets added around the image. I don't know how to find the proper dimensions, especially since the source code of the product page references the 3500x2759 image.

-------------------
Example 3 (from https://tuxedo.menswearhouse.com/notch-lapel-tuxedo-black-vera-wang-id-5242):

https://images.menswearhouse.com/is/image/TMW/MWTSP19_WED_PSL_FML_1130_MAIN?$TUXPDPZOOM$
--> is already largest size and should NOT become -->
https://images.menswearhouse.com/is/image/TMW/MWTSP19_WED_PSL_FML_1130_MAIN?hei=3500&wid=2759&align=0,-1

Notice how the product page already contains the max image. Using the hei and wid parameters just adds a bunch of unnecessary white space around the image.

-------------------
Thank you!

**Comment by qsniyg** [comment]
Thank you very much! Turns out it uses a similar rule to many other online stores (`/is/image/`), so replacing the ending with `?scl=1&fmt=png-alpha` works fine for all the images you sent! :)

**Comment by user-00** [comment]
Awesome, thank you! (Wow you're fast!)
