### ISSUE TITLE
Pop-up support for plain hyperlinks

### ISSUE THREAD

**Issue by 07416** [qsniyg/maxurl#25]
Pop-up for direct image hyperlinks isn't supported: https://user-images.githubusercontent.com/14923168/48137062-e4c0ef80-e2a9-11e8-8ec8-3ffcdfb1d463.jpg

Can you enable all direct links with one global rule?

**Comment by qsniyg** [comment]
That's a good idea! I'll try implementing that soon.

>Can you enable all direct links with one global rule?

I'm not quite sure I follow, sorry, do you mean for this behavior to be an option? Or for this behavior to work on all websites? If it's one of the above, then the answer is yes :)

**Comment by 07416** [comment]
>I'm not quite sure I follow, sorry, do you mean for this behavior to be an option? Or for this behavior to work on all websites? If it's one of the above, then the answer is yes :)

To work on all websites. Sorry for being unclear.

**Comment by qsniyg** [comment]
Should work now. It's disabled by default, because there's no way for it to know what hyperlinks are images or not (while checking the extension for `.jpg` is a good clue, many websites host images that don't have extensions).

**Comment by LoneFenris** [comment]
Not sure how feasible this is in your project, but couldn't you detect the supported sites from plain hyperlinks and use that in addition to whether the link has an image extension to decide whether to popup?

**Comment by qsniyg** [comment]
@LoneFenris Right now it works for all links, but the option has to be manually enabled. But yes, that's a good idea to narrow down the results, thank you!

**Comment by qsniyg** [comment]
I'll close this issue as I believe it's been properly implemented. Feel free to reopen or create a new issue if there are any issues or a further feature request for this.
