### ISSUE TITLE
Pop-up support for Reddit

### ISSUE THREAD

**Issue by 07416** [qsniyg/maxurl#26]
It's great that Reddit thread links are rewritten to direct images. Pop-up support would allow seamless browsing on image-based subreddits.

https://www.reddit.com/r/corgi/
https://old.reddit.com/r/corgi/ (legacy)

**Comment by qsniyg** [comment]
I did add support for reddit a while back actually... if you move your mouse over an image and trigger a popup, it doesn't work?

**Comment by 07416** [comment]
> 
> 
> I did add support for reddit a while back actually... if you move your mouse over an image and trigger a popup, it doesn't work?

I've disabled thumbnails by blocking redditmedia.com domain in uBlock Origin. The purpose was to disable custom subreddit CSS without relaying on Reddit account configuration settings.

When the images are loaded the pop-up appears. Sorry. I don't know if modifying the current behavior is worth it.

**Comment by qsniyg** [comment]
It could be possible to do so, and I could see the use case for sure, but it would be unexpected for most for the image popup to show anywhere else other than the thumbnail, so it would need to be an option, which would be site-specific. So like I said in the other issue, implementing this so it works on more than just the thumbnail would require a plugin framework of sorts :)
