### ISSUE TITLE
discovery-expedition.com

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#266]
Source: https://www.discovery-expedition.com/goods/%EA%B3%B5%EC%9A%A9/%EC%8B%A0%EB%B0%9C/DXSH02911-BE

Small: https://static.discovery-expedition.com/images/goods/detail/x/20190507/DXSH02911-BE-8998685969005915.jpg/dims/resize/940x1253
Large: https://static.discovery-expedition.com/images/goods/detail/x/20190507/DXSH02911-BE-8998685969005915.jpg

**Comment by qsniyg** [comment]
Thank you very much, as usual! :)

Interesting, I see the /dims/(resize|quality)/ thing a lot, on many different websites with completely different systems (e.g. mt.star.co.kr, yes24.com, and a few others), but so far only on Korean websites. I'm curious what the common factor is
