### ISSUE TITLE
Twitter/TweetDeck does not work with tracking protection turned on

### ISSUE THREAD

**Issue by migynster** [qsniyg/maxurl#27]
Not directly related to the script but.
Maybe some other sites too. In Firefox, when browser internal tracking protection is set to "always" popup and redirections stop working. Adding exception doesn't help.
I found it just right now. But for information, Twitter/TweetDeck not worked for me from the beginning when first installed the script, then at some point it started. And recently somewhere at version 0.7.6 7(?) this bug(?) is back. So maybe it was the reason from the beginning? No noticeable problems with other sites.

**Comment by qsniyg** [comment]
Not sure why the bug would have been fixed in 0.7.6/7, but the problem was actually (mainly) due to the background script requiring a response body, instead of gracefully accepting null.

Although it won't keep spinning endlessly, it still won't be able to load any popups on Twitter/TweetDeck. That's due to a bug in the tracking protection for some reason, but I'm not sure why. Non-twitter images do work however (such as youtube previews).

**Comment by migynster** [comment]
> Not sure why the bug would have been fixed in 0.7.6/7

This is probably just on my end, maybe temporarily turned it off and forgot about it. I remember like two weeks ago, was surprised that developers reworked options dialog. And made enough changes in the privacy settings.

**Comment by qsniyg** [comment]
Ah, you're right, it could be that they fixed it during that period. If you were to open a bug report there, hopefully they should be able to fix it :)

**Comment by migynster** [comment]
No I mean...
Twitter stopped working again just two weeks ago, around the time these versions were released. When I probably set the settings back, the option was just turned off all this long time. They did not fix anything lol.
And this is not necessarily their fault, perhaps Disconnect.me built-in filters.

Can you temporarily test :orig instead ?name=orig ?
Cause it's really strange, I tried it on tens of sites and only damn Twitter doesn't work.

**Comment by qsniyg** [comment]
@migynster Tried it, and no change unfortunately. Interestingly enough though, I found this article: https://medium.com/firefox-test-pilot/test-pilot-tracking-protection-graduation-report-7452b5ccc477

> Early on, we noticed that one service — Twimg, Twitter’s remote image hosting service — consistently showed up as a source of reported breakage. By diving into our user feedback, we figured out that this breakage caused images not to render and often lead to broken layout. We communicated our findings to Disconnect (the tracking protection company that provides our block list), and they were able to re-categorize the Twimg domain as a content provider, mitigating the breakage.

Twimg is the only website they noted on the article that had problems with it. The article was from last year, but I guess the problem has reappeared or something. Non-twitter pages that host twitter images have the same problem as well, but viewing a twitter image directly (in its own tab) somehow works without any problems.

This also applies for profile pictures as well (where `?name=orig` etc. don't work), and the issue appears regardless of whether `:orig`, `?name=orig`, `:large`, or `?name=large` is added to regular images or if it's kept without any modifiers (as in, it ends purely with `.jpg`).

**Comment by qsniyg** [comment]
@OutrageOrange `:large` crops it to a maximum of 2048px on either side, while `:orig` crops it to a maximum of 4096px on either side (despite the name, it's not the original version). I'm not aware of a method to find the original version of the image though (other than having it as your profile picture, not sure if they patched that yet or not). However, I did test it as well, with no luck either.

**Comment by migynster** [comment]
So there are several articles similar to
https://bugzilla.mozilla.org/show_bug.cgi?id=1458915
I guess the issue is Disconnect.me block list.

**Comment by qsniyg** [comment]
Interesting, and that makes sense that it happens with the userscript, because it has the same problem with the addon version of the script.

I know this isn't much of a fix, but I would personally recommend using uBlock instead, and enable the default tracking filter lists. You can enable any of Disconnect's filters with uBlock, but you have complete control over them :)

Also, I believe it has many more tracking filters than Firefox has at default, which is another plus. The only downside I can think of is that it only works for websites, not extensions.

**Comment by migynster** [comment]
On a side note.
I recommend in the options dialog to make the switcher between keyboard keys and delays. Because it took me enough time to understand that "Ctrl Shift Alt" keys do not work with delays together. You can choose five options, but the top and bottom row are not compatible with each other! Or is it also a bug? If not, it is not very intuitive.

**Comment by qsniyg** [comment]
Odd, that is a bug... It works fine here with the Firefox addon and the userscript under Chrome. To be clear, you held down the Ctrl/Shift/Alt keys for the delay time specified, correct? For example, if "Ctrl" "Shift" and "Delay 1s" are selected, you held Ctrl and Shift down for at least 1 second?

**Comment by migynster** [comment]
Yes the circle starts spinning over the mouse pointer, as if something is about to happen... But the popup does not appear.
Give me time, I will try turn off all my other "protections" maybe this is something on my side again.

**Comment by qsniyg** [comment]
By "circle starts spinning over the mouse pointer", do you mean the progress cursor? (mouse over "progress" here: https://www.w3schools.com/csSref/tryit.asp?filename=trycss_cursor if you don't know what I'm talking about)

If it's the full "wait" cursor (the mouse is replaced with the spinning circle), then that's not supposed to happen.

Could you check the console (F12) and see if there are any errors? Or if it shows "Trying [url]"?

**Comment by migynster** [comment]
Nah turned off all private settings, add-ons, other scripts everything
I switched from Greasemonkey to Tampermonkey two months ago, and it didn't work even then.

Do not see any difference in the console, in all cases it is
Trying [url] userscript.html:24779:9 

A small circle hangs over the cursor when I press the hot keys above the picture. The cursor does not turn into a full circle, as in another working (when I press ONLY hot keys OR delay activated) case.

**Comment by qsniyg** [comment]
@migynster Sorry for getting back so late. I'm not sure if this commit will fix it or not though, as I still have absolutely no idea why the issue is happening.

Here's the issue:

```
function do_popup() {
    start_waiting(); // <- doesn't get run, as this would turn the small circle into a full one
    [...]
}

start_progress(); // <- clearly gets run, as you said the cursor turns into a small circle
delay_handle = setTimeout(function() {
    delay_handle = null;
    do_popup();
}, delay * 1000);
```

The only way I can see that failing is if `delay` is somehow huge, or NaN, neither of which should happen, but I added code to ensure `delay` is never NaN.

**Comment by qsniyg** [comment]
@migynster Sorry for getting back so late, I had entirely forgotten! In later releases, as you said, there's no reason to use hot keys with a delay, so the option has been removed :)
