### ISSUE TITLE
Can you support websites hs.fi/is.fi

### ISSUE THREAD

**Issue by fyhtma** [qsniyg/maxurl#270]
Could you please add support for sites hs.fi and is.fi? Thanks!

Site: https://www.hs.fi/talous/art-2000006442426.html
When open this image to new tab...: https://hs.mediadelivery.fi/img/658/9121cba7d33948309c52ff5691581cec.jpg
....I want to see this one instead: https://hs.mediadelivery.fi/img/1920/9121cba7d33948309c52ff5691581cec.jpg

Similar issue with other site of same company:
https://www.is.fi/kotimaa/art-2000006441004.html
https://is.mediadelivery.fi/img/658/0fc78cb8a1474ec2b20d891a8e033b37.jpg
https://is.mediadelivery.fi/img/1920/0fc78cb8a1474ec2b20d891a8e033b37.jpg

Other values following /img/ (658 in previous examples) which I want to be "1920" are listed here:
"data-srcset =" // hs.mediadelivery.fi/img/115/952fdd5f007e41c29483b1a859edaae9.jpg 115w, // 230v, // hs.mediadelivery.fi/img/320/952fdd5f007e41c29483b1a859edaae9.jpg 320w, // hs.mediadelivery.fi/img/468/952fdd5f007e41c29483b1a859edaae9.jpg 468w, / /hs.mediadelivery.fi/img/658/952fdd5f007e41c29483b1a859edaae9.jpg 658w, // hs.mediadelivery.fi/img/978/952fdd5f007e41c29483b1a859edaae9.jpg 978w, // hs.mediadelivery.fi/img/1440/952fdd5f007e41c29483b1a859edaae9.jpg 1440w, //hs.mediadelivery.fi/img/1920/952fdd5f007e41c29483b1a859edaae9.jpg 1920w "/>

**Comment by qsniyg** [comment]
Thanks!

Darn... I can't find any way to find the original version of the image (tried nothing, 0, -1, raw, master, org, orig, origin, original, full, source, src, and a few others I forgot as well). Unfortunately, as you can see here: https://hs.mediadelivery.fi/img/1920/adc2268f4e0442b2843abd5166ed8ed3.jpg it upscales smaller images.

I'll add the rule tomorrow, alongside a new option "Possibly upscaled images" :) (you'll have to enable that option for the rule to take effect)

In the meantime though, you can use the popup (bound to Shift+Alt+I by default), which will automatically fetch the largest version from the srcset you pasted.

**Comment by qsniyg** [comment]
Sorry for getting back so late. I've added in the rule, but as I noted above, you'll need to enable "Possibly upscaled images".

Hopefully a pattern for the original image can be found :)

**Comment by fyhtma** [comment]
this currently forwards to .webp file instead of .jpg, could you fix it to use .jpg thanks

example https://www.is.fi/viihde/art-2000005548573.html
https://is.mediadelivery.fi/img/1920/0ab8da52fedb4f3fabff5d85a638a994.jpg.webp
->
https://is.mediadelivery.fi/img/1920/0ab8da52fedb4f3fabff5d85a638a994.jpg

**Comment by qsniyg** [comment]
Thanks, fixed!

**Comment by fyhtma** [comment]
For some reason, when using Firefox with the Image Max URL addon (version 2024.8.0), the larger image doesn't load if "Possibly upscaled images" is set to "No."

For example:
https://is.mediadelivery.fi/img/1440/eaf305a6a34bd36415eaabfae32f9bda.jpg.webp
should be redirected to:
https://is.mediadelivery.fi/img/1920/eaf305a6a34bd36415eaabfae32f9bda.jpg

However, when using Edge with the userscript (version 2024.8.0) and "Possibly upscaled images" set to "No," the redirect to the larger image works perfectly.

**Comment by qsniyg** [comment]
The `.jpg.webp` -> `.jpg` conversion should be fixed now!

**Comment by fyhtma** [comment]
Sites of this Sanoma Corporation has changed again. Currently these seems to works this way:

HS.fi:
https://www.hs.fi/ilta/art-2000002878430.html
-> https://images.sanoma-sndp.fi/b9fb6b475bd64f9a8d91569d3cc139ce.jpg/normal/978.webp
--> https://images.sanoma-sndp.fi/75459afdd3594273ac75dc873023d3cb.jpg/normal/1920.jpg

IS.fi
https://www.is.fi/digitoday/esports/art-2000010953863.html
-> https://images.sanoma-sndp.fi/895512fa607f5dcf675be073b644511e/normal/978.webp
--> https://images.sanoma-sndp.fi/895512fa607f5dcf675be073b644511e/normal/1920.jpg

**Comment by qsniyg** [comment]
Updated, thanks!

**Comment by qsniyg** [comment]
Updated, thanks!
