### ISSUE TITLE
ONErpm

### ISSUE THREAD

**Issue by nimuxoha** [qsniyg/maxurl#271]
https://onerpm.com/disco/album?album_number=4838993301

Thumbnail examples:
https://soup.onerpm.com/web/user/images/1/aa/aaEQyKG8aZIjzBaQ6Q7D.200.jpg
https://soup.onerpm.com/web/user/images/1/aa/aaEQyKG8aZIjzBaQ6Q7D.400.jpg

Original: 
https://soup.onerpm.com/web/user/images/1/aa/aaEQyKG8aZIjzBaQ6Q7D.orig.jpg

Also found alternative path /content/ instead of /images/

**Comment by qsniyg** [comment]
Thank you very much! Added it in now, with both /images/ and /content/ supported
