### ISSUE TITLE
crank-in.net

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#272]
https://www.crank-in.net/news/75056/1

https://www.crank-in.net/img/db/1386421_650.jpg 
https://www.crank-in.net/img/db/1386421_150.jpg
->
https://www.crank-in.net/img/db/1386421_1200.jpg

**Comment by qsniyg** [comment]
Darn... unfortunately this also upscales images: https://www.crank-in.net/img/db/1294425_1200.jpg

I've added in the rule, but it'll only be enabled if "Possibly upscaled images" is enabled.

I've also found this pattern: https://m.crank-in.net/img/sp/images/_DSC0097.JPG, but I don't think there's any way to retrieve it.

**Comment by fireattack** [comment]
Yeah, I do find out later they upscale. Not sure if there is a pattern for orig size image.

**Comment by qsniyg** [comment]
I tried the usual roster of src/raw/org/orig/origin/original/0/-1/nothing, and none worked unfortunately. If you do happen to come across one later though, please let me know! :)
