### ISSUE TITLE
Improve AllMusic support on release pages

### ISSUE THREAD

**Issue by nimuxoha** [qsniyg/maxurl#279]
AllMusic proves to be a valuable source of cover art. Especially for old and obscure stuff.
Unfortunately they are making it hard to easily access the image files. Their gallery feature allows zooming but they won't show the original image. Even worse, they disable the right click menu on images.

So far I've found two different hosts. `cps-static.rovicorp.com` is already supported but not `rovimusic.rovicorp.com`. Furthermore Image Max URL does not yet support galleries for either of them. 

----

**Host and gallery support for `rovimusic.rovicorp.com`**

[Example 1](https://www.allmusic.com/album/release/mr0002329530) (hi-res plus gallery)

`https://rovimusic.rovicorp.com/image.jpg?c=yYHZyRxSklE9doh5teJWQh_TZlp6n_cq-Emr2zx15tU=&f=6`
`https://rovimusic.rovicorp.com/image.jpg?c=kv7IcD6PCBY106TjSLBrrQSijaXJlYnq0St31qpAJWo=&f=6`

```
var imageGallery = [{
        "height": 492,
        "width": 500,
        "formatid": 16,
        "author": "",
        "copyrightOwner": "",
        "imageTypeId": 0,
        "zoomLevel": true,
        "url": "https:\/\/rovimusic.rovicorp.com\/image.jpg?c=yYHZyRxSklE9doh5teJWQh_TZlp6n_cq-Emr2zx15tU=&f=5",
        "album": true,
        "zoomURL": "https:\/\/rovimusic.rovicorp.com\/image.jpg?c=yYHZyRxSklE9doh5teJWQh_TZlp6n_cq-Emr2zx15tU=&f=6",
        "artist": "Raulin Rosendo",
        "albumTitle": "Disco de Oro"
    },
    {
        "height": 492,
        "width": 500,
        "formatid": 16,
        "author": "",
        "copyrightOwner": "",
        "imageTypeId": 0,
        "zoomLevel": true,
        "url": "https:\/\/rovimusic.rovicorp.com\/image.jpg?c=kv7IcD6PCBY106TjSLBrrQSijaXJlYnq0St31qpAJWo=&f=5",
        "album": true,
        "zoomURL": "https:\/\/rovimusic.rovicorp.com\/image.jpg?c=kv7IcD6PCBY106TjSLBrrQSijaXJlYnq0St31qpAJWo=&f=6"
    }
];
```

[Example 2](https://www.allmusic.com/album/release/mr0002781134) (single image, lo-res only)

`https://rovimusic.rovicorp.com/image.jpg?c=xzKo0kWqwqp7ptqpGPSaWD6KsMttLlyBmmVTZ6_CLs0=&f=4`

```
var imageGallery = [{
    "height": 395,
    "width": 400,
    "formatid": 64,
    "author": "",
    "copyrightOwner": "",
    "imageTypeId": 0,
    "zoomLevel": null,
    "url": "https:\/\/rovimusic.rovicorp.com\/image.jpg?c=xzKo0kWqwqp7ptqpGPSaWD6KsMttLlyBmmVTZ6_CLs0=&f=4",
    "album": true
}];
```

It looks like `zoomURL`  is only present when a higher res version exists. `zoomLevel` behaves similarly, it's `null` when `zoomURL` is missing. 

----

**Gallery support for `cps-static.rovicorp.com`**

[Example 3](https://www.allmusic.com/album/release/mr0000570239) (hi-res plus gallery)

```
var imageGallery = [{
    "height": 500,
    "width": 498,
    "formatid": 16,
    "author": "",
    "copyrightOwner": "",
    "imageTypeId": 0,
    "zoomLevel": true,
    "url": "https:\/\/cps-static.rovicorp.com\/3\/JPG_500\/MI0000\/331\/MI0000331346.jpg?partner=allrovi.com",
    "album": true,
    "zoomURL": "https:\/\/cps-static.rovicorp.com\/3\/JPG_1080\/MI0000\/331\/MI0000331346.jpg?partner=allrovi.com",
    "artist": "Julia Douglass",
    "albumTitle": "Fetish for the Underdog"
}, {
    "height": 426,
    "width": 500,
    "formatid": 16,
    "author": "",
    "copyrightOwner": "",
    "imageTypeId": 0,
    "zoomLevel": true,
    "url": "https:\/\/cps-static.rovicorp.com\/3\/JPG_500\/MI0000\/331\/MI0000331347.jpg?partner=allrovi.com",
    "album": true,
    "zoomURL": "https:\/\/cps-static.rovicorp.com\/3\/JPG_1080\/MI0000\/331\/MI0000331347.jpg?partner=allrovi.com"
}];
```

[Example 4](https://www.allmusic.com/album/release/mr0001144566) (single image plus higher res)

```
var imageGallery = [{
    "height": 500,
    "width": 500,
    "formatid": 16,
    "author": "",
    "copyrightOwner": "",
    "imageTypeId": 0,
    "zoomLevel": true,
    "url": "https:\/\/cps-static.rovicorp.com\/3\/JPG_500\/MI0001\/754\/MI0001754760.jpg?partner=allrovi.com",
    "album": true,
    "zoomURL": "https:\/\/cps-static.rovicorp.com\/3\/JPG_1080\/MI0001\/754\/MI0001754760.jpg?partner=allrovi.com",
    "artist": "Cynthia Greene",
    "albumTitle": "Life's Lessons"
}];
```
`JPG_1080` should always be replaced with `JPG_SRC` otherwise it might be upscaled.

**Comment by qsniyg** [comment]
Wow, thank you very much for the detailed explanation and examples!! :) I've implemented it in the following way:

 * Since the URLs aren't (currently) signed, we can modify the format without needing to parse the imageGallery variable. Turns out that `f=0` returns the original version (in the first example, 1408x1386 instead of 1080x*)!
 * It currently parses the DOM to support galleries. If there's a gallery with a bunch of images and it doesn't handle it properly, please let me know! :)

**Comment by nimuxoha** [comment]
> Turns out that f=0 returns the original version
Now I feel kinda stupid :D 

Thanks a lot for the speedy implementation.

**Comment by LemonMeringueTie895** [comment]
They have now changed from rovimusic to allmusic in their directory image links, like here: fastly-s3.allmusic.com/release/mr0001196883/back/400/LWpalZjGqPRvFrwKszIL3t_M69_UI9rrJSVvWL2-yAg=.jpg

If you replace 400 with 1080 in the url you get close to the original, but not the original. 

Any way to get the original front and rear pic of albums on Allmusic now, or no? Hopefully there's a way?

**Comment by LemonMeringueTie895** [comment]
Nice, that's cool. That is a temporary fix at least but it might go down at any time if the rovicorp hosting lapses, unless they are keeping it for a backup. Let's hope they do am I right?

**Comment by LemonMeringueTie895** [comment]
> The old method still works: `https://rovimusic.rovicorp.com/image.jpg?c=LWpalZjGqPRvFrwKszIL3t_M69_UI9rrJSVvWL2-yAg=&f=0`

Nice, that's cool. That is a temporary fix at least but it might go down at any time if the rovicorp hosting lapses, unless they are keeping it for a backup. Let's hope they do am I right?

**Comment by LemonMeringueTie895** [comment]
> The old method still works: `https://rovimusic.rovicorp.com/image.jpg?c=LWpalZjGqPRvFrwKszIL3t_M69_UI9rrJSVvWL2-yAg=&f=0`

This doesn't work anymore. Correct?
