### ISSUE TITLE
[ISSUE] Firefox : Settings page won't load

### ISSUE THREAD

**Issue by iWARR** [qsniyg/maxurl#287]
Tested: Firefox v73.0.1 / v75
OS: Windows 10 / 8.1
Version: v0.12.23

### ISSUE

**Add-ons -> Image Max URL -> Options**

Settings page won't load (endless loading, blank page).

### RESULT

1) Options Loading... (stuck)
2) Missing "Image Max URL" item inside RMB-Menu

**Comment by qsniyg** [comment]
Thanks for reporting the issue! Could you screenshot the console (press F12 and click on the Console tab, there should be some lines in red)? It works on my end with v75...

**Comment by iWARR** [comment]
F12 console shows nothing for me.

Other stuff (many others Add-ons and basic FF functions) working as expected. May be except my last founding with "Temporary containers" bug (to be honest, it's relativee to old FF Cache API and Local storage issue).

I'm using the massive disabling logs inside the FF (same as Telemetry and other nonsese) since FF becomes a half-bloatwared software more and more. The code quality is low. Devs are crazy collecting users data. So I decide disable logs everywere over FF presets. Let FF devs sorry for that (not me).

Feel free asking questions or asking for making some extra testing.
(But I can't provide logs in case of disabled logs and privacy reasons).

I'm not saying that a problem is on your side only. Probably, I have some kind of sensitive preset disabled / tweaked that cause the described issue. However, don't forget, all other stuff I have installed works for me as expected (all other add-ons except "Image Max URL" have healthy Options).

**Comment by qsniyg** [comment]
I've pushed a new commit that should display the information needed (https://github.com/qsniyg/maxurl/commit/41ccb5e05896d760a241fcb2c54fc8bf26152519). To use it, either clone the repository and sideload manifest.json through about:debugging -> This Firefox -> Load Temporary Add-on..., or you can use this build: https://drive.google.com/open?id=1bND01DnPDsC6UZGu_EWX2hMOfjKaxAQ4 (you'll still need to sideload it though).

It will contain the exception that caused the options page to fail loading. Just copy and paste that here (and feel free to redact any information you'd rather not share, although I don't think any private information should be contained, just the user-agent string and the part of the code that failed).

If, however, it still displays loading without showing that, could you check if it works on this page? https://qsniyg.github.io/maxurl/options.html

**Comment by iWARR** [comment]
Beginning from the end of your message:

1) Good news : just after script insallation (Violentmonkey) I can see the Options.

2) Disable script

3) Install sideloaded plugin + manifest

```
response is undefined  ............................................................................................... 48 userscript.user.js:60805
Error: Could not establish connection. ............................................................................... Receiving end does not exist. tabs.js:143:34
Incorrect argument types for contextMenus.update. .................................................................... 20 background.js:1165
Unchecked lastError value: Error: Please set webextensions.storage.sync.enabled to true in about:config .............. 170 background.js:837
Incorrect argument types for contextMenus.update. .................................................................... 6 background.js:1165
sendRemoveListener on closed conduit maxurl@xxxxxx.XXXXXXXXXXXX ...................................................... ConduitsChild.jsm:108
Loading <script> by address «moz-extension://XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/extension/background.js» failed. ... _generated_background_page.html:5:1
Use of nsIFile in content process is deprecated. ..................................................................... 3 NetUtil.jsm:253:8
Error: Could not establish connection. Receiving end does not exist. ................................................. 2 tabs.js:143:34
```
(XXX) - IDs (or whatsoever) were redacted by me in this log

**So I have this setting disabled inside the "user.js" :**
```

// WebExtensions : Sync = [ Disabled ]
/*	[BUG]		The browser.storage.sync API is exposed even when the API is disabled.
			When disabled, this may potentially break saving a settings for some extensions.
	[1]		https://bugzilla.mozilla.org/show_bug.cgi?id=1331179
	[2]		https://forums.informaction.com/viewtopic.php?t=24394     */
user_pref("webextensions.storage.sync.enabled", false);
user_pref("webextensions.storage.sync.serverURL", "");
```

4) Some extra log's entries after restarting browser with sideloaded Add-on:

```
Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. .................. 231 undefined
Error: Content script already unregistered ........................................................................... undefined
Incorrect argument types for contextMenus.update. .................................................................... background.js:1165
Incorrect argument types for contextMenus.update. .................................................................... 5 background.js:1165
Error: Could not establish connection. Receiving end does not exist. ................................................. 4 tabs.js:143:34
Incorrect argument types for contextMenus.update. .................................................................... background.js:1165
Incorrect argument types for contextMenus.update. .................................................................... 3 background.js:1165
Error: Could not establish connection. Receiving end does not exist. ................................................. tabs.js:143:34
Use of nsIFile in content process is deprecated. ..................................................................... 5 NetUtil.jsm:253:8
Error: Could not establish connection. Receiving end does not exist. ................................................. 3 tabs.js:143:34
TypeError: NetworkError when attempting to fetch resource.
```

Seems like switching `webextensions.storage.sync.enabled` doen't have influence on this (quick test).
And I want to keep this disabled on regular basis.

**Settings page won't load (endless loading, blank page).**

**Comment by qsniyg** [comment]
@iWARR Thank you very much! I can reproduce the issue now, by disabling `webextensions.storage.sync.enabled`.

Indeed, the code doesn't properly test for when sync storage is disabled. I'll have to add some more tests to see if it can be used, and rely on local storage if it can't.

**Comment by iWARR** [comment]
Great! I'm happy to be helpful discovering this issue.
And  thak you very much for the cool addon :) Good luck, my friend!

**Comment by qsniyg** [comment]
Thank you very much for reporting, and you're welcome! :) It should be fixed now. The fix is a little flimsy (if the error message change, I might need to update it), but it should work for the moment.
