### ISSUE TITLE
Extend the hotkey support for the addon

### ISSUE THREAD

**Issue by 894-572** [qsniyg/maxurl#30]
Currently only `Shift`, `Ctrl` and `Alt` can be set as the popup hotkeys and all keys interfere with standard computer usage, I constantly experience the webpage background image being opened when typing (for instance on https://steamcommunity.com/). Preferably allow setting any key and combination of keys.

**Comment by qsniyg** [comment]
This is a great idea! I'll add it in soon, but it will require a bit of refactoring to implement so it might take some time.

**Comment by qsniyg** [comment]
This is now implemented in 0.8.24, thanks again for the suggestion!
