### ISSUE TITLE
hovering over danbooru thumbnail doesn't show full image

### ISSUE THREAD

**Issue by nadomodan** [qsniyg/maxurl#304]
https://danbooru.donmai.us/posts?tags=rimukoro

Hovering over thumbnails on page like above opens popup with the same small image, expected to get full original image like it does when hovering on pixiv thumbnails

**Comment by qsniyg** [comment]
Thank you very much, should be fixed now! Turns out that they just added a new domain that IMU didn't support yet :)

**Comment by BrandonKMLee** [comment]
For some notes, currently `https://cdn.donmai.us/360x360/81/17/8117c4c2aabfa25832d4c763b46717a4.jpg` does not jump to the original `https://cdn.donmai.us/original/81/17/8117c4c2aabfa25832d4c763b46717a4.jpg`
