### ISSUE TITLE
Imgur album support for the extension

### ISSUE THREAD

**Issue by 894-572** [qsniyg/maxurl#31]
Imgur albums don't seem to be supported. It's also possible to upload _one image as an album_, you'll often see instances like this around the web: https://www.reddit.com/r/pcgaming/comments/ae98lx/the_division_2_is_regionlocked_to_account_country/
`
https://imgur.com/a/kdTZAjK`

**Comment by 894-572** [comment]
Yes, gallery support of course.

**Comment by qsniyg** [comment]
@894-572 It _kind of_ works now, but admittedly it could be improved. I'll work on that at some point :)

**Comment by qsniyg** [comment]
It should now work completely with 5592e9bdcee50346ce866514d400b1c3a5736525 :) (will be in the next update)
