### ISSUE TITLE
Support tinder

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [qsniyg/maxurl#317]
`if (domain === "images-ssl.gotinder.com") {`
//images-ssl.gotinder.com/5755b8c48be011eaa4b9e755/172x216_75_6e91cc4e-8be0-11ea-8414-37577a564efc.jpg
//images-ssl.gotinder.com/5755b8c48be011eaa4b9e755/172x216_6e91cc4e-8be0-11ea-8414-37577a564efc.jpg
//images-ssl.gotinder.com/5755b8c48be011eaa4b9e755/original_6e91cc4e-8be0-11ea-8414-37577a564efc.jpeg
`\/+[a-z0-9]+\/+([\d]{2,3}x[\d]{2,3})_([\d]{0,2}_)?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.(webp|jpg)`

`if (domain === "preview.gotinder.com") {`

`\/+[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/+([\d]{2,3}x[\d]{2,3})_([\d]{0,2}_)?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.(webp|jpg)`

replace $1
`original`

remove $2 

replace $3
`jpeg`

blurred images dont know howto get original. they give access denied. so excluded:
images-ssl.gotinder.com/3f06c832-8be3-11ea-94fd-c3422c8832aa/84x106_75_6e91cc4e-8be0-11ea-8414-37577a564efc.jpg

_______________________________________________________

2 aspect ratios

Max known:
640x640
640x800

Original 675 x 900  Pixel (3:4):
original_       suffix  jpeg instead of jpg

observed that can be replaced with max or orignal:
172x172
172x216
320x400
84x106
Suffix:		        
jpg,webp
original 
jpeg

Can't add test cases for member only site i guess.

**Comment by qsniyg** [comment]
Thank you very much!! I'll try to find some example images. So far, I found:

https://images-ssl.gotinder.com/5e56e7874136bd01007e48ea/640x800_938a4826-659d-4a9c-b330-3e16c2757c46.jpg -> original + .jpeg works, looks like the image is upscaled

https://images-ssl.gotinder.com/59fb90fe62dab66a0c554a33/1080x1080_415283a5-ae1d-4bfa-81a9-ae04f53130cd.jpg - original + .jpeg doesn't work, but there is 1080x1080 (320x320 works too)

If you could share any example images as well, that would be great! :)

**Comment by qsniyg** [comment]
Should be fixed! :) Please let me know if there are any URLs that don't work though.

For now, it will just aggressively try to use original for them all. I guess it could also be possible to try every known size above the current size as well, but it's possibly upscaled.

**Comment by pikseli3a** [comment]
It doesn't work for me with a 640x800 image that is used as a thumbnail in Tinder's "Share a Profile" shares, such as:

```
What do you think about Jenna? 

https://go.tinder.com/pXYh7WqPSd8-Jenna
```

<img width="946" height="1354" alt="Image" src="https://github.com/user-attachments/assets/6318c574-cf2c-45f1-b0f0-39a9c6f337a7" />

When posting this to Discord, for example, the link generates an embed preview with this image:
https://images-ssl.gotinder.com/6a63510958b6d92f806599c5/640x800_d96360f3-bded-4d77-966f-03727baab64a.jpg

However, I can manually get the original-sized image by replacing the prefix:
https://images-ssl.gotinder.com/6a63510958b6d92f806599c5/original_d96360f3-bded-4d77-966f-03727baab64a.jpg

**Comment by qsniyg** [comment]
@pikseli3a Thanks, fixed!
