### ISSUE TITLE
Disabling "Enable image popup" causes an error in loading the options page

### ISSUE THREAD

**Issue by OmarNamis** [qsniyg/maxurl#322]
I tested using Firefox 76 and Chrome 81, both the userscript and the addon and all of them had the same issue.

If the option "Enable image popup" is set to 'No', the options page will not load and this error message appears instead:

Firefox userscript:
> User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
> Is userscript: true
> Is addon: false
> Image Max URL version: 0.13.2
> Userscript manager: Tampermonkey
> Userscript manager version: 4.10.6112
> TypeError: option_el is null
> fill_requirements@moz-extension://54ecb9d9-2ff3-4d8e-9bb9-445c2618629d/userscripts/Image%20Max%20URL.user.js?id=78a88684-2d6d-4535-b1e9-e636684dcea0:41017:24
> check_disabled_options@moz-extension://54ecb9d9-2ff3-4d8e-9bb9-445c2618629d/userscripts/Image%20Max%20URL.user.js?id=78a88684-2d6d-4535-b1e9-e636684dcea0:41107:23
> do_options@moz-extension://54ecb9d9-2ff3-4d8e-9bb9-445c2618629d/userscripts/Image%20Max%20URL.user.js?id=78a88684-2d6d-4535-b1e9-e636684dcea0:41967:3
> start/<@moz-extension://54ecb9d9-2ff3-4d8e-9bb9-445c2618629d/userscripts/Image%20Max%20URL.user.js?id=78a88684-2d6d-4535-b1e9-e636684dcea0:49717:7
> state_cb@moz-extension://54ecb9d9-2ff3-4d8e-9bb9-445c2618629d/userscripts/Image%20Max%20URL.user.js?id=78a88684-2d6d-4535-b1e9-e636684dcea0:40353:6

Firefox addon:
> User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
> Is userscript: false
> Is addon: true
> Image Max URL version: 0.13.2
> 
> TypeError: option_el is null
> fill_requirements@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:61918:24
> check_disabled_options@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:62008:23
> do_options@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:62868:3
> start/<@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:70618:7
> onload@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:61249:4
> start@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:70616:11
> process_setting/</</<@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:63226:14
> add_value_change_listeners@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:63201:13
> process_setting/</<@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:63225:34
> upgrade_settings_with_version@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:63155:5
> upgrade_settings/<@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:63173:33
> get_value/<@moz-extension://ba04aae1-2480-48c1-8510-eece3baa25b3/userscript.user.js:62921:7

Chrome userscript:
> User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
> Is userscript: true
> Is addon: false
> Image Max URL version: 0.13.2
> Userscript manager: Tampermonkey
> Userscript manager version: 4.10
> TypeError: Cannot read property 'getElementsByClassName' of null
> TypeError: Cannot read property 'getElementsByClassName' of null
>     at fill_requirements (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:41017:34)
>     at check_disabled_options (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:41107:6)
>     at do_options (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:41967:3)
>     at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:49717:7)
>     at onload (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:40348:4)
>     at start (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:49715:5)
>     at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:42325:9)
>     at add_value_change_listeners (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:42314:5)
>     at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:42324:8)
>     at upgrade_settings_with_version (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:42254:3)
>     at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:42272:4)
>     at get_value (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:42027:11)
>     at upgrade_settings (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:42271:3)
>     at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:42323:7)
>     at get_value (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:42027:11)
>     at process_setting (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:42318:5)
>     at do_config (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:42336:5)
>     at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:49776:2)
>     at Window.tms_5e372f8f_93b0_406d_a948_1b1e6d4d4a51 (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:49777:3)
>     at <anonymous>:3:98
>     at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:1:95)
>     at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:1:790)
>     at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:49781:6)
>     at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Image%2520Max%2520URL.user.js&id=5e372f8f-93b0-406d-a948-1b1e6d4d4a51:49783:3)
>     at eval (<anonymous>)
>     at <anonymous>:3:98
>     at Object.c [as F_c] (<anonymous>:2:146)
>     at Object.E_u (<anonymous>:3:267)
>     at la (eval at exec_fn (:1:147), <anonymous>:60:53)
>     at Object.create (eval at exec_fn (:1:147), <anonymous>:71:325)
>     at Object.run (eval at exec_fn (:1:147), <anonymous>:13:205)
>     at eval (eval at exec_fn (:1:147), <anonymous>:73:20)
>     at Array.forEach (<anonymous>)
>     at <anonymous>:3:98
>     at c (<anonymous>:2:146)
>     at eval (eval at exec_fn (:1:147), <anonymous>:73:1)
>     at eval (eval at exec_fn (:1:147), <anonymous>:73:30)
>     at TM_back (eval at exec_fn (:1:147), <anonymous>:74:3)
>     at Object.eval (eval at exec_fn (:1:147), <anonymous>:74:10)
>     at <anonymous>:3:98
>     at Object.exec_fn (<anonymous>:1:145)
>     at <anonymous>:12:365
>     at HTMLDocument.R (<anonymous>:11:134)

**Comment by qsniyg** [comment]
Thank you very much for the report! Could you try using the git master version of the userscript? https://github.com/qsniyg/maxurl/blob/master/userscript.user.js?raw=true

I've just made it provide more information (namely, which setting causes the issue, and adding the user's settings to the crashlog). It might "fix" the issue, but the underlying cause is still not fixed, so there may still be other issues.

Could you attach a screenshot of the browser console (press F12, then go to the Console tab) when going to the options page, once you've updated the userscript? If it doesn't work, can you post the new crashlog, and if it does, can you export the settings (through the "export" button at the top), then paste them here?

**Comment by OmarNamis** [comment]
I tried the master git version and it looks the issue is fixed!

Here's a screenshot of the console:
![image](https://user-images.githubusercontent.com/14346945/81270521-266f5980-904b-11ea-906a-8f34c689f7e4.png)


And here are my settings (pretty much default):

> {"imu_enabled":true,"language":"en","check_updates":false,"check_update_interval":24,"dark_mode":true,"settings_tabs":false,"settings_visible_description":true,"settings_show_disabled":true,"settings_show_requirements":true,"advanced_options":false,"allow_browser_request":true,"use_blob_over_arraybuffer":false,"allow_live_settings_reload":true,"allow_remote":true,"disable_keybind_when_editing":true,"redirect":true,"redirect_history":true,"canhead_get":true,"redirect_force_page":false,"print_imu_obj":false,"redirect_disable_for_responseheader":false,"mouseover":false,"mouseover_open_behavior":"popup","mouseover_trigger_behavior":"keyboard","mouseover_trigger_key":["shift","alt","i"],"mouseover_trigger_delay":1,"mouseover_trigger_mouseover":false,"mouseover_trigger_prevent_key":["shift"],"mouseover_close_behavior":"esc","mouseover_close_need_mouseout":true,"mouseover_jitter_threshold":30,"mouseover_cancel_popup_when_elout":true,"mouseover_cancel_popup_with_esc":true,"mouseover_auto_close_popup":false,"mouseover_auto_close_popup_time":5,"mouseover_use_hold_key":true,"mouseover_hold_key":["i"],"mouseover_hold_position_center":false,"mouseover_close_el_policy":"both","mouseover_close_click_outside":false,"mouseover_allow_partial":"video","mouseover_use_blob_over_data":false,"mouseover_enable_notallowed":true,"mouseover_notallowed_duration":300,"mouseover_minimum_size":20,"mouseover_exclude_backgroundimages":false,"mouseover_exclude_page_bg":true,"mouseover_only_links":false,"mouseover_exclude_sameimage":false,"mouseover_exclude_imagetab":true,"mouseover_video_controls":false,"mouseover_video_controls_key":["c"],"mouseover_video_loop":true,"mouseover_video_playpause_key":["space"],"mouseover_video_muted":false,"mouseover_video_mute_key":["m"],"mouseover_video_volume":100,"mouseover_video_resume_from_source":false,"mouseover_video_seek_amount":10,"mouseover_video_seek_left_key":["shift","left"],"mouseover_video_seek_right_key":["shift","right"],"mouseover_video_seek_vertical_scroll":false,"mouseover_video_seek_horizontal_scroll":false,"mouseover_video_speed_down_key":["["],"mouseover_video_speed_up_key":["]"],"mouseover_video_speed_amount":0.25,"mouseover_ui":true,"mouseover_ui_opacity":80,"mouseover_ui_imagesize":true,"mouseover_ui_zoomlevel":true,"mouseover_ui_gallerycounter":true,"mouseover_ui_gallerymax":50,"mouseover_ui_gallerybtns":true,"mouseover_ui_closebtn":true,"mouseover_ui_optionsbtn":true,"mouseover_ui_downloadbtn":false,"mouseover_ui_rotationbtns":false,"mouseover_ui_caption":true,"mouseover_ui_wrap_caption":true,"mouseover_use_remote":false,"mouseover_zoom_behavior":"fit","mouseover_zoom_custom_percent":100,"mouseover_pan_behavior":"drag","mouseover_movement_inverted":true,"mouseover_drag_min":5,"mouseover_scrolly_behavior":"zoom","mouseover_scrollx_behavior":"gallery","scroll_override_page":false,"scroll_zoom_origin":"cursor","scroll_zoom_behavior":"fitfull","scroll_incremental_mult":1.25,"mouseover_move_with_cursor":false,"mouseover_move_within_page":true,"zoom_out_to_close":false,"mouseover_position":"cursor","mouseover_prevent_cursor_overlap":true,"mouseover_add_link":true,"mouseover_add_video_link":false,"mouseover_download":false,"mouseover_hide_cursor":false,"mouseover_hide_cursor_after":0,"mouseover_links":false,"mouseover_only_valid_links":true,"mouseover_allow_canvas_el":false,"mouseover_allow_svg_el":true,"mouseover_enable_gallery":true,"mouseover_gallery_cycle":false,"mouseover_gallery_prev_key":["left"],"mouseover_gallery_next_key":["right"],"mouseover_gallery_move_after_video":false,"mouseover_styles":"","mouseover_fade_time":100,"mouseover_enable_mask_styles":false,"mouseover_mask_styles2":"background-color: rgba(0, 0, 0, 0.5)","mouseover_mask_fade_time":100,"mouseover_ui_styles":"","mouseover_wait_use_el":false,"mouseover_add_to_history":false,"mouseover_download_key":[["s"],["ctrl","s"]],"mouseover_open_new_tab_key":["o"],"mouseover_open_bg_tab_key":["shift","o"],"mouseover_open_options_key":["p"],"mouseover_rotate_left_key":["e"],"mouseover_rotate_right_key":["r"],"mouseover_flip_horizontal_key":["h"],"mouseover_flip_vertical_key":["v"],"mouseover_zoom_in_key":[["+"],["="],["shift","="]],"mouseover_zoom_out_key":[["-"]],"mouseover_zoom_full_key":["1"],"mouseover_zoom_fit_key":["2"],"mouseover_apply_blacklist":true,"apply_blacklist_host":false,"mouseover_matching_media_types":false,"mouseover_support_pointerevents_none":true,"website_inject_imu":true,"website_image":true,"extension_contextmenu":true,"allow_video":true,"allow_dash_video":false,"allow_hls_video":false,"allow_watermark":false,"allow_smaller":false,"allow_possibly_different":false,"allow_possibly_broken":false,"allow_possibly_upscaled":true,"allow_thirdparty":false,"allow_apicalls":true,"allow_thirdparty_libs":false,"deviantart_prefer_size":false,"imgur_source":true,"instagram_use_app_api":true,"instagram_gallery_postlink":false,"tiktok_no_watermarks":true,"tumblr_api_key":"xrMpLM8n1eCeL3oRYSZG7CLALw6EHhYDdU6Wq5eD1PbMkld7Y1","bigimage_blacklist":"","bigimage_blacklist_engine":"glob","replaceimgs_enable_keybinding":false,"replaceimgs_keybinding":["shift","alt","r"],"replaceimgs_auto":false,"replaceimgs_replaceimgs":true,"replaceimgs_addlinks":false,"replaceimgs_replacelinks":false,"replaceimgs_usedata":true,"replaceimgs_wait_fullyloaded":true,"replaceimgs_totallimit":8,"replaceimgs_domainlimit":2,"highlightimgs_enable_keybinding":false,"highlightimgs_keybinding":["shift","alt","h"],"highlightimgs_enable":false,"highlightimgs_auto":"never","highlightimgs_onlysupported":true,"highlightimgs_css":"outline: 4px solid yellow","last_update_check":1588838020390,"last_update_version":null,"last_update_url":null,"settings_version":5}

**Comment by qsniyg** [comment]
I'm seriously confused as to what the problem might be now haha, I can't reproduce the issue at all, even with the same version of Firefox... Would you mind running the following command in the console for the options page:

`copy(document.documentElement.outerHTML)`

Then pasting it to a text file (or pastebin) and uploading/linking it here? Sorry, I really don't understand why it's not working haha.

**Comment by OmarNamis** [comment]
Here's the code:
[outerHTML.txt](https://github.com/qsniyg/maxurl/files/4592187/outerHTML.txt)

**Comment by qsniyg** [comment]
Thank you!! The issue (I believe) was due to tabbed settings being enabled, and I've managed to fix the issue. That said, if it doesn't work, please let me know!

However, I don't understand why the tabbed settings appear to have been disabled in the exported settings you sent... was it an old export?

**Comment by OmarNamis** [comment]
Indeed, the issue seems to be fixed and there are no more errors in the console.

I didn't think tabbed settings was a factor in this issue, that's why it was disabled in my exported settings as I tried to make my settings as close to default as possible.

Sorry for the trouble! and thanks for your effort.

**Comment by qsniyg** [comment]
Ah good to know! I thought there was some kind of bug in the exporting code haha :)

No worries, and thank you very much for reporting!!
