### ISSUE TITLE
Support for pixiv ?

### ISSUE THREAD

**Issue by bokunodev** [qsniyg/maxurl#323]
is this support Pixiv website ?
i didnt see pixiv listed in the list.

**Comment by qsniyg** [comment]
It is! :)

The reason it isn't in the list is because only the image domains (`i.pximg.net` and `tc-pximg01.techorus-cdn.com`) need to be supported, usually the host website (`pixiv.net`) doesn't need any special code for supporting their images (exceptions being sites like Instagram and Tumblr) :)
