### ISSUE TITLE
Script hangs when trying to parse a thumbnail of an Upcoming Premiere YouTube video

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#326]
Example: https://i.ytimg.com/vi/mpvQhQIP1sU/maxresdefault.jpg (from vid: https://www.youtube.com/watch?v=mpvQhQIP1sU)

Well not really hangs, but it spat out bunch of errors and the cursor icon got stuck as "waiting".

**Comment by qsniyg** [comment]
Thank you very much for reporting! Fixed now :)
