### ISSUE TITLE
booth.pximg.net: some image has larger png version

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#33]
Example:

https://booth.pximg.net/30cd84bf-4155-491d-abee-5770b2947e00/i/1236274/0df91fe3-7ce5-41ad-89f8-a6a52625e752_base_resized.jpg

This doesn't redirect which I assume it because `0df91fe3-7ce5-41ad-89f8-a6a52625e752.jpg` returns 404; but it has a larger version at `0df91fe3-7ce5-41ad-89f8-a6a52625e752.png`.

(Keep in mind that's not the case for all the images: some do only have JPEG original image. [Example](https://booth.pximg.net/users/30729/icon_image/8036b56a-897e-44ec-a192-aa418b9df730_base_resized.jpg). So I'm not sure if it's easy to implement it.)

**Comment by qsniyg** [comment]
Thank you very much for reporting it! Fixed in the repo, it'll be part of the next update :)
