### ISSUE TITLE
Please support this site

### ISSUE THREAD

**Issue by liraqb** [qsniyg/maxurl#337]
Example: https://apps.qoo-app.com/app/6681

I want the largest image of the APP icon and introduction image.

If the number at the end of the image url is changed to `4000` or `9999`, the largest image will be loaded.

By the way, in the README of the project homepage, the link of Greasyfork should be changed from `https://greasyfork.org/en/scripts/36662-image-max-url` to `https://greasyfork.org/scripts/36662-image-max-url` so that the website automatically selects the local language.

**Comment by qsniyg** [comment]
Thanks, it's supported now! Looks like it's just a proxy for one of Google's image servers (I guess the google play one?), so I just added it to that rule, adding `=s0?imgmax=0` seems to work fine!

Good idea about the Greasyfork link, I'll fix that right away, thanks again!
