### ISSUE TITLE
Add webnewtype

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#34]
`https://webnewtype.com/rsz/S1/182540/1085543.jpg/w600h450/` -> `https://webnewtype.com/rsz/S1/182540/1085543.jpg`

Basically any image on https://webnewtype.com/ will follow this rule, such as the one on https://webnewtype.com/news/article/182559/

**Comment by qsniyg** [comment]
Thank you! I've implemented it in :) Unfortunately, a HEAD request will return 404, which means it cannot check if the resulting URL is correct, but hopefully the rule is strict enough to not fail.
