### ISSUE TITLE
TypeError: can't access dead object (if Allowing showing partially loaded not allowed)

### ISSUE THREAD

**Issue by Carl-Robert** [qsniyg/maxurl#349]
Hey,

I'm using this userscript in Pale Moon 28.9.3 64-bit browser with Greasemonkey 3.31.4 (newest supported version). The script works just fine if use new-tab instead of a pop-up. 

With pop-up I get the following error messages to the browser console while mouse-over thumbnails:
```
TypeError: can't access dead object Image_Max_URL.user.js:695:27
"Trying {image-url-here} Image_Max_URL.user.js:45262:3
```
Opening those lines in the debugger shows for TypeError:
`							newresp.response = new native_blob([resp.response], blob_options);`

Just unsupported combination or is there something I can try to fix it? The hour-glass icon stays visible, but nothing happens even if wait.
Edit: Replacing images fails similarly.

EDIT 2: Changing "Allowing showing partially loaded" to Media fixes the pop-up!

**Comment by qsniyg** [comment]
Thank you for reporting! I've (kind of) fixed the issue now, but the root cause (objects found under iframes cannot be accessed once the iframe is removed) still lingers, I'll have to implement a proper fix for it at some point :)
