### ISSUE TITLE
Find larger images on jaxsta.com

### ISSUE THREAD

**Issue by nimuxoha** [qsniyg/maxurl#352]
One of the easy sites :)
Removing the `d` parameter should be enough to get the hi-res image

Release pages:
https://jaxsta.com/release/36bf1f4e-48ab-43f9-a501-fe0eec6180ec/3529ba14-dcde-4e9f-919a-26100bd5b016/overview

https://artwork.jaxsta.com/550/18UMGIM52273_T1_cvrart.jpg?d=85x85
https://artwork.jaxsta.com/550/18UMGIM52273_T1_cvrart.jpg

Profile pages:
https://jaxsta.com/profile/22d59ccb-2d98-4d68-a763-669ce30ba694/catalogue

https://artwork.jaxsta.com/995/e6c1a3ee-e276-4bd7-8c86-d1784df93b13.png?d=85x85
https://artwork.jaxsta.com/995/e6c1a3ee-e276-4bd7-8c86-d1784df93b13.png

BTW, the number of the first directory on the artwork host seems to refer to distributors:
https://jaxsta.com/profile/f58b02fd-136e-4309-85d9-229c87a0f2a2/catalogue
https://artwork.jaxsta.com/995/VirginEMIRecords.png

https://jaxsta.com/profile/c0299465-3495-467a-9bab-0057ce15e0c9/catalogue
https://artwork.jaxsta.com/550/c0299465-3495-467a-9bab-0057ce15e0c9.jpg

**Comment by qsniyg** [comment]
Thank you! It should be supported now :)
