### ISSUE TITLE
No longer works on deviantart images

### ISSUE THREAD

**Issue by spectrefps** [qsniyg/maxurl#36]
As of yesterday, deviantart images are no longer affected by this script (and remain the default "-fullview" lower-res size/quality assigned by deviantart/wixmp). I noticed, when opening them in a new tab, that the new tab no longer refreshes/reloads with the higher/max resolution & quality. Attempting to edit the dimensions or quality in the URL results in an "unauthorized" error page.

For example:
https://www.deviantart.com/raikoart/art/Riven-790761430

Behavior BEFORE:
(in chrome)
Click on image to zoom until max zoomed > right click > open in new tab >image opens in new tab (default "-fullview" low-res version > after a second, script reloads image w/ larger dimensions + higher quality

Behavior NOW:
Click on image to zoom until max zoomed > right click > open in new tab >image opens in new tab (default "-fullview" low-res version > script does not reload image, instead is mouse cursor is constantly 'loading' when in the new tab

Tried enabling/disabling tampermonkey, Image Max url, restart chrome, no good.

The Firefox plugin *appears* to be working normally however, so perhaps it is a chrome-specific issue?

EDIT: Nevermind, the firefox extension no longer reloads deviantart images with their larger/full res versions either now. Just had it work on one image, and no more after that (using the shift+control key to bring up a popup just displays an endless loading cursor on the mouse).

**Comment by qsniyg** [comment]
Thanks for letting me know! Turns out there was an infinite loop bug with DeviantArt, and possibly other rules as well, I've fixed it in the latest commit. It also fixes other possible websites with that issue.

**Comment by spectrefps** [comment]
Wow! That was an incredibly fast response and fix! Much appreciated!

**Comment by spectrefps** [comment]
Uh oh! Just updated to ver. 0.8.22 and *it now redirects to the smaller, 'preview' version of images* (smaller dimensions/lower quality and has the "-pre" suffix to the filename vs. the "-fullview" suffix).

**Comment by qsniyg** [comment]
@spectrefps Darn I was afraid that was going to happen. Could you send a link of a problematic image?

**Comment by spectrefps** [comment]
Ok, here is a link to one (tried a bunch of different images with only a "-fullview" version and no Download button):

(hope you don't have a fear of spiders XD)

https://www.deviantart.com/rynkadraws/art/Lolth-the-Spider-Queen-348363543

**Comment by qsniyg** [comment]
@spectrefps Thanks! I've kind of fixed it. It's not perfect, but it'll at least try to find the largest version available, which fixes the image you linked.

Later I'll try to implement a proper comparison algorithm which might fix some edge cases. If you happen across another image that's scaled down, please let me know!
