### ISSUE TITLE
Find larger images on samplerinfos.de

### ISSUE THREAD

**Issue by nimuxoha** [qsniyg/maxurl#361]
Yet another site with cover art. Unfortunately entries don't have their own pages so you might need to scroll a bit or use <kbd>CTRL</kbd> + <kbd>F</kbd>

If you are not logged in only a small version of the back is displayed and should a larger version exist it shows this notice:
> Wenn Sie sich einloggen, wird dieses Cover in einer besseren Qualität angezeigt.

Example where larger version exists:
0600753277201: https://samplerinfos.de/serie/4050/0
https://samplerinfos.de/covers/4050/big_40502270b.jpg?1577984564

There are also thumbnails versions:
https://samplerinfos.de/covers/4050/th_40502270b.jpg?1577984564

Omitting `big_` returns the small version. If a larger version doesn't exist you get a 404.
`f` and `b` seem to be shorthands for front and back. I have yet to find an entry with more than 2 images.
I'm not sure what relevance the numbers in the query string have though leaving them out doesn't seem to break anything.

Front image is always embedded big when available regardless of login status **on Coveransicht**.
In other views it may not, e.g. **Alle Frontcovers**:
https://samplerinfos.de/serie/0031/The_Dome

Note: That site uses frames and some overlays don't work properly (notably "Alle Frontcovers") unless you use the site as intended. In that case click on the box saying: "bitte hier klicken zum Neuladen der Seite"

**Comment by qsniyg** [comment]
Wow, thank you for the super detailed explanation!! I believe the commit I did should be able to handle most of the site, I've also looked around in google images to find a few other rules for it.

If it's missing anything though, please let me know! :)
