### ISSUE TITLE
Find larger images on imagery.zoogletools.com

### ISSUE THREAD

**Issue by nimuxoha** [qsniyg/maxurl#363]
Often embedded on Bandzoogle sites. Example from https://jrharbidge.com/press-media

Original: https://imagery.zoogletools.com/u/243801/88f8a590bc091005ed1823c00dca5bc173e97c89/original/rnr-interview.jpg

Variations:
https://imagery.zoogletools.com/u/243801/88f8a590bc091005ed1823c00dca5bc173e97c89/thumb/rnr-interview.jpg
https://imagery.zoogletools.com/u/243801/88f8a590bc091005ed1823c00dca5bc173e97c89/thumbnail/rnr-interview.jpg
https://imagery.zoogletools.com/u/243801/88f8a590bc091005ed1823c00dca5bc173e97c89/small/rnr-interview.jpg
https://imagery.zoogletools.com/u/243801/88f8a590bc091005ed1823c00dca5bc173e97c89/medium/rnr-interview.jpg
https://imagery.zoogletools.com/u/243801/88f8a590bc091005ed1823c00dca5bc173e97c89/large/rnr-interview.jpg
https://imagery.zoogletools.com/u/243801/88f8a590bc091005ed1823c00dca5bc173e97c89/photo/rnr-interview.jpg

The `original` image and `photo`  variation can also be found on `https://s3.amazonaws.com/content.sitezoogle.com/` and `http://content.sitezoogle.com/`: https://s3.amazonaws.com/content.sitezoogle.com/u/243801/88f8a590bc091005ed1823c00dca5bc173e97c89/original/rnr-interview.jpg
https://s3.amazonaws.com/content.sitezoogle.com/u/243801/88f8a590bc091005ed1823c00dca5bc173e97c89/photo/rnr-interview.jpg
http://content.sitezoogle.com/u/243801/88f8a590bc091005ed1823c00dca5bc173e97c89/original/rnr-interview.jpg
http://content.sitezoogle.com/u/243801/88f8a590bc091005ed1823c00dca5bc173e97c89/photo/rnr-interview.jpg

`small` and `thumb` seem to be synonymous. There might be more keywords but those are all I could find.

**Comment by qsniyg** [comment]
Thanks as always for the super detailed report!! I've updated the rule, it should work properly now :)
