### ISSUE TITLE
Famitsu.com rule improvement

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#364]
Currently the rule doesn't match images like

https://www.famitsu.com/images/000/160/712/5b46f32b76a9a.jpg
(Largest version: https://www.famitsu.com/images/000/160/712/z_5b46f32b76a9a.jpg).

From: https://www.famitsu.com/news/201808/06160712.html

**Comment by qsniyg** [comment]
Thank you! Yeah I forgot to test for no prefix, should be fixed now :)
