### ISSUE TITLE
Not working on VGMdb

### ISSUE THREAD

**Issue by DesertStars** [qsniyg/maxurl#371]
I'm using the Firefox Extension version but it doesn't work on VGMdb for some reason. For example, ideally the extension should redirect me from https://medium-media.vgm.io/albums/32/36823/36823-1357394776.jpg (resized image) to https://media.vgm.io/albums/32/36823/36823-1357394776.jpg (untouched image) but I have to do it manually if I want to get the original resolution. I've checked my blacklist to see if I accidentally put VGMdb in there but no luck there.

I can reproduce the issue on https://qsniyg.github.io/maxurl/ as well.

Browser is Firefox 78.0.1, I also updated the extension to see if it's fixed in the latest version but it's still there.

**Comment by qsniyg** [comment]
Oops, thank you very much for reporting! I didn't know they had the `medium-media` domain, fixed! :)

**Comment by DesertStars** [comment]
Glad I could be any help, thanks for fixing it so quickly.
