### ISSUE TITLE
Fails to download videos of instagram multi-entry posts

### ISSUE THREAD

**Issue by aker2** [qsniyg/maxurl#376]
When multi-entry posts contain videos in other than first position the corresponding freeze frame is fetched instead of the video.

**Comment by qsniyg** [comment]
Oops, thanks! I added an optimization a while back to avoid querying when not necessary, but I clearly forgot about albums haha. Fixed!

**Comment by aker2** [comment]
Wow, thanks, that was quick. Looking forward to the new release.

**Comment by qsniyg** [comment]
You're welcome! They usually tend to be weekly, unless there's a serious regression (which has happened more frequently than I'd like to admit... :)

In the meantime though, you can either sideload it from github, or open the post in a new tab, which should work without issue without the patch.

**Comment by aker2** [comment]
Thanks for info and the workaround (which I should have found out by myself). By the way: Great script.
