### ISSUE TITLE
omny.fm

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#386]
`https://omny.fm/shows/douse/ep-153/image.jpg?t=1596591781&size=Small` -->

`https://omny.fm/shows/douse/ep-153/image.jpg?t=1596591781`

Source page: https://omny.fm/shows/douse

Edit: removing all parameters (`https://omny.fm/shows/douse/ep-153/image.jpg`) redirects you to `https://omny.fm/shows/douse/ep-153/image.jpg?t=1596591781&size=Original`), which appears to be the same as without `size` query.

**Comment by qsniyg** [comment]
Thank you very much!!

Interesting! Some more URLs:

https://omny.fm/shows/the-kieno-kammies-show/saa-to-appoint-ceo-by-end-march/image.jpg?t=1490334380&size=Large -- 2048x2048

https://omny.fm/shows/the-kieno-kammies-show/saa-to-appoint-ceo-by-end-march/image.jpg?t=1490334380 -- 150x200

https://omny.fm/shows/the-kieno-kammies-show/saa-to-appoint-ceo-by-end-march/image.jpg?t=1490334380&size=Original -- 150x200

https://omny.fm/shows/bill-kelly-show/what-are-the-public-s-thoughts-on-hamilton-s-first/image.jpg?t=1472736373&size=WideShare -- 1200x630

https://omny.fm/shows/bill-kelly-show/what-are-the-public-s-thoughts-on-hamilton-s-first/image.jpg?t=1472736373&size=Original -- 2048x3641

https://omny.fm/shows/bill-kelly-show/what-are-the-public-s-thoughts-on-hamilton-s-first/image.jpg?t=1472736373 -- 2048x3641

https://omny.fm/shows/bill-kelly-show/what-are-the-public-s-thoughts-on-hamilton-s-first/image.jpg?t=1472736373&size=asdf -- 2048x3641

https://omny.fm/shows/bill-kelly-show/what-are-the-public-s-thoughts-on-hamilton-s-first/image.jpg?t=1472736373&size=Large -- 2048x2048

https://omny.fm/shows/am640-the-morning-show/image.jpg?t=1544205962&size=Large -- 3000x3000

https://omny.fm/shows/am640-the-morning-show/image.jpg?t=1544205962 -- 3000x3000

As you said, `size=Original` seems to be the same as without, and also the same as if it's a nonsense value.

I've just implemented it as a simple rule to replace the `size` query parameter, as it's probably the simplest way to support it :)

**Comment by fireattack** [comment]
@qsniyg new domain for this site:

https://www.omnycontent.com/d/programs/67122501-9b17-4d77-84bd-a93d00dc791e/e9c977c0-eb88-4444-b8d6-ab7600454421/image.jpg?t=1584608243&size=small
->
https://www.omnycontent.com/d/programs/67122501-9b17-4d77-84bd-a93d00dc791e/e9c977c0-eb88-4444-b8d6-ab7600454421/image.jpg?t=1584608243

**Comment by qsniyg** [comment]
@fireattack Thanks! Updated
