### ISSUE TITLE
Support shop.new-art.nl

### ISSUE THREAD

**Issue by anonyno** [qsniyg/maxurl#390]
This is used as the CDN for ecmrecords.com.

For example, if you click view image from [this page](https://www.ecmrecords.com/catalogue/1580225075) you are taken to <https://shop.new-art.nl/assets/image.php?width=800&image=/content/img/new_products_queue/1581692709.jpg>. If you increase the width parameter in the URL you can make the image go up to the maximum size. Usually 3000 is the maximum size but I've only tested a few albums.

**Comment by qsniyg** [comment]
Thank you very much! Actually it turns out that the path can just be joined to the domain, so: https://shop.new-art.nl/content/img/new_products_queue/1581692709.jpg :)
