### ISSUE TITLE
Give out PNG links for iTunes JPEG input

### ISSUE THREAD

**Issue by a-vrma** [qsniyg/maxurl#393]
A link like <https://is1-ssl.mzstatic.com/image/thumb/Music62/v4/1c/1e/0d/1c1e0d2c-81c3-3658-90b3-728403ac8822/source/999999999x0w-999.jpg> compresses the image to JPEG at quality level 100. But if we do <https://is1-ssl.mzstatic.com/image/thumb/Music62/v4/1c/1e/0d/1c1e0d2c-81c3-3658-90b3-728403ac8822/source/999999999x0w.png> then we will get a losslessly compressed image which might have less artifacts.

They definitely aren't the same image, running `magick compare -metric ae coop.png coop.jpg /dev/null` gives me 2.09749e+06, which means that many pixels differ. On the other hand I can't see any difference using my eyes, which is probably because JPEG compression at quality 100 is [near lossless](https://stackoverflow.com/questions/7982409/is-jpeg-lossless-when-quality-is-set-to-100), even for text which JPEG is supposed to be bad at compressing.

Do you think we should give out PNG links, since they are technically higher quality?

**Comment by qsniyg** [comment]
Ah that's a great point, thanks for bringing this up!! Yeah, the difference is [very subtle](https://i.imgur.com/Dcs1rN5.png) (this was after bringing up the brightness to absurd amounts), but yeah why not! :)

It'll default to PNGs, and fall back to JPGs if it fails for whatever reason.
