### ISSUE TITLE
hellofresh

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#399]
`https://img.hellofresh.com/f_auto,fl_lossy,q_auto,w_360/hellofresh_s3/image/5f0619e1899ede042d77d003-0d509f38.jpg`

from `https://www.hellofresh.com/plans/`

**Comment by qsniyg** [comment]
Thank you!! I should probably figure out a way to make the cloudinary rule at least somewhat generic... only problem is that it'll probably be incomplete in order to prevent the rule being overreaching...
