### ISSUE TITLE
Script fails to run

### ISSUE THREAD

**Issue by 501stRookie** [qsniyg/maxurl#4]
I recently found this script and installed it using Tapermonkey on Google Chrome. However, when I try to open an image in a new tab, nothing happens.

**Comment by qsniyg** [comment]
Which image are you trying to view?

**Comment by 501stRookie** [comment]
I found this script via the Reddit bot MaxImageBot. It found a larger version of the image in the post, so I tested the script using the same image.

This is the image
http://3.bp.blogspot.com/-9X2M416XVSA/UGJE1LOzZ2I/AAAAAAAAuuk/Xoi9OZiBbyM/s400/Donkey+luftwaffe+funny+german+nazi.jpg

The post/bot
https://www.reddit.com/r/shittytechnicals/comments/8giosc/german_ww2_anti_tank_donkey/dybxrro/?context=3

**Comment by qsniyg** [comment]
Ah I see the problem now, you're most likely using GreaseMonkey? They killed support for old-style scripts, deprecating them for newer APIs (which are more efficient, but only work on newer browsers). I'll work on a shim to hopefully get both to work without requiring newer browsers.

**Comment by qsniyg** [comment]
@bbtora I'm very sorry for not responding earlier (more than a year later..), I must have forgotten to reply. Could you confirm if this is still an issue with 0.10.1?

**Comment by bbtora** [comment]
I don't see a problem now. It must've been fixed a long time ago.
