### ISSUE TITLE
Greasyfork's 2MB limit

### ISSUE THREAD

**Issue by qsniyg** [qsniyg/maxurl#40]
The base userscript is now more than 2MB, which prevents it from being able to be on Greasyfork.

The current solution is to [strip comments](https://github.com/qsniyg/maxurl/blob/master/remcomments.js), which brings it down to <1MB.

**Comment by rEnr3n** [comment]
Does openuserjs have similar limit?

**Comment by qsniyg** [comment]
[Seems like the default is 1MB](https://github.com/OpenUserJS/OpenUserJS.org/blob/b2c69c6ffeaaa7d12748b6a58a256b61560c2fc5/models/settings.json#L4)

**Comment by rEnr3n** [comment]
I guess you'll have to start informing users about this in some way.

**Comment by qsniyg** [comment]
@rEnr3n It's not yet an issue, as removing comments has brought it down to <1MB, it'll likely be at the 4000-5000 rule mark that I'll need to start worrying. That'll probably be in a few years at this pace haha (currently 2400 rules).

**Comment by qsniyg** [comment]
Closing as the userscript has been deleted from GF.
