### ISSUE TITLE
New rule request: lapisrelights.com

### ISSUE THREAD

**Issue by jloqfjgk** [qsniyg/maxurl#408]
#### Summary
https://www.lapisrelights.com is the official webpage for _Lapis Re:LiGHTs_, a Japanese multimedia franchise.

For some of the images on that website, there is a larger version available.

#### Example
On https://www.lapisrelights.com/news/2339/:
Lower resolution version image URL: https://www.lapisrelights.com/assets/img/uploads/2020/08/lapis_crossword_thumb2-1024x576.jpg
Larger version (1920x1080) image URL: https://www.lapisrelights.com/assets/img/uploads/2020/08/lapis_crossword_thumb2.jpg

**Comment by qsniyg** [comment]
Thank you!! As far as I can tell (browsed through the site a little), it's just a matter of removing the -???x??? at the end of the URL, but let me know if there are any images that don't work with this :)
