### ISSUE TITLE
add domain using uploadcare resizing

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#412]
`https://uploadcare.com/docs/transformations/`

May I suggest commenting that URL or the name "uploadcare" in the userscript for organization/documentation purposes?

URL:
```
https://images.universe.com/87135321-9b85-480d-a4f1-8d526b879789/-/scale_crop/972x389/-/quality/lightest/-/progressive/yes/-/format/webp/-/inline/yes/ => https://images.universe.com/87135321-9b85-480d-a4f1-8d526b879789/
```

**Comment by qsniyg** [comment]
Thank you!!

It seems like a bunch of websites use uploadcare (or maybe uploadcare uses a core engine that a bunch of other websites use?)... I should probably reorganize the rules a little so that it becomes clearer that it is the source.
