### ISSUE TITLE
New rule request: static.mercdn.net

### ISSUE THREAD

**Issue by jloqfjgk** [qsniyg/maxurl#413]
#### Summary
static.mercdn.net is used by Mercari Japan.

Thumbnail images (on search results page) have a larger version available.

#### Example
Lower resolution version image URL: https://static.mercdn.net/c!/w=240/item/detail/orig/photos/m81805157460_1.jpg?1598779743
Larger version image URL: https://static.mercdn.net/item/detail/orig/photos/m81805157460_1.jpg?1598779743

**Comment by qsniyg** [comment]
Thank you!! I've added it here: https://github.com/qsniyg/maxurl/commit/8f4213777a69934016aaa8bda765f4969f716995

Interestingly, it uses the same system that pixiv uses... I wonder if it's some kind of generic system licensed to them, or they're in some way related?
