### ISSUE TITLE
improve bytedance rule

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#426]
(wouldn't it be better to add `*.tiktokcdn.com`?)

(1) Subdomain `p16-amd-va.tiktokcdn.com`  -- used for profile photos (web and app):
```
https://p16-amd-va.tiktokcdn.com/img/musically-maliva-obj/d8bcd7b974df059dd548e98a39b705d9~c5_100x100.jpeg
```

Can be changed to any of the following:
```
https://p16-amd-va.tiktokcdn.com/img/musically-maliva-obj/d8bcd7b974df059dd548e98a39b705d9~noop.image
https://p16-amd-va.tiktokcdn.com/img/musically-maliva-obj/d8bcd7b974df059dd548e98a39b705d9~c5.jpeg
https://p16-amd-va.tiktokcdn.com/img/musically-maliva-obj/d8bcd7b974df059dd548e98a39b705d9~99999x99999.jpeg
https://p16-amd-va.tiktokcdn.com/origin/musically-maliva-obj/d8bcd7b974df059dd548e98a39b705d9.jpeg (is this best?)
```

(2) Subdomain `p16-sign-va.tiktokcdn.com`-- used for video thumbnails and some profile pics (below url from app):

```
https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068/3cc29b70b9ed45d1b86f5a525da02f13_1598931018~tplv-tiktokx-360p.image?x-expires=1599033600&x-signature=%2BJAF%2BVz2hXai0gjnYm6R97lLk7c%3D
```

Can be changed to any of the following:
```
https://p16-amd-va.tiktokcdn.com/tos-maliva-p-0068/3cc29b70b9ed45d1b86f5a525da02f13_1598931018~noop.image
https://p16-amd-va.tiktokcdn.com/tos-maliva-p-0068/3cc29b70b9ed45d1b86f5a525da02f13_1598931018~c5.jpeg
https://p16-amd-va.tiktokcdn.com/tos-maliva-p-0068/3cc29b70b9ed45d1b86f5a525da02f13_1598931018~99999x99999.jpeg
https://p16-amd-va.tiktokcdn.com/origin/tos-maliva-p-0068/3cc29b70b9ed45d1b86f5a525da02f13_1598931018.jpeg
```

Signed profile picture example from the website: `https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/6efe4666ac0588c4c3df91ca6774ffae~c5_100x100.jpeg?x-expires=1599102000&x-signature=KeZZ4ryQA%2FMFgoKhOpGpYmhSz0s%3D`

Caveat -- if it's served without extension it's already at max res (I think) and the above tricks fail. For example this URL (from website):
```
https://p16-sign-va.tiktokcdn.com/obj/tos-maliva-p-0068/af3de2fba1d14be1acec66e680ace0f0?x-expires=1599188400&x-signature=46nLVCmcHczpmYo4rev%2FJRILYso%3D
```

(3) `p16-sign-sg.tiktokcdn.com`
Example URLs:
```
https://p16-sign-sg.tiktokcdn.com/aweme/300x400/v0201/351a548f244242b083bd25ad4694f1fa.jpeg?x-expires=1599037200&x-signature=zWvZpPwroz0zMoF%2Fu5amBRicWEI%3D
https://p16-sign-va.tiktokcdn.com/obj/tos-maliva-p-0068/3c666aa393714922b10def1ee39ad780_1599009621?x-expires=1599184800&x-signature=zlebXO%2FNyq0PKG3BN%2FctFLpI%2BmI%3D
```

Larger:
```
https://p16-amd-va.tiktokcdn.com/origin/v0201/351a548f244242b083bd25ad4694f1fa.jpeg
https://p16-amd-va.tiktokcdn.com/origin/tos-maliva-p-0068/3c666aa393714922b10def1ee39ad780_1599009621
```

(4) Subdomains of `ibytedtos.com`
(url tricks from number 1 apply)
Example URLs: 
```
https://sf-tb-sg.ibytedtos.com/img/ttfe-malisg/tiktok_web/store-badge/en.png~296x0.webp
http://sf16-muse-va.ibytedtos.com/img/tos-maliva-p-0000/e5cd91966a794433a1f0f846b12fb0df~500x500.image
```

(5) Unusual case of `byteimg.com` (found on `feishu.cn`)
```
https://p1-hera.byteimg.com/tos-cn-i-jbbdkfciu3/753f819c23db45ca9c505a4d073657f6~tplv-jbbdkfciu3-webp:720:436.webp
https://p6-hera.byteimg.com/tos-cn-i-jbbdkfciu3/0792f29e59ae41238c7f9f93333aee40~tplv-jbbdkfciu3-webp:960:600.webp
```
change to
```
https://p1-hera.byteimg.com/tos-cn-i-jbbdkfciu3/753f819c23db45ca9c505a4d073657f6~tplv-jbbdkfciu3-webp:0:0.webp
https://p6-hera.byteimg.com/tos-cn-i-jbbdkfciu3/0792f29e59ae41238c7f9f93333aee40~tplv-jbbdkfciu3-webp:0:0.webp
```

There are probably more but I don't want to waste hours before I even open the issue, if I find anything more I'll leave it in a comment.

**Comment by qsniyg** [comment]
Wow, thank you very much for sharing all this research!!

I'll take a closer look and implement it tomorrow, but here are some notes I have (mostly just notes to self, but feel free to reply to any if you want):

 * I agree, the whole domain situation isn't great, as tiktok keeps changing its domains. I'm not sure what an elegant solution would be though, as it needs to be strict-ish for it to not be applied on video domains, as well as the signature thing you mentioned (and possibly other reasons I'm currently too tired to remember for the moment haha)
   * That being said, every example domain I have begin with either `pb?[0-9]+` or `i[0-9]+`... perhaps `^[pi][a-z]?[0-9]+` might be good enough? I _believe_ every video domain begins with `v[0-9]+` as well.
   * It doesn't fix the signing issue, but that could perhaps be detected by looking at the query strings? How then does it know which domain to redirect it to? Perhaps a table?
 * The signed URL you sent also works when turned into `-amd`: http://p16-amd-va.tiktokcdn.com/img/tos-maliva-p-0068/af3de2fba1d14be1acec66e680ace0f0~noop.jpeg , but `/img/` needs to be added after the domain for it to work
 * The webp one is indeed strange, thanks for sharing! I can't yet find a way to turn it into `~noop` or similar. The `:0:0` trick looks great though! I guess the plan is then to implement that, and if a `~noop` or `origin` trick is later found, then default to that instead, and use the `:0:0` as a fallback

**Comment by lnp5131** [comment]
There seems to be compression artifacts in the non-origin versions while none in the origin version. I also see perhaps a slight reduction in the color space.

As for 
```
https://p16-sign-va.tiktokcdn.com/obj/tos-maliva-p-0068/af3de2fba1d14be1acec66e680ace0f0?x-expires=1599188400&x-signature=46nLVCmcHczpmYo4rev%2FJRILYso%3D
```
A few minor tweaks like sign to amd and adding origin similar to what qsniyg said. This change seems to be universally applicable on the domain.
```
https://p16-amd-va.tiktokcdn.com/origin/tos-maliva-p-0068/af3de2fba1d14be1acec66e680ace0f0.jpeg
```
This can also be applied on 
```
https://sf-tb-sg.ibytedtos.com/img/ttfe-malisg/tiktok_web/store-badge/en.png~296x0.webp
```
Changing it to
```
https://sf-tb-sg.ibytedtos.com/origin/ttfe-malisg/tiktok_web/store-badge/en.png
```
Also this has some issues involving the other ways like replacing origin and changing nothing else or removing ~500x500 without changing img
```
http://sf16-muse-va.ibytedtos.com/img/tos-maliva-p-0000/e5cd91966a794433a1f0f846b12fb0df~500x500.image
```
But it can work like this.
```
http://sf16-muse-va.ibytedtos.com/origin/tos-maliva-p-0000/e5cd91966a794433a1f0f846b12fb0df.png
```

Another note is that the webp version has some nuances. When using `:0:9999` or some large value yields a far sharper image than `:0:0`. It may be that they run image upscalers. (Adding an extra 9 would run into resource allocation problems) Also, you can add `/img/` to this. If there is a way to get the origin then that would be preferred. 

This would match all the links above and the ones I have here if we want to do it restrictively. This may involve a fair bit of upkeep though. I'm wondering would it be too different to try to append `origin` or replace `img` for `origin` on all these links in a generic way and remove everything at and after ? or ~ and replace it with .png to preserve transparency. 
```http(s)?\:\/\/(p[0-9]+\-(amd|sign)\-(va|sg)\.tiktokcdn|sf[0-9]*\-(tb\-sg|muse\-va)\.ibytedtos)\.com\/(origin|img|obj|aweme)?(\/[0-9]+x[0-9]+\/)?(\/?(tos-maliva-p-[0-9]+|musically\-maliva\-obj|ttfe-malisg\/tiktok\_web\/store-badge|[a-z][0-9]+)+)(\/.+)?```

**Comment by qsniyg** [comment]
I decided to basically rewrite the rule. It still has some ways to go (for example, using `.png` for all images as @lnp5131 suggested), but so far it works for all the example links given. 

It's still a little bit hacky, for example, adding `/origin/` to `https://p16-amd-va.tiktokcdn.com/tos-maliva-p-0068/3cc29b70b9ed45d1b86f5a525da02f13_1598931018~noop.image` requires testing for `/tos-maliva-`, which is probably a bit too strict (I added this check in order to avoid it redirecting the strange webp examples, which fail).

As with the last version with the rule, I implemented it layered, so that it will return multiple valid URLs, the last of which will be the highest quality (/origin/), but earlier ones are also (possibly) more likely to succeed.

Thank you very much again to both for sharing your research regarding this!! :D It's definitely a rather tricky system haha

**Comment by llacb47** [comment]
Not sure if I'm doing something wrong but it doesn't work here: `https://p16-sign-va.tiktokcdn.com/musically-maliva-obj/1663656694255621~c5_100x100.jpeg?x-expires=1599156000&x-signature=nStsWM6ZtewLuGlGbLp5N9o6MTg%3D`

**Comment by qsniyg** [comment]
@llacb47 Fixed, thanks! Yeah that's what I was mentioning about with `/tos-maliva-` being too strict haha.

**Comment by helmijunaedihazwan-design** [comment]
Game nya sangat menyenangkan dan menarik grafis nya realistis dan sangat bagus
