### ISSUE TITLE
add ecrater

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#428]
original urls:
```
https://s.ecrater.com/stores/50746/50e104b29b24b_50746f.jpg
https://s.ecrater.com/stores/403772/5a02f8870538a_403772s.jpg
```

desired urls:
```
https://s.ecrater.com/stores/50746/50e104b29b24b_50746b.jpg
https://s.ecrater.com/stores/403772/5a02f8870538a_403772b.jpg
```

test images can be found at:
```
https://booksnthings.ecrater.com/
https://oil-painting-art-2017.ecrater.com/
https://www.ecrater.com/filter.php?keywords=book
```

**Comment by qsniyg** [comment]
Thank you!! I've just implemented it using a simple `[a-z]` rule for the last character, not sure if it's too overreaching...

Interestingly, some thumbnails don't have a letter after: https://s.ecrater.com/stores/50746/47af50b4789de_50746.jpg , but also cannot work with a letter after.
