### ISSUE TITLE
Add support to obtain original images from discogs.com

### ISSUE THREAD

**Issue by Gertcha** [qsniyg/maxurl#429]
**Example:**

This release [https://www.discogs.com/release/12801670](url)

If you click on the image in the top left, it is displayed at 600x600px which is the max size that is displayed by Discogs though the original image was 970x970px (see [here](https://www.discogs.com/release/12801670-Voodoo-Lounge-Uncut/images/update)).

The URL scheme for the reduced size image is
`https://img.discogs.com/MjmbFRJJih89NH1vTPzlL4hV-8Q=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-12801670-1542565929-6791.jpeg.jpg`

We want to be
`https://www.discogs.com/image/R-12801670-1542565929-6791.jpeg`

to display the original.

Thanks.

**Comment by qsniyg** [comment]
Wow thank you very much!! I've been trying to find the discogs source domain/folder for a long time, I guess I wasn't looking in the right place haha.

Fixed now! :)

**Comment by Gertcha** [comment]
Thanks for the quick amend!
Not my find, just porting the info from elsewhere as will be quicker using maxurl.

Thanks for this tool btw too!
