### ISSUE TITLE
update nymag rule

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#432]
Original URLs:
```
https://pyxis.nymag.com/v1/imgs/729/cc9/040edf97c4ef041ec1f48829be69842eed-24-Doja-Cat.rsquare.w330.jpg
https://pyxis.nymag.com/v1/imgs/5d3/ba9/44036335bf752271c445cd3ed12bf0c20d-02-LL-cool-J--WICLW-NEW.rhorizontal.w700.jpg
https://pyxis.nymag.com/v1/imgs/92c/88f/d4a2dede7120bc943ed95943b6ac5fe212-trump.rsquare-zoom.w100.jpg
```

Desired URLs:
```
https://pyxis.nymag.com/v1/imgs/729/cc9/040edf97c4ef041ec1f48829be69842eed-24-Doja-Cat.jpg
https://pyxis.nymag.com/v1/imgs/5d3/ba9/44036335bf752271c445cd3ed12bf0c20d-02-LL-cool-J--WICLW-NEW.jpg
https://pyxis.nymag.com/v1/imgs/92c/88f/d4a2dede7120bc943ed95943b6ac5fe212-trump.jpg
```

**Comment by qsniyg** [comment]
Thanks!!

Neat, a new domain for nymag... looks like it's dynamic too, which makes it easy to test various patterns. Seems like you can chain any number of operations, and it'll use whichever one's last for precedence (but it doesn't apply them one-by-one, for example: https://pyxis.nymag.com/v1/imgs/92c/88f/d4a2dede7120bc943ed95943b6ac5fe212-trump.h50.w50.h1000.w1000.jpg doesn't wildly stretch the image).

I've done a little bit of `inurl:pyxis.nymag.com`-ing and added a few more patterns... for the moment I _think_ it should cover most use cases? My main concern would be in the `r(?:square|horizontal|vertical|social)` portion of the rule, in case they keep adding more types (I'm guessing it's a resize preset?), maybe `r[a-z]+(?:-[a-z]+)?` would suffice, but I'd be worried about it being too general.

Also, looks like the part after the hex is optional, for example, both of the following work:

```
https://pyxis.nymag.com/v1/imgs/92c/88f/d4a2dede7120bc943ed95943b6ac5fe212-trump.jpg
https://pyxis.nymag.com/v1/imgs/92c/88f/d4a2dede7120bc943ed95943b6ac5fe212.jpg
```
