### ISSUE TITLE
Improve twitter rule

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#437]
Currently the twitter rule doesn't work at all for `format=webp` because the modified URLs all return 404. In general, should the twitter rule fallback to the other extensions (`png`, `jpg`) to prevent this from happening?

Example:
```
https://pbs.twimg.com/media/EhML7FPXkAEK4GZ?format=webp&name=tiny
https://pbs.twimg.com/media/EhMO9OhU0AA6vZv?format=webp&name=tiny
```

should redirect to
```
https://pbs.twimg.com/media/EhML7FPXkAEK4GZ.jpg?name=orig
https://pbs.twimg.com/media/EhMO9OhU0AA6vZv.jpg?name=orig
```

**Comment by qsniyg** [comment]
Thank you very much! Yeah it didn't account for webp haha, fixed :)
