### ISSUE TITLE
add sites

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#439]
beatsource:
```
https://geo-media.beatsource.com/image_size/500x500/8/c/6/8c608f85-4018-4657-91c6-8037169ec9b3.jpg => https://geo-media.beatsource.com/8/c/6/8c608f85-4018-4657-91c6-8037169ec9b3.jpg
https://geo-media.beatsource.com/image_size/500x500/0/9/f/09f5cedc-496a-4058-a383-a7f6916fea3b.jpg => https://geo-media.beatsource.com/0/9/f/09f5cedc-496a-4058-a383-a7f6916fea3b.jpg (worse quality?)
https://geo-media.beatsource.com/image_size/500x500/f/9/5/f95bcc58-f2f3-4acb-959d-44caffa08444.jpg => https://geo-media.beatsource.com/f/9/5/f95bcc58-f2f3-4acb-959d-44caffa08444.jpg
```

meijer:
```
https://www.meijer.com/content/dam/meijer/product/0007/04/7000/30/0007047000300_2_A1C1_0200.png => https://www.meijer.com/content/dam/meijer/product/0007/04/7000/30/0007047000300_2_A1C1_1200.png
https://www.meijer.com/content/dam/meijer/product/0071/37/3301/85/0071373301850_4_A1C1_0600.png => https://www.meijer.com/content/dam/meijer/product/0071/37/3301/85/0071373301850_4_A1C1_1200.png
```

kroger:
```
https://www.kroger.com/product/images/thumbnail/left/0003338320027 => https://www.kroger.com/product/images/xlarge/left/0003338320027
https://www.kroger.com/product/images/medium/front/0004900000044 => https://www.kroger.com/product/images/xlarge/front/0004900000044
https://www.kroger.com/product/images/small/back/0003800019904 => https://www.kroger.com/product/images/xlarge/back/0003800019904
https://www.kroger.com/product/images/large/right/0008768400095 => https://www.kroger.com/product/images/xlarge/right/0008768400095
```
Note: sometimes `xlarge` isn't actually any larger. For example: `https://www.kroger.com/product/images/medium/front/0003338320027` and `https://www.kroger.com/product/images/xlarge/front/0003338320027`

Less common town news domain `tn-cloud.net`:
```
https://wpcdn.us-east-1.vip.tn-cloud.net/www.channel3000.com/content/uploads/2020/09/Drink-1024x576.jpg => https://www.channel3000.com/content/uploads/2020/09/Drink.jpg
https://wpcdn.us-midwest-1.vip.tn-cloud.net/www.9and10news.com/content/uploads/2020/07/BOAT-3-553x360.jpg => https://www.9and10news.com/content/uploads/2020/07/BOAT-3.jpg
https://wpcdn.us-east-1.vip.tn-cloud.net/www.wbbjtv.com/content/uploads/2020/03/MGN_1280x960_00321B00-INZQY-1024x768.jpg => https://www.wbbjtv.com/content/uploads/2020/03/MGN_1280x960_00321B00-INZQY.jpg
https://wpcdn.us-east-1.vip.tn-cloud.net/www.kxly.com/content/uploads/2020/09/computer-keyboard-Cropped-1024x576-640x360.jpg => https://www.kxly.com/content/uploads/2020/09/computer-keyboard-Cropped-1024x576.jpg
```
Note: if there's no `-wxh` part then there's no point in rewriting the URL. for example: `https://wpcdn.us-east-1.vip.tn-cloud.net/www.abc6.com/content/uploads/2020/07/mosquito.jpg`

**Comment by qsniyg** [comment]
Thank you very much as usual!

About beatsource, interesting, so the ones you sent all get scaled to 1400x1400, but it appears to be the original version stored on their servers, because for `https://geo-media.beatsource.com/image_size/2160x864/4/8/6/486b594c-eb2d-4f64-980c-7bd53bd55c04.jpg`, removing `/image_size/*x*/`, it will still be 2160x864. But yeah, that one image is definitely upscaled. I'll add it anyways because it appears to be the original version :)

The rest I've implemented as you stated, though I just redirected all tn-cloud domains, in case a website has a different rule.

**Comment by llacb47** [comment]
I think you should make [this part](https://github.com/qsniyg/maxurl/commit/2b3eba9d650355f7f66449b563bb5759f97e0269#diff-27f9d4a32bb1055d6e25712679ce34afR21551) generic for `tn-cloud.net` somehow. All of these sites use this resizing format: https://publicwww.com/websites/%22tn-cloud.net%22/

**Comment by qsniyg** [comment]
Ah good point, fixed!

Thanks for linking that site by the way, super useful!!
