### ISSUE TITLE
update timthumb rule to support absolute paths

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#446]
on `https://www.foundation-media.com/releases/`

`https://www.foundation-media.com/wp-content/themes/minuet/functions/timthumb.php?src=wp-content/uploads/2020/09/rayven.jpg&w=432&h=432&zc=1&q=90`

should be redirected to

`https://www.foundation-media.com/wp-content/uploads/2020/09/rayven.jpg`

**Comment by qsniyg** [comment]
Thank you very much! There's probably some kind of setting in timthumb that lets the server owner specify where the base url is, so I just added a simple variable for this :)
