### ISSUE TITLE
linkfire.com

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#453]
`https://amamiyasora.lnk.to/kimiwotoushite`
`https://linkstorage.linkfire.com/medialinks/images/875d8b6d-5238-4f5c-8b71-4599cd3030c0/artwork-440x440.jpg`
--> `https://linkstorage.linkfire.com/medialinks/images/875d8b6d-5238-4f5c-8b71-4599cd3030c0/artwork.jpg`

**Comment by qsniyg** [comment]
Thanks! Fixed now :) And thankfully they don't use `pointer-events: none` like other link hub sites do...
