### ISSUE TITLE
update bytedance

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#454]
add `p77-sign-sg.tiktokcdn.com`

`https://p77-sign-sg.tiktokcdn.com/musically-maliva-obj/1640051850297350~c5_100x100.jpeg?x-expires=1601161200&x-signature=bCErvp6OtiUTB9NRl4nqNTaiob0%3D`

`https://p16-amd-va.tiktokcdn.com/origin/musically-maliva-obj/1640051850297350.jpeg`

**Comment by qsniyg** [comment]
Thanks! Good to know the p16-amd-va redirection works for more than just p16, so I made it generic :)
