### ISSUE TITLE
base64 decode iheartradio images

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#456]
URLS of the form `https://i.iheart.com/v3/url/...` are followed by the base64 encoded URL of the original image. I think this userscript should redirect to the encoded (original-ish) URL.

For example

```
https://i.iheart.com/v3/url/aHR0cHM6Ly9kM3dvNXdvanZ1djdsLmNsb3VkZnJvbnQubmV0L3RfcnNzX2l0dW5lc19zcXVhcmVfMTQwMC9pbWFnZXMuc3ByZWFrZXIuY29tL29yaWdpbmFsLzc2ZjIwODk3MDQyN2M1MDEwOTkwMjBlYmVmMTg3Yjg0LmpwZw?ops=fit(240%2C240)

```

can be redirected to

```
https://d3wo5wojvuv7l.cloudfront.net/t_rss_itunes_square_1400/images.spreaker.com/original/76f208970427c501099020ebef187b84.jpg
```

which can be redirected _again_ to the original image

```
http://images.spreaker.com/original/76f208970427c501099020ebef187b84.jpg
```

Another few examples:

```
https://i.iheart.com/v3/url/aHR0cDovL2ltYWdlLmloZWFydC5jb20vYmVsbC1pbmdlc3Rpb24tcGlwZWxpbmUtcHJvZHVjdGlvbi11bWcvZnVsbC8wMDYwMjUwODk4NzIzNl8yMDIwMDgwMjE2NTA1Mjc4MS8yMFVNR0lNMjExNjZfVDFfY3ZyYXJ0LmpwZw==
https://i.iheart.com/v3/url/aHR0cDovL2ltYWdlLmloZWFydC5jb20vU0JNRzcvVGh1bWJfQ29udGVudC9GdWxsX1BDL1NCTUcvQXByMTQvMDQxNDE0L0ExMDMwMUEwMDAzMTMxNjM0WV8yMDE0MDQxMTE3NDkzNTM5NC9yZXNvdXJjZXMvQTEwMzAxQTAwMDMxMzE2MzRZX1QtMTAyMDJfSW1hZ2UuanBn
https://i.iheart.com/v3/url/aHR0cCUzQSUyRiUyRmltYWdlLmloZWFydC5jb20lMkZpaHItaW5nZXN0aW9uLXBpcGVsaW5lLXByb2R1Y3Rpb24td21nJTJGbmV3X3JlbGVhc2UlMkYyMDIwMDczMTIwMzI1MjY4MiUyRjA3NTY3OTgwNTQxNiUyRnJlc291cmNlcyUyRjA3NTY3OTgwNTQxNi5qcGc=
```

to

```
http://image.iheart.com/bell-ingestion-pipeline-production-umg/full/00602508987236_20200802165052781/20UMGIM21166_T1_cvrart.jpg
http://image.iheart.com/SBMG7/Thumb_Content/Full_PC/SBMG/Apr14/041414/A10301A0003131634Y_20140411174935394/resources/A10301A0003131634Y_T-10202_Image.jpg
http://image.iheart.com/ihr-ingestion-pipeline-production-wmg/new_release/20200731203252682/075679805416/resources/075679805416.jpg (need to unescape first)
```

**Comment by qsniyg** [comment]
Thank you very much!! Especially the last URL, I'd have missed the decodeURIComponent otherwise! :)

**Comment by llacb47** [comment]
new url format: `https://i.iheart.com/v3/surl/aHR0cDovL2ltYWdlLmloZWFydC5jb20vY29udGVudC9tdXNpYy9wcm9kL1dNRzQvVGh1bWJfQ29udGVudC9GdWxsX1BDL1dNRy9TZXAxNS8wOTE3MTUvODE0OTA4MDIwMjAyL3Jlc291cmNlcy84MTQ5MDgwMjAyMDIuanBn?ops=fit%2875%2C75%29&sn=eGtleWJhc2UyMDIxMTExMDpZ68wLlqYG4ddD8laW_OxG5Dhkug04Me0Ak8U65_7iDQ%3D%3D&surrogate=1cOXl179JY-syhxYSCX6Q0O_JMGiBKwf7UslJDIRJEsSokWCM3NHgICEbRjKslIKm-S3yl67xkE6shDSqTadRdH6Yr-bGPSCVHtNgC9ah49g_ap7L1ug8YYTKki-VreBJyMZEjjAoegtojIoUnnlkyR1VzvwWLiyLFlU_v8yawNz_Qnn-8ONRnC62wcsOVEhzkU5LwCe4NAsgMzfiN552wY3ABm46QoZA5vjzFWTSraPG-tCKy903v84DTSVmkz9ZUHe-5PK5SDE5IJRUo7IGDf41-dzGNsORNZSUtJaYlxwuoL1keVg-BFeVL6Xg4mMpglJzjhrAQ%3D%3D`

**Comment by qsniyg** [comment]
Thank you!
