### ISSUE TITLE
reddit profile icons and banners

### ISSUE THREAD

**Issue by PwnicornDev** [qsniyg/maxurl#46]
The image is loaded as e.g. https://styles.redditmedia.com/t5_3pguo/styles/profileIcon_hdpofk4olag01.jpg?width=256&height=256&crop=256:256,smart&s=3df0ac6cd6b812fc38a249f3579e261d442424b3 or https://styles.redditmedia.com/t5_3khyj/styles/profileBanner_kfn1qeqdfh521.png?width=1280&height=384&crop=1280:384,smart&s=22650cf8b2e788c04289f7ab224745d3c2a3fd3cwith the original available at https://styles.redditmedia.com/t5_3pguo/styles/profileIcon_hdpofk4olag01.jpg and https://styles.redditmedia.com/t5_3khyj/styles/profileBanner_kfn1qeqdfh521.png respectively.

**Comment by qsniyg** [comment]
Thank you! I've added it in :)
