### ISSUE TITLE
pbase issue

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#470]
For some reason the redirection fails on this image: 

`https://a4.pbase.com/g12/47/949547/3/169384542.7kh4gRMp.jpg`

console:

![image](https://user-images.githubusercontent.com/16567977/95131518-2ffd0a80-072c-11eb-903b-cd004ba58a35.png)

**Comment by qsniyg** [comment]
Ah, they added right click "protection", which broke the regex match.

Fixed, thanks for reporting!! :)
