### ISSUE TITLE
amplience.net

### ISSUE THREAD

**Issue by SlugMan336** [qsniyg/maxurl#475]
Add this website.
Small image: https://i8.amplience.net/i/jpl/jd_146327_b?qlt=92&w=600&h=765&v=1
Large image: https://i8.amplience.net/i/jpl/jd_146327_b
This is cdn for jdsports websites.

**Comment by qsniyg** [comment]
Thank you!! I've just added it to a simple remove-everything-after-? rule for the moment, but hopefully it's strict enough that it won't fail for images that don't use that system (if there are).

Seems like the `_b` ending has to do with the image, not the size (e.g. https://i8.amplience.net/i/jpl/jd_146327_a is a different image).
