### ISSUE TITLE
jdsports.com

### ISSUE THREAD

**Issue by SlugMan336** [qsniyg/maxurl#476]
small: https://media.jdsports.com/i/jdsports/1361945_001_M4?$default$&w=1000&h=1000&bg=rgb(237,237,237)
large: https://media.jdsports.com/i/jdsports/1361945_001_M4

**Comment by qsniyg** [comment]
Thanks! Seems to be using the same system as the other one (e.g. `qlt=10` has an effect on both, and they both use `/i/` as the first folder), so I just bunched the rules together :)
