### ISSUE TITLE
[url] static.wikia.nocookie.net

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#490]
`https://static.wikia.nocookie.net/non-aliencreatures/images/f/f6/Machineelf.jpg/revision/latest/scale-to-width-down/600?cb=20110214083503`

(from `https://non-aliencreatures.fandom.com/wiki/Machine_Elf?file=Machineelf.jpg` )

**Comment by qsniyg** [comment]
Thank you!! I've added the new domain :)
