### ISSUE TITLE
klix.ba and olx.ba (pik.ba)

### ISSUE THREAD

**Issue by keophcp** [qsniyg/maxurl#492]
small: https://static.klix.ba/media/images/vijesti/s11_201020058.jpg?v=1
medium: https://static.klix.ba/media/images/vijesti/b_201020058.jpg?v=1
large: https://static.klix.ba/media/images/vijesti/201020058.jpg?v=1

small: https://static.klix.ba/media/images/vijesti/201020131.10_mn.jpg?v=1
https://static.klix.ba/media/images/vijesti/201020131.10.jpg?v=1
medium: https://static.klix.ba/media/images/vijesti/201020131.10_xxl.jpg?v=1 (but this redirects to the _mn above for some reason, probably needs also referrer header, because it can only be viewed in frame as when clicked on this page: https://www.klix.ba/vijesti/bih/sarajevo-gradjani-u-jesenjoj-setnji-policija-kontrolisala-postivanje-mjera/201020131)
large: https://static.klix.ba/media/images/vijesti/201020131.10_xxl.jpg?v=1

Looks like words like b, mn, xl, xxl, s**, mean big, mini, extra large, extra extra large, small.

small: https://s5.pik.ba/galerija/2019-08/14/09/slika-1068915-5d5467db0c8bb-default.jpg
https://s5.pik.ba/galerija/2019-08/14/09/slika-1068915-5d5467db0c8bb-thumb.jpg
large: https://s5.pik.ba/galerija/2019-08/14/09/slika-1068915-5d5467db0c8bb-velika.jpg

**Comment by qsniyg** [comment]
Thank you!!

The klix.ba one was a bit of a challenge! Turns out that `_mn` is often used for linking the original version, but not in some cases (like the one you linked). So now it will compare the image sizes to see which one is larger, because I can't find any other way to detect this.

**Comment by keophcp** [comment]
Exception is this one, can you make rule for nonexisting xxl images to redirect to xl ones:
https://static.klix.ba/media/images/vijesti/161022053.11_xl.jpg?v=1
https://static.klix.ba/media/images/vijesti/161022053.11_xxl.jpg?v=1

**Comment by qsniyg** [comment]
Thanks for letting me know, will try to fix soon (reopening so I don't forget)

**Comment by qsniyg** [comment]
Sorry for getting back so late! Was a bit of a challenge (again), but it should be fixed now :)
