### ISSUE TITLE
Add XenForo forums

### ISSUE THREAD

**Issue by gtumanyan** [qsniyg/maxurl#494]
https://www.hairlosstalk.com/interact/threads/exploring-the-hormonal-route-hair-life.109288/page-529#post-1870713
https://www.hairlosstalk.com/interact/attachments/fe597f5d-b6b5-470d-bfd4-92c2a4c7fcc6-jpeg.137056/
and 
https://www.hairlosstalk.com/interact/threads/exploring-the-hormonal-route-hair-life.109288/post-1872339
https://www.hairlosstalk.com/interact/attachments/5b33eea3-3cb2-44ee-aecb-a7875220e3ae-jpeg.137444/

**Comment by qsniyg** [comment]
Thank you!!

I've been meaning to support xenforo attachments for a while, but the sites I stumbled upon always required logging in unfortunately. Now with this I can finally support it, thank you!! :)
