### ISSUE TITLE
[BUG?] Constant errors and conflicts in google drive when this extension is enabled. (Even when blacklisted)

### ISSUE THREAD

**Issue by Michael18751** [qsniyg/maxurl#495]
![image](https://user-images.githubusercontent.com/53535277/97066784-24ac3a80-1586-11eb-8a54-62469f94e47a.png)
This works on 0.14.6 and possibly older versions. It will forever generate infinite errors, freeze the page, and use a ton of CPU usage.

**Comment by qsniyg** [comment]
Oh no (and thanks for reporting)! Can you send your settings? (click the `Export` button at the top, paste them to a pastebin, then copy the link here)

I can't replicate it on my side, but from the error, it seems like it's using a different combination of settings than I'm using.

**Comment by Michael18751** [comment]
https://pastebin.com/E4PMJG2P

**Comment by qsniyg** [comment]
Thanks! I can replicate the issue.

I believe it's due to the combination of "Popup link for linked images" and "Automatically highlight images". Will try to fix asap! :)

**Comment by qsniyg** [comment]
Actually nevermind, I wasn't able to replicate the issue for some reason...

But I _may_ have fixed it in https://github.com/qsniyg/maxurl/commit/700832a3185708ab83f05cdcdaa76e839af4c4ae, can you test? (just download userscript.user.js from the git repo and install that one)

**Comment by Michael18751** [comment]
Seems fixed in 700832a!
