### ISSUE TITLE
Option to close popup when popup is clicked

### ISSUE THREAD

**Issue by qsniyg** [qsniyg/maxurl#498]
Thanks to bitst0rm on greasyfork for the idea: https://greasyfork.org/en/scripts/36662-image-max-url/discussions/65364

Probably by adding a "click behavior", replacing the "clicking link downloads" option

**Comment by bitst0rm** [comment]
Thank you very much for the quick implementation!
Btw, i am greatly impressed by your high energy and enthusiasm on coding.
Everyone can code, but only few can hack >7000 hardcoded websites: gorhill @ uBlock and you.
I will nominate you for the Nobel Prize.

**Comment by qsniyg** [comment]
Hahaha thank you!! Yeah gorhill is truly amazing, reverse-engineering anti-adblock scripts is incredibly difficult work. I generally have it much easier with what I'm doing haha :) (much less obfuscation on the website's part)
