### ISSUE TITLE
maxurl messes up the display of XML 

### ISSUE THREAD

**Issue by alexolog** [qsniyg/maxurl#507]
Load the following URL with and without the add-on to see an example:
https://www.casioeducation.com/resource/techspec/module-fx-260solariipk.pdf

Note: even setting the "Enable extension" option to off does not fix it, need to disable it from the add-on manager.

**Comment by qsniyg** [comment]
Thanks for reporting! Should be fixed in https://github.com/qsniyg/maxurl/commit/ae46137ce7fd7c1b5ad5ab3455fdec4297c8d8ea :)

**Comment by alexolog** [comment]
Thank you!
Can you please push it to Mozilla?

**Comment by qsniyg** [comment]
Will do soon! (probably in a day or two, still have a few more things to get done, as well as just general testing)

In the meantime, feel free to use this: [extension.xpi.zip](https://github.com/qsniyg/maxurl/files/5456263/extension.xpi.zip) (unzip, then about:debugging -> my firefox -> load temporary addon)
