### ISSUE TITLE
maximkorea.net

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#51]
http://www.maximkorea.net/missmaxim/m2girl/20145/73_2014502_133127_img_300.jpg
http://www.maximkorea.net/missmaxim/m2girl/20145/73_2014502_133127_img.jpg

Source: http://www.maximkorea.net/missmaxim/m2girl_view.php?m2girl_uid=151

**Comment by qsniyg** [comment]
Thank you very much! The original rule was too specific :)
