### ISSUE TITLE
e-outdoor.co.uk

### ISSUE THREAD

**Issue by keophcp** [qsniyg/maxurl#515]
This one is not redirecting although url is obvious, and small version has useless white space: https://www.e-outdoor.co.uk/pi/ronhill/RH-003394_BA_8.jpg?w=800&h=800

**Comment by qsniyg** [comment]
Thank you! Looks like the `/pi/` URL is the only one that's still used by the site for images (`/images/..._thumb.` doesn't seem to be used anymore)
