### ISSUE TITLE
Bookwalker redirect broken

### ISSUE THREAD

**Issue by synthtech** [qsniyg/maxurl#516]
After updating to 0.14.7 the final redirect to the full size image bugs out.

Page: https://bookwalker.jp/de00b92658-0e2d-4b74-a343-e093a6f40652/
Thumb: https://rimg.bookwalker.jp/81036/frDGCemG5kX9EBY8IrbThQ__.jpg
Redirected thumb: https://c.bookwalker.jp/81036/t_700x780.jpg

The following error then appears in the console:
`ReferenceError: run_arrayd_string is not defined`
And the final redirect to the full image doesn't occur.

I'm speculating that the changes here https://github.com/qsniyg/maxurl/commit/94667390b5b198dc55bfaf1cd7742ee717b75bfa are causing an issue with rules using `reverse_str`.

**Comment by qsniyg** [comment]
Oops, really stupid mistake on my part, I should have tested it before changing it. Thanks for reporting!! :)
