### ISSUE TITLE
New rule request: tonikawa.com

### ISSUE THREAD

**Issue by jloqfjgk** [qsniyg/maxurl#520]
#### Summary
http://tonikawa.com is the official webpage for the anime adaptation of the manga series _TONIKAWA: Over The Moon For You_.

Screenshots of each episode have a larger version available.

#### Format
The URL should start with `http://tonikawa.com/assets/images/common/story/ep`.

#### Examples
For Episode 4:
* Low res: http://tonikawa.com/assets/images/common/story/ep04/img_2.jpg
* High res: http://tonikawa.com/assets/images/common/story/ep04/img_2_l.jpg

For Episode 6:
(1st example)
* Low res: http://tonikawa.com/assets/images/common/story/ep06/img_5.jpg
* High res: http://tonikawa.com/assets/images/common/story/ep06/img_5_l.jpg

(2nd example)
* Low res: http://tonikawa.com/assets/images/common/story/ep06/img_10.jpg
* High res: http://tonikawa.com/assets/images/common/story/ep06/img_10_l.jpg

**Comment by qsniyg** [comment]
Thank you very much for the detailed description!! All the example links you sent work on my side with this rule :)
