### ISSUE TITLE
useless facebook redirect

### ISSUE THREAD

**Issue by keophcp** [qsniyg/maxurl#522]
original: https://scontent-frt3-1.xx.fbcdn.net/v/t1.0-9/120795514_3623873584292089_1109773157226751357_n.jpg?_nc_cat=107&ccb=2&_nc_sid=8bfeb9&_nc_ohc=ViNCX-I_wKkAX-0j7vM&_nc_ht=scontent-frt3-1.xx&oh=ea04ad55ebb6811b982470e218e89b17&oe=5FCB60FB

redirected: https://scontent-frt3-1.xx.fbcdn.net/v/t1.0-9/120795514_3623873584292089_1109773157226751357_n.jpg?ccb=2&_nc_sid=8bfeb9&_nc_ohc=ViNCX-I_wKkAX-0j7vM&_nc_ht=scontent-frt3-1.xx&oh=ea04ad55ebb6811b982470e218e89b17&oe=5FCB60FB

ref: https://www.facebook.com/SkolaTrcanjaKlix/photos/3623873564292091

Both images are same size and resolution, so this is time waste. Exclude it.

**Comment by qsniyg** [comment]
Yeah you're right, my idea was to kind of "normalize" the URL to be as simple as possible (helps esp. in the case of api calls returning possibly different urls), but yeah that does lead to useless redirects.

At some point I guess I should add some kind of "useless" property for the object, where it'll use the url, but won't redirect.
