### ISSUE TITLE
redirects images even when off, but only once in new tabs

### ISSUE THREAD

**Issue by keophcp** [qsniyg/maxurl#523]
I noticed this long time ago (but now confirmed and found when), that extension works even when it is pressed in toolbar, when button becomes gray. It just works less frequently than when on.

Example:

When I turn off extension via it's button and and open this link (https://upload.wikimedia.org/wikipedia/en/thumb/9/94/Symbol_support_vote.svg/19px-Symbol_support_vote.svg.png) in new tab (either via extension like 'open image in new tab' or pasting it in address bar) it redirects to https://upload.wikimedia.org/wikipedia/en/9/94/Symbol_support_vote.svg

If I now paste it again into current window where it is redirected, it redirects no more, meaning bug is not present.

If I disable it in extensions via Firefox, bug is no longer present.

If I reenable it in extensions bug reappears.

**Comment by qsniyg** [comment]
Thank you!! It was due to the "Do redirection in extension" option, I had completely forgotten to make it aware of the disabled status when implementing it.
