### ISSUE TITLE
[Update] marieclairekorea.com

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#530]
Old: https://img.marieclairekorea.com/2020/11/mck_5fb36322aa3c3-scaled.jpg
New: https://img.marieclairekorea.com/2020/11/mck_5fb36322aa3c3.jpg

Source: https://www.marieclairekorea.com/celebrity/2020/11/beautiful-mind/

**Comment by qsniyg** [comment]
Thank you very much!! Should be fixed :)

There was actually a small period where the original image returned 404 for some reason, but retrying the exact same URL worked fine about a minute later... not quite sure what was going on there.
