### ISSUE TITLE
Stopped working on Vivaldi!?

### ISSUE THREAD

**Issue by PietroPizzi69** [qsniyg/maxurl#541]
The userscript version has worked with Tempermonky in all of my Vivaldi browsers (The newest Win. and Linux version on different PCs). Some time ago they stopped working completely (some days or weeks, idk exactly). Even the options page (https://qsniyg.github.io/maxurl/options.html) said "Once the userscript is installed, this page will allow you to configure it". But they are installed. I also tried to reinstalled it and checked the Tempermonkey option page if I find some strange settings there. My actual Version is 0.14.8 from Greasy Fork.

**Comment by qsniyg** [comment]
I don't have Vivaldi installed at the moment, but I'll try to test it once I can get it running (my internet's a bit slow at the moment).

Since the options page displays that message, it means something's critically wrong, as it should normally display an error if there was one while displaying it. Could you check the console (F12 -> console tab), and see if anything's logged there when you load the options page? You may have to reload the page once the console is open to get anything logged. If so, can you send a screenshot of the console?

Also just as a test, could you see if it works under Violentmonkey instead of Tampermonkey?

**Comment by PietroPizzi69** [comment]
Of course can I help testing. I'm now at work, here I have the Windows version running. At home I can test the Linux version if it makes a difference. I have some other Extentions but I deactivated the ones that I think could potentially interfere (even if it worked with them before), like uBlock and "I don't care about cookies".

Console Output:
`
userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:1
ERROR: Execution of script 'Image Max URL' failed! update_seetting is not defined
eval | @ | userscript.html?name…977c-492267c84eec:1
-- | -- | --
  | eval | @ | userscript.html?name…977c-492267c84eec:1
  | eval | @ | userscript.html?name…-492267c84eec:66883
  | eval | @ | userscript.html?name…-492267c84eec:66885
  | (anonymous) | @ | VM307:3
  | N | @ | VM307:2
  | (anonymous) | @ | VM307:3
  | Ka | @ | VM320:61
  | create | @ | VM320:73
  | run | @ | VM320:12
  | eval | @ | VM320:74
  | (anonymous) | @ | VM307:3
  | N | @ | VM307:2
  | eval | @ | VM320:74
  | eval | @ | VM320:74
  | TM_back | @ | VM320:75
  | eval | @ | VM320:75
  | (anonymous) | @ | VM307:3
  | exec_fn | @ | VM307:1
  | (anonymous) | @ | VM307:12
  | Aa | @ | VM307:11
  | send | @ | content.js:7
  | next | @ | content.js:12
  | (anonymous) | @ | content.js:28
  | (anonymous) | @ | content.js:25

userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:1
ReferenceError: update_seetting is not defined
at upgrade_settings_with_version (userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:57887)
    at eval (userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:57914)
    at eval (userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:57647)
    at get_values (userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:57622)
    at get_value (userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:57646)
    at upgrade_settings (userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:57913)
    at eval (userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:57977)
    at get_values (userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:57622)
    at process_settings (userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:57968)
    at do_config (userscript.html?name=Image%20Max%20URL.user.js&id=e3d915b5-45ed-4a77-977c-492267c84eec:57987)
`

**Comment by qsniyg** [comment]
... I really should learn to double check for typos before committing.

Thanks for reporting! Should be fixed in https://github.com/qsniyg/maxurl/commit/90883bf948cc78fde81215667ddf9cb3e77a7e14 :)

**Comment by PietroPizzi69** [comment]
You are quick :). THX!!

Now, a little to late as it seems ;), I can report that with Violentmonkey the Option page works but the Script don't (testet on Google Images, Pinterest and DevianArt).

**Comment by qsniyg** [comment]
You're welcome, and thanks for sending that log! I'd have been scratching my head for a while without it haha.

The reason it works under violentmonkey is because the (now-)obsolete "support pointer-events: none" option was modified under tampermonkey somehow (though it could have been automatic too). Since the violentmonkey is (likely) a fresh install, it'll work. 

>but the Script don't

Weird... it works fine on my end (3.4.2066.106 linux). Just to rule out possibilities, could this be because you modified the settings (e.g. trigger keybind, etc.) under tampermonkey, but violentmonkey has the default settings?

**Comment by PietroPizzi69** [comment]
Interesting. I have fixed the update_seetting typo direkt in the code (with the Tempermonkey&Violentmonkey editors).
Now the option page worked with both ..monkeys. But the Script don't gives me a popup.

Because I originally have changed some script options, I have removed all of them for testing (I tested it with GoogleImage, DeviantArt & Facebook). And for good measure I disabled all Extensions. Now I tested it with Tempermonkey and Violentmonkey, with default option and with my previously exported option, nothing works (beside the Option page... and when I hit the "Replace Images" Button/Option I get a progress bar on top). And this time I don't get error in the console when I open the option page or the GoogleImageSearch.

If it helps, these are my settings:
`
{"imu_enabled":true,"language":"en","check_updates":true,"check_update_interval":24,"check_update_notify":true,"dark_mode":true,"settings_tabs":true,"settings_alphabetical_order":false,"settings_visible_description":true,"settings_show_disabled":true,"settings_show_requirements":true,"advanced_options":true,"allow_browser_request":true,"retry_503_times":3,"retry_503_ms":2000,"use_blob_over_arraybuffer":false,"allow_live_settings_reload":true,"allow_remote":true,"disable_keybind_when_editing":true,"enable_gm_download":true,"gm_download_max":15,"enable_webextension_download":false,"redirect":true,"redirect_history":true,"redirect_extension":true,"canhead_get":true,"redirect_force_page":true,"redirect_infobox_url":false,"redirect_infobox_timeout":3,"print_imu_obj":false,"redirect_disable_for_responseheader":false,"redirect_to_no_infobox":true,"mouseover":true,"mouseover_open_behavior":"popup","mouseover_trigger_behavior":"keyboard","mouseover_trigger_key":["shift","alt","i"],"mouseover_trigger_delay":1,"mouseover_trigger_mouseover":false,"mouseover_trigger_enabledisable_toggle":"disable","mouseover_trigger_prevent_key":["shift"],"mouseover_close_behavior":["any"],"mouseover_close_need_mouseout":true,"mouseover_jitter_threshold":2,"mouseover_cancel_popup_when_elout":true,"mouseover_cancel_popup_with_esc":true,"mouseover_cancel_popup_when_release":true,"mouseover_auto_close_popup":false,"mouseover_auto_close_popup_time":5,"mouseover_use_hold_key":true,"mouseover_hold_key":["i"],"mouseover_hold_position_center":false,"mouseover_hold_close_unhold":false,"mouseover_hold_unclickthrough":true,"mouseover_close_el_policy":"both","mouseover_close_click_outside":false,"mouseover_allow_partial":"video","mouseover_partial_avoid_head":false,"mouseover_use_blob_over_data":false,"mouseover_enable_notallowed":true,"mouseover_enable_notallowed_cant_load":true,"mouseover_notallowed_duration":300,"mouseover_minimum_size":20,"mouseover_exclude_backgroundimages":false,"mouseover_exclude_page_bg":true,"mouseover_exclude_imagemaps":true,"mouseover_only_links":false,"mouseover_linked_image":true,"mouseover_exclude_sameimage":false,"mouseover_exclude_imagetab":true,"mouseover_video_controls":false,"mouseover_video_controls_key":["c"],"mouseover_video_loop":true,"mouseover_video_autoloop_max":60,"mouseover_video_playpause_key":["space"],"mouseover_video_muted":false,"mouseover_video_mute_key":["m"],"mouseover_video_volume":100,"mouseover_video_volume_down_key":["9"],"mouseover_video_volume_up_key":["0"],"mouseover_video_volume_change_amt":5,"mouseover_video_resume_from_source":true,"mouseover_video_resume_if_different":false,"mouseover_video_pause_source":true,"mouseover_video_seek_amount":10,"mouseover_video_seek_left_key":["shift","left"],"mouseover_video_seek_right_key":["shift","right"],"mouseover_video_frame_prev_key":[","],"mouseover_video_frame_next_key":["."],"mouseover_video_framerate":25,"mouseover_video_speed_down_key":[["["],["shift",","]],"mouseover_video_speed_up_key":[["]"],["shift","."]],"mouseover_video_speed_amount":0.1,"mouseover_video_reset_speed_key":["backspace"],"mouseover_ui":true,"mouseover_ui_opacity":80,"mouseover_ui_use_safe_glyphs":false,"mouseover_ui_imagesize":true,"mouseover_ui_zoomlevel":true,"mouseover_ui_filesize":true,"mouseover_ui_gallerycounter":true,"mouseover_ui_gallerymax":50,"mouseover_ui_gallerybtns":true,"mouseover_ui_closebtn":true,"mouseover_ui_optionsbtn":true,"mouseover_ui_downloadbtn":true,"mouseover_ui_rotationbtns":true,"mouseover_ui_caption":true,"mouseover_ui_wrap_caption":true,"mouseover_ui_caption_link_page":true,"mouseover_ui_link_underline":true,"mouseover_use_remote":false,"mouseover_zoom_behavior":"fit","mouseover_zoom_custom_percent":100,"mouseover_zoom_max_width":0,"mouseover_zoom_max_height":0,"mouseover_pan_behavior":"drag","mouseover_movement_inverted":true,"mouseover_drag_min":5,"mouseover_scrolly_behavior":"zoom","mouseover_scrollx_behavior":"gallery","mouseover_scrolly_video_behavior":"default","mouseover_scrolly_video_invert":false,"mouseover_scrollx_video_behavior":"default","scroll_override_page":false,"scroll_zoom_origin":"cursor","scroll_zoom_behavior":"fitfull","scroll_incremental_mult":1.25,"mouseover_move_with_cursor":true,"mouseover_move_within_page":true,"zoom_out_to_close":false,"scroll_past_gallery_end_to_close":false,"mouseover_position":"cursor","mouseover_prevent_cursor_overlap":true,"mouseover_add_link":false,"mouseover_add_video_link":false,"mouseover_click_image_close":true,"mouseover_click_video_close":true,"mouseover_download":false,"mouseover_hide_cursor":true,"mouseover_hide_cursor_after":100,"mouseover_mouse_inactivity_jitter":5,"mouseover_clickthrough":false,"mouseover_links":true,"mouseover_only_valid_links":true,"mouseover_allow_iframe_el":true,"mouseover_allow_canvas_el":false,"mouseover_allow_svg_el":false,"mouseover_enable_gallery":true,"mouseover_gallery_cycle":false,"mouseover_gallery_prev_key":[["left"]],"mouseover_gallery_next_key":["right"],"mouseover_gallery_move_after_video":false,"mouseover_styles":"","mouseover_enable_fade":true,"mouseover_enable_zoom_effect":false,"mouseover_zoom_effect_move":false,"mouseover_fade_time":100,"mouseover_enable_mask_styles":false,"mouseover_mask_styles2":"background-color: rgba(0, 0, 0, 0.5)","mouseover_mask_fade_time":100,"mouseover_ui_styles":"","mouseover_wait_use_el":false,"mouseover_add_to_history":false,"mouseover_close_key":["esc"],"mouseover_download_key":[["s"],["button3"]],"mouseover_open_new_tab_key":["o"],"mouseover_open_bg_tab_key":["shift","o"],"mouseover_open_options_key":["p"],"mouseover_open_orig_page_key":["n"],"mouseover_rotate_left_key":["e"],"mouseover_rotate_right_key":["r"],"mouseover_flip_horizontal_key":["h"],"mouseover_flip_vertical_key":["v"],"mouseover_zoom_in_key":[["+"],["="],["shift","="]],"mouseover_zoom_out_key":[["-"]],"mouseover_zoom_full_key":["1"],"mouseover_zoom_fit_key":["2"],"mouseover_fullscreen_key":["f"],"mouseover_apply_blacklist":true,"apply_blacklist_host":false,"mouseover_matching_media_types":true,"mouseover_find_els_mode":"hybrid","popup_allow_cache":true,"popup_cache_duration":30,"popup_cache_itemlimit":1000,"popup_cache_resume_video":true,"website_inject_imu":true,"website_image":true,"extension_contextmenu":true,"allow_video":true,"allow_dash_video":false,"allow_hls_video":false,"custom_xhr_for_lib":false,"hls_dash_use_max":true,"max_video_quality":null,"allow_watermark":false,"allow_smaller":false,"allow_possibly_different":false,"allow_possibly_broken":false,"allow_possibly_upscaled":true,"allow_thirdparty":true,"allow_apicalls":true,"allow_thirdparty_libs":true,"allow_thirdparty_code":false,"allow_bruteforce":true,"process_format":{},"deviantart_prefer_size":false,"deviantart_support_download":true,"imgur_filename":true,"imgur_source":false,"instagram_use_app_api":true,"instagram_dont_use_web":false,"instagram_gallery_postlink":true,"snapchat_orig_media":true,"tiktok_no_watermarks":true,"tiktok_thirdparty":null,"tumblr_api_key":"xrMpLM8n1eCeL3oRYSZG7CLALw6EHhYDdU6Wq5eD1PbMkld7Y1","bigimage_blacklist":"","bigimage_blacklist_engine":"glob","replaceimgs_enable_keybinding":false,"replaceimgs_keybinding":["shift","alt","r"],"replaceimgs_auto":false,"replaceimgs_replaceimgs":true,"replaceimgs_addlinks":false,"replaceimgs_replacelinks":false,"replaceimgs_usedata":true,"replaceimgs_wait_fullyloaded":true,"replaceimgs_totallimit":8,"replaceimgs_domainlimit":2,"replaceimgs_delay":0,"highlightimgs_enable_keybinding":false,"highlightimgs_keybinding":["shift","alt","h"],"highlightimgs_enable":true,"highlightimgs_auto":"never","highlightimgs_onlysupported":true,"highlightimgs_css":"outline: 4px solid yellow","last_update_check":1606322267170,"last_update_version":null,"last_update_url":null,"settings_version":7}
`

**Comment by PietroPizzi69** [comment]
SORRY!! Forget the last Post. It works with default settings. I just forgot that the mouse over is not default. I changed just that and it works. It now has something to do with my settings. I will figure that out by my self ;). THX for your work!!
