### ISSUE TITLE
[url] assets.website-files.com

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#544]
from: https://assets.website-files.com/5bc63f5a577d83657b247707/5f4564dc5710e4bdb176147a_hero-image%20(1)-p-1600.jpeg

to: https://assets.website-files.com/5bc63f5a577d83657b247707/5f4564dc5710e4bdb176147a_hero-image%20(1).jpeg

(via https://paper.bywetransfer.com )

**Comment by qsniyg** [comment]
Thank you very much!! Supported now :)
