### ISSUE TITLE
klix.ba news

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#548]
Although you made some rules, this is not redirecting.
small: https://static.klix.ba/media/images/vijesti/m11_201203036.jpg?v=3
large: https://static.klix.ba/media/images/vijesti/201203036.jpg?v=4
pages on which such images are found:
small images: https://www.klix.ba/najnovije
large images: https://www.klix.ba/vijesti/bih/sjeca-sume-na-spornoj-granici-bih-i-hrvatske-vidljiva-iz-svemira/201203036

**Comment by qsniyg** [comment]
Thank you!! Should be supported now :)
