### ISSUE TITLE
open replaced links in new tab

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#550]
I liked ability to be able to replace only links and make links if not available to images on current site.
However when I replace and add links, then some links are still not clickable via right click and if left clicked first they try to open what would they normally open and image, but even if it was only image, it is annoying to have to go back to page later.
If I press ctrl + right click then image opens in new tab but so does default action of click made by website.
Can you add ability to make all those added and replaced links open in new tab by default so I don't have to hold crtl, just like that exists for popup?
Example link (that larger image to the right): https://www.olx.ba/artikal/40721215/hard-disk-2-5-laptop/
I used options in Replace Images:
Replace images: no
Add links: yes
Replace links: yes

Wanna see another option: open those links in new tab

**Comment by qsniyg** [comment]
Great idea, thank you!! I've added it in :)

That said, for the website you linked, it doesn't work on the lightbox, only on the thumbnails. I believe this is because the lightbox has javascript handlers. I'll create a new issue for that, but the fix would be relatively hacky.
