### ISSUE TITLE
image shown as text (symbols)

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#554]
https://www.wakshitvs.com/index.php?main_page=product_info&products_id=494143
When opened in new tab by popup feature.
e.g. https://www.wakshitvs.com/send_imgs.php?img=abe91d36bea45a343609fca197da54079HR0cHM6Lybe91d36bea45a343609fca197da540799pbWFnZXMtbmEuc3NsLWltYWdlcy1hbWF6b24uY29tL2ltYWdlcy9JLzUxLTk0JTJCWkFTMUwuX1VMMTIwMF8uanBn
The same happens even without extension, for example by inspect element in chrome.
If response headers could be set or something.

**Comment by qsniyg** [comment]
Yeah it looks like a server bug to me. However, the URL is some weird combination of hex and a base64 URL, so it should be possible for the script to redirect to the original URL... let me see if I can figure it out :)

**Comment by qsniyg** [comment]
Wow what a strange system... they just insert a specific hex value (`be91d36bea45a343609fca197da54079`) twice for no seemingly good reason. It's a generic system, not specific to the site you linked, I believe it's related to zencart (though I don't know if it's an addon or part of the distribution), but the hex value remains constant. I thought it might have been a signature or perhaps a license key or something, but unless it's bugged, that doesn't appear to be the reason. Genuinely no idea what's the purpose of doing it like that haha.

Anyways, should be supported now, thanks for reporting! :)
