### ISSUE TITLE
rediff

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#564]
small: https://imshopping.rediff.com/imgshop/300-400/shopping/pixs/16284/u/untitled_5c514820cdbb6._set-of-2-polyester-spandex-beautiful-flower-and-girl-print-jeans-code-2jegging-.jpg
large: https://imshopping.rediff.com/imgshop/800-1280/shopping/pixs/16284/u/untitled_5c514820cdbb6._set-of-2-polyester-spandex-beautiful-flower-and-girl-print-jeans-code-2jegging-.jpg
ref: https://shopping.rediff.com/product/set-of-2-polyester-spandex-beautiful-flower-and-girl-print-jeans-code-2jegging-/24839195?sc_cid=www.google.com|search_printed-jeggings

**Comment by qsniyg** [comment]
Thank you very much!!

Turns out there's a way to get an even larger version of the image: If you just remove the numbers entirely and go for `/-/`, it seems to display the original version!
