### ISSUE TITLE
e-hentai ehgt *.hath.network

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#569]
small: https://ehgt.org/t/b2/d6/b2d62f7eebedec2db43c2052ebae68f078b95c51-288186-750-1000-jpg_l.jpg
large: https://wtcywbu.yfvazqkqbstu.hath.network/h/8b254ad5c4235de42b8b3072e85100fd01069e96-90244-750-1000-jpg/keystamp=1607890500-e1a76ec972;fileindex=87376758;xres=980/En1O6wcVkAIVdjA.jpg
ref: https://e-hentai.org/lofi/g/1799021/4eaf6c436a/

**Comment by qsniyg** [comment]
I forgot how awful the e-hentai rule was haha. I've mostly rewritten it, should work now :)

A bit more work still needs to be done though, e.g. to find the full version when you're in a lofi image page (rather than the gallery).
