### ISSUE TITLE
VSCO support

### ISSUE THREAD

**Issue by modelfe** [qsniyg/maxurl#57]
Would it be possible to support VSCO images? 

Here's an example image, which would change from:
https://image-aws-us-west-2.vsco.co/00b02e/28967640/5cdace744c51282134f55d8c/735x1024/vsco5cdace96a2daa.jpg
to:
https://image-aws-us-west-2.vsco.co/00b02e/28967640/5cdace744c51282134f55d8c/vsco5cdace96a2daa.jpg

You can find an endless number of images to test on here (no account needed): https://vsco.co/feed

Thanks, I love this addon!

**Comment by qsniyg** [comment]
Thank you very much! I've added it in :)

It seems that the im.vsco.co links redirect automatically to the image-aws-... links, so I didn't add support for those, but if you find anything missing, let me know!

**Comment by modelfe** [comment]
This works perfectly for newer posts, but it seems that older im.vsco.co links don't redirect. Here's one such  example: https://vsco.co/inkawilliams/media/5603ae65d3dca50b0760e937

Thanks again! :)

**Comment by qsniyg** [comment]
@modelfe Thank you! I've added support for them too now :)
