### ISSUE TITLE
decathlon

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#572]
small: https://contents.mediadecathlon.com/p1894357/k$fcbb88bf54b4b21d10c0a14264cbc0d3/sq/Kids+Athletics+Tights+AT+100+faded+neon+coral.webp?f=250x250
large: https://contents.mediadecathlon.com/p1894357/k$fcbb88bf54b4b21d10c0a14264cbc0d3/sq/Kids+Athletics+Tights+AT+100+faded+neon+coral.webp
ref: https://www.decathlon.co.uk/browse/c0-kids/c1-clothing/c3-leggings/_/N-tk7qy

**Comment by qsniyg** [comment]
Thank you very much, as usual! :) Should be supported now.

I haven't seen this system before either. I'm guessing it's custom?
