### ISSUE TITLE
aliexpress (alicdn)

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#578]
https://ae01.alicdn.com/kf/HTB1TQqIOpXXXXbhXXXXq6xXFXXX3/Leggings-Fitness-Women-Sexy-Women-Jean-Skinny-Jeggings-Fake-Ripped-Holes-Pocket-Print-Stretchy-Slim-Leggings.jpg_Q90.jpg_.webp
and without _.webp:
https://ae01.alicdn.com/kf/HTB1TQqIOpXXXXbhXXXXq6xXFXXX3/Leggings-Fitness-Women-Sexy-Women-Jean-Skinny-Jeggings-Fake-Ripped-Holes-Pocket-Print-Stretchy-Slim-Leggings.jpg_Q90.jpg
I thought you had alicdn rule, or is this some exception?

**Comment by qsniyg** [comment]
Yeah, it was evidently incomplete. I've added support for removing `_.webp` and `_Q[0-9]+.jpg`, which should result in `https://ae01.alicdn.com/kf/HTB1TQqIOpXXXXbhXXXXq6xXFXXX3/Leggings-Fitness-Women-Sexy-Women-Jean-Skinny-Jeggings-Fake-Ripped-Holes-Pocket-Print-Stretchy-Slim-Leggings.jpg`
