### ISSUE TITLE
Add update manifest for chrome auto-update

### ISSUE THREAD

**Issue by qsniyg** [qsniyg/maxurl#581]
Continuing from #28, thanks to @raisehero for the idea.

Relevant links: https://github.com/NeverDecaf/chromium-web-store/commit/0464d762a6ee6073906e6550d975a12e0901502c

https://github.com/NeverDecaf/chromium-web-store/blob/master/updates.xml

https://github.com/NeverDecaf/chromium-web-store/blob/master/src/manifest.json

The idea is to have a fixed path (forever) for the built extension to be stored. Probably in build?

**Comment by raisehero** [comment]
Latest will always point to the latest release on GitHub releases.

**Comment by qsniyg** [comment]
This should (theoretically) work now :)

Sorry for getting back so late in fixing this!
