### ISSUE TITLE
booklive.jp

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#587]
`https://res.booklive.jp/883771/001/thumbnail/2L.jpg` -> `https://res.booklive.jp/883771/001/thumbnail/X.jpg`
`https://res.booklive.jp/185887/001/thumbnail/M.jpg` -> `https://res.booklive.jp/185887/001/thumbnail/X.jpg`

Found from Google, not sure if there are other variants.

**Comment by qsniyg** [comment]
Thank you very much! Should be supported now :)

I tried a `{A..Z}` test, and only found the ones listed in the rule (S, M, l, and of course X). L seemed to be the only one supporting `2L`, S, M, and X didn't seem to support a 2 prefix. Haven't tested other numbers yet.

**Comment by Tenome** [comment]
I seem to have encountered a book that doesn't trigger for some reason. Does this work for anyone else? Not sure what's different about it.
https://res.booklive.jp/114012/009/thumbnail/2L.jpg

https://booklive.jp/product/index/title_id/114012/vol_no/009

**Comment by Tenome** [comment]
Just now remembered to check the console log since it happened again. It's not being recognized as an image for some reason?

https://res.booklive.jp/100937/001/thumbnail/2L.jpg

`https://res.booklive.jp/100937/001/thumbnail/X.jpg Image Max URL.user.js:382:26

Error: Not an image: (no content-type) Image Max URL.user.js:94640:20
    cb moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/ Image Max URL.user.js#157:94640
    onload_cb moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/ Image Max URL.user.js#157:94487
    onprogress moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/ Image Max URL.user.js#157:94530
    Le moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/sandbox/injected-web.js:1
    HttpRequested moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/sandbox/injected-web.js:1
    onHandle moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/sandbox/injected-web.js:1
    Ge moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/sandbox/injected-web.js:1
`
