### ISSUE TITLE
instagram profile pictures not redirecting in new tab

### ISSUE THREAD

**Issue by DirtyGoblinLegislator** [qsniyg/maxurl#588]
I noticed they redirect to large images only in popup, but not in new tab. Option is enabled.
Sample:
https://scontent-muc2-1.cdninstagram.com/v/t51.2885-19/s150x150/109136688_610125179899980_1868015297406610141_n.jpg?_nc_ht=scontent-muc2-1.cdninstagram.com&_nc_ohc=sIzjrupgG78AX_XNjIB&tp=1&oh=0b51845d51b5b57e5c0c14ec6d651719&oe=601BCE22

**Comment by qsniyg** [comment]
Yeah, unfortunately it's impossible (afaik) to get a larger version from redirection, as I don't know of any way to find the information about the source of the photo from the photo itself (this is, perhaps surprisingly, in contrast to Facebook where it's usually possible to _some_ degree to do so).

Instagram was actually the reason I added the popup in the first place, it used to be only redirection before that.
