### ISSUE TITLE
avaz.ba waiting forever

### ISSUE THREAD

**Issue by DirtyGoblinLegislator** [qsniyg/maxurl#589]
Cursor shows waiting animation, and nothing happens.
When this opened in new tab: https://avaz.ba/media/2021/01/02/1407640/thumbs/240x225.jpg
Possibly upscaled images are turned on.
When opened in new tab. While in popup the image that appears (redirected) when opened in new tab also displays waiting cursor.

**Comment by qsniyg** [comment]
Does https://github.com/qsniyg/maxurl/commit/c5db76bc56a3e688e66ec9c4ef8649df709b2fb8 fix it for you? It fixes it for me, but the log you provided doesn't seem to corroborate with the issue strangely...

**Comment by DirtyGoblinLegislator** [comment]
Now works, thanks!
