### ISSUE TITLE
Behance support

### ISSUE THREAD

**Issue by rahidz** [qsniyg/maxurl#59]
The resolution parameter after "project_modules" can be changed to "source" for the original image.

Example:

https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/27452674022631.5c1db814e8a02.jpg

to

https://mir-cdn.behance.net/v1/rendition/project_modules/source/27452674022631.5c1db814e8a02.jpg

**Comment by qsniyg** [comment]
Thanks! I noticed many URLs started to fail with /fs/, but I didn't know /source/ existed! It's now the default, and /fs/ is now the fallback :)
