### ISSUE TITLE
Support for Nintendo64Ever

### ISSUE THREAD

**Issue by CetaceanNation** [qsniyg/maxurl#590]
Easy rule to hardcode, doesn't appear to exist elsewhere in the plugin yet.

Site: http://www.nintendo64ever.com

Example:
Thumbnail: http://www.nintendo64ever.com/scans/boites/thumbnails/007--Le-Monde-ne-Suffit-pas-4-scan-boite-avant_178x127.jpg
Full size: http://www.nintendo64ever.com/scans/boites/007--Le-Monde-ne-Suffit-pas-4-scan-boite-avant.jpg

Currently I just use a small userscript matching the URL `http://www.nintendo64ever.com/scans/*/thumbnails/*` and redirecting me with
```js
window.location.href = window.location.href.replace('thumbnails/','').replace(/(_\d+x\d+)/,'');
```
although to match most of the userscript you'd probably swap `\d` with `[0-9]`.

**Comment by qsniyg** [comment]
Thank you very much!! Supported now :)
