### ISSUE TITLE
BBC tracklist images no longer work

### ISSUE THREAD

**Issue by Anamon** [qsniyg/maxurl#595]
The rules no longer work for the pictures that go with the tracklists of BBC Radio music programmes.

**Example URL:** https://www.bbc.co.uk/programmes/m000qh8r

The rule works for the main picture of the programme:
`https://ichef.bbci.co.uk/images/ic/640x360/p090gspf.jpg` -> `https://ichef.bbci.co.uk/images/ic/raw/p090gspf.jpg`
but not for the little square images in the tracklist, such as
`https://ichef.bbc.co.uk/images/ic/96x96/p01bqjml.jpg`
If I replace `96x96` with `raw` manually, I get the full resolution.

Note `bbc.co.uk` vs. `bbci.co.uk`. The extension used to work for these pictures as well, so it's possible they have moved some things around.

**Comment by qsniyg** [comment]
Thank you very much for reporting! Fixed :)
