### ISSUE TITLE
Add support for imgrock_net,kropic_com and kvador.com

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#600]
Would it be possible ?

Some time ago I found links referring to these places.
Would be nice to add support to read from them.

Links:
[https://imgrock.net/](url)
[https://kropic.com/](url)
[https://kvador.com/](url)

**Comment by qsniyg** [comment]
Thank you very much! I remember trying to support imgrock a while back actually, but it's not possible due to requiring a captcha in order to find the image url (so it can't be found automatically). The other two however, I've added support for :)

**Comment by elvisef** [comment]
Nice, thanks : ) 
Kropic checked - works. 
Kvador - do not know, but problably yes. Unfortunately I had links, where thumbnails were visible and I was wondering why big size is not being showed by the script, but after checking the source URL - pictures were deleted. So I will check next time I have working Kvador links.
