### ISSUE TITLE
Can't resize imgbox_com images

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#603]
I've just checked a gallery with this hosting images and no images were replaced.

The FF console log looks like this:
![firefox_2021-01-06_18-42-26](https://user-images.githubusercontent.com/25976749/103802215-18952c80-504f-11eb-8ce8-7255a7c25780.png)

So hmm.. looks good, as images were probably checked but.. nothing changed.
This was checked without any addons, using the newest MAXurl addon for FF.

And that's how the process bar looks like (looks like it freezes or sth):
![firefox_2021-01-06_18-45-33](https://user-images.githubusercontent.com/25976749/103802457-73c71f00-504f-11eb-8012-ae00d9aaa078.png)

**Comment by qsniyg** [comment]
Can you send an example image (or page) that doesn't work?

This one works for me:

`https://thumbs2.imgbox.com/6b/e7/rklghXlY_t.jpg` -> `https://images2.imgbox.com/6b/e7/rklghXlY_o.jpg`

**Comment by elvisef** [comment]
> 
> 
> Can you send an example image (or page) that doesn't work?
> 
> This one works for me:
> 
> `https://thumbs2.imgbox.com/6b/e7/rklghXlY_t.jpg` -> `https://images2.imgbox.com/6b/e7/rklghXlY_o.jpg`

One example is: `https://images3.imgbox.com/6d/4f/dhieHdaK_o.jpg`

I think it's about the pattern of the server (sub)domain names.
images1,2,3,4...etc.. or thumbs1,2,3,4...etc..

**Comment by qsniyg** [comment]
`_o` is the original image for imgbox, so it probably did redirect properly... is this the same issue as https://github.com/qsniyg/maxurl/issues/593#issuecomment-754609502, where it's that the images aren't physically larger?

**Comment by elvisef** [comment]
> 
> 
> `_o` is the original image for imgbox, so it probably did replace properly... is this the same issue as [#593 (comment)](https://github.com/qsniyg/maxurl/issues/593#issuecomment-754609502), where it's that the images aren't physically larger?

Not really. This is a source link redirecting to the image: `http://imgbox.com/dhieHdaK` - You can check it Yourself.
For a quick check I alwasy use ImagePicka to get images from the current page, moreover I am checking if original, big size images are loading successfully. So here, it does nothing, nothing changes.

**Comment by qsniyg** [comment]
Sorry, I'm still confused as to what the issue is. If the url of the image ends with `_o`, then it won't replace it, as it's the original image (so nothing to replace to). If this is the case, what is the intended result you're looking for?

**Comment by elvisef** [comment]
The result URL (after HandyImage read it, so it's original URL) is:
![2021-01-07_14-47-48](https://user-images.githubusercontent.com/25976749/103899917-69606000-50f7-11eb-9421-c8570decbd53.png)
And the link to the BIG size image is: `https://images3.imgbox.com/6d/4f/dhieHdaK_o.jpg`

This is how the "a" tag code looks like (BEFORE I click on it to open, but I do not want to open it of course directly):
![firefox_2021-01-07_14-47-30](https://user-images.githubusercontent.com/25976749/103899921-6b2a2380-50f7-11eb-932e-50712f90dcd8.png)

When I run MaxURL on links like this (let's say there are 50 links on one page, so it's a some kind of gallery), no images links are changing. In the code inspector I still see thumbnails only: `https://8-t.imgbox.com/dhieHdaK.jpg`.

So even ImagePicka with constraints of minimum 100x100 px and 10kB of size is not able to find any images, beacuse thumbnails are smaller or can't reach even 10KB.

Try to add this "a" tag code to the clean html page:
`<a href="http://imgbox.com/dhieHdaK" target="_blank" class="link link--external" rel="noopener">
	
	
		
		
	


	<div class="lbContainer lbContainer--inline" data-xf-init="lightbox" data-lb-single-image="1" data-lb-container-zoom="1" data-lb-trigger=".js-lbImage-_xfUid-95-1610020843" data-lb-id="_xfUid-95-1610020843">
		
			<div class="lbContainer-zoomer js-lbImage-_xfUid-95-1610020843" data-src="https://8-t.imgbox.com/dhieHdaK.jpg" aria-label="Zoom"></div>
		
		<img src="https://8-t.imgbox.com/dhieHdaK.jpg" data-url="https://8-t.imgbox.com/dhieHdaK.jpg" class="bbImage" data-zoom-target="1" alt="dhieHdaK.jpg" title="dhieHdaK.jpg">
	</div>

</a>`

and see what happens, and if it replaces images : )

**Comment by qsniyg** [comment]
Ah I see what the issue is now, it's because the short url format was just assumed to be redirected. Should be supported now :)

**Comment by elvisef** [comment]
Nice to hear I was finally understood : D
But.. it still does not seem to work.

Can You recheck this please ?
No images are replaced, still thumbnail images are present on page.

I've updated MaxURL to the newest version just a moment ago.

**Comment by qsniyg** [comment]
Weird, I don't understand... I tried with the code snippet you sent in a blank html page, and it works fine for me...

Can you send your settings? I have no idea what's causing this on your end, sorry...

**Comment by elvisef** [comment]
Alright, I will recheck this. And I will send You my settings.
I know it's weird, but I will try with completely clean Firefox now - new clean profile, with maxurl only, and will see.

**Comment by qsniyg** [comment]
You can also reset to the defaults by importing `{}` (but remember to export first in order to avoid losing your settings :)

**Comment by elvisef** [comment]
It Works !!!
I've exported first and then I tried new clean profile FF - worked. Then I tried in my current profile - worked as well - of course I've updated MaxURL before checking.

So Yes, it works now, thank You : ) 
We can close the issue now.
