### ISSUE TITLE
max url for www.nhm.ac.uk wildlife photographer of the year please

### ISSUE THREAD

**Issue by arovane** [qsniyg/maxurl#605]
sample page: https://www.nhm.ac.uk/wpy/gallery/2019-wild-asses-in-a-wild-land?tags=ed.8
webp displayed: https://www.nhm.ac.uk/resources/visit/wpy/2019/large/webp/19.webp
jpg opened by mouse gesture: https://www.nhm.ac.uk/resources/visit/wpy/2019/medium/19.jpg
max size jpg: https://www.nhm.ac.uk/resources/visit/wpy/2019/large/19.jpg
please add, thank you!

**Comment by qsniyg** [comment]
Thank you very much! I can't seem to find a way to find the original image though, all the `/large/` ones appear to be scaled down to 2560x* width (though at least they are not upscaled either).
