### ISSUE TITLE
imagebam_com - hosting re-check

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#607]
Hello.

I've found images like this one `http://www.imagebam.com/image/782a951254529604`.
A link to the image for the above link is `http://thumbs2.imagebam.com/c9/13/b9/782a951254529604.jpg`.
But if I click it, it redirects me to `http://www.imagebam.com/image/782a951254529604` where I see only "loading" message. 
But a "HandyImage" script loaded in my Firefox makes it to redirect directly to the image at `https://images2.imagebam.com/62/5b/28/782a951254529604.jpg` which is non existent content ? (I see 404 error, not found)

But... I found out that changing "images2" to "images" will show me the full sized image.

Can U check this one to make it work with MaxURL ?

**Comment by qsniyg** [comment]
It works for me... and `https://images2.imagebam.com/62/5b/28/782a951254529604.jpg` works for me too (and is in fact what image max url redirects me to when I go to the thumbs2 url).

Can you double check to make sure your dns settings are correct? And perhaps try pressing ctrl+shift+r to reload and clear cache.

If it still fails, since you said `images.imagebam.com` works, try replacing these lines:

```
					done({
						url: ogimage,
						is_original: true,
						headers: {
							Referer: "https://www.imagebam.com/"
						},
```

To this:

```
					done({
						url: ogimage.replace(/\/\/images[0-9]*\./, "//images."),
						is_original: true,
						headers: {
							Referer: "https://www.imagebam.com/"
						},
```

**Comment by elvisef** [comment]
Tried the "dig" and hmmm weird... `images.imagebam.com` indeed points to IP You've mentioned, but "images2" not really.. it points to my localhost... I'm just wondering if it is blocked, but why ? Ehh... to much vpn's, firewalls and antiviruses apparently : ]

But this change, where do I need to change this exactly ? I mean, which file ? I am talking about FF addon, not the script for "monkey".

**Comment by qsniyg** [comment]
>but "images2" not really.. it points to my localhost... I'm just wondering if it is blocked, but why ? 

Yeah I believe that would indicate some kind of local configuration issue...

>But this change, where do I need to change this exactly ? I mean, which file ? I am talking about FF addon, not the script for "monkey".

It's in "userscript.user.js", the ff addon uses it too (even though it's named as a userscript, it functions as a userscript, a content script for webextensions, a normal script for browsers, and a library for node.js).
