### ISSUE TITLE
Support for bear-family.com

### ISSUE THREAD

**Issue by nimuxoha** [qsniyg/maxurl#608]
On items pages original images can be found in `data-img-original` although in a `span` element
e.g https://www.bear-family.com/various-james-dean-birthday-celebration-cd.html

Original:
https://www.bear-family.com/media/image/d4/b5/e2/5397102175718a.jpg

When multiple images exist thumbnails are displayed and `href` original images:
e.g. https://www.bear-family.com/various-talking-on-the-telephone-rock-n-roll-and-teen-pop-cd.html

There, Image Max URL grabs the thumbnails instead of the large ones:
https://www.bear-family.com/media/image/52/2e/79/5397102175992_200x200.jpg
-> https://www.bear-family.com/media/image/9b/6c/68/5397102175992.jpg

If you use their own gallery viewer they also embed originals directly and Image Max URL works as expected.

There are other images on item pages (sample player, similar products, etc.) but there seem to be no hints to original URLs unfortunately.

On the [front page](https://www.bear-family.com/) `picture` elements are used but again no original URLs in sight.

**Comment by qsniyg** [comment]
Thank you!! I've added support for both types of rules :)
