### ISSUE TITLE
What is fastest way to update extension in Firefox?

### ISSUE THREAD

**Issue by GoblinLegislator** [qsniyg/maxurl#609]
I am currently using Chrome and find downloading zip file or using some Git app very fast to immediately use latest version.
But in Firefox I have to wait until new version. Is there faster way to get last version in Firefox?
I've heard extension sideloading ability being removed...so what is the solution? I believe userscript is also not getting updated as it is on github and having restrictions compared to extension.

**Comment by qsniyg** [comment]
Honestly, I don't know myself. Personally, I use `about:debugging` to sideload it, but of course that comes with the downside of having to do it each time you open firefox (and losing your settings in some cases, seems to be rather inconsistent though, not sure what causes it).

Slight rant here, but... Firefox will of course let you use `about:config` to change pretty much everything about the browser, including seriously compromising your security, or rendering the browser permanently unusable (save for deleting your profile) ... but they don't allow you to install extensions they don't explicitly approve (or rather, the switch doesn't work on non-developer builds). To my knowledge, they were the first browser to do this (at the time, even safari didn't force this, though they obviously quickly followed suit). To be clear, this is not necessarily coming from a personal perspective, I don't think my addon will be targeted for removal (though obviously this causes issues with using git builds, as your question stated), I just really disagree with them doing this.

My personal recommendation would be to perhaps use a browser like Waterfox (or another fork), which allows you to install unsigned addons.

**Comment by GoblinLegislator** [comment]
Actually I use developer edition and can install unsigned addons. So I just use last extension version from AMO and replace few files with updated ones (userscript.user.js...) from github?

**Comment by qsniyg** [comment]
Sure, or you can run `./tools/package_extension.sh`, which will generate `extension.xpi` for you
