### ISSUE TITLE
animageplus.jp

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#610]
https://animageplus.jp/articles/gallery/34894/62760

`https://images.animageplus.jp/articles_photos/34000/34894/478x850/276f60fb5e84e158be6d6c818528d9c7.jpg`
`https://images.animageplus.jp/articles_photos/34000/34894/231x410/276f60fb5e84e158be6d6c818528d9c7.jpg`
---> `https://images.animageplus.jp/articles_photos/34000/34894/ORG/276f60fb5e84e158be6d6c818528d9c7.jpg`

**Comment by qsniyg** [comment]
Thank you very much as usual!! :)

**Comment by fireattack** [comment]
Yeah I vaguely remember seeing something similar too. Maybe from some CMS solutions they both use.
