### ISSUE TITLE
Force the size of displayed replaced images on page

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#614]
Hello.

Is there a way to force displaying replaced images in defined width and/or height ?
Imagine I have "broken" links from imagebam server - links look like this:

`<a href="https://images2.imagebam.com/53/30/30/b47a851340915364.jpg" target="_blank" rel="noopener" class="mycode_url"><img src="https://images2.imagebam.com/53/30/30/b47a851340915364.jpg" alt="[Image: b47a851340915364.jpg]" class="mycode_img" style="height: auto !important; width: auto !important;"></a>`

So the thumbnail works. But images2. return 404 ?! I tried many methods, ublock disable, ghostery, new profiles etc... nothing worked. Even tried to other VPN servers, no VPN servers, nothing worked at all.

The thing is (I wrote it in another issue already) that changin "images2" to "images" in A href works, and the image is shown.

Alright so if I have situation like this, no images, no tjumbnails are being shown, but in clean new FF profile MaxURL can do the thing and show LARGE images (yes, from these "broken" links), I need to scroll down to see any downloads links, or to choose images I am interested in. These images are too big. I wish to  have option to say replace images to big sized, on page, but for example force to show them in 400px height max. So I would not need to scroll down for hours from the first to the last one.

It's chaotic what I wrote but maybe You will understand it : ]

**Comment by qsniyg** [comment]
I've added a new "Replacement CSS" option with https://github.com/qsniyg/maxurl/commit/3caec939cccb4597f70bb1c6602fb8d0f1b11c3c, try setting it to `max-height: 400px` :)

**Comment by elvisef** [comment]
Genius ! :D
Love this option now. 
Thanks !
