### ISSUE TITLE
[support] imgsen_com hosting

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#615]
A source looks like:

`<a href="https://imgsen.com/text1/text2.jpg.html" target="_blank" rel="noopener" class="mycode_url"><img src="https://imgsen.com/i/00005/text1_t.jpg" alt="[Image: text1_t.jpg]" class="mycode_img"></a>`

A full sized image is:

`https://imgsen.com/img/probably_generated_string/text2.jpg`

Sorry, no non-nsfw links found for this hosting ; /

But maybe You'd like to support it ? : )

**Comment by qsniyg** [comment]
Thank you!! Same system as kropic/kvador :)
