### ISSUE TITLE
Issue with deviantART urls

### ISSUE THREAD

**Issue by MrSeyker** [qsniyg/maxurl#616]
I'm once again experiencing issues with the script not recognizing higher quality urls for deviantART.

This is the url where I realized there was an issue:

[URL](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/80619ff1-0edb-4915-af7f-f2b8dd0fe6c1/d5sh28w-4850c99e-7eda-48bb-8af0-d235f9d58d21.png/v1/fill/w_600,h_849,q_80,strp/mario_style___commission_by_vaultman_d5sh28w-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD04NDkiLCJwYXRoIjoiXC9mXC84MDYxOWZmMS0wZWRiLTQ5MTUtYWY3Zi1mMmI4ZGQwZmU2YzFcL2Q1c2gyOHctNDg1MGM5OWUtN2VkYS00OGJiLThhZjAtZDIzNWY5ZDU4ZDIxLnBuZyIsIndpZHRoIjoiPD02MDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.bG-4ySZNAkdIH9UOqUYbweV8enEDYpBR2G4UapY4zX4) 

I can change it manually to get the full resolution

[Correct URL](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/intermediary/f/80619ff1-0edb-4915-af7f-f2b8dd0fe6c1/d5sh28w-4850c99e-7eda-48bb-8af0-d235f9d58d21.png)

Don't understand why it's not working anymore. Maybe some setting I'm missing?

EDIT:

Error is in version 0.16.0. Downgraded to 0.15.1 and the redirection is working properly.

**Comment by qsniyg** [comment]
It works fine for me... can you send your settings? (settings->export)

**Comment by MrSeyker** [comment]
I'm using greasemonkey 4.10.0 on Firefox mobile (68.3.0).

The script version of 0.16.0 I used was from userscripts, but I also tried to install from here.

The downgrade to 0.15.1 was from here.

Although I can't say it works flawlessly, as I tried another deviantART url from a picture thumbnail, and the redirection to a higher quality copy worked, but it never showed the pop up to download using the deviantart method (the picture has downloads enabled and that one was higher quality than the redirected image, it even kept the original deviantart filename).

This has happened before, I issued this same problem in version 0.14.2 or 0.14.3.

The pop up should be showing up according to the settings. Show image url in tooltip is enabled, and use of download links fo deviantart is enabled.

**Comment by qsniyg** [comment]
Hmm weird, it works for me under Greasemonkey too (desktop though, not mobile ... unfortunately I can't test under mobile as I don't have a working phone to test with at the moment).

>the picture has downloads enabled and that one was higher quality than the redirected image, it even kept the original deviantart filename

Are you sure it's for the image you sent? I can't find a way to download it from the deviantart website, and there's no "download" property in the json object for the one you sent...

>Yeah, 0.16.0 just doesn't install properly, it basically locked down the browser and had to kill the app in order for it to start working. And the script still didn't register despite greasemonkey showing it.

Does the image max url addon work? Or does using another userscript manager (like tampermonkey/violentmonkey) work? (others like usi don't work properly, there's some kind of bug on their end for a number of different issues, I'm still in the process of debugging it)

**Comment by qsniyg** [comment]
Can you test with the latest git version (https://github.com/qsniyg/maxurl/commit/2c0d019e03b29bcbbfc405019d24b2c37c161f06)? It should work in theory.

**Comment by MrSeyker** [comment]
> Can you test with the latest git version ([2c0d019](https://github.com/qsniyg/maxurl/commit/2c0d019e03b29bcbbfc405019d24b2c37c161f06))? It should work in theory.

Ok, the 0.16.0 is now installing properly on Firefox mobile with Greasemonkey.

> Are you sure it's for the image you sent? I can't find a way to download it from the deviantart website, and there's no "download" property in the json object for the one you sent...

No, it was another picture [this one](https://www.deviantart.com/japunix/art/Dakota-VB-288060617)

The working script redirects to [this url](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/intermediary/f/045ef501-f9c6-4448-a7ac-90eaeb8c0bcd/d4ri4zt-a63fdb61-5b17-4afa-8a71-bcd6a03dc2b7.jpg), but the tooltip to download never shows up (it does for tumblr, so tooltips themselves work).

The settings are as I explained in the other post.

Behavior on mobile has not changed. Successfully redirects, doesn't show download tooltip.

I'll try to test the latest script in desktop later today to see if the tooltip issue is restricted to mobile or not.

Sorry for the radio silence.

**Comment by qsniyg** [comment]
Strange, it redirects fine for me (to the download url). The userscript version shows the tooltip, and the extension version redirects to the download url without the tooltip (as it can override the headers, so it's able to redirect without needing the popup). Since I can't currently test under mobile, I've tested it under waterfox classic, which uses an older rendering engine.

However, it only works when I'm logged into DA. If I'm not logged in, it won't work (DA's download url returns 404). Could this be the case for the mobile version?

>The settings are as I explained in the other post.

Are you referring to https://github.com/qsniyg/maxurl/issues/616#issuecomment-759839999? I've tried with the settings you mentioned, but it still works for me.

If logging into DA doesn't fix it, can you send your exported settings (through the "Export" button at the top)? It's not unlikely that there's some other setting that interferes with this. Alternatively, you could also try importing `{}`, which will reset all settings to their defaults. Basically I'm just trying to have our environments match as much as possible so that I'm able to replicate the issue on my end, so I can fix it :)

**Comment by MrSeyker** [comment]
Just tested on mobile and desktop, and can confirm that the 0.16.1 version of the script is working fine.

The trick for the download tooltip on deviantART was indeed to be logged to my account. I wasn't logged in on firefox mobile because it's not my primary browser (I only use it when I need to work some extension or run some script). The latest version of the script is working as intended.

I still have have one last trouble link, [this one](https://www.deviantart.com/hugotendaz/art/Rosetta-The-Best-Buns-Cartoony-PinUp-Comm-729023803). The script currently redirects to [this](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/intermediary/f/a776a3e5-3e6f-4f61-89b7-1724ab9c2567/dc21id7-2610a389-46ea-4388-83ec-e144cfa0b73c.jpg), which is a jpeg that weights 42kb.

However, the version that can be viewed without redirection [here](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/a776a3e5-3e6f-4f61-89b7-1724ab9c2567/dc21id7-2610a389-46ea-4388-83ec-e144cfa0b73c.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvYTc3NmEzZTUtM2U2Zi00ZjYxLTg5YjctMTcyNGFiOWMyNTY3XC9kYzIxaWQ3LTI2MTBhMzg5LTQ2ZWEtNDM4OC04M2VjLWUxNDRjZmEwYjczYy5qcGcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.a2r6yvXOnOCD3TTPWd0JK9VBqJghR-NqaaAnhCQTr-0) is actually better quality, weighting about 70kb and with far less jpeg artifacts.

Not sure if a setting can be created to have the script not redirect on deviantART when the original url provides better quality than the redirection.

But that's another issue entirely, the problem with the script on mobile has been solved.

**Comment by qsniyg** [comment]
Thank you! Should be fixed with https://github.com/qsniyg/maxurl/commit/44a0773b273a102224039f509dc1fe3dbd23f0ba :)

**Comment by MrSeyker** [comment]
Ok, I tested with some older pictures in my favourites that redirecting via intermediary resulted in lower quality and the script detects that and takes me back to the higher quality version. As far as I have been able to test, everything seems to be working fine now.

Only suggestion I have is to update the options to make it clear that the download option for deviantART requires an account.

**Comment by qsniyg** [comment]
Thank you! Fixed with https://github.com/qsniyg/maxurl/commit/2c28d32bbc59f5de234f13e017f160e0a44da0cf :)
