### ISSUE TITLE
New config option for "broken" images links

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#617]
I've found many pages with such links, that seems to be broken but HandyImage loads them without effort.
![2021-01-14_09-05-28](https://user-images.githubusercontent.com/25976749/104562089-28f96880-5648-11eb-8315-4facf84142b2.png)

The problem here is (I think) that there are A tags only, without IMG.
![firefox_2021-01-14_09-05-41](https://user-images.githubusercontent.com/25976749/104562153-4595a080-5648-11eb-93ce-515a793169c8.png)

Example:
`<a href="http://img102.imagetwist.com/th/05195/3hb2c9gh0s7m.jpg" target="_blank">http://img102.imagetwist.com/th/05195/3hb2c9gh0s7m.jpg</a>`

full sized image: `https://img102.imagetwist.com/i/05195/3hb2c9gh0s7m.jpg/fa24120831.jpg`

Do we have such option, or eventually would it be possible to add an option to add an IMG tag inside/outside (or wherever better) A tag ? So images would be shown. Maybe it's my DNS settings, but without IMG tag I would not expect t oimage being shown. Maybe some anti-scripts are blocking it (JS shows images using these A tags only?).

**Comment by qsniyg** [comment]
Are you referring to replacing images (in this case, plain hyperlinks->full images), or opening them in the popup? If you're referring to the former, not yet, I'll have to add that feature.

For the latter however, just enable the "popup for plain hyperlinks" option, and you should be good to go :)

**Comment by qsniyg** [comment]
I've added support for replacing plain hyperlinks here: https://github.com/qsniyg/maxurl/commit/dc317e2a2f611923534d160a7229ae5ae363308a

I haven't yet done much extensive testing though, only on a simple webpage with a link so far, so if there are any issues, please report them! :)

**Comment by elvisef** [comment]
Alright, thanks for effort : )

But... I've just checked it and hmm.. it does not work for me.

Please test using this URL: [testing url](http://www.phforum.com/forum/index.php?s=59e67436e08498772339fc581e1bbf85&showtopic=198388&st=0&p=1120373) - hopefully it is not nfsw (this thread has normal pics) : )

Images are not even showed on page. Maybe Imagetwist need to be fixed, what You think ?

**Comment by qsniyg** [comment]
Thank you! It should be fixed now :)

Note that the images in that thread will be duplicated, but that's because of the way the thread is setup, as you can see in the html code you sent (there's a link to the page and a link to the thumbnail, both will be replaced). However, I've just setup the script so that it won't request the image twice, so while it'll work the same, it'll use less bandwidth (though it already has a cache feature, it wouldn't be used if images were being requested at the same time .. this is technically a bug, but since fixing it would require a fair amount of rewriting, I've worked around it for the moment)

**Comment by elvisef** [comment]
Alright, but why if I am entering the page it looks like this:
![2021-01-21_22-19-14](https://user-images.githubusercontent.com/25976749/105413915-10381680-5c37-11eb-8b76-14cda92ee99e.png)

Have no idea why. Links look like they were broken but if I click any of them, it loads successfully into a new tab a full sized image.
But

If I understand coorectly, this option
![firefox_2021-01-21_22-31-39](https://user-images.githubusercontent.com/25976749/105414943-72dde200-5c38-11eb-81af-cbe97eb248e7.png)

should change `http://img102.imagetwist.com/th/05195/by0oyrhcih6y.jpg` (as seen on the image - plain hyperlink):
![firefox_2021-01-21_22-28-19](https://user-images.githubusercontent.com/25976749/105414756-301c0a00-5c38-11eb-8004-be32a859beb4.png)

to `<img src="http://img102.imagetwist.com/th/05195/by0oyrhcih6y.jpg" />` ?

**Comment by qsniyg** [comment]
>Links look like they were broken

If you're referring to the fact that it's `(IMG:http://...)`, this is on the website's end (probably the uploader decided to do it that way, for whatever reason). You can check this in the source code :)

>If I understand coorectly, this option

Yes, but it will replace it to the full-sized image, not the thumbnail image.

**Comment by elvisef** [comment]
Yeah, if I click "replace images" the plain link `http://img102.imagetwist.com/th/05195/by0oyrhcih6y.jpg` (which is covered by A tag) should be replaced by somethjing like this: `<img src="http://img102.imagetwist.com/th/05195/by0oyrhcih6y.jpg" />` - am I right ?

But oif I click to replace images, nothing happens, that's why I am asking if this sould work a sI wrote or am I missing something ?

These plain links are still plain, even after using "replace images" option from MaxURL.
I know that the author, or a website admin chose to paste links like that, but if I replace manually plane image links to be in IMG tags, they will be showed on that page and I will see them. Now I do not see anything but "broken" tags.

Hope You understand what I mean : )

**Comment by qsniyg** [comment]
>should be replaced by something like this: ... - am I right ?

Yes exactly :)

>But if I click to replace images, nothing happens, that's why I am asking if this sould work a sI wrote or am I missing something ?

Yes that would be a bug, it should work as you described (it works for me on that page). Could you share your settings?

>Now I do not see anything but "broken" tags.

Sorry, I'm not sure if I understand this. By "broken" tags, are you referring to image tags that point to an invalid source (i.e. it shows the "broken image" icon)? And do the "broken" tags only happen after running the replace images function?

**Comment by elvisef** [comment]
Alright, I registered on the forum images are from, and voilla, it seems that links are performed to be "broken" to guests only : )
