### ISSUE TITLE
dgtle.com

### ISSUE THREAD

**Issue by doio** [qsniyg/maxurl#620]
`http://s1.dgtle.com/dgtle_img/sale/2021/01/15e2d26202101151330153356_1800_500.jpeg`
->
`http://s1.dgtle.com/dgtle_img/sale/2021/01/15e2d26202101151330153356.jpeg`

More images for reference:
`https://www.dgtle.com/sale-1626897-1.html`

**Comment by qsniyg** [comment]
Thank you very much! Should be supported with https://github.com/qsniyg/maxurl/commit/b4a3b314cc0f2bcccbf2bb4ab5ee0b0975c14c08 :)

**Comment by qsniyg** [comment]
Thanks, fixed!
