### ISSUE TITLE
[question] Toggle option to disable "auto-turn" image into full sized version

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#623]
Hello.

Maybe the topic is not fulyl understandable, but I'll show You an example:

When I go here - I see a real thumbnail: `https://img102.fappic.com/i/02534/5t1s6wkgih51_t.jpg`
But while ImageMaxURL is active, it turns the image into full sized version.

I want to disable it. I am looking for this option but didn't find anything : | Where is it ?

My TamperMonkey is completely disabled - a whole extension. I am not using it now at all.
So wondering, why the FF addon do this without using a scipt for ex. TamperMonkey.

Can You advise me where to find that option ? : ]

**Comment by qsniyg** [comment]
Are you referring to redirection? If so, just go to the Redirection tab, and set "Enable redirection" to "No", and it should work :)

**Comment by elvisef** [comment]
Wow, works ! Thanks.

Weird, yesterday I checked this option and it didn't work ; /
Alright, sovled, thanks again.

By the way, shouldn't the option be named like "redirect to full image" or "show full image" - something with showing the image in full size ? I don't quite  know what this option to redirect is used for by reading it's name. Hmmm.. I thought it is used to something completely else.

**Comment by qsniyg** [comment]
Good idea, thank you for reporting!!

While names/descriptions are obviously clear to me as the developer, I don't know what is and isn't clear for a user, so these kinds of reports are also really helpful :)

**Comment by elvisef** [comment]
Thanks ! Looks much better ; )
