### ISSUE TITLE
zcool.cn

### ISSUE THREAD

**Issue by doio** [qsniyg/maxurl#625]
`https://img.zcool.cn/community/01e8d65facdc7b11013ee04d8abc61.png@1280w_1l_2o_100sh.png`
→
`https://img.zcool.cn/community/01e8d65facdc7b11013ee04d8abc61.png`

via `https://www.zcool.com.cn/work/ZNDg5MTc4ODQ=.html`

**Comment by qsniyg** [comment]
Thank you very much! I've added support for it in https://github.com/qsniyg/maxurl/commit/84e5ac02521de77eb74736a0500c88295ad49907 :)
