### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by GoblinLegislator** [qsniyg/maxurl#627]
https://scontent.ftzl2-1.fna.fbcdn.net/v/t1.0-0/c27.0.206.206a/p206x206/135043832_2727661240819029_2064783936574392261_n.jpg?_nc_cat=108&ccb=2&_nc_sid=0debeb&_nc_ohc=tGfy5NsJaYwAX_0g3iw&_nc_ht=scontent.ftzl2-1.fna&tp=27&oh=4ec7445149ada6531aaa0bfbcf2b830a&oe=602C62ED

https://scontent.ftzl2-1.fna.fbcdn.net/v/t1.0-9/135043832_2727661240819029_2064783936574392261_n.jpg?_nc_cat=108&ccb=2&_nc_sid=0debeb&_nc_ohc=tGfy5NsJaYwAX_0g3iw&_nc_ht=scontent.ftzl2-1.fna&oh=c931396bfcc8014d6c3e81d1d94f66f1&oe=602D285B

Does not work popup nor redirection. From url: https://www.facebook.com/ngomarathon/photos/a.2727663534152133/2727661230819030/?type=3 and https://www.facebook.com/pg/ngomarathon/photos/

**Comment by qsniyg** [comment]
Thank you very much! I don't know if it's really possible to support redirection from the URLs (though there is a chance, if an extra pattern can be discovered), but I've added support for it if using the popup on the `https://www.facebook.com/pg/ngomarathon/photos/` page.
