### ISSUE TITLE
[support] new image hosting list

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#628]
Hello.

If You could look into these, would be great : )

~~`fotokiz.com`~~
~~`silverpic.com`~~
~~`fappic.com` (sorry, forgot it's already supported)~~
~~`picdollar.com`~~
~~`crownimg.com`~~ (can't be supported due to captcha)
~~`pics4you.net`~~

**Comment by qsniyg** [comment]
Fappic should already be supported, in fact you mentioned it in #623. Is there a specific image that doesn't work? Feel free to [send it privately](https://qsniyg.github.io/) if it's nsfw.

The other two should be supported now :)

**Comment by elvisef** [comment]
I've edited my first post. I've added three more.
Do me a favour, If You could strike (I have no such option in the editor here, I cannot remember bbcodes or whatever is used here) the names of already supported hostings in the first post, would be great : )

Fappic is doing well, it is working very well, thanks of course !
Silverpic and Fotokiz as well.

**Comment by qsniyg** [comment]
Thank you, picdollar and pics4you are now supported! Crownimg uses a captcha, so it can't be supported unfortunately.

FYI, to strike out text using markdown (what github uses): `~~text~~` :)

**Comment by elvisef** [comment]
I will check new changes in a moment.
Btw. thanks for github's "strike out" shortcut "tag" ; )

**Comment by elvisef** [comment]
Alright, works great, thanks again !
