### ISSUE TITLE
[support] some more hostings

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#632]
Hello.

As always, something new:

`iceimg.net` (sample: https://iceimg.net/yteihxux )
`vestimage.site` (sample: https://vestimage.site/lysaq )
`chaosimg.site` (sample: http://www.chaosimg.site/site/v/7166069#4&7166069  )

I did not find any captchas but... You never know ; )

**Comment by qsniyg** [comment]
Thank you, supported! Seems to all be different domains for fiyar.live

**Comment by elvisef** [comment]
Thanks !

**Comment by qsniyg** [comment]
Thanks for reminding me of this, they've added yet another domain.
