### ISSUE TITLE
[website] images.macrumors.com

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#637]
from: https://images.macrumors.com/t/hiI0bzxHHRVRKFxXTNfAQJIYyXs=/1600x0/filters:quality(90)/article-new/2020/12/Apple-car-wheel-icon-feature-triad.jpg

to: https://images.macrumors.com/article-new/2020/12/Apple-car-wheel-icon-feature-triad.jpg

via: https://www.macrumors.com/2021/02/03/apple-car-kia-investment/

**Comment by qsniyg** [comment]
Thank you very much! Supported :)

I've added a new "get_thumbor_url" function for this, something I've been meaning to do for a very long time. Supporting new websites using thumbor should be significantly easier now.
