### ISSUE TITLE
[website] blog.corp-site.envato.com

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#638]
from: `https://blog.corp-site.envato.com/cdn-cgi/image/width=1200,quality=95,format=auto/uploads/2021/01/UX-Tips-from-Envatos-Newest-Recruits.jpg`

to: `https://blog.corp-site.envato.com/uploads/2021/01/UX-Tips-from-Envatos-Newest-Recruits.jpg`

via: `https://envato.com/blog/ux-tips-from-envatos-design-team/`

possible more within `*.corp-site.envato.com` or `*.envato.com` :shrug:

**Comment by qsniyg** [comment]
Thank you very much as usual! Yep you're right, there are some from `envato.com` too. If you're interested, the way I found the other urls was by searching `inurl:envato.com inurl:cdn-cgi -blog`. The `inurl:` trick is massively helpful when working on this script! :)
