### ISSUE TITLE
[url] *.optimole.com

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#648]
`optimole.com` seems to be a new image processer targeting wordpress crowd

from: `https://mltr5l57ke57.i.optimole.com/RDDCmdI.6weG~523aa/w:372/h:372/q:82/dpr:1.5/https://oioi.gg/wp-content/uploads/2021/01/oioi_lushperfumelibrary6.jpg`

to: `https://oioi.gg/wp-content/uploads/2021/01/oioi_lushperfumelibrary6.jpg`

via: `https://oioi.gg/project/lush-the-perfume-library`

**Comment by qsniyg** [comment]
Thank you very much! It seems like the rule should encompass most urls, but it might be a little too strict. I'll look around to see if there's anything it doesn't support.
