### ISSUE TITLE
Add media.taringa.net

### ISSUE THREAD

**Issue by Art-2** [qsniyg/maxurl#650]
Small:
`https://media.taringa.net/knn/fit:550/Z3M6Ly9rbjMvZGYxNzZiYzNkZTY1OTczODUxNDU0MDM2NjNjNjU5ODA`

Large:
`https://media.taringa.net/knn/identity/Z3M6Ly9rbjMvZGYxNzZiYzNkZTY1OTczODUxNDU0MDM2NjNjNjU5ODA`

**Comment by qsniyg** [comment]
Thank you very much! Supported :)
