### ISSUE TITLE
akamaized or coub-anubis

### ISSUE THREAD

**Issue by GoblinLegislator** [qsniyg/maxurl#653]
smaller: https://coub-anubis-a.akamaized.net/coub_storage/coub/simple/cw_timeline_pic/e3605a26794/a3db5373a4aa697080b28/med_1494630110_image.jpg
larger: https://coub-anubis-a.akamaized.net/coub_storage/coub/simple/cw_timeline_pic/e3605a26794/a3db5373a4aa697080b28/1494630110_image.jpg
Don't know if this is all akamaized images or just coub-anubis ones.

**Comment by qsniyg** [comment]
Thanks! It's another domain for coub.com. Akamaized is just a CDN (one that facebook uses, or used to use) :)
