### ISSUE TITLE
Open larger image in a new tab in the background?

### ISSUE THREAD

**Issue by rowrawer** [qsniyg/maxurl#661]
Hello,

When the context menu entry is used to find a larger image, the result is opened in an active tab, which can get annoying when there are multiple images per page. Would is be possible to add an option for opening new tabs in the background?

**Comment by qsniyg** [comment]
Try setting "Popup Action -> New background tab" :)

Sorry, I realize that it's a bit confusing to call it "popup" when it's the context menu entry, it was added mostly as an afterthought. I'll have to spend some time to either better document or (preferably) improve the organization/naming of the settings.

(I'll close this, but if you have any further questions or if this doesn't answer your question, please feel free to reply :)

**Comment by rowrawer** [comment]
Thanks for the hint! I had to turn on "enable image popup" and only then I could set that option. Then I switched "enable image popup" back off and it still works as intended. Thanks again.
