### ISSUE TITLE
Any chance of inputing URLs as a query string?

### ISSUE THREAD

**Issue by MillennialDIYer** [qsniyg/maxurl#665]
Hey there!

Just found this feature via a Discog thread, and at a first glance it looks promising for accessing full sizes images of album art that is otherwise downsized to a near-useless 600px squared.

My question is regarding the [https://qsniyg.github.io/maxurl/](https://qsniyg.github.io/maxurl/) link. Out of efficiency, I've taken a liking to creating bookmarklets for often-used functions. In this case, it would be pretty pragmatic if I could, say, visit the image URL of the image I want to see full sized, then click on a javascript bookmarklet to open a new tab and with an auto-generated url, say, 'https://qsniyg.github.io/maxurl/?search=https://ImageSite.com/img/downsized/original_image_12312.jpg'. Bonus points if it directly redirects to the correct link. Basically just appending the current image url to the appropriate search query or url parameter. I routinely do similar things with YouTube searches, Amazon orders, etc.

Currently that doesn't seem possible, or at the least, I'm not aware of the correct URL structure for a search as the site's interface does the work behind the scenes without a URL redirect.

By the way, I'm using Brave so I don't believe there's an extension, and plus, I kinda have enough extensions as is, which is why these days I try to opt for the bookmarklet route.

Anyway, just thought I would ask. If anything is unclear I'd be glad to clarify, but I might as well just leave it here in case this never gets a response.

Regards and thanks for the great idea.

**Comment by qsniyg** [comment]
Great idea, thanks for sharing! I've implemented it like such:

`https://qsniyg.github.io/maxurl/#url=...`

By the way, if you do want to use the extension under brave, I'd recommend either using the userscript with violentmonkey/tampermonkey (I use VM personally), or sideload the extension (though it's a bit more annoying to update).

**Comment by MillennialDIYer** [comment]
Hey there, qsniyg!

You can imagine how surprised I am from the near-instant response and solution. Thank you for that! I already bookmarked the javascript bookmarklet to do what I want:

`javascript:void( window.open('https://qsniyg.github.io/maxurl/#url='+document.location.href) )`

For anyone else who may see this that's interested, in any modern browser all you have to do is click 'Add Page/Bookmark/Favorite...', give the bookmark a name, and place the code above in the URL field. When you're on the page of the image in question, click on the bookmark and a new tab will open up with the image URL already inserted in the proper field of MAXURL. All you'd have to do is copy or click the link and you're golden.

As far as a link to test it with: [Bobby Bland ‎– Spotlighting The Man](https://img.discogs.com/4wrS9T0xCx_JrWghGS66bW780NY=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2407869-1610831295-7318.jpeg.jpg)

Regarding the extension, I just found this project minutes before writing the question so I wasn't even aware there was one for Chrome/Brave. But in any case, I got fed up with how Brave treats sideloaded extensions in the past (having to confirm every time it's launched - I don't know if this has changed), so if this works I'll probably stick with it for now. For better or worse I'm trying to keep things as simple as possible these days. God knows things are overwhelming enough as is.

Anyway, thanks again and my best wishes!
