### ISSUE TITLE
Issue Report: Re-Add suport for https://rule34hentai.net/

### ISSUE THREAD

**Issue by jollld** [qsniyg/maxurl#671]
Hello there. I hope i'm writing this in the right place, i'm still a novice to github...
I'd like to ask if it would be possible to re-add support for rule34hentai.net, that site is hard to navigate, and the tool is currently not catching the original imagem that each thumbnail there represents, and displaying them in a gallery.
Thank you beforehand, your tool is extremely handy for annoying sites like these!

**Comment by qsniyg** [comment]
So this appears to be due to cloudflare. It works fine under the extension (with the fix I added), but under violentmonkey, it still crashes because the right cookies aren't being sent. I'm not really sure why though, but I think it's an issue on their end. I'll try to submit a bug report :)

**Comment by jollld** [comment]
Alright, thanks for the support, ill check the extension you mentioned.
