### ISSUE TITLE
Perform more advanced content type detection for sites with ambiguous extensions and no content type

### ISSUE THREAD

**Issue by qsniyg** [qsniyg/maxurl#672]
For example: rule34hentai.net (#671)

**Comment by jollld** [comment]
I'm having trouble with the videos still, with the update you posted...
The images work fine but the vids are stlll only thumbails.

**Comment by qsniyg** [comment]
Yes that's what this issue should address :)

**Comment by qsniyg** [comment]
@jollld Should be fixed now, can you confirm?

**Comment by jollld** [comment]
Tested some thumbs after updating some minutes ago. It works!
Thanks a lot man!
