### ISSUE TITLE
MUBI (mubicdn.net) images redirect to different files

### ISSUE THREAD

**Issue by TheLastZombie** [qsniyg/maxurl#675]
Example:

> https://images.mubicdn.net/images/film/781/cache-47795-1605261679/image-w1280.jpg

redirects to

> https://images.mubicdn.net/images/film/781/cache-47795-1605261679/image-original.jpg

**Comment by qsniyg** [comment]
Thank you! Should be fixed now :) I've re-enabled the "Possibly different images" option for it.
