### ISSUE TITLE
Issue Report: videos aren't being detected in main sites rule34.xxx and rule34.paheal.net

### ISSUE THREAD

**Issue by jollld** [qsniyg/maxurl#687]
Hi again, I think some of your recent fixes broke the way the tool catches videos in these sites.
The only thing that's being displayed in either of these sites are the thumbs (or snapshots?), not the videos that they link too.

Thanks again for your assistance, i'd love it if i could use your tool in every site i mainly use.

**Comment by qsniyg** [comment]
Thanks! Should be fixed now :)

Note that redirection under rule34.paheal is currently broken (only popups will work properly), I need to find some way to fix this.
