### ISSUE TITLE
news.kstyle.com

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#693]
Small: https://cdn.livedoor.jp/kstyle/2db7a49a8ad303b5e9cd913b125e7eb7.jpg/r.580x0
Big: https://cdn.livedoor.jp/kstyle/2db7a49a8ad303b5e9cd913b125e7eb7.jpg

Some images are the same even if `/r.` suffix is removed like this one:
https://cdn.livedoor.jp/kstyle/3839f6eaaad5ead8e0357b11cc01a669.jpg/r.580x0
https://cdn.livedoor.jp/kstyle/3839f6eaaad5ead8e0357b11cc01a669.jpg

Source: https://news.kstyle.com/article.ksn?articleNo=2164776

**Comment by qsniyg** [comment]
Thank you very much as usual! Supported :)

(Livedoor really does have a lot of systems...)
