### ISSUE TITLE
Vivaldi 3.7 crashes on image download from popup

### ISSUE THREAD

**Issue by PietroPizzi69** [qsniyg/maxurl#694]
Hi,

I have updated my Vivaldi today, from 3.6 to 3.7 under Win10 and Linux, and on both systems Vivaldi crashes when i press the "Download key" ('S' or 'Button3' in my case) when the Pop-Up is open. I'm on v0.18.1 on all systems. The exact same config (exported from Vivaldi, imported in Chrome) works in my actuall Chrome 89.0.

Can I provide something which helps you find the problem?

**Comment by qsniyg** [comment]
Thanks for reporting! I can't actually replicate this on my end unfortunately, could you send the following?

  * Exported settings (through the options page -> Export button at the top)
  * Whether you're using the userscript or the extension, and which userscript manager you're using if using the userscript
  * The link that crashes when downloading

**Comment by PietroPizzi69** [comment]
{"imu_enabled":true,"language":"en","check_updates":true,"check_update_interval":24,"check_update_notify":true,"dark_mode":true,"settings_tabs":true,"settings_alphabetical_order":false,"settings_visible_description":true,"settings_show_disabled":true,"settings_show_disabled_profiles":false,"settings_show_requirements":true,"advanced_options":true,"allow_browser_request":true,"retry_503_times":3,"retry_503_ms":2000,"use_blob_over_arraybuffer":false,"allow_live_settings_reload":true,"allow_remote":true,"disable_keybind_when_editing":true,"enable_gm_download":true,"gm_download_max":15,"enable_webextension_download":false,"write_to_clipboard":false,"redirect":true,"redirect_video":true,"redirect_audio":false,"redirect_history":false,"redirect_extension":true,"canhead_get":true,"redirect_force_page":true,"redirect_infobox_url":true,"redirect_infobox_timeout":3,"print_imu_obj":false,"redirect_disable_for_responseheader":false,"redirect_to_no_infobox":false,"redirect_host_html":false,"mouseover":true,"mouseover_open_behavior":"popup","t2_mouseover_open_behavior":"popup","t3_mouseover_open_behavior":"popup","mouseover_trigger_behavior":"mouse","mouseover_trigger_key":["shift","alt","i"],"mouseover_trigger_key_t2":[],"mouseover_trigger_key_t3":[],"mouseover_trigger_delay":0.3,"mouseover_trigger_mouseover":false,"mouseover_trigger_enabledisable_toggle":"disable","mouseover_trigger_prevent_key":["shift"],"mouseover_close_behavior":["any"],"mouseover_close_need_mouseout":true,"mouseover_jitter_threshold":2,"mouseover_cancel_popup_when_elout":true,"mouseover_cancel_popup_with_esc":true,"mouseover_cancel_popup_when_release":true,"mouseover_auto_close_popup":false,"mouseover_auto_close_popup_time":5,"mouseover_hold_key":["i"],"mouseover_hold_position_center":true,"mouseover_hold_close_unhold":false,"mouseover_hold_unclickthrough":true,"mouseover_close_el_policy":"thumbnail","mouseover_close_click_outside":true,"mouseover_allow_partial":"video","mouseover_partial_avoid_head":false,"mouseover_use_blob_over_data":false,"popup_use_anonymous_crossorigin":false,"mouseover_enable_notallowed":true,"mouseover_enable_notallowed_cant_load":true,"mouseover_notallowed_duration":300,"mouseover_minimum_size":20,"mouseover_exclude_backgroundimages":false,"mouseover_exclude_page_bg":true,"mouseover_exclude_imagemaps":true,"mouseover_only_links":false,"mouseover_linked_image":true,"mouseover_exclude_sameimage":true,"mouseover_exclude_imagetab":true,"mouseover_allow_video":true,"t2_mouseover_allow_video":true,"t3_mouseover_allow_video":true,"mouseover_allow_audio":false,"t2_mouseover_allow_audio":false,"t3_mouseover_allow_audio":false,"mouseover_allow_hlsdash":true,"t2_mouseover_allow_hlsdash":true,"t3_mouseover_allow_hlsdash":true,"enable_stream_download":false,"stream_mux_mp4_over_mkv":false,"hls_dash_use_max":true,"max_video_quality":null,"mouseover_video_autoplay":true,"mouseover_video_controls":false,"mouseover_video_controls_key":["c"],"mouseover_video_loop":true,"mouseover_video_autoloop_max":60,"mouseover_video_playpause_key":["space"],"mouseover_video_muted":false,"mouseover_video_mute_key":["m"],"mouseover_video_volume":100,"mouseover_video_volume_down_key":["9"],"mouseover_video_volume_up_key":["0"],"mouseover_video_volume_change_amt":5,"mouseover_video_resume_from_source":true,"mouseover_video_resume_if_different":false,"mouseover_video_pause_source":true,"mouseover_video_seek_amount":10,"mouseover_video_seek_left_key":["shift","left"],"mouseover_video_seek_right_key":["shift","right"],"mouseover_video_frame_prev_key":[","],"mouseover_video_frame_next_key":["."],"mouseover_video_framerate":25,"mouseover_video_speed_down_key":[["["],["shift",","]],"mouseover_video_speed_up_key":[["]"],["shift","."]],"mouseover_video_speed_amount":0.1,"mouseover_video_reset_speed_key":["backspace"],"mouseover_video_screenshot_key":["shift","s"],"popup_video_screenshot_format":"png","mouseover_ui":true,"mouseover_ui_toggle_key":["u"],"mouseover_ui_opacity":80,"mouseover_ui_use_safe_glyphs":false,"mouseover_ui_imagesize":true,"mouseover_ui_zoomlevel":true,"mouseover_ui_filesize":true,"mouseover_ui_gallerycounter":true,"mouseover_ui_gallerymax":50,"mouseover_ui_gallerybtns":true,"mouseover_ui_closebtn":true,"mouseover_ui_optionsbtn":true,"mouseover_ui_downloadbtn":true,"mouseover_ui_rotationbtns":true,"mouseover_ui_caption":true,"mouseover_ui_wrap_caption":true,"mouseover_ui_caption_link_page":true,"mouseover_ui_link_underline":true,"mouseover_use_remote":false,"mouseover_zoom_behavior":"fit","mouseover_zoom_custom_percent":100,"mouseover_zoom_max_width":0,"mouseover_zoom_max_height":0,"mouseover_pan_behavior":"drag","mouseover_movement_inverted":true,"mouseover_drag_min":5,"mouseover_scrolly_behavior":"zoom","mouseover_scrollx_behavior":"gallery","mouseover_scrolly_video_behavior":"seek","mouseover_scrolly_video_invert":true,"mouseover_scrollx_video_behavior":"default","scroll_override_page":true,"scroll_zoom_origin":"cursor","scroll_zoom_behavior":"fitfull","scroll_incremental_mult":1.25,"mouseover_move_with_cursor":true,"mouseover_move_within_page":true,"zoom_out_to_close":true,"scroll_past_gallery_end_to_close":false,"mouseover_position":"cursor","mouseover_prevent_cursor_overlap":true,"mouseover_add_link":false,"mouseover_add_video_link":false,"mouseover_click_image_close":true,"mouseover_click_video_close":true,"mouseover_download":false,"mouseover_hide_cursor":true,"mouseover_hide_cursor_after":100,"mouseover_mouse_inactivity_jitter":0,"mouseover_clickthrough":false,"mouseover_mask_ignore_clicks":false,"mouseover_links":true,"mouseover_only_valid_links":true,"mouseover_allow_self_pagelink":false,"mouseover_allow_iframe_el":true,"mouseover_allow_canvas_el":false,"mouseover_allow_svg_el":false,"mouseover_enable_gallery":true,"mouseover_gallery_cycle":false,"mouseover_gallery_prev_key":[["left"]],"mouseover_gallery_next_key":["right"],"mouseover_gallery_move_after_video":false,"mouseover_gallery_download_key":["shift","d"],"gallery_download_unchanged":true,"gallery_zip_filename_format":"{host_domain_nosub}-{items_amt}-{download_unix}\n{items_amt}-{download_unix}","gallery_zip_add_tld":false,"gallery_zip_add_info_file":true,"mouseover_styles":"","mouseover_enable_fade":true,"mouseover_enable_zoom_effect":false,"mouseover_zoom_effect_move":false,"mouseover_fade_time":100,"mouseover_enable_mask_styles2":"never","mouseover_mask_styles2":"background-color: rgba(0, 0, 0, 0.5)","mouseover_mask_fade_time":100,"mouseover_ui_styles":"","mouseover_wait_use_el":false,"mouseover_add_to_history":false,"mouseover_close_key":["esc"],"mouseover_download_key":[["s"],["button3"]],"mouseover_open_new_tab_key":["o"],"mouseover_open_bg_tab_key":["shift","o"],"mouseover_copy_link_key":["shift","c"],"mouseover_open_options_key":["p"],"mouseover_open_orig_page_key":["n"],"mouseover_rotate_left_key":["e"],"mouseover_rotate_right_key":["r"],"mouseover_flip_horizontal_key":["h"],"mouseover_flip_vertical_key":["v"],"mouseover_zoom_in_key":[["+"],["="],["shift","="]],"mouseover_zoom_out_key":[["-"]],"mouseover_zoom_full_key":["1"],"mouseover_zoom_fit_key":["2"],"mouseover_fullscreen_key":["f"],"mouseover_apply_blacklist":true,"apply_blacklist_host":false,"mouseover_matching_media_types":true,"mouseover_find_els_mode":"hybrid","popup_allow_cache":true,"popup_cache_duration":30,"popup_cache_itemlimit":1000,"popup_cache_resume_video":true,"website_inject_imu":true,"website_image":true,"extension_contextmenu":true,"extension_hotreload":true,"allow_watermark":false,"allow_smaller":false,"allow_possibly_different":false,"allow_possibly_broken":false,"allow_possibly_upscaled":true,"allow_thirdparty":true,"allow_apicalls":true,"allow_thirdparty_libs":true,"custom_xhr_for_lib":false,"allow_thirdparty_code":false,"allow_bruteforce":true,"process_format":{},"deviantart_prefer_size":false,"deviantart_support_download":true,"ehentai_full_image":true,"imgur_filename":true,"imgur_source":false,"instagram_use_app_api":true,"instagram_dont_use_web":false,"instagram_prefer_video_quality":true,"instagram_gallery_postlink":true,"snapchat_orig_media":true,"tiktok_no_watermarks":true,"tiktok_thirdparty":null,"tumblr_api_key":"xrMpLM8n1eCeL3oRYSZG7CLALw6EHhYDdU6Wq5eD1PbMkld7Y1","twitter_use_ext":false,"bigimage_blacklist":"","bigimage_blacklist_engine":"glob","filename_format":"{author_username} {filename}","replaceimgs_enable_keybinding":false,"replaceimgs_keybinding":["shift","alt","r"],"replaceimgs_auto":false,"replaceimgs_replaceimgs":true,"replaceimgs_addlinks":false,"replaceimgs_replacelinks":false,"replaceimgs_plainlinks":"none","replaceimgs_links_newtab":false,"replaceimgs_remove_size_constraints":false,"replaceimgs_usedata":true,"replaceimgs_wait_fullyloaded":true,"replaceimgs_totallimit":8,"replaceimgs_domainlimit":2,"replaceimgs_delay":0,"replaceimgs_css":"","replaceimgs_simple_progress":true,"highlightimgs_enable_keybinding":false,"highlightimgs_keybinding":["shift","alt","h"],"highlightimgs_enable":true,"highlightimgs_auto":"never","highlightimgs_onlysupported":true,"highlightimgs_css":"outline: 4px solid yellow","last_update_check":1616682604439,"last_update_version":"0.18.1","last_update_url":null,"settings_version":10}

Userscript with Tempermonkey

https://www.google.com/search?q=test&tbm=isch&tbs=isz:l&hl=en&sa=X&biw=2543&bih=1286
and there e.g. the red "Test button" from medium.com. The SVGs (eg. https://upload.wikimedia.org/wikipedia/commons/c/c6/Test_Logo.svg) opens instead of downloadTry->crash.

I'm testing these right now on Windows with Vivaldi 3.7.2218.45 (Stable channel) (64-Bit)

**Comment by PietroPizzi69** [comment]
Forget it: Was Vivaldis fault and they fixed it in a day :).

Change Log from today's Version:
[Extensions][Crash] Via GM_download() in Tampermonkey VB-77791
