### ISSUE TITLE
order.mandarake.co.jp

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#70]
All thumbnail images for items for sale on this website seem to have a bigger version by removing `s_`.

See any thumbnail images on page https://order.mandarake.co.jp/order/listPage/list?keyword=Test

`https://img.mandarake.co.jp/webshopimg/03/30/430/0330290430/s_03302904302.jpg`->
`https://img.mandarake.co.jp/webshopimg/03/30/430/0330290430/03302904302.jpg`

**Comment by qsniyg** [comment]
Thank you very much! Just in case, I've set it to be [a-z]_ instead of just s_, probably won't hurt :)
