### ISSUE TITLE
[Suggestion] Option to keep zoom amount when cycling between images in gallery

### ISSUE THREAD

**Issue by Michael82548** [qsniyg/maxurl#701]
When I cycle between images in the gallery while zoomed in, the image zoom resets back to the default amount (0% zoom)

An option could be added to keep the current zoom amount when cycling between the gallery so the zoom amount stays the same.

**Comment by qsniyg** [comment]
Good idea! I think also an option to keep the same overall position on the screen would be helpful.

I'll implement this soon! :)

**Comment by Michael82548** [comment]
> Good idea! I think also an option to keep the same overall position on the screen would be helpful.
> 
> I'll implement this soon! :)

I would like it if those two options were separated due to the fact that if you are reading comics, you would need to scroll all the way up every time you switch between the gallery if those 2 options were enabled.

**Comment by qsniyg** [comment]
Done! Since you mentioned the scrolling issue, I've also added an option to set the popup position when overflowing ("Overflow origin")
