### ISSUE TITLE
internetstores

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#706]
https://images.internetstores.de/products//1204816/02/7dfc07/Hoka_One_One_Stinson_ATR_6_Laufschuhe_Herren_frost_gray_bright_marigold[640x480].jpg?forceSize=true&forceAspectRatio=true&useTrim=true

https://images.internetstores.de/products//1204816/02/7dfc07/Hoka_One_One_Stinson_ATR_6_Laufschuhe_Herren_frost_gray_bright_marigold[280x280].jpg?forceSize=true&forceAspectRatio=true&useTrim=true

https://images.internetstores.de/products//1204816/02/7dfc07/Hoka_One_One_Stinson_ATR_6_Laufschuhe_Herren_frost_gray_bright_marigold[640x480][640x480].jpg?forceSize=true&forceAspectRatio=true&useTrim=true?forceSize=true&forceAspectRatio=true&useTrim=true

https://images.internetstores.de/products//1204816/02/7dfc07/Hoka_One_One_Stinson_ATR_6_Laufschuhe_Herren_frost_gray_bright_marigold[640x480][640x480].jpg

large: https://images.internetstores.de/products//1204816/02/7dfc07/Hoka_One_One_Stinson_ATR_6_Laufschuhe_Herren_frost_gray_bright_marigold.jpg

**Comment by qsniyg** [comment]
Thanks!

Rather unique way of handling URLs, can't really imagine many advantages of storing it that way (filesystems and shells generally not being much of a fan of `[]`), but it does look rather pretty admittedly.
