### ISSUE TITLE
instagram different file name

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#709]
Is there any way file name after popup and pressing S key on instagram photo have name of ref url part instead of direct url part?
For example so that photo on this url: https://www.instagram.com/p/BSbclhbjJcd/
has name `in_stl1281 BSbclhbjJcd.jpg` instead of current `in_stl1281 17494601_665772160289665_5376620926500601856_n.jpg`
Reason is that such file name would tell us direct link of ref url which is more useful if need to revisit url and also shorter.
Also can you make separator character between username and file name being able to switch between: space, -, _

**Comment by qsniyg** [comment]
Yes, add the following to the top of Rules->Filename format:

`{author_username} {id}`

Each format is processed line-per-line, and it'll use the first one that is valid. In this case, if `id` or `author_username` does not exist, it'll use the format below it. Instagram currently provides: `caption`, `author_username`, `id`, and `created` (in addition to the domain/ext/download/filename options that are present for all images)
