### ISSUE TITLE
add ability to reset settings

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#710]
Can you add ability (button) to reset settings in Firefox addon? So I don't have to remove and reinstall extension just to reset settings. Reason is that there are lots of settings that could be set up wrong and it's difficult to remember what they were before, while it is easy to remember for me what I changed from default. Currently the only possible way I see is to install extension after not having it or removing it, then export settings and label them default, and import when needed.

**Comment by qsniyg** [comment]
For the moment, you can import `{}` to achieve this.

I completely agree though that this should be easier to do. My current plan is to add a "preset" button/bar, which'll allow things like resetting to default, or setting it up to act like other extensions (Imagus, MPIV, Hover Zoom, etc.) to allow for easier migration.

(I'll close this as it's the same as #209)
