### ISSUE TITLE
question: - list of hostings with hacked access to normally unavailable original\bigger image versions?

### ISSUE THREAD

**Issue by Owyn** [qsniyg/maxurl#712]
e.g. 500px and some old deviantart images where script can get original\bigger image versions normal viewers can't access anyhow

people usually save images they like, so getting a script to get better quality versions would make them want to go and check images on those sites again for resaving, tho we don't know on which sites we can do that currently

**Comment by qsniyg** [comment]
(Note that I wouldn't use the term hacked, as it's just using publicly available resources)

I don't think anything fancy is done for 500px, unless they have now made the previews smaller? It just uses the same API call that their website uses IIRC.

To answer your question, I don't know if it's really possible to make an automatically generated list like that, as for the most part, I have no idea what's exposed to users or not (as written in sites.txt, most of the sites are found from some image search engine, and supported directly from there - I usually don't visit the sites as it's usually not necessary).

However, as you mentioned, some older deviantart images can be made larger, and instagram images can be made to have 1440x* (with higher image quality [by removing `&se=`](https://github.com/qsniyg/maxurl/issues/239), something other ig full image extensions unfortunately still don't do, hopefully they'll do it soon - been meaning to contact them about it, but still haven't gotten around to it). A while ago it was able to find original resolution discogs images, but they removed that (resulting in [a fair bit of controversy with their userbase](https://www.discogs.com/forum/thread/828335), enjoy the read...).

As for creating a manual list, it would take a lot of work as it would require looking through a ton of sites to see if they do indeed provide the original quality through their website. Plus, websites change their layouts way more frequently than their backend, so what's relevant now might change very quickly soon. Normally I might consider maintaining a list like this, but I unfortunately don't have much time anymore, and still have a lot of other high priority things to address in the script.

Personally I would say, search for sites you download from a lot in [sites.txt](https://github.com/qsniyg/maxurl/raw/master/sites.txt). If it supports it, check if it makes it larger. If it does, write it down somewhere (or copy it to your script ;)

Sorry, I know this isn't a great answer, but hopefully it's somewhat useful to you :)

**Comment by Owyn** [comment]
I've just been wondering how much of popular websites has such "hacks", 

and yea, mentioning instagram alone was useful :)

**Comment by qsniyg** [comment]
Ah, yeah perhaps. Honestly I haven't been keeping up to date much on this.
