### ISSUE TITLE
Dilan Gwyn gallery support

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#713]
Hello.

I don't know how many times this gallery will change, or if whenever changes, but You can support it as well : )

The link is: `http://dilangwyn.com/gallery`

I've used a regex for ImagePicka addon to download images, so You will see how simple it is to replace links:

> images\/(.*)(Thmb)\.jpg$
> images/$1.jpg

This gallery is probably just an advert but there are about 60 images here.
What You think ? : )

**Comment by qsniyg** [comment]
Thank you very much as usual! Absolutely, anything that can be supported is supported :) There are a fair amount of other single-purpose websites like that within the script.
