### ISSUE TITLE
Duplicates in Instagram galleries containing videos

### ISSUE THREAD

**Issue by Anamon** [qsniyg/maxurl#726]
I've noticed this happening for a few months now, and it's still in the current v0.19.0, at least in the Firefox extension.

**Steps to reproduce**
1. Open an Instagram post with a gallery containing at least one video that is not in position 1.
  E.g. https://www.instagram.com/p/CG0Qwzsn_9c/
2. Open the Max URL popup

**What should happen?**
* The popup should display the correct number of images/videos contained in the gallery.
* Navigating through the gallery images/videos using the arrows is possible.
* The arrows display correctly.
* Videos are played properly in the popup and stop playing once navigating to a different image/video of the gallery or closing the popup.

**What happens instead?**
* The popup shows a higher number of images/videos than the gallery actually contains.
* It's not possible to navigate through the gallery's images/videos using the popup's arrows.
* The navigation arrows are rendered twice, sometimes three times, next to each other.
* Opening videos in the popup seems to play multiple copies of them in parallel, some of them hidden and they won't stop playing even after navigating away from the video or closing the popup.
* The browser tab slows down considerably, even on a gallery with just 4 images and 2 videos, opening the Max URL popup increases Firefox's UI response time to several seconds, the tab stays sluggish for several seconds after the popup is closed; sometime only refreshing the tab will make the browser perform well again.

**Further details**
I'm not sure exactly what might be going wrong with gallery parsing here, but one thing I've noticed is that the extent of the bug's symptoms (excessive number of gallery images displayed, duplication of navigation arrows, number of copies of the videos being played in parallel, extent of browser slowdown) increases by the number of videos following the currently opened picture in the gallery.
In the example URL given,
* the gallery contains 4 images followed by 2 videos, but
* if I open image 1, the popup displays that I'm on image 1/47,
* if I open image 2, the popup displays that I'm on image 3/25,
* if I open image 3, the popup displays that I'm on image 7/17,
* if I open image 4, the popup displays that I'm on image 15/19,
* if I open video 5, the popup displays that I'm on image 31/32 (and plays at least 2 copies of the video in parallel, one of which won't stop when closing the popup),
* if I open video 6, the popup displays that I'm on image 32/32
So neither the the display of the current image nor the number of total images is correct. Figuring out how these numbers relate to the content of the gallery feels like one of those "continue the following series" puzzles, to which I haven't figured out the solution 😄 

**Environment**
OS: Windows 10 Version 10.0.19042 Build 19042
Browser: Firefox 88.0
Extension: 0.19.0 (AMO)

**Comment by qsniyg** [comment]
Thank you for the super detailed report! I can replicate the issue, and all I can say is that it's quite possibly the most spectacular failure I've seen so far for the userscript haha.

I haven't looked too deep in the issue, but there are two places that the album is calculated. It now uses a newer technique, but I hadn't disabled the older one for some reason (superstition, most likely). The "fix" was just to disable the older one :)

**Comment by Anamon** [comment]
Cool, thank you for the quick confirmation and fix! 👍🙂
