### ISSUE TITLE
rename instagram photos to time

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#727]
Does not work: `{author_username} {id} {updated__yyyymmdd}` or `{author_username} {id} {updated_yyyymmdd}`
I want them to be as in last-modified header. Did I write it wrong?
Even simple similar syntaxes like {created_iso} does not work.

**Comment by qsniyg** [comment]
`{author_username} {id} {updated_yyyymmdd}` works for me... what are you trying it with?

**Comment by AdClear247** [comment]
It did not work with any image. Now it works with all. Probably some extension or crash or did not refresh page...

**Comment by qsniyg** [comment]
I think I should add error checking then (#729), to allow the user to know whether or not they made a typo :)
