### ISSUE TITLE
Re-add support for chan.sankakucomplex.com

### ISSUE THREAD

**Issue by jollld** [qsniyg/maxurl#728]
Hi, it's me again, the tool isn't fetching the images or videos correctly on this site, all of them are blurred thumbnails, could you fix it?

Thanks!

**Comment by qsniyg** [comment]
Actually, the site itself doesn't work for me, clicking on any of the images sends me to variations of https://chan.sankakucomplex.com/redirect.png .

If there's one that works for you, can you send me a link?

**Comment by jollld** [comment]
Strange it works perfectly for me, even in mobile.

But here an example
![2021-05-01 20_14_49-rating_safe _ Sankaku Channel - Anime, manga   game related images   videos - Pe](https://user-images.githubusercontent.com/72407660/116792675-0a659300-aaba-11eb-914b-59c95039cdfb.jpg)

Maybe it's some addon you have that doesn't work with the site?

**Comment by qsniyg** [comment]
You're right, it was an addon! Fixed, thanks for reporting! :)

**Comment by jollld** [comment]
Checked and the images work perfectly with the tool, however videos aren't playing... (still showing as thumbs)
Sorry to keep bothering you with this, if i knew programming i'd just do it myself and post the fix...

**Comment by qsniyg** [comment]
Sorry about that! I had changed one, and forgot to do the others! Should be fixed now :)
