### ISSUE TITLE
Add Twitch emote resizing

### ISSUE THREAD

**Issue by Finbae** [qsniyg/maxurl#73]
Examples: https://static-cdn.jtvnw.net/emoticons/v1/414579/1.0 (smallest size),
https://static-cdn.jtvnw.net/emoticons/v1/414579/3.0 (largest size)

Seems to go up to 3.0 as a maximum, everything larger is the same size.

Thanks!

**Comment by qsniyg** [comment]
Thank you very much, I've added it in! Yeah, I can't seem to find any larger either.

5.0 seems to be the largest it allows, but even the [unusually large one punch man emoticon](https://static-cdn.jtvnw.net/emoticons/v1/79710/3.0) is the same size at 5.0.
