### ISSUE TITLE
support gravatar

### ISSUE THREAD

**Issue by C4illin** [qsniyg/maxurl#733]
example original image:
https://s.gravatar.com/avatar/cf0bd1f2e1e14a98358c37ccf31ccd32?r=pg&s=128&d=404

big image:
https://s.gravatar.com/avatar/cf0bd1f2e1e14a98358c37ccf31ccd32?r=pg&s=2048&d=404

according to the docs (https://en.gravatar.com/site/implement/images/) the biggest size is s=2048 but numbers bigger than 2048 also work (but they return the same image as 2048).

**Comment by qsniyg** [comment]
Thank you! I hadn't added the rule before because afaik there's no way to get the original, non-upscaled image, but I should have added it under "Possibly upscaled images" before. Anyways, fixed now!
