### ISSUE TITLE
thejeansnet.com

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#734]
small:
https://www.jeansgetwet.com/updates/m/mandy/01/jeansgetwet-mandy-1s.jpg

large:
https://www.jeansgetwet.com/updates/m/mandy/01/jeansgetwet-mandy-1.jpg

I think same is for all other sites:
https://www.jeansgetwet.com
https://www.jeanslesbians.com
https://www.jeanslezdom.com
https://www.jeansorgasm.com
https://www.jeanstease.com
https://www.jeansverytight.com
https://www.thejeansnet.com

**Comment by qsniyg** [comment]
Thank you! Fixed with https://github.com/qsniyg/maxurl/commit/4025e3c01bd7cc3c707e27796102010fc71610f4 (typo with the issue number)
