### ISSUE TITLE
cdn-outlet.com

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#735]
small: https://photos.cdn-outlet.com/photos/alternate/100x122/8116678/8116678-10852-3A-100x122.jpg
large: https://photos.cdn-outlet.com/photos/options/8116678-10852-3A-zoomin.jpg
ref: https://www.swimoutlet.com/p/body-glove-womens-loose-fit-long-sleeve-rashguard-8116678/

**Comment by qsniyg** [comment]
Thank you! Unfortunately I can't find a way to get the original image, and `-zoomin` can upscale it: https://photos.cdn-outlet.com/photos/7543-2-zoomin.jpg
