### ISSUE TITLE
leisurepro.com

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#736]
https://www.leisurepro.com/image/Product/Medium/CSBRGWSSBA.jpg
https://www.leisurepro.com/Image/Product/Large/CSBRGWSSBA.jpg
https://www.leisurepro.com/Image/Product/XLarge/CSBRGWSSBA.jpg

**Comment by qsniyg** [comment]
Thanks! Supported.

Like the other one, I can't seem to find a way to get original images though. Interestingly, they do have a `Full` size, but it's 221x221 always (I believe).
