### ISSUE TITLE
VK support

### ISSUE THREAD

**Issue by qsniyg** [qsniyg/maxurl#74]
VK is likely going to be one of the websites where finding a larger image requires being on the page, like Instagram or Facebook. Implementing it therefore isn't going to be easy, but it is important.

**Comment by eightyy8** [comment]
VK images hosted for other sites have a different URL but use the same domain (sunX-XX.userapi.com).

Here are two examples:

https://sun1-91.userapi.com/s/v1/ig2/Ep0EJ9p29EZqVXgevqKOCmOlul8FEQzMvKYmDe6ycsEBn0qDW_LaDi7T9IGsL9o-GcdySS-3Nhwxx9y3sJnVbS_w.jpg?size=200x200&quality=95&crop=232,0,2304,2304&ava=1

https://sun9-83.userapi.com/s/v1/if1/rHCwPvTfD9vW8-c90mXFjsyocBe-iA5ERtG-BnzeL_Xp6CsyviYLdDYxOmpzhc_QXAInonUk.jpg?size=400x473&quality=96&crop=0,0,502,594&blur=20,10&ava=1

I tried to understand the gibberish before the parameters, but with no luck. Hopefully it's possible.

**Comment by qsniyg** [comment]
@eightyy8 Unfortunately I can't figure out a way to get the original page from them. I believe it's some kind of signature as changing any part of the query parameters results in a 404 error.
