### ISSUE TITLE
onlinescuba.com

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#740]
HTTP:
http://www.onlinescuba.com/Assets/ProductImages/AL100286black_t.png
http://www.onlinescuba.com/Assets/ProductImages/AL100286black.png
HTTPS:
https://www.onlinescuba.com/Assets/ProductImages/4701_t.png
https://www.onlinescuba.com/Assets/ProductImages/4701.png

**Comment by qsniyg** [comment]
Thank you!
