### ISSUE TITLE
jcrew.com

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#741]
https://www.jcrew.com/s7-img-facade/E8726_PK5652?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=160&hei=160
https://www.jcrew.com/s7-img-facade/E8726_PK5652?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=2000&hei=2000

**Comment by qsniyg** [comment]
Thanks! Interestingly, removing everything after `?` works, but it makes the image somewhat less sharp. My guess is that the sharpness is a post-processing filter.
