### ISSUE TITLE
azbro.com

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#742]
http://image23.azbro.com/o_img/2016/09/23/207766-10105846-category/women-s-2-piece-long-sleeve-cropped-rash-guard.jpg
http://image23.azbro.com/o_img/2016/09/23/207766-10105846/women-s-2-piece-long-sleeve-cropped-rash-guard.jpg

**Comment by qsniyg** [comment]
Thank you! Looks like most of the -`-category` ones are upscaled though, unfortunately.

7900th website supported! :)
