### ISSUE TITLE
canstockphoto.com

### ISSUE THREAD

**Issue by ghost** [qsniyg/maxurl#744]
https://cdn.w600.comps.canstockphoto.com/detective-or-spy-clipart-vector_csp22691154.jpg
https://www.canstockphoto.com/zoom/?height=497&width=395&id=22691154&_ts=1620045427699&scale=1.6096579476861168&left=100&top=103
https://cdn.xxl.thumbs.canstockphoto.com/detective-or-spy-man-in-cartoon-style-for-security-concept-design-clipart-vector_csp22691154.jpg
ref: https://www.canstockphoto.com/detective-or-spy-22691154.html

**Comment by qsniyg** [comment]
Adding URLs from #815:

https://cdn.xxl.thumbs.canstockphoto.com/young-fit-woman-in-rome-italy-tying-shoelaces-gladiator-inspiring-trainings-young-fit-woman-in-picture_csp51141519.jpg
https://cdn.w600.comps.canstockphoto.com/young-fit-woman-in-rome-italy-tying-picture_csp51141519.jpg
https://www.canstockphoto.com/zoom/?height=382&width=598&id=51141519&_ts=1623703027801&scale=1.3377926421404682&left=0&top=127

**Comment by qsniyg** [comment]
Closing as canstockphoto.com has shut down.
