### ISSUE TITLE
instagram mp4 video does not support id, date, time in file name

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#750]
This file name is named: 56721190_159399215070113_6493205506131918400_n.mp4
https://www.instagram.com/p/BwE0JtYh4B4/
instead of like pictures in this format: {author_username} {id} {updated_yyyymmdd_utc} {updated_hhmmss_utc} {filename}
When I disable option: Allow HLS/DASH streams

**Comment by qsniyg** [comment]
This is because for whatever reason, IG doesn't send the `Last-Modified` header during a HEAD request.

I've added a new `date` format variable, which will use either the created or the updated date (in that order). If you replace `updated_` with `date_` (with https://github.com/qsniyg/maxurl/commit/f5fa8f3a62dedb1f88aba68fc34e9e37a6a653c7 applied), it should work :)

**Comment by AdClear247** [comment]
Now it calls file: zoeleggings BwE0JtYh4B4 20190410 123751 56721190_159399215070113_6493205506131918400_n.jpg
But what is created date??? Something from headers or current date? Obviously not current date.

**Comment by qsniyg** [comment]
Created date is when the post was created/uploaded, which should be roughly equal to updated_date. This however can only be filled in per-rule, and only if the website exposes this information (which Instagram thankfully does provide).

The new `date` property will choose `created_date` first, and if it doesn't exist (i.e. for most websites), it'll fall back to `updated_date`.

**Comment by AdClear247** [comment]
Now I am worried I will have to again redownload all 100 files I downloaded in last 2 days just because of bit different date. Can you make it reverse? So that created date only is used if updated date is not available?

**Comment by qsniyg** [comment]
Actually I'll do you one better: With https://github.com/qsniyg/maxurl/commit/7af7cb78f11c779a2657864667f8aa4e188234b0, `updated_date` will automatically be filled by `created_date` if it doesn't exist, which really should've been the default behavior all along (as for most websites, `updated_date` should be almost if not entirely equal to `created_date`)
