### ISSUE TITLE
[support] LiveJournal proxy images

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#755]
A nice example:
`https://imgprx.livejournal.net/7ab10bef3938e112cee127cb43e369a98b72828c/IWT9g8HLAHrjagV4vcveBxuJ_VUAqDMeloizxRtNPD8yqp9MVBC8bjXf3Gm5Gf5914-RhAosF3BEi2kxlvFkpN9zAHmbCe-5-VPHvSBN03I`

It seems that this link redirects to another link, where the image URL is visible.
Practically the image URL is in the page URL, wow. But... the redirection exists...

Would be nice : ))

**Comment by qsniyg** [comment]
Thanks! Should be supported now.

Not all livejournal sites have proxy links that redirect though, strangely, and some don't even have surrounding links. I'm not sure what to do about those, because the link url is encrypted unfortunately.

**Comment by elvisef** [comment]
Alright, I've just loaded the newest version but it still does not show a direct image URL. Just the link after redirection.
Any ideas ?  : (

Do I need specific options to be enabled ?
Attac
[Uploading maxurl_options.txt…]()

hing options.

**Comment by qsniyg** [comment]
Can you send the original page URL?

**Comment by elvisef** [comment]
> 
> 
> Can you send the original page URL? Since this works partly as a host rule, it could be due to some conflict there.

I meant URL from the first post, I've posted.

**Comment by qsniyg** [comment]
Should be fixed with https://github.com/qsniyg/maxurl/commit/90a402e98d4c6f8f674f99c78b0a936ece284830 now :)

**Comment by elvisef** [comment]
Hmm, weird... If I go to the link in my first post, I still have no plain image visible. 

Look:
![firefox_2021-05-17_22-37-08](https://user-images.githubusercontent.com/25976749/118553161-3f334480-b760-11eb-93ee-7dac3a1c0bf7.png)

What option should I have enabled to see a direct link image ?

**Comment by qsniyg** [comment]
If you go to the link, it'll redirect to the page. In fact, if you go to a direct radikal image link, it'll often redirect to the page (not always, again due to cache). This is because the server detects whether it's being loaded as an image (i.e embedded within a document), or as a document (i.e opened in a new tab). The script can't do very much in that case, but it should work if you open the popup or use the replace images feature.

**Comment by elvisef** [comment]
Alright. I have no clue how to test it now. I've just came back to answer unclosed issues, but...
- [https://livejournal.net/](url) is a dead link now
- [https://imgprx.livejournal.net/](url) is forbidden

I don't know, but if the plugin makes images from the link larger, using the original format image, I think You can close it now, as done. We can re-open it anytime or make a new issue if something goes wrong.

The link from my first post returns blank page ;/

**Comment by elvisef** [comment]
Alright. I have no clue how to test it now. I've just came back to answer unclosed issues, but...
- [https://livejournal.net/](url) is a dead link now
- [https://imgprx.livejournal.net/](url) is forbidden

I don't know, but if the plugin makes images from the link larger, using the original format image, I think You can close it now, as done. We can re-open it anytime or make a new issue if something goes wrong.

The link from my first post returns blank page ;/

**Comment by qsniyg** [comment]
Wow, livejournal being shut down is a bit depressing. Another era of the internet gone. A bit like yahoo answers being shut down a few months ago.

**Comment by elvisef** [comment]
Alright. I have no clue how to test it now. I've just came back to answer unclosed issues, but...
- [https://livejournal.net/](url) is a dead link now
- [https://imgprx.livejournal.net/](url) is forbidden

I don't know, but if the plugin makes images from the link larger, using the original format image, I think You can close it now, as done. We can re-open it anytime or make a new issue if something goes wrong.

The link from my first post returns blank page ;/
