### ISSUE TITLE
images.tori.fi

### ISSUE THREAD

**Issue by thomas-ed** [qsniyg/maxurl#759]
tori.fi: example of smaller image of page
https://www.tori.fi/uusimaa/Iciw_uusi_vaatepaketti_84145688.htm
when opening some of image urls of product page to new page, example
https://images.tori.fi/api/v1/imagestori/images/5994569715.jpg?rule=adwatches
https://images.tori.fi/api/v1/imagestori/images/5994569715.jpg?rule=medium_660
https://images.tori.fi/api/v1/imagestori/images/5994569715.jpg?rule=medium
https://images.tori.fi/api/v1/imagestori/images/5968999758.jpg?rule=thumbs

-> need it to change to bigger version:
https://images.tori.fi/api/v1/imagestori/images/5994569715.jpg?rule=big
(can be found here) https://www.tori.fi/kaikki_kuvat.htm?id=84145688

thanks

**Comment by qsniyg** [comment]
Thank you! Turns out `rule=original` works too, and results in even higher quality :)

**Comment by fyhtma** [comment]
> Thank you! Turns out `rule=original` works too, and results in even higher quality :)

Site has totally changed. Need support, example 142px width thumbnail to 1280px width image
https://web.archive.org/web/20240614221632/https://webcache.googleusercontent.com/search?q=cache:https:%2F%2Fwww.tori.fi%2Frecommerce%2Fforsale%2Fitem%2F9171352

https://img.tori.net/dynamic/142w/2024/6/vertical-0/01/2/917/135/2_0b3fc6f5-3959-45e1-96f9-0676ae4924fa.jpg
->
https://img.tori.net/dynamic/1280w/2024/6/vertical-0/01/2/917/135/2_0b3fc6f5-3959-45e1-96f9-0676ae4924fa.jpg

and https://www.tori.fi/recommerce/forsale/item/9584656?ci=2
https://img.tori.net/dynamic/960w/2024/6/vertical-0/11/6/958/465/6_ae54bef6-6f18-4966-bb82-1919a99c515e.jpg
->
https://img.tori.net/dynamic/1280w/2024/6/vertical-0/11/6/958/465/6_ae54bef6-6f18-4966-bb82-1919a99c515e.jpg

idk is there any wider resolution than1280px

**Comment by fyhtma** [comment]
doesn't work for me, tried couple different web browers

active listing https://www.tori.fi/recommerce/forsale/item/30107652
https://img.tori.net/dynamic/142w/item/30107652/5ec45473-daf7-495c-9f42-8a5c12c6a9f0
https://img.tori.net/dynamic/320w/item/30107652/5ec45473-daf7-495c-9f42-8a5c12c6a9f0
https://img.tori.net/dynamic/1280w/item/30107652/5ec45473-daf7-495c-9f42-8a5c12c6a9f0
https://img.tori.net/dynamic/1600w/item/30107652/5ec45473-daf7-495c-9f42-8a5c12c6a9f0
-> https://img.tori.net/dynamic/original/item/30107652/5ec45473-daf7-495c-9f42-8a5c12c6a9f0


deleted listing, images still online:
https://img.tori.net/dynamic/960w/3d/3d6d0e12-d798-4d0a-b531-531085024b7f
https://img.tori.net/dynamic/1600w/3d/3d6d0e12-d798-4d0a-b531-531085024b7f
-> https://img.tori.net/dynamic/original/3d/3d6d0e12-d798-4d0a-b531-531085024b7f

old active listing https://www.tori.fi/recommerce/forsale/item/9584656?ci=2
https://img.tori.net/dynamic/1600w/2024/6/vertical-0/11/6/958/465/6_ee63bbb7-572f-44f5-926f-54d27268de76.jpg
-> https://img.tori.net/dynamic/original/2024/6/vertical-0/11/6/958/465/6_ee63bbb7-572f-44f5-926f-54d27268de76.jpg

**Comment by qsniyg** [comment]
Thanks, supported!

**Comment by fyhtma** [comment]
this need to be fix
https://img.tori.net/dynamic/480x480c//item/32172235/8cf31737-0403-4562-a495-968f61f13e9a
->
https://img.tori.net/dynamic/original//item/32172235/8cf31737-0403-4562-a495-968f61f13e9a


it work from [/dynamic/960w/3](https://img.tori.net//dynamic/960w//item/32172235/8cf31737-0403-4562-a495-968f61f13e9a) and https://img.tori.net//dynamic/1600w//item/32172235/8cf31737-0403-4562-a495-968f61f13e9a but not from /dynamic/480x480c/

**Comment by qsniyg** [comment]
Thanks, fixed!
