### ISSUE TITLE
[pattern] relative path in `?url=`

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#763]
from: `https://opencollective.com/_next/image?url=%2Fstatic%2Fimages%2Fhome%2FcelebrateSupporters-screenshot.png&w=1920&q=75`

to: `https://opencollective.com/static/images/home/celebrateSupporters-screenshot.png`

tech: https://nextjs.org/docs/api-reference/next/image

**Comment by qsniyg** [comment]
Thank you!

I've supported it as a non-generic rule for the moment, until more websites are found (just to make sure it's generic enough without being too generic). I'll try to look for some later when I have some time :)

As for trying the relative path, see https://github.com/qsniyg/maxurl/issues/384 . That said, I just remembered that `looks_like_valid_link` is indeed accessible from bigimage now, so I should probably get on that soon...
