### ISSUE TITLE
Support ARD Mediathek

### ISSUE THREAD

**Issue by kellnerd** [qsniyg/maxurl#770]
It would be nice if you could support ARD Mediathek (https://www.ardmediathek.de/ and https://www.ardaudiothek.de/), these German public broadcasting sites share the same server for images and their URLs can be easily manipulated to return images in a higher (the highest?) resolution.

Default image URLs (these also work without the `?mandant=ard` query parameter):
1. https://img.ardmediathek.de/standard/00/86/73/27/62/-1774185891/1x1/448?mandant=ard
2. https://img.ardmediathek.de/standard/00/89/49/17/14/-1774185891/16x9/1280?mandant=ard
2. https://img.ardmediathek.de/standard/00/71/97/58/06/-1852531467/16x9/1920?mandant=ard

Hires Image URLs:
1. https://img.ardmediathek.de/standard/00/86/73/27/62/-1774185891/1x1/9999 redirects to https://img.ardmediathek.de/standard/00/86/73/27/62/-1774185891/1x1/4992?mandant=ard
2. https://img.ardmediathek.de/standard/00/89/49/17/14/-1774185891/16x9/9999 redirects to https://img.ardmediathek.de/standard/00/89/49/17/14/-1774185891/16x9/4992?mandant=ard

Currently the default image width seems to be either 1280px, 1920px (16:9 aspect ratio) or 448px (1:1 aspect ratio) while the hires versions always seem to be 4992px, at least for the images I have experimented with so far, but it is possible that there other default values and they may change them in the future.
I am mainly interested in the 1:1 aspect ratio images as the 16:9 images look like they are simply upscaled (the source video of the screenshot is unlikely to have a higher resolution than 1920px).

Apparently there also is a second URL format where it is sufficient to remove the `?w=368` query parameter (these do not get upscaled to 4992px if this is beyond their original resolution):
- JPEG: https://images.ardmediathek.de/vrwifdtrtsys/6B0pQKK5D6VKnpETpWkp0L/20f93de9e39723911351ac8e3fe6ef20/Mord_im_Spiegel.jpg?w=368
- PNG: https://images.ardmediathek.de/vrwifdtrtsys/MPjpOH4IwFTyEWxlhGnQn/65828fbad0b207683e83d0fd6c168047/16x9-Hackerville.png?w=368

**Comment by qsniyg** [comment]
Thank you very much for sharing your research, supported! Turns out `/0x0/` allows you to get a non-upscaled image :)
