### ISSUE TITLE
cdn.sonyselect.com.cn

### ISSUE THREAD

**Issue by nimuxoha** [qsniyg/maxurl#774]
https://hi-resmusic.sonyselect.kuke.com/page/album.html?id=1052
http://cdn.sonyselect.com.cn/Hi-Res/flacs_20170628/Covers/a-lin_512.jpg
http://cdn.sonyselect.com.cn/Hi-Res/flacs_20170628/Covers/a-lin.jpg

There are also cases where there seems to be no larger image:
https://hi-resmusic.sonyselect.kuke.com/page/album.html?id=252
http://cdn.sonyselect.com.cn/Hi-Res/flacs_20160518/Covers/cd_512.jpg
http://cdn.sonyselect.com.cn/Hi-Res/flacs_20160518/Covers/cd.jpg (404)

And at least one case where the filename pattern is completely different
https://hi-resmusic.sonyselect.kuke.com/page/album.html?id=29
http://cdn.sonyselect.com.cn/Hi-Res/flacs_20150115/covers/7432435_2007-mlib_1500x1500_300dpi_RGB_100Q.jpg
No idea if that one exists in larger

**Comment by qsniyg** [comment]
Thank you! I wasn't able to find anything larger for that one either unfortunately, from the quick experimentation I did.
