### ISSUE TITLE
bkimg.cdn.bcebos.com

### ISSUE THREAD

**Issue by nimuxoha** [qsniyg/maxurl#775]
These seem rather easy
https://baike.baidu.com/item/%E5%93%81%E5%86%A0/225046
https://bkimg.cdn.bcebos.com/pic/3b87e950352ac65c1038460fc9b9a5119313b07e1c3e?x-bce-process=image/resize,m_lfit,h_250,limit_1/format,f_auto
https://bkimg.cdn.bcebos.com/pic/3b87e950352ac65c1038460fc9b9a5119313b07e1c3e

There is even a parameter that adds a watermark:
https://bkimg.cdn.bcebos.com/pic/4d086e061d950a7b0208ada7389a75d9f2d3572c6336?x-bce-process=image/watermark,image_d2F0ZXIvYmFpa2UxMTY=,g_7,xp_5,yp_5/format,f_auto
https://bkimg.cdn.bcebos.com/pic/4d086e061d950a7b0208ada7389a75d9f2d3572c6336

**Comment by qsniyg** [comment]
Thanks! Indeed, it seems like just a small variation over the standard `x-oss-process` rule.
