### ISSUE TITLE
Add ability to drag image outside of the browser

### ISSUE THREAD

**Issue by grudir** [qsniyg/maxurl#78]
Add an option to disable popup panning, so that the image can be dragged to another place (tab or program). For example, many times it is useful to drag an image to Windows Explorer, so that it gets downloaded to a folder.

P.S. Very useful extension. Thank you!

**Comment by qsniyg** [comment]
This should work if you set "Popup panning method" to "Movement" :) And you're welcome!

If it doesn't though, feel free to reopen this issue and I'll try to fix it.

**Comment by grudir** [comment]
Thanks for the hint @qsniyg I didn't notice that! By the way I keep *Popup UI* disabled and dragging doesn't work for me until I enable *Popup UI*. But it is not a big deal, so I can enable it back :)

**Comment by qsniyg** [comment]
That's odd, it works for me, and I don't see anything in the code that would modify it...

Would you mind sending a screenshot of the settings page when Popup UI is disabled so I can replicate your setup?

**Comment by grudir** [comment]
Sorry for the late reply. Attaching the settings and an example of the UI on google.com. It looks like when the Popup UI is disabled dragging is also disabled. I use Firefox 67.0.1 (64-bit) on Windows 10.
![image-max-url-settings](https://user-images.githubusercontent.com/24936746/59262572-22269a80-8c48-11e9-933f-c066a8c5bfc8.png)
![image-max-url-ui-example-google com](https://user-images.githubusercontent.com/24936746/59262598-2d79c600-8c48-11e9-8f50-fac192224a5e.png)

**Comment by qsniyg** [comment]
Very strange issue, it seems like it only works if an invisible div is added after (like the popup UI does). Should be fixed now though :)
