### ISSUE TITLE
No longer works on Instagram

### ISSUE THREAD

**Issue by MickeyMcNickname** [qsniyg/maxurl#782]
I've used this for months and it was retrieving the max size insta pictures. It no longer does that. I've even tested it on pictures I downloaded previously and know are at 1440. Today maxurl returns the 1080 version only.

Here's the URL for a typical insta picture that used to be available at 1440. 

https://scontent-lga3-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/147443652_1709227485923424_3655756833037547032_n.jpg?tp=1&_nc_ht=scontent-lga3-1.cdninstagram.com&_nc_cat=100&_nc_ohc=0Vnpa69cB1IAX-bfQ7d&edm=AABBvjUBAAAA&ccb=7-4&oh=4d8c10eacba41bf07bde7b270e0dc51a&oe=60BCA02F&_nc_sid=83d603

Please look into this.

**Comment by llacb47** [comment]
That URL isn't helpful. What's the post's URL?

**Comment by qsniyg** [comment]
Please check https://github.com/qsniyg/maxurl/issues/778 :)

(Closing as a duplicate, but if it isn't, please let me know)

**Comment by MickeyMcNickname** [comment]
It is duplicate to #778 and the fix you suggested works for me.

(To fix this, enable "Instagram: Use native API" under the Rules tab. )
