### ISSUE TITLE
img.insight.co.kr

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#79]
The current rule redirects this image:
https://img.insight.co.kr/static/2019/02/08/1200/43gwit848hlwkwzu0y9e.jpg (1200 x 685)
to
https://img.insight.co.kr/static/2019/02/08/43gwit848hlwkwzu0y9e.jpg (700 x 400)

There are also images like this. Replacing 700 with 1200 doesn't work. Removing it doesn't work either.
https://img.insight.co.kr/static/2019/06/07/700/blj7f3x9894qm6ynlyht.jpg

**Comment by qsniyg** [comment]
Thanks for reporting. I looked into this for a bit, but I can't find any examples of images that aren't upscaled that are scaled down via the rule (the first image you linked was upscaled).

Another (more extreme) example is this: https://img.insight.co.kr/static/2017/12/19/2000/92re699ayktd084o5f53.jpg (2000x2666, very upscaled)

Removing /2000/ results in: https://img.insight.co.kr/static/2017/12/19/92re699ayktd084o5f53.jpg (720x960, not upscaled).

Just to make sure (with the image you sent), I tried downloading both, scaling up the smaller one, and subtracting the layers. The result was nearly identical, with only jpeg artifacting being the difference: https://i.imgur.com/RmdeLq6.jpg.

Although I haven't tried doing that with the other ones I tested, the ones that are reduced after the rule are all quite upscaled, which leads me to believe it's the same case for them.

If you find an example where an image that's not upscaled is made smaller, please let me know and I'll disable the rule. For now though, it seems that it's just extracting the original, non-upscaled image :)

About the second image, yeah I don't know what to do about them either :( The usual barrage of original/origin/orig/org/source/src/raw/binary/photo/image/0/-1 did nothing (as expected), and searching for "inurl:img.insight.co.kr -1200 -300 -2000 -700" and blocking out `/ART` and `/issue_` (both of which lead to broken images, using [this userscript](https://greasyfork.org/en/scripts/371978-image-search-exclusion) to block them out) didn't lead to any other patterns either.

**Comment by rEnr3n** [comment]
I'm not really good at spotting upscaled images. I guess I'll close this now.
