### ISSUE TITLE
images.asics.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#790]
https://images.asics.com/is/image/asics/1012A898_400_SR_RT_GLB?$thumb$
https://images.asics.com/is/image/asics/1012A898_400_SB_BT_GLB
https://images.asics.com/is/image/asics/1012A898_400_SB_BT_GLB?$sfcc-product$
https://images.asics.com/is/image/asics/1012A898_400_SB_BT_GLB?$zoom$

Also can you make gallery e.g. for this page: https://www.asics.com/nl/en-nl/noosa-tri-13/p/1012A898-400.html?width=Standard

**Comment by qsniyg** [comment]
Thanks! Should be supported now :)
