### ISSUE TITLE
imgcloud.pw & crazyimg.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#791]
NSFW
https://imgcloud.pw/images/2018/05/11/a0025da32520e6cf10ed83deb477dc1e6527cd7288c5fdee.th.jpg
https://imgcloud.pw/images/2018/05/11/a0025da32520e6cf10ed83deb477dc1e6527cd7288c5fdee.jpg

NSFW
https://crazyimg.com/images/2020/04/jydzkj7zvlenpbatuh0e_tn.jpg
https://crazyimg.com/images/2020/04/jydzkj7zvlenpbatuh0e.jpg

**Comment by qsniyg** [comment]
Thanks! Supported.
