### ISSUE TITLE
images-static.nykaa.com & assets.myntassets.com

### ISSUE THREAD

**Issue by ghost** [qsniyg/maxurl#792]
https://assets.myntassets.com/dpr_2,h_240,q_50,w_180/assets/images/productimage/2019/12/21/9eb4d964-5c68-4b2f-adf2-df7fde570b871576889282570-1.jpg
https://assets.myntassets.com/assets/images/productimage/2019/12/21/9eb4d964-5c68-4b2f-adf2-df7fde570b871576889282570-1.jpg

https://images-static.nykaa.com/media/catalog/product/7/a/7a73905c861_1.jpg?tr=w-500,pr-true
https://images-static.nykaa.com/media/catalog/product/7/a/7a73905c861_1.jpg

**Comment by qsniyg** [comment]
Thanks! nykaa seems to use magento, I wonder if it's a custom version of it? Usually magento uses the `/media/catalog/product/cache/` way to resize images.
