### ISSUE TITLE
theedge-sports.com & static.nike.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#794]
https://www.theedge-sports.com/images/adidas-response-longsleeve-tee-womens-shock-pink-p15811-95561_image.jpg
https://www.theedge-sports.com/images/adidas-response-longsleeve-tee-womens-shock-pink-p15811-95561_medium.jpg
https://www.theedge-sports.com/images/adidas-response-longsleeve-tee-womens-shock-pink-p15811-95561_zoom.jpg

https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/6d6c66ec-4866-45a5-a311-d0c31b9a6f7a/run-short-sleeve-running-top-PQszMF.png
https://static.nike.com/a/images/t_PDP_864_v1/6d6c66ec-4866-45a5-a311-d0c31b9a6f7a/run-short-sleeve-running-top-PQszMF.png
https://static.nike.com/a/images/6d6c66ec-4866-45a5-a311-d0c31b9a6f7a/run-short-sleeve-running-top-PQszMF.png

**Comment by qsniyg** [comment]
Thanks! Supported with https://github.com/qsniyg/maxurl/commit/6a0555baaee077328bff4347ddcd5014deb88aa8
