### ISSUE TITLE
bodytalk.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#796]
https://www.bodytalk.com/uploads/resources/114225/gynaikeio-psilomeso-athlitiko-kolan-thumb.jpg
https://www.bodytalk.com/uploads/resources/114225/gynaikeio-psilomeso-athlitiko-kolan-normal.jpg

**Comment by qsniyg** [comment]
Thanks! Supported. Can't find a way to get the original image, but there is `-huge` (and `-mediafancybox` for photo sets).
