### ISSUE TITLE
media.littlewoodsireland.ie

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#798]
https://media.littlewoodsireland.ie/i/littlewoodsireland/NWUFA_SQ1_0000000005_GREY_MDf?$300x400_retinamobilex2$
https://media.littlewoodsireland.ie/i/littlewoodsireland/NWUFA_SQ1_0000000005_GREY_MDf

**Comment by qsniyg** [comment]
Thanks! Seems like they use their own system, despite how similar it looks to the `/is/image/` one (don't know what it's called).
