### ISSUE TITLE
images.asos-media.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#799]
https://images.asos-media.com/products/nike-running-miler-long-sleeve-top-in-grey/14971488-2?$XXL$&wid=513&fit=constrain
https://images.asos-media.com/products/nike-running-miler-long-sleeve-top-in-grey/14971488-2
https://images.asos-media.com/products/nike-running-miler-long-sleeve-top-in-grey/14971488-2?$XXL$

https://images.asos-media.com/products/asos/9503862-1-black?wid=1959&hei=2500&size=1959,2500&rect=653,625,653,625&qlt=90

**Comment by qsniyg** [comment]
Thanks! Now _that_ one is /is/image (which is apparently scene7)
