### ISSUE TITLE
Key combinations for mouseover popup trigger

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#8]
Can you add key combinations for the popup trigger? The single key trigger can get annoying when I'm navigating tabs (`Ctrl+Shift+Tab`) and windows (`Alt+Shift+Tab`).

Two-key combinations (e.g. `Ctrl+Alt`) would be good. Three-key combinations (e.g. `Alt+Shift+x` or `Ctrl+Alt+Shift`) would be better.

**Comment by bbtora** [comment]
I would like to add that using `Ctrl+LMB` for opening links gets obstructed by the pop-up too.

**Comment by qsniyg** [comment]
I agree, it got quite annoying for me too. I also added support for a mouse delay instead of a keyboard chord.
