### ISSUE TITLE
seprun.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#801]
https://www.seprun.com/media/x70/Nike_Lifestyle_Shoes/Nike_Cortez/Nike_Cortez_Basic_Nylon_Prem_Long_Beach_Blue_White_Royal_Gold_Metallic_902804-400_P1.jpg
https://www.seprun.com/uploads/Nike_Lifestyle_Shoes/Nike_Cortez/Nike_Cortez_Basic_Nylon_Prem_Long_Beach_Blue_White_Royal_Gold_Metallic_902804-400_P1.jpg

**Comment by qsniyg** [comment]
Thanks! Seems to be a custom variation on magento
