### ISSUE TITLE
rackcdn.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#802]
https://df0a04043ae3b0be60ce-0769ebb99367e103e6cc409064fb3339.ssl.cf2.rackcdn.com/550147b7-e06b-4b37-9526-dd7b4e98760e.jpg
https://df0a04043ae3b0be60ce-0769ebb99367e103e6cc409064fb3339.ssl.cf2.rackcdn.com/550147b7-e06b-4b37-9526-dd7b4e98760e__L.jpg

**Comment by qsniyg** [comment]
Thanks! By the way, rackcdn is just the cdn service (from rackspace), like cloudflare :)
