### ISSUE TITLE
static.nike.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#804]
https://static.nike.com/a/images/t_PDP_144_v1/f_auto/afa82b8f-7bd1-4815-9717-062e2da4ea87/indy-light-support-padded-v-neck-sports-bra-P6hxlh.png
https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/126a4647-2aad-484b-9fd6-275a42463250/indy-light-support-padded-v-neck-sports-bra-P6hxlh.png

https://static.nike.com/a/images/t_default/b5f793e9-d912-47e3-8725-8890b4814dce/air-ribbed-long-sleeve-top-81FkRD.jpg

**Comment by qsniyg** [comment]
All of the ones you linked work fine for me (thanks to your report in #794), do they fail for you?

I'll close this in the meantime as I suspect it was a mistake, but please let me know if they don't work :)
