### ISSUE TITLE
Disabling redirecting from video doesn't work properly

### ISSUE THREAD

**Issue by qsniyg** [qsniyg/maxurl#813]
Copying from @InSimpleTermsJordan's comment at https://github.com/qsniyg/maxurl/issues/503#issuecomment-860295879

Version: 1.19.1
Imgur GIF, GIFV, and WEBM links always redirect to the MP4 link (as expected), but if the "Redirect from/to video" setting is disabled, the MP4 link will redirect to the JPG link. For some links, the JPG link will then redirect back to the MP4 link, causing a redirect loop.
Example: https://i.imgur.com/ouePGl6.gif

**Comment by haarp** [comment]
i'm running v0.19.5 of the userscript and I'm still experiencing imgur videos getting redirected to static images

**Comment by qsniyg** [comment]
@haarp Sorry for getting back so late, I had entirely forgotten to reply. Can you send me your settings? (Export button at the top)
