### ISSUE TITLE
myntassets.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#816]
https://assets.myntassets.com/dpr_2,h_240,q_50,w_180/assets/images/productimage/2020/11/9/9c081b63-bd33-457a-b642-cf87967423781604926461757-1.jpg
https://assets.myntassets.com/assets/images/productimage/2020/11/9/9c081b63-bd33-457a-b642-cf87967423781604926461757-1.jpg

**Comment by qsniyg** [comment]
Thanks! Gotta love cloudinary :)
