### ISSUE TITLE
Kavyar.com + Models.com

### ISSUE THREAD

**Issue by sn3akyb3ar** [qsniyg/maxurl#818]
It should be pretty easy to add rules for these two websites.
Examples:

**Kavyar** - https://kavyar.com/works/jihprmkkjk7w
--
https://dfocupmdlnlkc.cloudfront.net/original/974e2500-8f48-44d6-90a3-2ed20967771f_1200x1200.jpg
should be changed to
https://dfocupmdlnlkc.cloudfront.net/original/974e2500-8f48-44d6-90a3-2ed20967771f_9999x9999.jpg

**Models** - https://models.com/work/vogue-hong-kong-all-a-glow/1525189
--
https://i.mdel.net/i/db/2021/6/1525189/1525189-800w.jpg
->
https://i.mdel.net/i/db/2021/6/1525189/1525189-orig.jpg

**Comment by qsniyg** [comment]
Thanks! I've supported kavyar :)

The i.mdel.net link redirects for me... does it not redirect for you?

**Comment by sn3akyb3ar** [comment]
> i.mdel.net
You're right, it works with a clean install. I guess one of my addons was preventing it from redirecting :( Thanks for adding Kavyar.

**Comment by sn3akyb3ar** [comment]
@qsniyg could you fix Kavyar, please? They serve webp instead of jpg now and redirection is broken for me.

https://dfocupmdlnlkc.cloudfront.net/original/634e934c-7665-4892-903a-b394f51aab7e_1500x3000q75_jpg.webp
->
https://dfocupmdlnlkc.cloudfront.net/original/634e934c-7665-4892-903a-b394f51aab7e_99999x99999.jpg

**Comment by qsniyg** [comment]
Thanks! Fixed :)
