### ISSUE TITLE
nijie.info support

### ISSUE THREAD

**Issue by Kattus** [qsniyg/maxurl#82]
nijie.info is a site similar to pixiv and other similar sites hosting anime style erotica.

an URL may look like this: `https://pic02.nijie.info/__rs_l30x30/nijie_picture/498_20120828123910.jpg` or `https://pic02.nijie.info/__rs_l300x300/nijie_picture/498_20120828123910.jpg`

removing `/__rs_l30x30` (or whatever may appear in the part before `nijie_picture`) gives you full resolution like so:
`https://pic02.nijie.info/nijie_picture/498_20120828123910.jpg`

there are subdomains other than pic02, so I guess a wildcard would have to be in place.

**Comment by qsniyg** [comment]
Thank you! I've added it in, I've only done a bit of research so let me know if there are any URLs that don't work under the rule :)

**Comment by Kattus** [comment]
I came across another few images that have `pic.nijie.net` as opposed to `pic##.nijie.info` like so:
`https://pic.nijie.net/02/__rs_cns30x30/nijie_picture/893000_20180402180213_0.png`

These obviously don't work with the current filter, but acts the same way (removing the same part of the URL)

**Comment by qsniyg** [comment]
@Kattus Thanks! I've updated the rule here: https://github.com/qsniyg/maxurl/commit/773b5e66d4395200ae8dba0907bd5915f1931875#diff-27f9d4a32bb1055d6e25712679ce34afL32128
