### ISSUE TITLE
How do I stop the "custom headers" popup?

### ISSUE THREAD

**Issue by DevWannabe-dot** [qsniyg/maxurl#822]
Basically this appears every time I open a Tumblr YouTube thumbnail in its maximum size. I don't know what's the purpose of this, just that it does not serve me. No specific setting really prevented it from loading; help?

![image](https://user-images.githubusercontent.com/64389041/122690780-c3fefb80-d201-11eb-8199-da0fc4806771.png)

**Comment by qsniyg** [comment]
Thanks for reporting! I've added an option ("Enable tooltip" under Redirection) to allow you to toggle this :)

**Comment by DevWannabe-dot** [comment]
big thx, it's all great 🔥
