### ISSUE TITLE
last modified header as file name for mbasic.facebook.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#826]
When I go to some public or private profile photo such as this one: https://mbasic.facebook.com/photo.php?fbid=1583065815213688&id=100005308538439&set=a.109070472613237
Then in normal network request (by browser) there is no last modified header for photo, probably their privacy concern, I remember previously it had.
But when I use popup action popup and observe in `[about:devtools-toolbox?id=maxurl%40qsniyg&type=extension](about:devtools-toolbox?id=maxurl%40qsniyg&type=extension)` headers, I see last modified header.
When I wanna save that either by pressing S or using default action of popup to be save, then it just uses picture name, instead of last modified header.
My rule for name is: `{updated_yyyymmdd_utc} {updated_hhmmss_utc}`
I also tried using my favorite instagram name rule: `{author_username} {id} {updated_yyyymmdd_utc} {updated_hhmmss_utc} {filename}`
Name in both cases is `130726180_1583065818547021_271647124025395998_n.jpg` instead.

**Comment by qsniyg** [comment]
Can you send the image itself? I can't access it as I don't have a FB account unfortunately

**Comment by MinuteAd8502** [comment]
Oh, it works when saved from new tab direct url, just does not work when from page.
https://scontent-lga3-2.xx.fbcdn.net/v/t1.6435-0/cp0/e15/q65/p320x320/130726180_1583065818547021_271647124025395998_n.jpg?_nc_cat=100&ccb=1-3&_nc_sid=85a577&efg=eyJpIjoiYiJ9&_nc_ohc=5vhPE3sHLO8AX_x-9H6&_nc_ht=scontent-lga3-2.xx&tp=3&oh=6e3a7f4e4b3527d75573d68f76f61f87&oe=60D64584

**Comment by MinuteAd8502** [comment]
Actually that what I said in last reply is true for file name rule 1.
But file name rule 2 does not work. I expected if rule part to the left does not work, it would try next. e.g. if `{author_username} {id} {updated_yyyymmdd_utc} {updated_hhmmss_utc} {filename}` does not work it will try `{id} {updated_yyyymmdd_utc} {updated_hhmmss_utc} {filename}` then if that neither `{updated_yyyymmdd_utc} {updated_hhmmss_utc} {filename}`...

**Comment by qsniyg** [comment]
Thanks! I managed to track down the issue, it was due to cache not returning the proper response type for head requests (which is what the download popup trigger does).
