### ISSUE TITLE
Rule for *.jutarni.hr

### ISSUE THREAD

**Issue by heptal** [qsniyg/maxurl#83]
Works in edited userscript:
```js
if (domain_nosub === "jutarnji.hr") {
    return src.replace(/(\/alternates\/)[^/]+/i, "$1BASE_FREE")
}
```

src-url-sized:
https://sportske.jutarnji.hr/incoming/dalic_moskva_pletikosajpg/9013841/alternates/FREE_680/Dalic_Moskva_pletikosa.jpg
large:
https://sportske.jutarnji.hr/incoming/dalic_moskva_pletikosajpg/9013841/alternates/BASE_FREE/Dalic_Moskva_pletikosa.jpg
___
src-url-sized:
https://www.jutarnji.hr/incoming/davorin_rudolf1-220316jpg/6319624/ALTERNATES/LANDSCAPE_380/davorin_rudolf1-220316.jpg
large:
https://www.jutarnji.hr/incoming/davorin_rudolf1-220316jpg/6319624/ALTERNATES/BASE_FREE/davorin_rudolf1-220316.jpg

**Comment by qsniyg** [comment]
Thank you very much! Actually there's an even larger version available:

https://sportske.jutarnji.hr/incoming/dalic_moskva_pletikosajpg/9013841/BINARY/Dalic_Moskva_pletikosa.jpg

and:

https://www.jutarnji.hr/incoming/davorin_rudolf1-220316jpg/6319624/BINARY/davorin_rudolf1-220316.jpg

It uses the same engine that a number of other news sources use (not sure what the name of it is) :)
