### ISSUE TITLE
open.spotify.com filter pattern

### ISSUE THREAD

**Issue by DevWannabe-dot** [qsniyg/maxurl#833]
I don't know better than opening an issue, so I'm open to advice! I just found out the pattern for [Spotify](https://open.spotify.com) max image url in case a user comes across a spotify [release](https://en.wikipedia.org/wiki/Art_release#Music "LPs, singles, EPs") or artist profile image in a new tab, either from network, sources or elements tab in devtools.

![Ed Sheeran's +](https://i.scdn.co/image/ab67616d00001e02f0e911d0e5aadefc431bf34a "Ed Sheeran's +")
given the url: 			
		  https://i.scdn.co/image/ab67616d00001e02f0e911d0e5aadefc431bf34a		  
1. i.scdn.co/image/ab67616d0000
2. 1e02
3. f0e911d0e5aadefc431bf34a

***
**universal rule:** 
1. [ab67616d0000](https://i.scdn.co/image/ab67616d00001e02f0e911d0e5aadefc431bf34a) labels a image for a [release](https://en.wikipedia.org/wiki/Art_release#Music "LPs, singles, EPs") on Spotify, [ab6761670000](https://i.scdn.co/image/ab6761670000ecd4b55df6eca9040d9056e0cbbd) for artist banner and [ab6761610000](https://i.scdn.co/image/ab6761610000517412a2ef08d00dd7451a6dbed6) for artist profile picture;
2. First identifies 300x300, second 640x640
	1. [1e02](https://i.scdn.co/image/ab67616d00001e02f0e911d0e5aadefc431bf34a) and [b273](https://i.scdn.co/image/ab67616d0000b273f0e911d0e5aadefc431bf34a) for a release thumbnail
	2. [f178](https://i.scdn.co/image/ab6761610000f17812a2ef08d00dd7451a6dbed6) and [5174](https://i.scdn.co/image/ab6761610000517412a2ef08d00dd7451a6dbed6) for artist profile picture
4. identifies an unique image id, each release in Spotify library has its own.
***

With a little browsing all the rules above can be verified. Now, what max image url is supposed to do is:

* find and replace [f178](https://i.scdn.co/image/ab6761610000f17812a2ef08d00dd7451a6dbed6) with [5174](https://i.scdn.co/image/ab6761610000517412a2ef08d00dd7451a6dbed6) if the URL begins with "https://i.scdn.co/image/ab6761610000"
* find and replace [1e02](https://i.scdn.co/image/ab67616d00001e02f0e911d0e5aadefc431bf34a) with [b273](https://i.scdn.co/image/ab67616d0000b273f0e911d0e5aadefc431bf34a) if the URL begins with "https://i.scdn.co/image/ab67616d0000"

Expected result: 640x640 (original image source) for artist profile picture or release thumbnail, originally 300x300, on spotify.com.

![](https://i.imgur.com/0k6L5kl.png)

**Comment by DevWannabe-dot** [comment]
sorry I have no idea how to implement this in my code nor to label this issue... but I thought it would be a good addition, not only on my browser :)

**Comment by qsniyg** [comment]
Thank you very much for both sharing that research and being so thorough with your explanation! I've implemented it in the script as you explained :)

I'll look around some more to see if I can find any other rules (mainly through `inurl:i.scdn.co`)...

**Comment by DevWannabe-dot** [comment]
I can't reopen the issue and don't wanna flood, so, just wanna add through this comment that [4851](https://i.scdn.co/image/ab67616d00004851f0e911d0e5aadefc431bf34a) must be replaced by [b723](https://i.scdn.co/image/ab67616d0000b273f0e911d0e5aadefc431bf34a) too, it's a size preset used for albums on [spotifycharts](http://spotifycharts.com). 

https://i.scdn.co/image/ab67616d00004851df16d539f508603bfb1efe02 - smallest
https://i.scdn.co/image/ab67616d00001e02df16d539f508603bfb1efe02 - medium
https://i.scdn.co/image/ab67616d0000b273df16d539f508603bfb1efe02 - biggest

Sorry if these contributions don't add much to the project, but it's what I've found :)

**Comment by qsniyg** [comment]
Thank you! Will add once I get a chance.

>Sorry if these contributions don't add much to the project

Anything and everything is very welcome! :)
