### ISSUE TITLE
Can't do image resize for these galleries

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#836]
It's a polish primary school site.
It has some galleries here: [http://sp5czerwionka.pl/galeria](url)

None of them can be used with ImageMaxURL or I do not have certain options enabled : ]
Can You please verify it ?

Sapmple galleries:
[http://sp5czerwionka.pl/index.php?c=modules&mod=mod_gallery&type=art&id=211](url)
[http://sp5czerwionka.pl/galeria,art,156,pasowanie-na-czytelnika](url)

Here's one more site, another school:
[http://sp4czerwionka.szkolnastrona.pl/art,1793,czytanie-na-dobranoc-online-w-kl-1a-i-1b](url)

**Comment by qsniyg** [comment]
Sorry for the late response, if I understand your question correctly, I've supported it here: https://github.com/qsniyg/maxurl/commit/e3baf53067fadc5567df3df98bfc0062fdd2e3a8

Or was the problem that the popup doesn't open at all on those sites? If so, please send your settings, it works fine on my end.

**Comment by elvisef** [comment]
For this link: [http://sp5czerwionka.pl/galeria](url) galleries work. I've checked at work, it did not work, but at home it's working, so maybe some blocking addons prevented some actions..

But this one: [http://sp4czerwionka.szkolnastrona.pl/art,1793,czytanie-na-dobranoc-online-w-kl-1a-i-1b(url) is not working for me. MaxUrl does nothing generally. Even the option to "find larger image" with the right click menu did not work, and the image found was just 400px, not 900px as the original picture while opening in the new tab.

I am sending You plugin options I have set.
[opts.txt](https://github.com/qsniyg/maxurl/files/6833091/opts.txt)

**Comment by qsniyg** [comment]
I'll look into the "find larger image" thing not working in a bit, it should in theory work...

I just remembered that you use the replace images feature. The issue with that site is that it uses images embedded within SVGs. I'll have to add support for that with replacing images, because it uses a different method to find images (mainly: "search for all <img> or <picture> tags").

**Comment by elvisef** [comment]
Yeah, I know it uses SVG tags, but I think this should not be a big deal for You.
Sincerely, I have never seen SVG's with images inside before. 

SVG's only - yes. But not with embedded images : ) But it looks like it works almost same.
Alright, would be good to support such elements in the future, because I think some more pages can use this.

**Comment by qsniyg** [comment]
If you're trying to batch download, could it be easier to use the gallery download (shift+d) feature for this? I don't think most batch image downloading addons support SVGs...

**Comment by elvisef** [comment]
I've just tries SHIFT + D and it does not download anything. Nothing happens.
Is this working for You with this gallery ( with the link: [http://sp4czerwionka.szkolnastrona.pl/art,1793,czytanie-na-dobranoc-online-w-kl-1a-i-1b](http://sp4czerwionka.szkolnastrona.pl/art,1793,czytanie-na-dobranoc-online-w-kl-1a-i-1b) ) ?

**Comment by qsniyg** [comment]
Yes, it works fine for me. Make sure the popup is open on one of the images in the gallery (doesn't matter which, as long as the gallery is detected) before pressing Shift+D.

If that doesn't work, can you send your settings?

**Comment by elvisef** [comment]
My settings. Still does not work for me. Wondering if this is due to my global keys settigns. But hmm... should work... ; /
[maxurl_settings.txt](https://github.com/qsniyg/maxurl/files/6953052/maxurl_settings.txt)

**Comment by qsniyg** [comment]
I don't understand, it still works fine for me with your settings, using the git version. Are you using the git version?

It did fail when HTTPS-only mode was enabled under Firefox though (creates infinite redirects for some reason). Perhaps if that's enabled, try disabling it?

**Comment by elvisef** [comment]
My FF version is 78 ESR - final version for my Debian 10.. So https-only mode is not forced I think.
Anyway, Chrome and FF was tested by me with Your addon.
I tried of course the git newest version, CH and FF.

It still does not work  for me. I've checked all keyboard shortcuts on my system, but it seems there is not SHIFT+D defined, so hmm.. should work.

Generally nothing happens while hitting the shortcut. Even if one of images is shown in the popup.
ehh... ; |

I am always using Your addon to make images bigger and then ImagePicka addon to batch download them.
It not always works, but almost every time it works well.

So You say if I press the SHIFT+D shortcut, images should be batch downloaded ?

**Comment by qsniyg** [comment]
Sorry, now I'm really confused what the cause might be. Just to make absolutely sure we're on the same page:

 1) Mouse over the image on the page (not when the image is opened in a new tab)
 2) Shift+alt+i to open the popup
 3) The popup opens with the image
 4) Shift+d to batch download
 5) A progress bar like the one used for replacing images should show up
 6) Once it's done, it should pop up a zip file containing all the images

So when doing steps 1-4, 5-6 doesn't happen?

Speaking of this issue though, I'll try to add an option to replace svg->normal images, so that they can be picked up by batch downloading addons.
