### ISSUE TITLE
images.nike.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#837]
https://images.nike.com/is/image/DotCom/NESSA421_693_A_PREM
https://images.nike.com/is/image/DotCom/NESSA421_693_A_PREM?bgc=f5f5f5&hei=1080&wid=1080

should be: https://images.nike.com/is/image/DotCom/NESSA421_693_A_PREM?scl=1&fmt=webp
or: https://images.nike.com/is/image/DotCom/NESSA421_693_A_PREM?scl=1&fmt=png-alpha

Looks like this `is/image/` should be made as more generic rule as too specific rule is less useful, there may be more sites.
We already had same rule for underarmour.scene7.com
Also when are you finally make webp instead of png-alpha as default or additional choice?

**Comment by qsniyg** [comment]
I agree, making it generic is probably a good idea at this point, thanks!

As for the option, I think what I have to do is to add another property (file format) to the returned info object, then filter it in `bigimage_recursive`. Sorry I've been very busy lately (hence the lack of activity), I'll try to get around to it soon :)
