### ISSUE TITLE
aceshowbiz.com max image url

### ISSUE THREAD

**Issue by DevWannabe-dot** [qsniyg/maxurl#840]
// [https://www.aceshowbiz.com/images/news-thumb/2010/07/gossip_girl_14_wenn2924972.jpg](https://www.aceshowbiz.com/images/news-thumb/2010/07/gossip_girl_14_wenn2924972.jpg) -- _smaller image_
// [https://www.aceshowbiz.com/images/wennpic/gossip_girl_14_wenn2924972.jpg](https://www.aceshowbiz.com/images/wennpic/gossip_girl_14_wenn2924972.jpg) -- _largest image_

// [https://www.aceshowbiz.com/images/news-thumb/2013/08/taylor-swift-references-kanye-west-s-vmas-rant-on-gift-for-ed-sheeran.jpg](https://www.aceshowbiz.com/images/news-thumb/2013/08/taylor-swift-references-kanye-west-s-vmas-rant-on-gift-for-ed-sheeran.jpg) -- _smaller image_
// [https://www.aceshowbiz.com/images/news/taylor-swift-references-kanye-west-s-vmas-rant-on-gift-for-ed-sheeran.jpg](https://www.aceshowbiz.com/images/news/taylor-swift-references-kanye-west-s-vmas-rant-on-gift-for-ed-sheeran.jpg) -- _largest image_

The 'wennpic' thing can only be found at [aceshowbiz.com](http://aceshowbiz.com), so I have no idea whether it's /wennpic/ or /news/ the correct target url for each case; but I'm sure image max url can attempt both the formats, right? And as far as I know, that news-thumb resized image is displayed across the website for article suggestions and above the news header for images in tall/portrait layout, which is just gross.

**Comment by qsniyg** [comment]
Sorry for getting back so late!

Thank you very much, I've implemented it as you've described :)
