### ISSUE TITLE
img.tennis-warehouse.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#841]
https://img.tennis-warehouse.com/watermark/rs.php?path=AWG8SCS-1.jpg&nw=700
https://img.tennis-warehouse.com/watermark/rs.php?path=AWG8SCS-1.jpg

**Comment by qsniyg** [comment]
Thank you very much! It redirects to `/new_big/` (though it tries the `/rs.php` link as a backup) as I don't really trust `.php` links. Seems like `/new_big/` is the source of the image.
