### ISSUE TITLE
[url] thesenior.com.au, canberratimes.com.au

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#842]
from: `https://www.thesenior.com.au/images/transform/v1/crop/frm/vuJmMAkyxKfBpiJqjiHTXS/6170b4c0-9085-4e3c-9a67-f7d0dba69ae6.jpg/r0_0_2291_1522_w1200_h678_fmax.jpg`

to: `.../r0_0_2291_1522_w0_h0_fmax.jpg`

via: `https://www.thesenior.com.au/story/6498201/fire-burn-and-cauldron-bubble/`

same goes for some similar domains like `canberratimes.com.au` (`https://www.canberratimes.com.au/images/transform/v1/crop/frm/vuJmMAkyxKfBpiJqjiHTXS/6170b4c0-9085-4e3c-9a67-f7d0dba69ae6.jpg/r0_0_2291_1522_w1200_h678_fmax.jpg`)

**Comment by qsniyg** [comment]
Thanks! I should probably make that rule generic, it's specific enough that it shouldn't hurt other rules in theory...
