### ISSUE TITLE
media.sssports.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#846]
https://media.sssports.com/630x630/media/catalog/product/1/9/192564613144_1.jpg
https://media.sssports.com/media/catalog/product/1/9/192564613144_1.jpg

**Comment by qsniyg** [comment]
(Fixed by https://github.com/qsniyg/maxurl/commit/8b0d18d23959d2a69e06a73ce31b6a3c8830aa31)

Seems to be a variation of magento. I wonder whether this should be added to the main rule or not...
