### ISSUE TITLE
static.footshop.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#847]
https://static.footshop.com/517144-full_product/105328.jpg
https://static.footshop.com/517144/105328.jpg

**Comment by qsniyg** [comment]
Thanks! And another prestashop :)

I should probably make it a generic rule, but it would exclude a bunch of urls on prestashop sites from working properly (to avoid breaking non-prestashop sites, as a true generic rule for that one would very likely overstep its boundaries), so they would need to be manually added anyways...
