### ISSUE TITLE
hips.hearstapps.com

### ISSUE THREAD

**Issue by ayunami2000** [qsniyg/maxurl#849]
[https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/close-up-of-white-shaggy-carpet-texture-background-royalty-free-image-921684404-1548358151.jpg?crop=1xw:1xh;center,top&resize=480:*](https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/close-up-of-white-shaggy-carpet-texture-background-royalty-free-image-921684404-1548358151.jpg?crop=1xw:1xh;center,top&resize=480:*)

hd image is at https://hmg-prod.s3.amazonaws.com/images/close-up-of-white-shaggy-carpet-texture-background-royalty-free-image-921684404-1548358151.jpg

**Comment by qsniyg** [comment]
It works for me... does it not for you? It does require the popup when using the userscript as it needs custom headers.

**Comment by ayunami2000** [comment]
ohhh i didnt notice the popup. while im here can you make the popup easier to read since its kinda hard to read with light background and white text? Ill close the issue

**Comment by qsniyg** [comment]
Thanks for letting me know, should be fixed now :)
