### ISSUE TITLE
Rule for pixsell.hr

### ISSUE THREAD

**Issue by heptal** [qsniyg/maxurl#85]
```js
        if (domain_nosub === "pixsell.hr") {
            return src.replace(/&var_suff[^&]+/, '')
        }
```

https://www.pixsell.hr/scripts/get_image.php?image_id= 21859428&var_suff=640x640
https://www.pixsell.hr/scripts/get_image.php?image_id=21859428

And is there a way in the rule to specify the 'Save As' name? For example here the path ends in `get_image.php` but it would be nice to tell it `someMeta.name = src.searchParams.get('image_id')` so it saves as `21859428.jpg`

As seen here: https://www.pixsell.hr/agencija/pxl-standard-news/zagreb-u-zagrebackoj-nadbiskupiji-predstavljena-knjiga-domovinski-rat-galerija-1029118/

**Comment by qsniyg** [comment]
Thank you! About the filename, that's a good idea, I'm not sure if it's possible to do it for the userscript, but I believe there's a header that lets you do that, so it could be done in the addon (as you can modify headers on the fly).

If you have any suggestions as to how to implement it in the userscript though, I'd be glad to support it there too!

**Comment by heptal** [comment]
I’ve been combining maxurl with my own helper userscript with hotkeys/added popup actions for saving via `GM_download` along with file naming rules (like the searchParams example), so it definitely works - I’m not aware of any particular userscript limitations for this

**Comment by qsniyg** [comment]
It should be fully implemented now :)

The userscript will only replace the filename if "Clicking image downloads" is set to "Yes", I'm not sure how else it can do it. The extension supports it fully as it can replace the Content-Disposition header.
