### ISSUE TITLE
doa.robinson.co.th

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#851]
https://doa.robinson.co.th/media/catalog/product/9/c/9cf533a8499a188af99ceef4979e9c52cbd545a0_mkp0009834dummy.jpg?impolicy=resize&width=553
https://doa.robinson.co.th/media/catalog/product/9/c/9cf533a8499a188af99ceef4979e9c52cbd545a0_mkp0009834dummy.jpg

**Comment by qsniyg** [comment]
Thanks, I've implemented it simply by just adding it to the `?.*` rule. I'm not sure whether or not this should be integrated in the usual magento rule though, as I don't think everything's affected by it.
