### ISSUE TITLE
"fashionnetwork.com" need an update

### ISSUE THREAD

**Issue by cbadoud** [qsniyg/maxurl#853]
For instance, images on this page
https://ch.fashionnetwork.com/news/Stella-forest-un-combat-du-quotidien-pour-assurer-la-perennite-de-la-marque,1268003.html
should be maximized when removing "cdn-cgi/image/fit=contain,width=1000,height=1000" parameter.

**Comment by qsniyg** [comment]
Just did, thanks for reporting! https://github.com/qsniyg/maxurl/commit/656eaf3fb4702cf48542e51b5d370c7e27144293 :)

**Comment by cbadoud** [comment]
Waaah, you're just the king of Regex! Thank you very much!

------ Message d'origine ------
De: "M.C." ***@***.***>
À: "qsniyg/maxurl" ***@***.***>
Cc : "Christian" ***@***.***>; "Author" 
***@***.***>
Envoyé : 30.07.2021 22:52:20
Objet : Re: [qsniyg/maxurl] "fashionnetwork.com" need an update (#853)

**Comment by cbadoud** [comment]
Sorry, I don't see the change. Moreover, I need a script update for pictures galeries like https://ch.fashionnetwork.com/galeries/photos/designer.html

**Comment by qsniyg** [comment]
@cbadoud The URL you sent returns 404 for me for some reason. Galleries like https://ch.fashionnetwork.com/galeries/photos/Roberto-Diz,38040.html work for me though (other than the star rating image being included, which I've now removed).

Are you using the git version of the userscript/addon?
