### ISSUE TITLE
Gumroad.com Thumbnails (public-files.gumroad.com)

### ISSUE THREAD

**Issue by antiops** [qsniyg/maxurl#854]
### Example 1:
Thumbnail: https://public-files.gumroad.com/variants/5qypo4josntnsoms61cuw1tlf2yx/3298c3eb001bbed90f1d616da66708480096a0a1b6e81bd4f8a2d6e9b831d301
Full Image: https://public-files.gumroad.com/5qypo4josntnsoms61cuw1tlf2yx

Redirecting to the full image seems fairly straightforward, removing `variants` and the last path string. The image ID is between those 2 in the thumbnail URL (ie `5qypo4josntnsoms61cuw1tlf2yx`)

### Extra Examples:
Thumb: https://public-files.gumroad.com/variants/3v83z8gfsgjpctqgm6sue3fa3u1s/e62e4bcd3d858e4839b5c2b465bae257f22dc2666e91f438860b8031380a9984
Full: https://public-files.gumroad.com/3v83z8gfsgjpctqgm6sue3fa3u1s

Thumb: https://public-files.gumroad.com/variants/iw2al8ewp7gmjk3ujuvtm3bdv1rh/baaca0eb0e33dc4f9d45910b8c86623f0144cea0fe0c2093c546d17d535752eb
Full: https://public-files.gumroad.com/iw2al8ewp7gmjk3ujuvtm3bdv1rh

**Comment by qsniyg** [comment]
(Thanks for reporting and sharing the multiple examples!) It redirects properly for me, does it not for you?

**Comment by antiops** [comment]
Indeed it does, just noticed today my installed version was way out of date. Updated to latest and works as intended
