### ISSUE TITLE
donationcoder.com

### ISSUE THREAD

**Issue by DevWannabe-dot** [qsniyg/maxurl#858]
<h1>Software:</h1>

- In this one, I've not figured out yet if there is a even bigger image out of `images/igallery/resized`. The URL itself suggests there is, but I could not find.
- So, all that needs to be done is:

1.  to remove whatever comes between `95` and `.png` [check example 1;](https://www.donationcoder.com/images/igallery/resized/301-400/mmb4_01-378-120-90-95-c.png)
2. to change the numbers before `95`, that is usually `xxx-xxx-` to `1600-1200-`, note that it does not define the dimensions of any of the images.

smaller:
https://www.donationcoder.com/images/igallery/resized/301-400/mmb4_01-378-120-90-95-c.png
https://www.donationcoder.com/images/igallery/resized/201-300/urlsnoop_Screenshot_main-289-600-300-95.gif

bigger:
https://www.donationcoder.com/images/igallery/resized/301-400/mmb4_01-378-1600-1200-95.png
https://www.donationcoder.com/images/igallery/resized/201-300/urlsnoop_Screenshot_main-289-1600-1200-95.gif
<hr>

<h1>Forum:</h1>
 

- This pattern is fairly easier, as all that must be done is to identify `attach=` in the URL and subtract 1 from the very next nest of numbers, that ends with ;
- The reason is: the thumbnail/smaller image is created right after the original image upload, so it's given the next position in the image index (note that not all the IDs exist, but this rule is universal).

smaller:
https://www.donationcoder.com/forum/index.php?action=dlattach;topic=50231.0;attach=111806;image
https://www.donationcoder.com/forum/index.php?action=dlattach;topic=51544.0;attach=113904;image;image

https://www.donationcoder.com/forum/index.php?action=dlattach;topic=50231.0;attach=111805;image
https://www.donationcoder.com/forum/index.php?action=dlattach;topic=51544.0;attach=113903;image;image

**Comment by qsniyg** [comment]
>The URL itself suggests there is, but I could not find.

There is indeed! :)

https://www.donationcoder.com/images/igallery/resized/301-400/mmb4_01-378-120-90-95-c.png
https://www.donationcoder.com/images/igallery/original/301-400/mmb4_01-378.png

If you're wondering how I found it, simply google `inurl:images/igallery`.

Thanks for the forum one! I hope that there aren't too many cases of images being uploaded right next each other... I'll add that one to "possibly different images" in case.

(I'll add these rules later, for the moment I'm still working on the typescript rewrite. Only 342 errors left to fix...)

**Comment by DevWannabe-dot** [comment]
Oh snap, 342 🥴 I appreciate the persistance, keep it up!!

**Comment by qsniyg** [comment]
Supported now, thanks again for reporting! :)
