### ISSUE TITLE
Some natalie.mu changes

### ISSUE THREAD

**Issue by qsniyg** [qsniyg/maxurl#859]
Copying from nimbuz on discord:

https://ogre.natalie.mu/media/pp/static/music/sayashiriho/photo01s.jpg larger:
 https://ogre.natalie.mu/media/pp/static/music/sayashiriho/photo01.jpg
https://natalie.mu/music/pp/sayashiriho
max url makes this image smaller:  from 
https://ogre.natalie.mu/media/pp/static/music/sayashiriho/pc_header.jpg?impolicy=pp_image to https://ogre.natalie.mu/media/pp/static/music/sayashiriho/pc_header.jpg

**Comment by DevWannabe-dot** [comment]
Nice :) it pisses me off yet is very amusing that every site has their own way to deliver the max image size lol

**Comment by qsniyg** [comment]
Indeed, hence why I started this project haha. At least most sites _tend_ to use common systems (wordpress, imgix, thumbor, etc.).

Interestingly (related to this rule), most Japanese websites tend to use the same "add `s` at the end of the url for small" rule, even if they internally use very different systems. While other websites also use this rule, I do find it fairly interesting that a good majority of Japanese websites use this. Interesting how culture is reflected even in areas like this as well :)

If you're curious, there are also a few other cultural similarities, but they're usually more in terms of CMS software being used. Search for websites like Vogue or Glamour within the script for some examples (most of the regional versions of their websites use a CMS that other websites in their respective country tend to use).

**Comment by DevWannabe-dot** [comment]
ohh that's new for me. Thanks for sharing the info! I had noticed this one too haha

> Interestingly (related to this rule), most Japanese websites tend to use the same "add `s` at the end of the url for small" rule
