### ISSUE TITLE
cdn.mydukaan.io

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#862]
https://cdn.mydukaan.io/app/image/221x308/?url=https://mydukaan.s3.amazonaws.com/1303442/9fbaca6f-816a-4797-b05c-1f32c1302c55/1609823040749.jpeg

https://mydukaan.s3.amazonaws.com/1303442/9fbaca6f-816a-4797-b05c-1f32c1302c55/1609823040749.jpeg

**Comment by qsniyg** [comment]
Thank you!
