### ISSUE TITLE
Discord images

### ISSUE THREAD

**Issue by ExiledEye** [qsniyg/maxurl#865]
Normally a discord image of a profile picture or of an emoji has the url.png and comes with ?size=128.
Normally to show the full image you have to change that 128 to 2048.
But Image Max Url redirects to the image url that ends in .png without ?size=x that in the discord case, shows the 128 image and not the full size one.

**Comment by qsniyg** [comment]
I think it might be fixed in git, can you check?

If not, can you send example links?

**Comment by ExiledEye** [comment]
I noticed that discord emojis and profile pictures have cdn.discordapp.com and in this case Image Max Url already changes 128 to 4096 to show the full image, For sticker is used media.discordapp.net instead where Image Max Url deletes ?sixe=128 instead of changing 128 to 4096.

Example link where this is happening: https://media.discordapp.net/stickers/870295330393034792.png?size=128 (Sticker) [?size=128 gets deleted]
Example link where Image Max Url works as it should: https://cdn.discordapp.com/avatars/144089432130060288/c43498ab8c4d9140921d19a7e95aff48.webp?size=128 (Profile Picture) [?size=128 is changed to ?size=4096].

**Comment by qsniyg** [comment]
Thank you for the links!

I'll close the issue as both of them redirect to 4096 under git (stickers were supported in https://github.com/qsniyg/maxurl/commit/218ee05bffbb73df8d747daf2b21c681f04742b8 ). If you're using the git version and it doesn't work for some reason however, please let me know! :)
