### ISSUE TITLE
cdn.sportsshoes.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#866]
https://cdn.sportsshoes.com/product/A/ASI12224/ASI12224_400_1.jpg
https://cdn.sportsshoes.com/product/A/ASI12224/ASI12224_1000_1.jpg

**Comment by qsniyg** [comment]
Thanks! Some URLs (but not all) can actually go up to 2500: https://cdn.sportsshoes.com/product/R/REE3493/REE3493_2500_8.jpg
