### ISSUE TITLE
upload.wikimedia.org

### ISSUE THREAD

**Issue by ayunami2000** [qsniyg/maxurl#868]
https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/United_States_Congressional_Districts_in_North_Carolina%2C_2021_-_2023.tif/lossless-page1-400px-United_States_Congressional_Districts_in_North_Carolina%2C_2021_-_2023.tif.png

using chrome and tampermonkey (is it because its a TIF file?)

**Comment by qsniyg** [comment]
Thank you! Actually it was because of the `lossless-page1-` prefix. But yes, it will fail to popup because it's a TIFF file, and most browsers don't support that.

I'll have to add support for rendering TIFF files on a canvas element or something...
