### ISSUE TITLE
ztat.net

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#874]
https://img01.ztat.net/article/spp-media-p1/369ffb094cae4443bee45519929dddb8/4269d8d79cfe418888fdc155bf1a8e2e.jpg?imwidth=762
https://img01.ztat.net/article/spp-media-p1/369ffb094cae4443bee45519929dddb8/4269d8d79cfe418888fdc155bf1a8e2e.jpg

**Comment by qsniyg** [comment]
Thanks! Another akamai one
