### ISSUE TITLE
elle.vn

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#875]
Small: https://www.elle.vn/wp-content/uploads/2021/08/14/446014/tap-chi-phai-dep-elle-thang-8-2021-Jennie-scaled.jpg
Large: https://www.elle.vn/wp-content/uploads/2021/08/14/446014/tap-chi-phai-dep-elle-thang-8-2021-Jennie.jpg
Source: https://www.elle.vn/tap-chi-phai-dep-elle/tap-chi-phai-dep-elle-thang-8-2021

This may be a recent change. A previous article uses a format that is already covered by the script.
https://www.elle.vn/tap-chi-phai-dep-elle/tap-chi-phai-dep-elle-thang-7-2021

**Comment by qsniyg** [comment]
Thank you! Yeah the `-scaled` rule didn't catch it because of the extra folders, so I had to add explicit support.
