### ISSUE TITLE
portalrapmais.com

### ISSUE THREAD

**Issue by DevWannabe-dot** [qsniyg/maxurl#876]
https://portalrapmais.com/wp-content/uploads/2020/05/travis-kylie-e1589054381471-120x86.jpg

I guess this site isn't "indexed", but the rule applied to it is actually a default for the `wp-content/uploads` thing. wp is for sites ran on wordpress, right? Well, anyways; if I ask image max url for the biggest image, it returns

https://portalrapmais.com/wp-content/uploads/2020/05/travis-kylie.jpg

When it just needs to remove `-120x86` to get the biggest image size

https://portalrapmais.com/wp-content/uploads/2020/05/travis-kylie-e1589054381471.jpg

**Comment by qsniyg** [comment]
Thank you! I've made the WP rule avoid falling through directly before first committing the `-[0-9]+x[0-9]+` removal.
