### ISSUE TITLE
New site/rule

### ISSUE THREAD

**Issue by waldens** [qsniyg/maxurl#877]
WARNING: NSFW LGBT site

Example Page: https://www.gayeroticvideoindex.com/V/4/54894.html

Small Image:
`https://www.gayeroticvideoindex.com/images/Covers/Icons/4/video54894.jpg`
Larger Image:
`https://www.gayeroticvideoindex.com/images/Covers/4/video54894.jpg`

**Comment by qsniyg** [comment]
Thanks!
