### ISSUE TITLE
ztat.net

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#879]
https://img01.ztat.net/article/spp-media-p1/64384a2f1ddc3987a9a340ee6006874e/dd7c3cfeea104afaae79620df59d9824.jpg?imwidth=500

https://img01.ztat.net/article/spp-media-p1/64384a2f1ddc3987a9a340ee6006874e/dd7c3cfeea104afaae79620df59d9824.jpg?imwidth=1800

https://img01.ztat.net/article/spp-media-p1/64384a2f1ddc3987a9a340ee6006874e/dd7c3cfeea104afaae79620df59d9824.jpg

**Comment by qsniyg** [comment]
It redirects for me (after https://github.com/qsniyg/maxurl/issues/874 was implemented), does it not for you?

**Comment by MinuteAd8502** [comment]
Probably, I did not update.
