### ISSUE TITLE
ostkcdn.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#882]
https://ak1.ostkcdn.com/images/products/is/images/direct/ea064dc4d5061a03cb0cc0d680d2e496e265e274/Under-Armour-Womens-Tech-V-Neck-Twist-Short-Sleeve-T-Shirt.jpg?imwidth=200&impolicy=medium

https://ak1.ostkcdn.com/images/products/is/images/direct/ea064dc4d5061a03cb0cc0d680d2e496e265e274/Under-Armour-Womens-Tech-V-Neck-Twist-Short-Sleeve-T-Shirt.jpg

**Comment by qsniyg** [comment]
Thanks! Strangely, it doesn't seem to respond to normal `/is/image/` queries (perhaps because it's `/is/images/`?).
