### ISSUE TITLE
i.em.com.br

### ISSUE THREAD

**Issue by DevWannabe-dot** [qsniyg/maxurl#888]
em.com.br is a news website, for a newsletter based on Minas Gerais. It's a well-known newspaper in Brazil and I think it'd be useful. The links used in articles thumbnails come from a proxy for external links, I think (like I said discord does to embed links), so all max url needs to do is to remove `/smart/` and anything that comes before, maybe replace it with a `http://` but I think every modern browser can connect to a website without that. So some examples below, 2 presented on the [right side](https://www.em.com.br/app/noticia/especiais/educacao/enem/2015/04/13/noticia-especial-enem,637166/o-principio-da-alavanca-de-arquimedes.shtml) of articles (100x66) and the last presented on the [home page](https://www.em.com.br/) (320x220); both following the same rule. Thanks in advance!

https://i.em.com.br/727sLRr_lrFKjNybpJe9-2NoyKg=/100x66/smart/imgsapp2.uai.com.br/app/da_conteudo_147034442637/2016/10/28/12/20161028112752931152e.jpg
https://imgsapp2.uai.com.br/app/da_conteudo_147034442637/2016/10/28/12/20161028112752931152e.jpg

https://i.em.com.br/uPkgj3UhfZ4gk8VUYSugAgxuckY=/100x66/smart/imgsapp2.uai.com.br/app/da_conteudo_147034442637/2016/11/09/21/20170904114344416906o.jpg
https://imgsapp2.uai.com.br/app/da_conteudo_147034442637/2016/11/09/21/20170904114344416906o.jpg

https://i.em.com.br/WAaCBWxpHqBY1PDAeh6eQ_7uKqA=/330x220/smart/imgsapp.em.com.br/portlet/523/22262/20210829095155428851a.jpg
https://imgsapp.em.com.br/portlet/523/22262/20210829095155428851a.jpg

And I think max url is interfering, because I am getting redirected to http://logo.uai.com.br/uai.jpg sometimes, even tho the links work just fine. Maybe it's the site or my browser :P

**Comment by qsniyg** [comment]
Thank you very much as usual!

This is actually a system called [thumbor](https://github.com/thumbor/thumbor), you can usually detect it by the single `=` after the signature (unsigned images are labelled `unsafe` instead). Thankfully nothing too special was required to get this one supported, just added it to the thumbor rule and it worked :)

>And I think max url is interfering, because I am getting redirected to http://logo.uai.com.br/uai.jpg sometimes, even tho the links work just fine. Maybe it's the site or my browser :P

I'm not sure I understand sorry, can you send an example of a link that does this?

**Comment by DevWannabe-dot** [comment]
https://user-images.githubusercontent.com/64389041/131408120-74fe3330-5f3a-4c0d-8163-5cb2e4f5cbd4.mp4

Certainly it's just the always HTTPS mode from firefox. Not max url, so it's fine :)
