### ISSUE TITLE
[url] courier.com

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#893]
from `https://www.courier.com/_next/image?url=%2Fimages%2Fpages%2Fhome%2Fworkflows%2Fworkflows.png&w=1080&q=75`
to `https://www.courier.com/images/pages/home/workflows/workflows.png`
(via `https://www.courier.com/` )

related: #763

**Comment by qsniyg** [comment]
Thank you! Maybe I should make the `_next/image` rule generic...
