### ISSUE TITLE
[url] egghead.io

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#894]
`https://egghead.io/_next/image?url=https%3A%2F%2Fd2eip9sf3oo6c2.cloudfront.net%2Fplaylists%2Fsquare_covers%2F000%2F487%2F059%2Ffull%2FPrisma_TS.png&w=750&q=100`
\>\> `https://d2eip9sf3oo6c2.cloudfront.net/playlists/square_covers/000/487/059/full/Prisma_TS.png`
(via `https://egghead.io/courses/build-a-backend-with-prisma-in-a-typescript-node-project-ca6628d3`)

and
`https://egghead.io/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdg3gyk0gu%2Fimage%2Fupload%2Fv1607523756%2Fegghead-next-ebombs%2Farticle-illustrations%2Fcodemods.png&w=3840&q=100`
\>\> `https://res.cloudinary.com/dg3gyk0gu/image/upload/v1607523756/egghead-next-ebombs/article-illustrations/codemods.png`
(via `https://egghead.io/blog/codemods-with-babel-plugins`)

related (again): https://github.com/qsniyg/maxurl/issues/763

**Comment by qsniyg** [comment]
Thank you!
