### ISSUE TITLE
feriasbrasil.com.br

### ISSUE THREAD

**Issue by DevWannabe-dot** [qsniyg/maxurl#898]
smaller: https://www.feriasbrasil.com.br/fotosfb/909105248-p.jpg
bigger: https://www.feriasbrasil.com.br/fotosfb/909105248-g.jpg
biggest: https://www.feriasbrasil.com.br/fotosfb/909105248-XG.jpg

keeping only the number.jpg will return 404 page

**Comment by qsniyg** [comment]
Thanks! Also added support for m/mob. Couldn't find anything larger either.
