### ISSUE TITLE
Expired greasyfork link

### ISSUE THREAD

**Issue by o-r-i-z-u-r-u** [qsniyg/maxurl#907]
There's a link in Tamper Monkey to a greasy fork script 

![pictured here](https://user-images.githubusercontent.com/88693606/134097345-78761cde-2336-419e-84f0-38b169d27279.png)

![and here ](https://user-images.githubusercontent.com/88693606/134097147-919eaa6b-c64e-4e2f-b563-e93f19058d95.png)

The link goes to https://greasyfork.org/en/scripts/36662

But it's expired and needs updating.

That's it, that's all, thanks.

**Comment by DevWannabe-dot** [comment]
The issue is explained on #903. If anything you can always use https://web.archive.org/web/*/https://greasyfork.org/en/scripts/36662/*

**Comment by o-r-i-z-u-r-u** [comment]
All good, as long as you're aware :)

What's up with the "disallowed external code"?
Is it because some of the script is hosted on github?

**Comment by DevWannabe-dot** [comment]
Yes. The script is safe but greasyfork has that scrict rule sadly.

> All good, as long as you're aware :)

Nice, but if you meant to talk to the repo owner, it's not me, but it's ok!

**Comment by qsniyg** [comment]
Thank you for reporting! Yes, I need to fix this, but I need to update the packaging scripts before in order for this to be possible.

Alternatively, I could perhaps simply link to the github repository, instead of the userscript. I'm not sure if they would accept this, but it would allow a single build to be used for all userscripts, instead of needing to maintain a special one for greasyfork.

**Comment by LucioAmely** [comment]
You can set up GitHub Actions to automatically compile your TypeScript sources to Userscript Javascripts. Then you can directly use this repository for releases and updates until Greasyfork issue gets resolved.

An example here:
https://github.com/Trim21/webpack-userscript-template/tree/master/.github/workflows

**Comment by qsniyg** [comment]
@LucioAmely Thanks! I'll take a closer look at GH Actions. The current build situation is far from ideal, and I need to improve it significantly.

**Comment by wykopx** [comment]
@qsniyg please remove GreasyFork link in [README.rst](https://github.com/qsniyg/maxurl#readme) file

https://github.com/qsniyg/maxurl#readme


The link doesn't work and is extremely misleading as it is the very first link in that document. 
![image](https://user-images.githubusercontent.com/123825950/217664347-f43571cb-c7d7-4937-ae6d-6efa032ff069.png)

**Comment by wykopx** [comment]
> e x t r e m e l y m i s l e a d i n g

Forgot to take your daily pills?

**Comment by qsniyg** [comment]
Sorry for getting to this so late. Fixed :)
