### ISSUE TITLE
charts-static.billboard.com

### ISSUE THREAD

**Issue by DevWannabe-dot** [qsniyg/maxurl#908]
source: https://charts-static.billboard.com/img/2020/11/the-kid-laroi-qev-without-you-mqd-155x155.jpg
sizes found:
https://charts-static.billboard.com/img/2020/11/the-kid-laroi-qev-without-you-mqd-240x240.jpg
https://charts-static.billboard.com/img/2020/11/the-kid-laroi-qev-without-you-mqd-480x480.jpg (biggest)

other case:
resized: https://charts-static.billboard.com/img/2008/04/lady-gaga-b8x-240x240.jpg
original: https://charts-static.billboard.com/img/2008/04/lady-gaga-b8x.jpg
resized: https://charts-static.billboard.com/img/2009/04/drake-p3d-155x155.jpg
original: https://charts-static.billboard.com/img/2009/04/drake-p3d.jpg

↑ In these cases, removing the size query string from the url works, but in other cases, all that must be done is to check for the sizes given.

_source webpages:_
https://www.billboard.com/charts/hot-100
https://www.billboard.com/music/lady-gaga/chart-history/HSI
https://www.billboard.com/charts/billboard-global-excl-us?rank=88

**Comment by DevWannabe-dot** [comment]
at this point everyone who browses through this repo knows my whole browsing history

**Comment by qsniyg** [comment]
Thanks as usual for reporting! Interesting, removing `-[0-9]+x[0-9]+` from charts-static used to work previously. For example with: https://charts-static.billboard.com/img/2020/08/24kgoldn-hvh-mood-23c-155x155.jpg (now it only accepts 480x480)
