### ISSUE TITLE
teddit.net

### ISSUE THREAD

**Issue by 07416** [qsniyg/maxurl#910]
It appears that only the generic extractor which retrieves direct images  currently works on the site, links to posts aren't compatible — this means that maxurl can't be used on subreddits ([example](https://teddit.net/r/PixelArt/top?t=year)) without opening each submission individually.

example image post: https://teddit.net/r/PixelArt/comments/praia7/some_icons/
example video post: https://teddit.net/r/PixelArt/comments/o3dmjz/been_working_on_a_pixel_art_25d_game_for_a_little/

**note**: I'm only referring to the Reddit's internal image host (which teddit.net serves from their own server), not any third-party services such as Imgur and Gfycat

**Comment by 07416** [comment]
Sorry, I didn't realize that [maxurl redirects teddit.net to Reddit](https://github.com/qsniyg/maxurl/commit/f5858749476f8ada5718d3ea5e52afad7dbbefee) — can the images be sourced directly from `teddit.net/pics/` assuming that the images are identical?

Additionally I assume that teddit.net users prefer not connecting to Reddit.

**Comment by 07416** [comment]
Also the teddit.net image galleries seem incompatible (loads 108x61 thumbnails): https://teddit.net/r/HiTMAN/comments/if2esr/just_in_case_you_missed_it_in_bangkok_after_using/

**Comment by qsniyg** [comment]
Thanks!

> Sorry, I didn't realize that maxurl redirects teddit.net to Reddit — can the images be sourced directly from teddit.net/pics/ if they (the images) are identical?

I've added an option for this, but I don't necessarily recommend enabling it. Unlike other proxy services like Nitter, Teddit's media system doesn't work as a proxy, but rather as a cache. This means that when you load a post, Teddit will download all of the images to their servers. But if they don't download a specific version of an image (such as the original version), that version cannot be fetched through their servers.

**Comment by 07416** [comment]
the related commits:

https://github.com/qsniyg/maxurl/commit/4d2ee81eb43fb6ee902509f8e2ab3fe1477b1a22
https://github.com/qsniyg/maxurl/commit/555099517691012e51a975f12504b4e24533f4b8
https://github.com/qsniyg/maxurl/commit/65db653637ce4fdf078937cf5ec38385719d31e8
https://github.com/qsniyg/maxurl/commit/6382f224084089d5d3c937d0125863d2f6b5c751
