### ISSUE TITLE
th.bing.com

### ISSUE THREAD

**Issue by DevWannabe-dot** [qsniyg/maxurl#916]
https://th.bing.com/th/id/OIP.kef7amvOdjQCragyEGUiHAHaHa?pid=ImgDet&w=100&h=100&c=7 - small
https://th.bing.com/th/id/OIP.kef7amvOdjQCragyEGUiHAHaHa?pid=ImgDet&c=7 - original

Used on bing.com, surprised this wasn't on Image Max Url already. Source page [here](https://www.bing.com/images/search?view=detailv2&iss=sbi&form=SBIVSP&sbisrc=UrlPaste&q=imgurl:https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FOIP.kef7amvOdjQCragyEGUiHAHaHa%3Fpid%3DImgDet%26c%3D7&idpbck=1&selectedindex=0&id=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FOIP.kef7amvOdjQCragyEGUiHAHaHa%3Fpid%3DImgDet%26amp%3Bc%3D7&ccid=rASv2%2BtB&mediaurl=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FOIP.kef7amvOdjQCragyEGUiHAHaHa%3Fpid%3DImgDet%26c%3D7&exph=474&expw=474&vt=2&sim=15). Removing the values `&w=100&h=100` is enough, and is on basically every bing image url if it's resized. Similtar to googleusercontent.com

**Comment by qsniyg** [comment]
Thanks! It was a different pattern (`/th/id/` instead of `/th?id=`) that I didn't come across when first writing the bing rule.
