### ISSUE TITLE
Issue with image redirection on Tumblr

### ISSUE THREAD

**Issue by tofuhoard** [qsniyg/maxurl#921]
Hello! First of all, thank you very much for creating and maintaining one of my favorite extensions ever.

Using the Firefox extension (and the userscript version, which I also tried), it appears something is preventing IMU from accessing the largest possible size of images on Tumblr. [This image](https://64.media.tumblr.com/c591753645758a590a282b14d4c642b4/99d7bfe7d29c6843-6c/s400x600/957221d26622edbdc2ae5d7a8b904318e587a91a.jpg), for example, stays at 400x600 despite being available at 1030x1030. Redirection unfortunately never happens, no matter which method I use to trigger it.

My extension settings string can be found [here](https://bin.snopyta.org/?294daceef9714fbe#3iMV4Ra9ffXWSiG3mWA7YVYyLCvuh7brGBrqh4dw6V9A).

Sorry for the trouble, and thank you very much in advance!

**Comment by qsniyg** [comment]
Thanks! It should be fixed now
