### ISSUE TITLE
artwork-cdn.7static.com

### ISSUE THREAD

**Issue by ROpdebee** [qsniyg/maxurl#922]
Smallest:
https://artwork-cdn.7static.com/static/img/sleeveart/00/143/859/0014385941_33.jpg

Default:
https://artwork-cdn.7static.com/static/img/sleeveart/00/143/859/0014385941_350.jpg

Largest:
https://artwork-cdn.7static.com/static/img/sleeveart/00/143/859/0014385941_800.jpg

Removing the `_800` suffix just redirects to a placeholder image.

Some docs on image sizes: https://docs.7digital.com/reference#image-sizes
The main takeaway is that `_800` and `_500` may not exist for some images, `_350` _should_ exist for all of them, so that could be used as a backup.

Source: https://de.7digital.com/artist/tu-ves-ovnis/release/curva-al-final-del-t%C3%BAnel-14385941

**Comment by qsniyg** [comment]
Thanks! I've added support for it :)
