### ISSUE TITLE
wiki.lycanitesmobs.com

### ISSUE THREAD

**Issue by DevWannabe-dot** [qsniyg/maxurl#928]
resized: https://wiki.lycanitesmobs.com/_media/equipment:equipment_example.png?w=500&tok=5b77e3
original: https://wiki.lycanitesmobs.com/_media/equipment:equipment_example.png

I haven't posted here in a long time, and I hope this is useful! The wiki page for [lycanites mobs](https://www.curseforge.com/minecraft/mc-mods/lycanites-mobs) minecraft mod may not be so popular, so I thought this rule could be made global with the "wiki." prefix, I don't know. Peace 🙏

**Comment by qsniyg** [comment]
Thanks! Less popular sites are also totally fine to add :)
