### ISSUE TITLE
famitsu.com

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#94]
Example page: https://www.famitsu.com/news/201907/21180011.html

`https://www.famitsu.com/images/000/180/011/y_5d33812461bbf.jpg`
->
`https://www.famitsu.com/images/000/180/011/z_5d33812461bbf.jpg`

**Comment by qsniyg** [comment]
Thanks! The website is a little inconsistent with its naming scheme... in some cases, some patterns work, in others they don't. In a few cases (https://www.famitsu.com/images/000/124/494/5874c0867b874.jpg), the original image can be found by not having any alphabetical prefixes, but in others (https://www.famitsu.com/images/000/124/494/5874c086779f9.jpg), it actually makes them smaller. I'm guessing the former is a bug on their side.

I'll try investigating it further later :) A few other patterns can also be found on the website (such as https://www.famitsu.com/cominy/img.php?filename=d_106047_1_1517286697.jpg)

**Comment by fireattack** [comment]
It doesn't seem to work on https://www.famitsu.com/images/000/180/646/y_5d41693ef3e28.jpg, despite the regex matches.

**Comment by fireattack** [comment]
Not sure if need to add yet, but some banners have the larger images by replacing s to o:

https://www.famitsu.com/serial/gameiscool/images/s00000028s.jpg 
->
https://www.famitsu.com/serial/gameiscool/images/s00000028o.jpg

From https://www.famitsu.com/serial/gameiscool/201908/25181637.html

**Comment by qsniyg** [comment]
Thank you! I've kept the rule to only work for images ending with `s`, as `a` is a completely different image. If you find any different images with this, please let me know.
