### ISSUE TITLE
NPR image URLs with _custom in image name not handled correctly

### ISSUE THREAD

**Issue by kuchenmitsahne** [qsniyg/maxurl#96]
**Userscript version: 0.9.6
Site: npr.org**

It seems that images with `_custom` in the name result in a cropped image if the `_custom` is removed (as the current regex prescribes, and which seems to work as expected with other suffixes that follow underscores).

(images taken from [this article](https://www.npr.org/sections/codeswitch/2018/09/27/647989652/if-we-called-ourselves-yellow))

Small URL: https://media.npr.org/assets/img/2018/09/17/linnaeus_custom-e310e859d180def59eb94bbe2f4e5415271451ab-s600-c85.jpg
Actual Max URL: https://media.npr.org/assets/img/2018/09/17/linnaeus_custom-e310e859d180def59eb94bbe2f4e5415271451ab.jpg
Script's Max URL:  https://media.npr.org/assets/img/2018/09/17/linnaeus-e310e859d180def59eb94bbe2f4e5415271451ab.jpg

Small URL: https://media.npr.org/assets/img/2018/09/19/gidra_custom-0678876221a4e7b5c56e9434acd44a3538e4051b-s1600-c85.jpg
Actual Max URL: https://media.npr.org/assets/img/2018/09/19/gidra_custom-0678876221a4e7b5c56e9434acd44a3538e4051b.jpg
Script's Max URL: https://media.npr.org/assets/img/2018/09/19/gidra-0678876221a4e7b5c56e9434acd44a3538e4051b.jpg

In [a different article](https://www.npr.org/sections/codeswitch/2019/06/22/452551172/the-hawaiian-language-nearly-died-a-radio-show-sparked-its-revival) from the same section (Code Switch), the URLs with `_custom` stripped out flat-out don't work, and instead redirect to a 404 page:

Small URL: https://media.npr.org/assets/img/2019/06/20/hawaii-post-kids_custom-808f27dd3700acfaf245bfb9f389c047cccf4792-s1600-c85.jpg
Actual Max URL: https://media.npr.org/assets/img/2019/06/20/hawaii-post-kids_custom-808f27dd3700acfaf245bfb9f389c047cccf4792.jpg
Script's Max URL: https://media.npr.org/assets/img/2019/06/20/hawaii-post-kids-808f27dd3700acfaf245bfb9f389c047cccf4792.jpg

I'm not sure if there's something deeper going on or if an exception would have to be carved out for this one suffix.

**Comment by qsniyg** [comment]
Thank you very much for reporting! For now I'll add `_custom` as an exception (makes sense from the name), but if you spot anything else, let me know and I'll try to use a whitelist instead :)
