### ISSUE TITLE
gamers.co.jp

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#964]
From `https://www.gamers.co.jp/resize_image.php?image=01071102_5e13e6d0b80e3.jpg`
To `https://www.gamers.co.jp/upload/save_image/01071102_5e13e6d0b80e3.jpg`

(Source: https://www.gamers.co.jp/pd/10482675/)

We already have this routine for its old img domain `gamers-onlineshop.jp` and animate's (`tc-animate.techorus-cdn.com`), needs to update for the new img domain `https://www.gamers.co.jp/resize_image.php?`.

Also currently the code for the above two are in two places. Need to merge.

**Comment by qsniyg** [comment]
Thanks! Fixed by https://github.com/qsniyg/maxurl/commit/f6635d798e0dfe4412e5e27216593454c52bf9f6
