### ISSUE TITLE
Getting thumbnails on lofter

### ISSUE THREAD

**Issue by contextnerror** [qsniyg/maxurl#965]
The extension seems to consistently give thumbnails on lofter. This is true for both the direct media links and the original post links. 

Some examples of where this happens:
https://zerokitty.lofter.com/post/1d555956_2b41c9bb7 (multi-image post)
https://zerokitty.lofter.com/post/1d555956_2b4142cf0 (single image post)

Is this a settings problem on my side or a bug in the program?

**Comment by qsniyg** [comment]
Thanks! Lofter added a new domain which it didn't yet support :)
