### ISSUE TITLE
I found some

### ISSUE THREAD

**Issue by coolhealer** [qsniyg/maxurl#966]
first of all, thank you so much!
I found some for your information

*** NSFW ***

https://imgaws.com/img-5dee01386a431.html
=>https://imgaws.com/upload/big/2019/12/09/5dee01386a3e1.jpg

https://i4.imagetwist.com/th/32171/xx2g07b42hwx.jpg
=> https://i4.imagetwist.com/i/32171/xx2g07b42hwx.jpg

https://i94.fastpic.org/thumb/2018/1031/6c/_c97c6be113683e510139b64774d0d26c.jpeg
=>https://i94.fastpic.org/big/2018/1031/6c/_c97c6be113683e510139b64774d0d26c.jpg

**Comment by qsniyg** [comment]
Thank you!

Does imagetwist and fastpic not work for you? Both URLs work for me.

I'll add support for imgaws, it looks similar to a few other sites, probably uses the same system.

**Comment by qsniyg** [comment]
I've added support for imgaws. I'm closing it, but if imagetwist and fastpic don't work for you, please let me know and I'll reopen it.

**Comment by elvisef** [comment]
> I've added support for imgaws. I'm closing it, but if imagetwist and fastpic don't work for you, please let me know and I'll reopen it.

Hey. If You look here: [https://ibb.co/qYDR6krp](https://ibb.co/qYDR6krp) You will find out there's still a little problem with fastpic.
After using Your addon, it does not change links to direct images (maybe regex issue ?).

**Comment by qsniyg** [comment]
@elvisef It seems to work for me on that page... are you using the latest (github) version of the userscript? If it doesn't work with the latest version, could you send your settings? (Export button at the top of the options page)
