### ISSUE TITLE
cults3d

### ISSUE THREAD

**Issue by WmeLuna** [qsniyg/maxurl#967]
example: https://cults3d.com/en/3d-model/home/round-spiked-caster-cup-for-table-legs-on-carpet
has: https://images.cults3d.com/Kolaywaa0oegyFxo6moObRFdB1A=/516x516/filters:format(webp)/https://files.cults3d.com/uploaders/17345056/illustration-file/c1985272-65c9-4405-802d-880e3372f3f6/IMG_20200321_205956.jpg
larger version can be obtained by removing: https://images.cults3d.com/Kolaywaa0oegyFxo6moObRFdB1A=/516x516/filters:format(webp)/

resulting in: https://files.cults3d.com/uploaders/17345056/illustration-file/c1985272-65c9-4405-802d-880e3372f3f6/IMG_20200321_205956.jpg

**Comment by qsniyg** [comment]
Thanks!
