### ISSUE TITLE
ascii.jp

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#973]
`https://ascii.jp/img/2020/02/26/2334697/l/6b3431147731201a.jpg`
`https://ascii.jp/img/2020/02/26/2334697/o/6b3431147731201a.jpg`

From:

https://weekly.ascii.jp/elem/000/002/622/2622339/
https://weekly.ascii.jp/elem/000/002/334/2334697/

**Comment by qsniyg** [comment]
Closing since seems to be supported now, but let me know if it isn't :)
