### ISSUE TITLE
cho-animedia.jp

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#975]
URL: https://cho-animedia.jp/article/2021/12/21/29794.html
Best size (as far as I can find): https://cho-animedia.jp/imgs/p/Dybu1wcglzgN6YILHHa9fs3Ml8DBwsPExcbH/321900.jpg

The service is the same as the ones at userscript.ts#L74217, with magic word of `Dybu1wcglzgN6YILHHa9fs3Ml8DBwsPExcbH`.

**Comment by fireattack** [comment]
A sidenote for myself, while you can get the original resolution (?) by finding the magic /p/, the images are re-compressed anyway :/

**Comment by fireattack** [comment]
It's hard to tell from the above example since it's tiny, but at least wp-content one has EXIF preserved.

**Comment by qsniyg** [comment]
Thanks, supported :)
