### ISSUE TITLE
discordapp.net

### ISSUE THREAD

**Issue by MarvNC** [qsniyg/maxurl#977]
If you look at the URLs for stickers, images, profile pictures, and other similar images from Discord they have a size parameter at the end. It seems the image at the url without the parameter is smaller than with that parameter, of which 2048 is the maximum. 
Example:
https://media.discordapp.net/stickers/919178130701307934.webp
https://media.discordapp.net/stickers/919178130701307934.webp?size=2048

**Comment by qsniyg** [comment]
Thanks for reporting! It should be supported in git, the link you sent redirects me to:

https://media.discordapp.net/stickers/919178130701307934.webp?size=4096 (571x554)
