### ISSUE TITLE
[url] `*.nocookie.net`

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#978]
i.e. `https://vignette.wikia.nocookie.net/ffa0bd26-76d5-476c-abd4-5a5f3a05aee7/zoom-crop/width/120/height/120`
to `https://vignette.wikia.nocookie.net/ffa0bd26-76d5-476c-abd4-5a5f3a05aee7`

or `https://static.wikia.nocookie.net/a8cf0955-ac01-4c9e-a858-fdd7f0df2d58/scale-to-width-down/800`
to `https://static.wikia.nocookie.net/a8cf0955-ac01-4c9e-a858-fdd7f0df2d58`

via `https://www.fandom.com/articles/sc-why-harry-and-hermione-should-have-been-together`
and its sidebar

**Comment by qsniyg** [comment]
It redirects for me... does it not for you? You may need to use the git version, as the released version hasn't been updated in some time.

**Comment by dym-sh** [comment]
does the site thing uses git version?
![Screenshot 2022-01-03 at 13-30-21 Image Max URL_20220103123030](https://user-images.githubusercontent.com/59403389/147930699-53cd6860-a1bf-480a-bfcf-1305f3dedfdf.png)
