### ISSUE TITLE
d2ufj6gm1gtdrc.cloudfront.net (postype)

### ISSUE THREAD

**Issue by contextnerror** [qsniyg/maxurl#980]
Post with image:https://fruitsnoir.postype.com/post/2454609

Base url of image: https://d2ufj6gm1gtdrc.cloudfront.net/2018/09/10/22/49/e91aea7d82404cdfcb12ecbc99ef856f.jpg?w=1200&q=90

Full size url (to my knowledge): https://d2ufj6gm1gtdrc.cloudfront.net/2018/09/10/22/49/e91aea7d82404cdfcb12ecbc99ef856f.jpg

Note that the site seems to be very particular about referers when loading images.

**Comment by qsniyg** [comment]
Thanks, I forgot to disable the "Spoof referer headers" option from uMatrix.

**Comment by qsniyg** [comment]
Should be supported now, thanks!
