### ISSUE TITLE
instagram.com caching graphql & extracting imageid error

### ISSUE THREAD

**Issue by robindz** [qsniyg/maxurl#983]
Using the latest commit from the main branch as of writing this issue. (0.19.5)

I am logged in on instagram.com and am trying to use the extension. This resulted in some errors logged to console. I resolved these by making changes to `fill_graphql_cache_with_postpage`, `cache_graphql_post` and `common_functions["instagram_get_imageid"]`.

Changes to `fill_graphql_cache_with_postpage`:

```js
var fill_graphql_cache_with_postpage = function(postpage_text) {
	if (!host_is_ig)
		return;
	var shareddata = get_sharedData_from_resptext(postpage_text);
	if (!shareddata)
		return;
	try {
		var entry_data = shareddata.entry_data;
		if ("ProfilePage" in entry_data) {
			var edges = entry_data.ProfilePage[0].graphql.user.edge_owner_to_timeline_media.edges;
			// todo: also cache edge_felix_video_timeline to avoid requesting videos
			for (var i = 0; i < edges.length; i++) {
				var edge = edges[i].node;
				cache_graphql_post(edge);
			}
		} else if ("PostPage" in entry_data) {
                        // ORIGINAL
                        // var shortcode_media = entry_data.PostPage[0].graphql.shortcode_media;
			var shortcode_media = entry_data.PostPage[0].items[0];    // Changes made here
			cache_graphql_post(shortcode_media);
		}
	} catch (e) {
		console_error(e, shareddata);
	}
};
```

Changes to `cache_graphql_post`:

```js
var cache_graphql_post = function(edge) {
	if (edge.shortcode) {
		api_cache.set("graphql_ig_post:" + edge.shortcode, edge);
	} else if (edge.code) {
                api_cache.set("graphql_ig_post:" + edge.code, edge);    // Added else if clause to not potentially break the old code
        }
};
```

Changes to `common_functions["instagram_get_imageid"]`:

```js
common_functions["instagram_get_imageid"] = function(image_url) {
	if (!image_url)
		return image_url;
	if (typeof image_url === "number")
		return image_url; // e.g. img_i: 0, 1, 2
	// story id
	var newurl = image_url.replace(/.*\/stories\/+[^/]+\/+([0-9]+)\/*(?:[?#].*)?$/, "$1");
	if (newurl !== image_url)
		return newurl;
	newurl = image_url.replace(/.*\/([^/.]*)\.[^/.]*(?:[?#].*)?$/, "$1");
	if (newurl === image_url)
		newurl = image_url.replace(/.*\/(.*)\?.*$/, "$1");    // Removed 'null' return here and used another regex to extract the file name as imageid
	return newurl;
};
```

Note: I don't know this repo well and just made changes that "fixed" my issue with instagram.com, I have no idea if by doing so, I broke other features.

**Comment by qsniyg** [comment]
Thank you very much for this!! I think I've addressed this in a the last few commits, based on the code you've sent.

Is the `instagram_get_imageid` change needed? If so, can you send an example URL that requires this?

**Comment by robindz** [comment]
I had to make the change because `instagram_get_imageid` kept returning null.
I don't know what the expected input is of that function, but I assume the url of the image/video? If that is the expected input, it never matched one of the regexs in that function, hence I added a regex that captures the file name, e.g.:

URL: https://scontent-bru2-1.cdninstagram.com/v/t51.2885-15/e35/271760634_141729454899363_6673546970842196313_n.webp.jpg?_nc_ht=scontent-bru2-1.cdninstagram.com&_nc_cat=103&_nc_ohc=w9sOJSYLo0kAX9yaJyp&edm=ALQROFkBAAAA&ccb=7-4&oh=00_AT-Xwh-154S-6nW7UQ8a8beeE_QMymcDWqlomVrHmMz04A&oe=61F2EEC5&_nc_sid=30a2ef

Captured: `271760634_141729454899363_6673546970842196313_n.webp.jpg`, which *should* be unique.

**Comment by qsniyg** [comment]
Thank you! Should be fixed now.

**Comment by robindz** [comment]
LGTM 👍
