### ISSUE TITLE
instagram.com retrieved url is not max resolution

### ISSUE THREAD

**Issue by robindz** [qsniyg/maxurl#984]
Tried on this post: https://www.instagram.com/p/B1S2xhUluoX/

First image looks fine, got this url: https://scontent-bru2-1.cdninstagram.com/v/t51.2885-15/e35/67276822_365700214352778_5585441925819893979_n.jpg?_nc_ht=scontent-bru2-1.cdninstagram.com&_nc_cat=106&_nc_ohc=s7GlDo3jlk4AX8XJo6f&edm=ALQROFkBAAAA&ccb=7-4&oh=00_AT_QfOwdmsyNA8GEXPMvWghohfe5HgwhMKXE7ThAgofFkA&oe=61F52A48&_nc_sid=30a2ef

Second image is "squared" and there were sections cut off: https://scontent-bru2-1.cdninstagram.com/v/t51.2885-15/e35/c0.101.810.810a/69295778_175579996813244_3298286052250310960_n.jpg?_nc_ht=scontent-bru2-1.cdninstagram.com&_nc_cat=108&_nc_ohc=h9qU4jYNkpoAX-qnbKF&tn=NK3rTXKiq5blq9VH&edm=AABBvjUBAAAA&ccb=7-4&oh=00_AT_AOv7i2SOC2sA0pqLH89_bOMybwLfPCR7D8w7g3VD9EA&oe=61F48698&_nc_sid=83d603

Seems like this isn't always the case however, for this post it always seems to return the highest resolution images: https://www.instagram.com/p/CZEAQagLqOJ/

Perhaps it has something to do with how the urls are ordered in the array that instagram's API returns?

**Comment by qsniyg** [comment]
Thanks for reporting, this error should be fixed in git master. Please let me know if it's not though, and I'll reopen the issue :)

**Comment by robindz** [comment]
LGTM!
