### ISSUE TITLE
usercontent.jamendo.com

### ISSUE THREAD

**Issue by ROpdebee** [qsniyg/maxurl#985]
From https://www.jamendo.com/album/454973/to-aurora:

https://usercontent.jamendo.com/?cid=1631882904&type=album&id=454973&width=300&trackid=1885651 -- 300x300
  -> https://usercontent.jamendo.com/?cid=1631882904&type=album&id=454973&width=0&trackid=1885651 -- 3000x3000
(width=9999 leads to a 500 error, as does omitting the width parameter)

Various other types of URLs, same strategy:
- https://usercontent.jamendo.com/?cid=1642079668&type=artist&id=535912&width=300
- https://usercontent.jamendo.com/?cid=1642079668&type=hero-artist&id=535912&width=1920&cache=1643136096873

I noticed that there's already a rule for `cdn-img.jamendo.com`, but that domain doesn't seem to exist anymore, so I guess they switched to this new URL format.

**Comment by qsniyg** [comment]
Sorry for getting back so late. It should be supported now, thank you!
