### ISSUE TITLE
Support for VRChat API

### ISSUE THREAD

**Issue by CetaceanNation** [qsniyg/maxurl#995]
Site: https://vrchat.com/

#### Where {VARIABLE} is the same between all URLs
For small thumbnails embedded in page: `https://api.vrchat.cloud/api/1/image/file_{GUID}/{REVISION #}/{RESOLUTION}` -redirect-> `https://d348imysud55la.cloudfront.net/thumbnails/file_{GUID}.{SIGNATURE}.{REVISION}.thumbnail-{RESOLUTION}.png`
For full size images: `https://api.vrchat.cloud/api/1/file/file_{GUID}/{REVISION}` -redirect-> `https://d348imysud55la.cloudfront.net/{FILE NAME}.file_{GUID}.{REVISION}.png`

### Example URLs
For small thumbnails embedded in page: https://api.vrchat.cloud/api/1/image/file_2e032059-5c01-4955-98c7-245079d603cb/1/256 -redirect-> https://d348imysud55la.cloudfront.net/thumbnails/file_2e032059-5c01-4955-98c7-245079d603cb.a8d2f0f76f2b0a0d9fbeb8455e25a44c70cbe91ca0b10431cd89d54d87f88ca9.1.thumbnail-256.png
For full size images: https://api.vrchat.cloud/api/1/file/file_2e032059-5c01-4955-98c7-245079d603cb/1 -redirect-> https://d348imysud55la.cloudfront.net/World-Nijisanji-Express-Image-20.file_2e032059-5c01-4955-98c7-245079d603cb.1.png

Since the name of the image for the full size CloudFront URL after redirect cannot be obtained from the thumbnail, you can use details from either the API or the CloudFront thumbnail URL to get to the full size API URL.

**Comment by qsniyg** [comment]
Thank you very much for the detailed explanation! Supported :)
